### ISSUE TITLE
Discrepancy between github.com and GHfVS PR diffs

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1007]
- GitHub Extension for Visual Studio version: 2.2.1.100
- Visual Studio version: 2015

I checked out a PR and noticed that some PR files seemed have no changes:

![image](https://user-images.githubusercontent.com/11719160/26882109-58d96700-4b91-11e7-897d-bdf657dae04f.png)

On github.com the same file does appear to have changes:

![image](https://user-images.githubusercontent.com/11719160/26882015-0bd90460-4b91-11e7-8a90-32e3f0090acc.png)

**Comment by jcansdale** [comment]
It looks like the author of https://github.com/nunit/nunit/pull/2221 also noticed the anomaly (on https://github.com).
> Everything is appearing here in the diff even though some of it is already in master. Not sure why that is.

It's a small World, @rprouse! 😄 I'll put out some feelers and see if I can find out what's going on. Have you seen this happen before?  Any ideas what might have caused it?

**Comment by jcansdale** [comment]
There does indeed seem to be a discrepancy between
https://github.com/github/VisualStudio/issues/1007.diff
and doing a `git diff master..release-371-merge` locally.

Here are the two diffs for comparison: [github.diff.txt](https://github.com/github/VisualStudio/files/1058476/github.diff.txt) (github.com), [git.diff.txt](https://github.com/github/VisualStudio/files/1058477/git.diff.txt) (local)

**Comment by rprouse** [comment]
@jcansdale when I do the `git diff master..release-371-merge` locally, I see what I expect to be merged back into master.

I have seen this before, often when working on hotfixes in a release branch. In this case, the extra changes in the GitHub diff are commits that I cherry picked into the release branch for a hotfix that are already merged into master. Since those commits are already in both branches, I don't expect to see them.

**Comment by jcansdale** [comment]
@rprouse it seems you need to do a `git diff master...release-371-merge` (with the extra `.`) to see what appears on https://github.com. Basically if master moves on, those extra commits shouldn't appear in the diff (they're not part of that PR). I *finally* understand what `...` means. 😉 

I've tweaked our code to use the merge base (rather than simply the base of the PR) and now it seems to work. 😄 

![image](https://user-images.githubusercontent.com/11719160/26892636-db31cbd8-4bb0-11e7-8b62-f9f1c52bec6b.png)

I've been using NUnit as a decent sized solution for testing inline comment support. Here's a teaser:

![image](https://user-images.githubusercontent.com/11719160/26893117-5143421a-4bb2-11e7-81fc-21a16b474a7f.png)

**Comment by jcansdale** [comment]
Fixed in #1008
