### ISSUE TITLE
Highlight the PR who's head branch the user is on

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1009]
It would be nice if when working on a PR branch, the associated PR would be highlighted on the list.

![image](https://user-images.githubusercontent.com/11719160/27076422-0f8bb97a-5025-11e7-9c11-11b0fdef0a1b.png)

**Comment by meaghanlewis** [comment]
This was added
![screen shot 2018-09-11 at 3 50 41 pm](https://user-images.githubusercontent.com/10103121/45392066-7e399100-b5da-11e8-9f3e-7af92548f0de.png)
