### ISSUE TITLE
Enhancement: Expose the current branch name as MACRO variable.

### ISSUE THREAD

**Issue by TronicLabs** [github/VisualStudio#1012]
$(CURRENT_GIT_BRANCH_NAME)
...
$(CURRENT_GIT_BRANCH_FOLDER)
....
and so on.

**Comment by paladique** [comment]
Hi @TronicLabs, are you asking to add it expose this through the GitHub for Visual Studio extension, or through Visual Studio? 

If this is through the extension could you elaborate on this? A screenshot will help us out, thanks!

**Comment by TronicLabs** [comment]
Hi @paladique.
Have the ability to access the current branch name in visual studio as a macro,
similar to $(Progect) and others.
Visualstudio sdk will allow you to generate variable macros?

**Comment by paladique** [comment]
Hi @TronicLabs, unfortunately that is specific to Visual Studio. This repo, for the GitHub VS extension, doesn't have access to expose the branch name as a macro variable.
