### ISSUE TITLE
[NullGuard] hosts is null. Parameter name:hosts

### ISSUE THREAD

**Issue by shiangyoung** [github/VisualStudio#1019]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio  version:
- Visual Studio version: 2.2.0.11

__What happened__ (with steps, logs and screenshots, if possible)
(https://user-images.githubusercontent.com/20599724/27509214-5ceddc94-592a-11e7-8f1f-a0e24d418051.png)

It appear after I click on manage connection->connect to github
Is there any steps I miss?

**Comment by grokys** [comment]
Hi @shiangyoung 

Sorry to hear you're having problems. When you say:

> It appear after I click on manage connection->connect to github

Do you mean you're just clicking on the link outlined in red here?

![image](https://user-images.githubusercontent.com/1775141/27583048-6737ec2a-5b33-11e7-9399-d0248be774cc.png)

Could you also attach the following log files:

`%LocalAppData%\GitHubVisualStudio\extension.log`
`%LocalAppData%\GitHubVisualStudio\GitHubVisualStudio-te.log`

Hopefully with that information we can work out what's going wrong.

**Comment by grokys** [comment]
NullGuard has been removed so this should have been fixed.
