### ISSUE TITLE
Error opening file: Could not retrieve <<filename>>@<<githash>> when trying to compare files in pull request

### ISSUE THREAD

**Issue by markoueis** [github/VisualStudio#1026]
I'm using Visual Studio 2017 enterprise. I'm successfully connected to github enterprise.

1) I open Open a pull request using the git hub plugin. it opens successfully and i see the changed files.
2) I right click on a file and click on "compare file"
3) I see "Error opening file: Could not retrieve <<filename>>@<<githash>>" in visual studio status bar in the bottom of the screen.

I expect to open the file and see the diffs. 

If i click on "open file" i see the latest file. But if i click on compare i get nothing but that error

![image](https://user-images.githubusercontent.com/23063832/27842575-14c30564-60d9-11e7-80e8-a1d379a6192a.png)

**Comment by markoueis** [comment]
I cannot reproduce anymore. Restart of machine may have helped. i hadn't restarted in a while. Just a quick question though. If i'm using a third party of compare like beyond compare, that doesn't seem to show up here. It's doing the compare in VS. however normal VS compare outside the plugin is doing it in beyond compare. Any way to get the plugin to do use the diff tool of choice?

Thanks and sorry for the "cannot reproduce"

**Comment by paladique** [comment]
Thanks for updating us, @markoueis. 
> Any way to get the plugin to use the diff tool of choice?

That is a good question! Quickly scanning the [code ](https://github.com/github/VisualStudio/blob/8d53fa1d0c792085c8f54a3dd3323ce2b0bd38ce/src/GitHub.VisualStudio/UI/Views/PullRequestDetailView.xaml.cs#L87) that opens the diff view points to this being a possibility, but could be a tricky addition now that [line comment feature](https://github.com/github/VisualStudio/pull/1004) is nearly done, where we're building on VS's diff view.

cc: @grokys in case he has more input on this.

**Comment by markoueis** [comment]
I would say, if possible, have a right click --> compare in external tool option. That would allow the best of both worlds. But i like what you guys are doing!
