### ISSUE TITLE
GitHub Clone window shows error but no text

### ISSUE THREAD

**Issue by WouterDeKort** [github/VisualStudio#1039]
Hi Team.,

When I click on GitHub on the start page of Visual Studio 2017.2, I can select a repo from GitHub and enter a local path. When entering a path that already exists I see the following:

![clone github repo in vs](https://user-images.githubusercontent.com/1763043/27960008-f417de90-6329-11e7-81fd-0fbb848753df.png)

I would expect that hovering the red ! would show a tooltip that explains the error. But nothing is shown and I guessed that the error had to do with an existing folder.

Can you please add an error message that tells what’s wrong?

Thanks,
Wouter

**Comment by paladique** [comment]
Thanks for the suggestion @WouterDeKort. You're absolutely right: this validation error is not descriptive enough to understand why it is happening.

**Comment by grokys** [comment]
The icon is also superimposed over the path text if the contents of the text box is long.

**Comment by meaghanlewis** [comment]
A warning shows in the new clone dialog when a repository cannot be cloned to a specific destination.
