### ISSUE TITLE
Correct comment count for different PR views

### ISSUE THREAD

**Issue by ungb** [github/VisualStudio#1045]
If user is in the non-diff view, the comment count next to the file is showing the total number of comments which includes the entire diff. 

<img width="1043" alt="screen shot 2017-07-07 at 10 00 12 am" src="https://user-images.githubusercontent.com/14828183/27961035-6876ff2a-62fb-11e7-9fc0-35466703fb96.png">

I believe it should show only the count for the current "view" opened, as the user can paginate through only the comments in the current "view". 

For example, if the PR view is open then count of two comments should show in the GH window. If the master view open, then one comment should show. Perhaps say we change to a ratio instead, like "1/3"?

(contact @tierninho for questions)

**Comment by grokys** [comment]
Is this the same as #1051?

**Comment by grokys** [comment]
I think it is, closing.

**Comment by tierninho** [comment]
Yep, thanks for closing
