### ISSUE TITLE
Margin is only visible when `Open File` is used, if there is already a diff view opened using `Compare File`.

### ISSUE THREAD

**Issue by ungb** [github/VisualStudio#1048]
Margin is only visible when `Open File` is used, if there is already a diff view opened using `Compare File`.

E.g., this works:
![image](https://user-images.githubusercontent.com/11719160/27760829-7d621850-5e48-11e7-9518-eb2776a4351c.png)

But only because `Diff- DiffUtilities.cs` is already open. If you open `DiffUtilities.cs` directly the margin isn't visible. Not sure what's causing this.

**Comment by grokys** [comment]
Unable to repro this either... Looks like you're on `github/VisualStudio` from the screenshot. Which PR? Any other useful information that might help me repro?

**Comment by grokys** [comment]
Managed to repro.

**Comment by grokys** [comment]
Should be fixed by #1069 if you could check.
