### ISSUE TITLE
Comment count in non-diff view?

### ISSUE THREAD

**Issue by ungb** [github/VisualStudio#1051]
If user is in the non-diff view, the comment count next to the file is showing the total number of comments which includes the entire diff. 

<img width="1043" alt="screen shot 2017-07-07 at 10 00 12 am" src="https://user-images.githubusercontent.com/14828183/27961035-6876ff2a-62fb-11e7-9fc0-35466703fb96.png">

I believe it should show only the count for the current "view" opened, as the user can paginate through only the comments in the current "view". 

For example, if the PR view is open then count of two comments should show in the GH window. If the master view open, then one comment should show. Perhaps say we change to a ratio instead, like "1/3"?

cc @tierninho who filed this

**Comment by grokys** [comment]
This is (currently) expected bahavior - the comment count is the total number of threads in the file - it doesn't change depending on the currently open view. It would be possible to make it change (although I imagine rather fiddly) but tbh to me the current behavior makes more sense...

**Comment by tierninho** [comment]
Sounds good. Closing this issue.
