### ISSUE TITLE
Adding a comment to a line in green gutter scroll section works, however the comment is not found if I were to click on that line again. 

### ISSUE THREAD

**Issue by ungb** [github/VisualStudio#1052]
Adding a comment to a line in green gutter scroll section works, however the comment is not found if I were to click on that line again. The comment count in the GH window does not increment either.

<img width="644" alt="screen shot 2017-07-07 at 10 19 06 am" src="https://user-images.githubusercontent.com/14828183/27961999-8da1ec12-62fe-11e7-8d3a-42fc82d806ac.png">

I can see the comment in PR on dotcom though. Not sure if this is the correct functionality. I would expect the comment to be sticky in VS and the comment count to increment.

<img width="1130" alt="screen shot 2017-07-07 at 10 20 18 am" src="https://user-images.githubusercontent.com/14828183/27962027-9dc17bd0-62fe-11e7-95e8-6fd0f5d56f08.png">

(contact @tierninho for questions)

**Comment by grokys** [comment]
@ungb this is indeed a bug, but not one I'm able to reproduce. Does it consistently act like this for you?

**Comment by tierninho** [comment]
@grokys this was my bug, and yes, it still behaves this way for me but only when the 'Removed`diff is populated. For instance on line 4 on the `Added` diff, I cannot post a comment.

<img width="841" alt="screen shot 2017-07-11 at 12 52 07 pm" src="https://user-images.githubusercontent.com/14828183/28079902-10279a38-6638-11e7-9640-b701a1e2a48e.png">

**Comment by jcansdale** [comment]
I've managed to repro this as well. It only seems to happen on one line on one repo.

![image](https://user-images.githubusercontent.com/11719160/28128754-c00bf868-6728-11e7-9685-c0250d9ce160.png)

**Comment by jcansdale** [comment]
It you checkout PR 1 from this fork and try to add a comment here:
https://github.com/jcansdale/PullRequestSandbox/pull/1/files#diff-b93145fc607215850e0ade00b83d3118R11

When I click on `Comment`, the buttons remain enabled and the textbox clears but no comment shows locally (it does however on github.com).
![image](https://user-images.githubusercontent.com/11719160/28130566-0a4b43ba-672f-11e7-97cc-e15c51e00fc1.png)
