### ISSUE TITLE
Keep coloured toolbar in OSX fullscreen

### ISSUE THREAD

**Issue by jpike88** [github/VisualStudio#1058]
We have two projects, client and server. I configured workspace settings to have client be green, server be blue. Really useful.

Until however, I fullscreen one of them. Then the coloured toolbar disappears, which defeats the purpose of styling it in the first place.

Would love an option to keep showing it in fullscreen, just to keep that distinction in there.

This is useful:
![screen shot 2017-07-12 at 11 18 53 am](https://user-images.githubusercontent.com/9585787/28101631-07bed3ae-66f4-11e7-8b07-e1cdaf3ab37e.png)

This isn't so useful (in fullscreen mode):
![screen shot 2017-07-12 at 11 19 00 am](https://user-images.githubusercontent.com/9585787/28101635-09e603a0-66f4-11e7-965f-1f56877afe19.png)

**Comment by grokys** [comment]
Hi @jpike88,  this repository is for the GitHub for Visual Studio Extension. You may be looking for the Visual Studio Code repository: https://github.com/Microsoft/vscode

**Comment by jpike88** [comment]
oh god, sorry
