### ISSUE TITLE
Pull Request behind a corporate proxy

### ISSUE THREAD

**Issue by kkirpichnikov** [github/VisualStudio#1061]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio  version: GitHub.VisualStudio   2.2.0.11
- Visual Studio version: Microsoft Visual Studio Community 2017 
Version 15.2 (26430.15) Release
VisualStudio.15.Release/15.2.0+26430.15
Microsoft .NET Framework
Version 4.7.02046
Installed Version: Community
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

__What happened__ (with steps, logs and screenshots, if possible)

1. We have a corporate network and GitHub Enterprise.

2. Tried to clone repo from GitHub Enterprise. Got Error about connection problems.

3. Added proxy to gitconfig ( git config --global http.proxy PROXY_URL )
 ![proxy_config](https://user-images.githubusercontent.com/13055750/28121219-603e9a52-66e8-11e7-813a-0e2302d8cadd.png)

4. After that, I was able to clone a repo

5. Changed some files.

6. Tried to create a pull request. Got this type of error **Failed to set proxy: The parameter is incorrect.**
 ![pullrequest](https://user-images.githubusercontent.com/13055750/28121212-5afea7c6-66e8-11e7-9ab0-e90074e8b164.png)

**Comment by grokys** [comment]
Thanks for the report @kkirpichnikov - looks like we have some issues related to proxies, we've had some other reports along these lines. As far as I can see this exception is coming from within libgit2sharp - just to be sure, could you send us the contents of these log files?

- `%LocalAppData%\GitHubVisualStudio\extension.log`
- `%LocalAppData%\GitHubVisualStudio\GitHubVisualStudio-te.log`

**Comment by kkirpichnikov** [comment]
Thank you for getting back. There is no GitHubVisualStudio-te.log file.
Extension.log is attached.

Konstantin.

**Comment by grokys** [comment]
@kkirpichnikov did you manage to resolve this issue? Apologies for not replying, it feel off our radar. Also I can't see your attached `extension.log`. If this is still an issue could you attach it?

**Comment by grokys** [comment]
Closing this due to no reply.
