### ISSUE TITLE
/usr/share/code/code uses 100% of cpu

### ISSUE THREAD

**Issue by bogomips** [github/VisualStudio#1062]
The interface becomes unresponsive for many seconds and  I see /usr/share/code/code that uses 100% of cpu.

- GitHub Extension for Visual Studio  version: not extensions
- Visual Studio version: 1.14.0

I think it happens since the last update, I deactivated every plug-in but it keeps happening.

**Comment by grokys** [comment]
Hi @jpike88, this repository is for the GitHub for Visual Studio Extension. You may be looking for the Visual Studio Code repository: https://github.com/Microsoft/vscode

**Comment by bogomips** [comment]
Sorry for the mistake! I did not realize it
