### ISSUE TITLE
Path field doesn't have default cloning path of C:\Users\[user]\Source\Repos

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#107]
**Steps to reproduce:**
1. Click on Clone action link
**Expected Results:** Path field contains default cloning path C:\Users\[user]\Source\Repos
**Actual Results:** Mine displays the VM path. _However_ is this just me b/c I'm VM? 

Will take a look on a windows machine to confirm. 
![screen shot 2015-09-30 at 2 12 52 pm](https://cloud.githubusercontent.com/assets/10725993/10207182/aa4ad31e-677f-11e5-980e-99a6ce77ee69.png)

**Comment by jakubsuchybio** [comment]
I have the same problem. 
It displays default location for user's "...\Documents\GitHubVisualStudio" folder every time.
**Expected result** should be location used in:
```Team Explorer -> Home -> Settings -> Git -> Global settings -> Default Repository Location```
