### ISSUE TITLE
Paginating backwards won't anchor "view" to comment thread

### ISSUE THREAD

**Issue by tierninho** [github/VisualStudio#1072]
If a user paginates forwards (right arrow) the comment threads are shown properly as the anchor moves to the top of the thread. However, if the user decides to paginate backwards (left arrow), the comment thread becomes out-of-view if the comment thread is on a line not shown in the current view.

For instance, user is viewing a comment thread on line 7, but decides to paginate backwards to the comment thread on line 1. User cannot see the comment thread on line 1 as it the user is scrolled all the way down like so:
<img width="438" alt="screen shot 2017-07-13 at 11 46 06 am" src="https://user-images.githubusercontent.com/14828183/28174950-f105076e-67c0-11e7-9c1d-86f8419ee314.png">

Once paginating backwards, user has opened the comment thread on line 1, but the view is stuck towards bottom of the diff.
<img width="487" alt="screen shot 2017-07-13 at 11 38 01 am" src="https://user-images.githubusercontent.com/14828183/28174982-0375fb38-67c1-11e7-9c0a-7dff13179b76.png">

Prerequisite: 
PR with at lease eight lines, with at lease one comment at the top and one at the bottom.

VS 2017, ext v2.3.0.0, Windows 10

**Comment by grokys** [comment]
I think this is a Visual Studio problem and as such may be difficult for us to fix...

**Comment by tierninho** [comment]
No worries, closing for now
