### ISSUE TITLE
Opening a comment thread pushes user to bottom of PR

### ISSUE THREAD

**Issue by tierninho** [github/VisualStudio#1073]
If a user has multiple comments with one being at the bottom of the "view" as so:
<img width="461" alt="screen shot 2017-07-13 at 11 53 27 am" src="https://user-images.githubusercontent.com/14828183/28175486-5fbacc4c-67c2-11e7-92c2-da070a6d32ee.png">
then clicking comment thread on line 5 should ideally show the the top of the thread to the user, however, it forces the user to the bottom of the PR instead (pic below), while still opening the thread on line 5. User has to scroll up to see the open thread. This is an anchor issue like #1072 
<img width="450" alt="screen shot 2017-07-13 at 11 53 49 am" src="https://user-images.githubusercontent.com/14828183/28175585-a5ef4a26-67c2-11e7-9051-f62f0de4dc27.png">

**Comment by grokys** [comment]
@tierninho could you point me to the repo and PR this is happening on? can't repro here.

**Comment by tierninho** [comment]
@grokys try this? https://github.com/tierninho-tester/dasdasdasd/pull/5/files

**Comment by grokys** [comment]
I think this is a Visual Studio problem and as such may be difficult for us to fix...

**Comment by tierninho** [comment]
No worries, closing for now...
