### ISSUE TITLE
Cursor is not in Search Repositories field by default

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#108]
**Steps to reproduce:**
1. Click on Clone action link
**Expected Results:** Cursor is in Search Repositories field
**Actual Results:** Cursor is in field path instead
![screen shot 2015-09-30 at 2 12 52 pm](https://cloud.githubusercontent.com/assets/10725993/10207245/06041df0-6780-11e5-8144-a3d4b50da3fa.png)

**Comment by shana** [comment]
This is because the search field isn't enabled initially. Related to #517

**Comment by paladique** [comment]
Fixed in #560
