### ISSUE TITLE
Feature request: More UI options

### ISSUE THREAD

**Issue by weitzhandler** [github/VisualStudio#1085]
- GitHub Extension for Visual Studio  version: 2.2.0.11
- Visual Studio version: 15.2

Please add more committing options to the GH UI in VS:
- Squash commits
- Commit with PR
- Commit to existing PR
- Allow opening any GitHub project in VS, by either cloning or forking+cloning, currently only projects owned (or forked) by me are available.

**Comment by grokys** [comment]
Hi @weitzhandler,

Regarding your requests:

1. Yes, this is definitely something missing. The actual git integration in Visual Studio is provided by Visual Studio Team Explorer and so we're hoping that Microsoft might add the feature at some time. If not, we may consider adding this ourselves.
2. What do envision for this feature?
3. You can already commit to an existing PR, by simply checking out the PR branch, or by using the inbuilt PR support: see "Working with Pull Requests" in our help at https://github.com/github/VisualStudio/blob/master/docs/contributing/index.md
4. This is something we have on our radar: https://github.com/github/VisualStudio/issues/900

**Comment by weitzhandler** [comment]
I'll check out your all links and try them all. Meanwhile I'm closing the issue.
Should I find anything unresolved, then I'll re-open or post a new one.

Thanks for your kind and detailed support!
