### ISSUE TITLE
Ctrl-clicking a selection in the list doesn't remove the selection and disable the clone button

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#109]
**Steps to reproduce:**
1. Click on Clone action link
2. Select a repo in the list
3. ctrl-click the selection to unselect it 

**Expected Results:** The selection is un-selected and the clone button is disabled

**Actual Results:** Nothing. I can un-select a repo by clicking outside the list (but inside the box). I am on a Mac so I tried control + clicking and cmd/command+ clicking as well. Hoping @shana can just take a :eyes: for me. 
:point_down:  is just to show that I can click outside the list but inside the box to unselect. :grin: 
![select](https://cloud.githubusercontent.com/assets/10725993/10208040/39926096-6785-11e5-96ba-e6e2cfe7c832.gif)

**Comment by grokys** [comment]
This is now fixed, however re-selecting the item doesn't re-enable the Clone button.
