### ISSUE TITLE
GitHub pane asks to sign in but Connect To GitHub dialog disables GitHub login

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#1094]
I've got into a state where the GitHub pane is asking me to login:

![image](https://user-images.githubusercontent.com/1775141/28782417-5379b71e-760d-11e7-979a-40b68cce0e63.png)

But when i click the "Sign in" link the GitHub tab is disabled and I can only sign into enterprise:

![image](https://user-images.githubusercontent.com/1775141/28782450-67113798-760d-11e7-864e-6d74d857c716.png)

This seems to be happening because I have valid credentials in the credential store, but a connection is not present in the `ghfvs.connections` file.

We need to make these two places where connection information is stored aware of each other.

**Comment by grokys** [comment]
To repro:

1. Sign in to .com
2. Delete the `ghfvs.connections` file from `C:\Users\grokys\AppData\Local\GìtHubVisualStudio`

**Comment by jcansdale** [comment]
I've had a report of this fix working for a user who couldn't log into GitHub Enterprise. They followed the following instructions:

- Open `Credential Manager` from the Windows Start Menu
- Click on `Windows Credentials`
- Select the credentials related to your Enterprise server
- Click on `Remove`

**Comment by grokys** [comment]
This should have been fixed in #1277 and will be shipped in the next minor version.

**Comment by Gante82** [comment]
Hello, I'm having this issue as of today. My visual studio 2019 version is **16.1.6** and my GitHub extension version is **2.9.1.7781** . I tried the workaround and was finally able to sign in.

![image](https://user-images.githubusercontent.com/26367595/61859486-7e780d80-aec8-11e9-866c-cf53f1a0f410.png)

**Comment by lekpkd** [comment]
I have same issue, Sign in button disabled. Visual Studio 2019 v16.6.2, GitHub extention version v2.11.104.25275

![image](https://user-images.githubusercontent.com/8196825/86990916-f61d7600-c1c7-11ea-8067-f5d1fa84ca38.png)

**Comment by lekpkd** [comment]
> Hello, I'm having this issue as of today. My visual studio 2019 version is **16.1.6** and my GitHub extension version is **2.9.1.7781** . I tried the workaround and was finally able to sign in.
> 
> ![image](https://user-images.githubusercontent.com/26367595/61859486-7e780d80-aec8-11e9-866c-cf53f1a0f410.png)

How do you solved your problem?

**Comment by jcansdale** [comment]
Hi @lekpkd,

Could you let me know if you see a sign-in button if you enter `https://ghe.io`?

The button is only supposed to appear when a GitHub Enterprise server is detected.

**Comment by lekpkd** [comment]
> Hi @lekpkd,
> 
> Could you let me know if you see a sign-in button if you enter `https://ghe.io`?
> 
> The button is only supposed to appear when a GitHub Enterprise server is detected.

Hi @jcansdale,

Token appear when I entered `https://ghe.io`, So I think I have to contact our Local GHE team.

Thank you for your help!

![image](https://user-images.githubusercontent.com/8196825/87264514-61c65280-c4ea-11ea-9d4c-08cce5c78a42.png)
![image](https://user-images.githubusercontent.com/8196825/87264591-99cd9580-c4ea-11ea-9643-5099742d80fa.png)
