### ISSUE TITLE
VS 2015 crashed with an Access Violation exception when a project was opened

### ISSUE THREAD

**Issue by prasethu** [github/VisualStudio#1125]
[Repro]
1. Launch [AppVerifier ](https://msdn.microsoft.com/en-us/library/ms220948(v=vs.90).aspx)and Enable Heaps tracking for VS
2. Start VS as administrator
3.Copy windbg.exe to desktop, open it as administrator.
4.File->Attach to a Process(F6) ,choose devenv.exe.
5.Type "g" on the bottom of windbg on and click enter , then showing "Debuggee is running"  on the bottom of windbg
6. In VS Start Page, click "Open Project..." to open a app.

 
[Observe]
Hit access Violation when open a project.

I'll follow up with a dump file - I'm waiting for it from the person who found the bug.

CallStack as bellows：
> GitHub.TeamFoundation.14.dll!GitHub.TeamFoundation.RegistryHelper.PokeTheRegistryForRepositoryList() Line 26 C#
  GitHub.TeamFoundation.14.dll!GitHub.Services.VSServices.GetKnownRepositories() Line 94 C#
  GitHub.VisualStudio.dll!GitHub.VisualStudio.ConnectionManager.RefreshRepositories.AnonymousMethod__20_0() Line 132 C#
  mscorlib.dll!System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<GitHub.Models.ISimpleRepositoryModel>>.InnerInvoke() Unknown
  mscorlib.dll!System.Threading.Tasks.Task.Execute() Unknown
  mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Unknown
  mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Unknown
  mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Unknown
  mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Unknown
  mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Unknown
  mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Unknown
  mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Unknown
  mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Unknown
  [Native to Managed Transition] 
  [External Code] 
  [Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]

**Comment by grokys** [comment]
@prasethu I tried this when the issue was submitted and was unable to repro, and I'm unable to repro on trying again now. Do you have any more information? Does it happen for you on all machines? Just one machine? Anything else that might be useful to know?

**Comment by meaghanlewis** [comment]
I'm going to close this issue out for now. @prasethu please re-open if you are still experiencing this issue.
