### ISSUE TITLE
Package Manager Console error - PowerShell version 2.0 is not supported. Please upgrade PowerShell to 3.0 or greater and restart Visual Studio.

### ISSUE THREAD

**Issue by bryanjhogan** [github/VisualStudio#1126]
Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.6.01055

Windows 7 - Version 6.1.7601 Service Pack 1 Build 7601

---
When I open Visual Studio the package manager console opens and immediately the following appears 

Package Manager Console Host Version 4.2.0.2457

Type 'get-help NuGet' to see all available NuGet commands.

**PowerShell version 2.0 is not supported. Please upgrade PowerShell to 3.0 or greater and restart Visual Studio.**

---
From the Package Manager I ran

PM> $PSVersionTable.PSVersion

Major  Minor  Build  Revision

2      0      -1     -1      

----------

But in PowerShell started from the Windows menu   - 
PS C:\>  $PSVersionTable.PSVersion

Major  Minor  Build  Revision

4      0      -1     -1

**Comment by jcansdale** [comment]
Hi @bryanjhogan,

This looks like an issue with the NuGet copnsole for Visual Studio.

I this this is probably the repo you're looking for:
https://github.com/NuGet/Home/issues

(github/VisualStudio is just for the GitHub Extension for Visual Studio)

**Comment by bryanjhogan** [comment]
Ok, thanks. Moved to - https://github.com/NuGet/Home/issues/5768

**Comment by MSAAAAuto** [comment]
Solution:
This works for me, run it in Package Manager Console:
`Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`
Source:
https://chocolatey.org/install#install-with-powershellexe
I have Windows 10.0.16299.19 and Visual Studio 2017 15.4.3.
