### ISSUE TITLE
Visual Studio Freezes When Pulling

### ISSUE THREAD

**Issue by davidshq** [github/VisualStudio#1151]
- GitHub Extension for Visual Studio  version: 2.2.0.11    
- Visual Studio version: 15.3.0

__What happened__ 
 
Navigating to Team Explorer --> GitHub --> Sync --> Pull results in software freezing up. I've let it run for quite a while and the CPU just keeps kicking away.

**Comment by grokys** [comment]
Hi @davidshq,

The Team Explorer pull functionality is not actually provided by us - it's a part of Team Explorer which is part of Visual Studio itself. The best way to communicate bugs to Microsoft is via the "Send Feedback" button in Visual Studio, next to the Quick Launch text box.

Having said that, you might want to try pulling from the command line or using desktop.github.com if you're still having problems.

Closing this for now as I think it's out of our hands. Please reopen/comment if you think I'm wrong in closing it.
