### ISSUE TITLE
Comment count doesn’t update after comment changes aren’t addressed

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1153]
**Steps to reproduce:**

1. Add comment on a line that has been changed
2. Update the lines that were previously commented on
3. Commit new changes
4. View file in Visual Studio

Notice that the file still shows the same count of comments, even after the lines have been updated and the comment no longer exists.

**Screenshot:**
![comment count not updated](https://user-images.githubusercontent.com/10103121/29437945-a09b3cc6-8368-11e7-8941-a728bbe5f4e9.PNG)
Note: 'Startup.cs' still shows 8 comments, but all the lines in the file have changed and the comments no longer exist.

tested build: VisualStudio#1150

**Comment by grokys** [comment]
We have a bit of a problem currently in that in some places we're using the editor contents to calculate the number of comments but in other places we're showing diffs that don't depend on the editor contents, but using the editor contents to calculate the number of comments.

I'm unable to reproduce the exact scenario you're seeing here, but I imagine it's coming from the same place.

**Comment by meaghanlewis** [comment]
Thanks for the explanation. I would imagine it's coming from the same place as well. I'll try to reproduce this and update this issue with any details later.

**Comment by grokys** [comment]
@meaghanlewis are you still able to repro this?

**Comment by meaghanlewis** [comment]
This looks good to me now 👍
