### ISSUE TITLE
VS exits with `Couldn't find merge base` exception

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1158]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio version: 2.3.0.18
- Visual Studio version: 2015

__What happened__ (with steps, logs and screenshots, if possible)

- Ended up on PR branch that had been deleted.
- VS crashes with the exception below:

![image](https://user-images.githubusercontent.com/11719160/29456696-db05102a-840e-11e7-8f28-0a6a08578ebb.png)

**Comment by jcansdale** [comment]
I haven't been able to consistently reproduce the merge base not being found. To reproduce the crash, I changed `GetPullRequestMergeBase` to always throw. Visual Studio then exits when a document with inline comments is opened.

**Comment by meaghanlewis** [comment]
It's not a crash, but I did encounter the `Couldn't find merge base` exception when trying to open this PR: https://github.com/AvaloniaUI/Avalonia/pull/1127.
![couldn t find merge base](https://user-images.githubusercontent.com/10103121/29589680-fb66d9d6-874a-11e7-8141-43fd8271be9f.PNG)

**Comment by jcansdale** [comment]
@meaghanlewis Thanks for the heads up. Hopefully now that it's not crashing Visual Studio, I have a chance of tracking down the issue! I'll investigate.

**Comment by jcansdale** [comment]
Does it consistently do this? If you try to open that PR again will it do the same thing?

**Comment by meaghanlewis** [comment]
Yes, it consistently does this with that PR in particular. Have no idea why.
