### ISSUE TITLE
"Getting Started" is too rudimentary

### ISSUE THREAD

**Issue by sjb-sjb** [github/VisualStudio#1182]
The "getting started" introduction for Visual Studio is too rudimentary, especially considering that it is linked from within Visual Studio itself. How do I create a local GitHub repository? How do I create a shared repository on a network file system? How do I move a repository from one place to another, such as from a local drive to a network drive or from there to GitHub? How do I link to a repository either on GitHub or on my network file system? What are the primitive operations, how does one use branches, what is the difference between Revert and Reset (and --mixed vs --hard), what is a pull request (and how do you make the request, how do you grant the request, how does one merge the results back), what does Cherry Pick mean, etc.

**Comment by shana** [comment]
Hi @sjb-sjb. You can check out the documentation on the extension at https://github.com/github/VisualStudio/tree/master/docs, https://github.com/github/VisualStudio/blob/master/docs/getting-started/index.md and https://github.com/github/VisualStudio/blob/master/docs/contributing/index.md

There is also git and GitHub documentation at https://help.github.com/, where you can find basic and advanced information about all of these operations, and training at https://services.github.com/on-demand and https://services.github.com/on-demand/windows/visual-studio.

I hope that helps!
