### ISSUE TITLE
Issue while accessing a file in repository through php code

### ISSUE THREAD

**Issue by Rrrajat** [github/VisualStudio#1185]
<?php
// your code goes here
    $respone=new \stdClass();
   $respone->displayText="some text here";
    $respone->source="any text";
    echo json_encode($respone);
$fp = fopen(urlencode('https://github.com/Rrrajat/WEBHOOK/blob/master/results.json'), 'w');
fwrite($fp, json_encode($response));
fclose($fp);
?>

I'm trying to write into a file(results.json) stored in repository WEBHOOK but this program results in "Access denied while accessing the file". please help.

**Comment by shana** [comment]
This repository is for the Visual Studio plugin for GitHub. It's not for Visual Studio itself. If you think this is a problem with Visual Studio, you should use its [report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) functionality.
