### ISSUE TITLE
Exception thrown when opening diff of .cshtml file

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1186]
__Version__

- GitHub Extension for Visual Studio  version: 2.3.0.22
- Visual Studio version: 2017

__What happened__ (with steps, logs and screenshots, if possible)

When trying to open diff for a .cshtml file from a pull request I get this exception that looks like this:

```System.Collections.Generic.KeyNotFoundException: key at Microsoft.VisualStudio.Utilities.PropertyCollection.GetProperty(Object key) at GitHub.InlineReviews.Tags.InlineCommentTagger.Initialize() at GitHub.InlineReviews.Tags.InlineCommentTagger.GetTags(NormalizedSnapshotSpanCollection spans) at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__39.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)```

After getting this exception, I am not able to add inline comments to the diff of the .cshtml file

![exception for file type](https://user-images.githubusercontent.com/10103121/29586276-f6200cf6-873e-11e7-87d7-ce9a89a4779b.PNG)

Discovered this while testing with this project and PR: https://github.com/meaghanlewis/TestWebAppProject/pull/6

**Comment by grokys** [comment]
Interesting. Is the reproducible or did it happen one time? Also if it is reproducible, does it still happen after a restart of VS?

**Comment by meaghanlewis** [comment]
This is happening 100% of the time for me- even after I shut down and then re-open VS. I also tried with multiple PR's.
