### ISSUE TITLE
Clone in Visual Studio closes if you don't press the Clone button really fast

### ISSUE THREAD

**Issue by birbilis** [github/VisualStudio#1187]
With VS2017 15.3.2 community edition, the Clone in Visual Studio action from github.com opens up the pane that has the Clone button, but if you don't press it really fast it closes again and goes to Changes/Sync/etc. pane

other person has submitted this to VS bugs, but they pointed them to fill a bug this repo (said they identified this as issue in the extension). Can't find the bug reported here, so reporting it myself

**Comment by shana** [comment]
@birbilis Could you link to the VS bug report where they indicated it was an issue with GhfVS?

**Comment by birbilis** [comment]
I was seeing the bug report through the Visual Studio 2017 bug-reporting dialog, not sure if that is also at some website. Will look for it. Probably if you try to post a new bug (via Report a Problem... action) from inside Visual Studio and write github it will find it.

see screenshot
![image](https://user-images.githubusercontent.com/3461504/29615633-55c8892a-8817-11e7-8388-abb3e28857a2.png)

**Comment by birbilis** [comment]
I don't understand why the VS team didn't escalate this themselves and expect the user to go and do it. They seem to have just closed the bug, asking the user to fill a report here

**Comment by meaghanlewis** [comment]
Closing this out. Feel free to re-open if this still continues to be an issue.
