### ISSUE TITLE
ASP.NET Core 1.2, EF Core 1.2 App - several problems after update to VS 15.3.x

### ISSUE THREAD

**Issue by ManuelHaas** [github/VisualStudio#1189]
Hi,

I have an ASP.NET Core 1.2 (using .NET framework 4.6.2) app with EF Core 1.2. After updating Visual Studio 2017 to version 15.3.x the startup of the applicaton takes minutes or even ends in 5.2.3 - Bad Gateway.
The loading of static files takes minutes for some files that even have not changed. 
Also the creation of the database (if it was deleted in a previous step) takes several minutes!! Before update the creation takes a few seconds.
Any ideas what could be wrong?

**Comment by ManuelHaas** [comment]
I previously created an issue in aspnet (which cannot be referenced here):
https://github.com/aspnet/Home/issues/2156

**Comment by khellang** [comment]
This repository is for the Visual Studio plugin for GitHub. It's not for Visual Studio itself. If you think this is a problem with Visual Studio, you should use its [report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) functionality.

**Comment by ManuelHaas** [comment]
@khellang Sorry I didn't noticed that!
