### ISSUE TITLE
Update 2.3.3.38 Crashes Installer

### ISSUE THREAD

**Issue by Chris-Dickerson** [github/VisualStudio#1197]
v2.3.0.24

Restarting Visual Studio 2017 allowing VSIX installer to install the update, a request for raised privileges occurs and you're faced with the following dialog:

[Window Title]
vsixinstaller.exe

[Main Instruction]
vsixinstaller.exe has stopped working

[Content]
A problem caused the program to stop working correctly. Please close the program.

[Close the program] [Debug the program]

**Comment by dev-cdd** [comment]
Running Developer Command Prompt elevated and executing this command allowed the install to work:
vsixinstaller /logFile:d:\temp\log.txt GitHub.VisualStudio.vsix

**Comment by shana** [comment]
@dev-cdd So you tried to install the update in 2017, 2017 asked to restart, and then when it ran the vsix installer it did not ask for permissions and just crashed?

**Comment by dev-cdd** [comment]
@shana Correct, I restarted Visual Studio 2017 Pro and received an error from vsixinstaller.

**Comment by dev-cdd** [comment]
There's an update today, restarted VS 2017, elevated credentials when prompted, same crash.

**Comment by commonsensesoftware** [comment]
I had similar problem. I was upgrading from 2.2.0.10 to 2.3.1.30. I would get the prompt for elevation, but then nothing. No errors. No dialogs. Nothing.

I run as a least-privileged user (LUA), which is almost certainly the cause or at least strongly related. On whim, I logged interactively into my local administrator account to attempt the update that way. This time it worked flawlessly.

I actually had this behavior happen for two extensions. The behavior appears to be a regression or previously undetected issue with elevation in the vsixinstaller.exe.

Sorry, but didn't capture the logs from the vsixinstaller.exe, but hopefully this information will still be useful to someone.

**Comment by rekabis** [comment]
Can confirm, got the same error message with the attempted upgrade from 2.3.0.24 to 2.3.1.30:

> An unhandled Microsoft .net framework exception occurred in vsixinstaller.exe [5028]

Even downloading the update and running the command

>vsixinstaller /logFile:d:\temp\log.txt GitHub.VisualStudio.vsix

In an elevated Developer Command Prompt did not resolve the issue, nor did it go far enough to create a log file to analyze; the exact same error occurred.

My system: Win10Pro x64, VS2017 Community, all Win10 spyware disabled via W10Privacy, IISCrypto with PCI v3.1 applied, Group Policy of "System Cryptography: Use FIPS-compliant algorithms" enabled to solve Schannel system log error.

**Comment by jcansdale** [comment]
@tinaschrepfer @Michael-Eng,

We have had a number of reports of the VSIX installer crashing after Visual Studio has been restarted to update the extension. Do you have any idea what might be going on here?

It looks like it works when `vsixinstaller` is executed from an elevated Command Prompt.

**Comment by Michael-Eng** [comment]
I'm not aware of any issues in this area. It would help to have a callstack. Do you have a crash dump? can you check your event log to see if there's a callstack in the event log when the vsixinstaller crashed?

**Comment by dev-cdd** [comment]
Stack trace from event log attached. 
[event1.txt](https://github.com/github/VisualStudio/files/1280666/event1.txt)
[event2.txt](https://github.com/github/VisualStudio/files/1280667/event2.txt)

**Comment by Chris-Dickerson** [comment]
I am running Visual Studio 15.3.4 but the crash is still happening. Again -- run as limited priv, try to update, restart VS, raise privs, vsixinstaller crashes.

Current version: 2.3.2.32 New Version: 2.3.3.38

**Comment by Cliff-Miller** [comment]
I have the same issue. I followed @Michael-Eng and @shana instructions but the issue remain. Install failed at the half track, don't finish successfully.
 
[Install VSIXInstaller_6a4a07eb-408e-4f2d-a4dd-feecf08846bf.log](https://github.com/github/VisualStudio/files/1353472/Install.VSIXInstaller_6a4a07eb-408e-4f2d-a4dd-feecf08846bf.log)
[Uninstall VSIXInstaller_078b5c8d-459e-4c0a-8443-3cc0e7747ceb.log](https://github.com/github/VisualStudio/files/1353474/Uninstall.VSIXInstaller_078b5c8d-459e-4c0a-8443-3cc0e7747ceb.log)

**Comment by Michael-Eng** [comment]
From the install log:
**03/10/2017 11:11:36 - Package 'GitHub.VisualStudio,version=2.3.3.38' failed to install. System.IO.IOException: The file 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\GitHub\GitHub\NativeBinaries\amd64\git2-785d8c4.dll' already exists.**

For security reasons, we do not allow an extension to replace any files which are already existing. For some reason, this/these files were likely orphaned during the last uninstall. Please manually delete this file (and any other files under the GitHub folder) before attempting to install the extension.

**Comment by Cliff-Miller** [comment]
Thanks for your prompt reply, Machael.
I understand security reasons but I don't understand why when I reverse the install process, the uninstall algorithm don't clean and clear all trash files. This way the second reinstall will be succesfully without any warning or fail.
Thanks in advance.

**Comment by grokys** [comment]
Hi @Chris-Dickerson, are you still having the problem after following @Michael-Eng's suggestions?

**Comment by Chris-Dickerson** [comment]
@grokys I can't answer that as I uninstalled it. I just use a git client when I need it.

**Comment by Chris-Dickerson** [comment]
@grokys I didn't have to do any clean-up, I installed it without issue with the latest version - 2.3.6.391

**Comment by grokys** [comment]
Ok, great to know this got fixed, thanks for letting us know!
