### ISSUE TITLE
Cannot connect via regular GitHub account

### ISSUE THREAD

**Issue by markjbrown** [github/VisualStudio#12]
I am attempting to connect to GitHub but the Connect to GitHub dialog will not let me click on GitHub, it forces GitHub Enterprise. Any idea how I fix this? I don't currently and never had an Enterprise account. Screen Grab of the dialog below and a screen grab of my VS About dialog too.

thanks.

![image](https://cloud.githubusercontent.com/assets/800166/8889920/c3b0561a-32a2-11e5-872d-c290a4d9636c.png)

![image](https://cloud.githubusercontent.com/assets/800166/8889939/1525a9b4-32a3-11e5-966e-407ee99e6d50.png)

**Comment by Haacked** [comment]
Hi Mark! So normally, that would indicate that you're already authenticated to GitHub.com. You can double check this by going into the Team Explorer pane and clicking the "Manage Connections" button (the one that looks like a plug).

When you click that, you should see GitHub listed with "Clone | Create | Sign out" link buttons. If not, send me a screenshot of what you see.

Also, the About dialog unfortunately doesn't show the actual version of the extension. Go into Tools | Extensions and click on the Installed tab and select "GitHub Extension for Visual Studio". In the right pane, it'll show you the actual version number.

**Comment by markjbrown** [comment]
Ah, ok. I see it now. After I posted this I went and did a git clone from the cmd line then reopened the project and I can now see its clearly connected.

Thanks Phil. Appreciated it. Closing issue.
