### ISSUE TITLE
Always asked to sign out and back in to create gitst

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#1201]
- GitHub Extension for Visual Studio version: 2.3.0.24
- Visual Studio version: 2015

When I go to create a gist, I am prompted to sign out and back in:

![image](https://user-images.githubusercontent.com/1775141/29722610-ceedaae6-89c1-11e7-900c-58ae8b5ba283.png)

I can then create the gist, but if I exit the dialog and try to create a gist again, I'm prompted to sign out and back in again.

The "sign out and back in" workflow was needed for an old version where a user may be logged in with the wrong scopes. This functionality can be taken out now.

**Comment by shana** [comment]
@grokys Agree that we probably don't need the check anymore, but why is it suddenly broken?
