### ISSUE TITLE
[Feature Request] Stage Individual Lines or Chunks in a File (patching)

### ISSUE THREAD

**Issue by NZSmartie** [github/VisualStudio#1202]
With git's cli, you can stage parts of a file using interactive patch mode (e.g: `git add example.py -p`). Visual Studio Enterprise also supports adding individual lines to a ChangeSet but this is only supported with Team Foundation Server (TFS), So it's not a too much of a foreign feature to Visual Studio. But it is mildly surprising this feature hasn't been requested here before.

Staging chunks of a file is helpful with keeping commits clean by only staging relevant changes. Such as 
  - New features that required refactoring. 
  - Bug fixes during normal development that need to be commited and merged or rebased.
  - etc...

**Comment by jcansdale** [comment]
I can imaging your suggestion being very handy in combination with `git stash --keep-index`.

A while back I started working on something like this except for stashing parts of a file rather than staging. It's still very much in its early stages and I haven't had a chance to tidy it up and make it into a repo.

**Comment by jcansdale** [comment]
I really like this idea and might have a crack at it one day. An extension that could stage (or stash) individual lines from a file file would be really useful. 😄 

I'm going to close this issue because it's out of scope for a GitHub specific extension (it would work with any Git repo).

**Comment by NZSmartie** [comment]
> @jcansdale I'm going to close this issue because it's out of scope for a GitHub specific extension (it would work with any Git repo).

Where would you recommend I create this feature request? I thought this would be the best place as Github extension for VS is the tool I use for managing my git projects. Unless Visual Studio itself handles git repositories and I should make a request on their feedback forum?

**Comment by jcansdale** [comment]
> Unless Visual Studio itself handles git repositories and I should make a request on their feedback forum?

The low level Git functions are actually handled by Visual Studio, see here:
https://docs.microsoft.com/en-gb/vsts/git/share-your-code-in-git-vs-2017

The feature you suggested could work with any local Git repo and doesn't depend on being logged into any particular Git provider (GitHub or VSTS). This extension focuses on features that depend on a GitHub connection.

It would work well as a stand-alone extension that uses libgit2sharp to interact with the local repo. It's possible someone might have already started a project where it would be a good fit. If you find anything, please add a link from this issue!
