### ISSUE TITLE
Link in PR links to fork repo (not the target repo)

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1208]
- GitHub Extension for Visual Studio version: 2.3.2.30

![image](https://user-images.githubusercontent.com/11719160/29882984-a75b9428-8da6-11e7-838e-c3e6bce43e44.png)

![image](https://user-images.githubusercontent.com/11719160/29883016-c98abf10-8da6-11e7-81bc-be34fbfc5f1b.png)

Expected link to: https://github.com/jaredpar/VsixUtil/pull/6

**Comment by tsimbalar** [comment]
Same for the link "view on github" once you are inside the PR

![image](https://user-images.githubusercontent.com/160544/29970319-5ca7dfac-8f24-11e7-9193-7c53ec1ebedd.png)

**Comment by jcansdale** [comment]
@tsimbalar, ah thanks for the heads up. I hadn't noticed that one.

I've started working on it here #1214.
