### ISSUE TITLE
Wrong symbols in Xamarin.Forms application wizard

### ISSUE THREAD

**Issue by piolo94** [github/VisualStudio#1209]
Hi everyone! I'm using VS 2017 Community Preview 15.4.0 1.0. Today I've noticed that, after the upgrade to the last version of the preview, the wizard for creating an app with xamarin has nonsense writes instead of words. This situation makes quite impossible creating a new app. Could this be an encoding problem?
Here you are a [screenshot](http://imgur.com/a/ibGVk)

**Comment by meaghanlewis** [comment]
Hi @piolo94 , thank you for writing us. This is not a part of the GitHub for Visual Studio extension. The best way to submit this feedback to Visual Studio is to use the feedback tool in the editor so they can improve it. Good luck!
