### ISSUE TITLE
Invalid origin url crashes Visual Studio

### ISSUE THREAD

**Issue by rcorre** [github/VisualStudio#121]
1. Install the Github extension (1.0.14.0) on VS 2015
2. Add a remote 'origin' with url 'asdf'
3. Watch the fireworks

Any further attempts to connect to that repo will crash Visual Studio.
If you restart Visual Studio, it will remain connected, and opening Team Explorer will cause a crash.

Relevant parts of the call stack:

    System.dll!System.Uri.CreateThis(string uri, bool dontEscape, System.UriKind uriKind) Line 49
    System.dll!System.Uri.Uri(string uriString) Line 400
    System.dll!System.UriBuilder.Uri.get() Line 320
    GitHub.Exports.dll!GitHub.Primitives.UriString.ToRepositoryUrl()	
    GitHub.Exports.dll!GitHub.VisualStudio.Services.GetUri(LibGit2Sharp.Repository repo)	
    GitHub.VisualStudio.dll!GitHub.VisualStudio.Base.TeamExplorerItemBase.RepoChanged()	
    GitHub.VisualStudio.dll!GitHub.VisualStudio.Base.TeamExplorerNavigationItemBase.UpdateRepo(Microsoft.VisualStudio.TeamFoundation.Git.Extensibility.IGitRepositoryInfo repo)	
    GitHub.VisualStudio.dll!GitHub.VisualStudio.Base.TeamExplorerServiceHolder.NotifyActiveRepo()	
    GitHub.VisualStudio.dll!GitHub.VisualStudio.Base.TeamExplorerServiceHolder.ActiveRepo.set(Microsoft.VisualStudio.TeamFoundation.Git.Extensibility.IGitRepositoryInfo value)	
    GitHub.VisualStudio.dll!GitHub.VisualStudio.Base.TeamExplorerServiceHolder.CheckAndUpdate.AnonymousMethod__2(object r)	

It’s ultimately throwing a `UriFormatException`.

**Comment by shana** [comment]
Thanks for the report!

**Comment by shana** [comment]
The fix for this has been included in release v1.0.15.2 which is available on the releases section, from the website and from the VS gallery. Thanks again for the catch!

**Comment by rcorre** [comment]
Thanks! Just verified that it works on the new release.
