### ISSUE TITLE
Cannot push to existing remote GitHub repositories

### ISSUE THREAD

**Issue by a-einstein** [github/VisualStudio#1216]
- I am working in Visual Studio 2017 on several solutions versioned in Git repositories. 
- Those repositories ARE configured towards remote repositories on GitHub, as is shown in the 'Settings' through Visual Studio.
- They are the SAME settings as used by GitExtensions, in fact they share the same .git\config file . I AM able to perform a push there.
- But in Visual Studio with this extension 2.3.2.32 this option is NOT enabled. When trying to 'Publish to GitHub' the extension contradictingly says "This repository does not have a remote."
- Even when really executing this 'Publish' it reports success, but nothing has changed.
- Removing and adding the remote URLs, or fiddling with them, does not help.
- I HAVE seen this functionality working on (some) of the same repositories in the past.

So, what is happening? Am I missing something, or is this a bug? Please help.

I would like to see this working to be able to push directly from Visual Studio, and avoid the extra step of pushing through GitExtensions.

By the way, it would be helpful to have a test option on the remote connections, like there is in GitExtensions.

**Comment by grokys** [comment]
@a-einstein oh dear, this one really fell through the cracks. Sorry for not responding. Did you get any further with this problem? Was this happening with a public or private repo?

**Comment by a-einstein** [comment]
Those are public repositories. 

We are some versions further of Visual Studio and GitHub.VisualStudio, I cannot test it again right away, I am in the middle of something. Please try it yourself in the mean time.

**Comment by grokys** [comment]
When you have a moment, just to clarify, your description mentions both "Publish to GitHub" and "Push" - are you talking about the Synchronization page in Team Explorer?

![image](https://user-images.githubusercontent.com/1775141/33958972-5672b6d4-e046-11e7-9d1a-13a65176f70d.png)

Or are you talking about "Publish to GitHub" here:

![image](https://user-images.githubusercontent.com/1775141/33959098-bc1593ee-e046-11e7-82ef-d6c16a8422c8.png)

If the former, this is Visual Studio functionality so you will have to report the problem to Microsoft: https://developercommunity.visualstudio.com

If the latter, the the is something strange going on with the remotes in your local repository. When you have time, if you could send a zipped copy of your repository to support@github.com, mentioning me I will investigate it further.

**Comment by a-einstein** [comment]
I expect to make a commit & push tomorrow in one of my repositories. I will check how the situation is now.

**Comment by a-einstein** [comment]
It seems I unintendedly closed this.

**Comment by a-einstein** [comment]
I Just tested on one of my repositories with GitHub.VisualStudio 2.3.6.391.
- I did a 'Commit All and Push' in 'Changes'. That worked all right.
- I did a 'Commit All' from 'Changes', then a 'Push' from 'Synchronization'. That worked all right too.

Looking closely at your question I was puzzled, because I sort of saw a mixture of both GUIs. I then disabled the extension and realised I did not even use it. I previously assumed the interaction with GitHub came from your extension, but apparently  it did not. I probably do not even need it.

I am not sure what was bothering me previously. I think I used the second scenario, but maybe in an other repository. I will see what happens there, if I come to it.

For the moment I conclude that it is not your extension. But I wonder what that adds to Visual Studio anyway.

**Comment by grokys** [comment]
Thanks for the response - glad you seem to no longer have the problem. Aas for what the extension brings to Visual Studio, you can look at [our docs](https://github.com/github/VisualStudio/tree/master/docs) but briefly:

- Logging in to GitHub and GitHub Enterprise instances (with 2fa)
- Publishing existing projects to GitHub
- Creating new repositories on GitHub
- Cloning from your repositories GitHub
- Viewing Pull Requests and diffs in the IDE
- Commenting on Pull Requests
- Creating Gists from the editor
- Navigating from a line of code in the editor to the line on GitHub

Hope that helps! I'm going to close this issue now, but let us know if you have any more questions.
