### ISSUE TITLE
Inline-comment doesn't appear immediately when using Open Changes in Solution

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1233]
- GitHub Extension for Visual Studio version: 2.3.4.40 (dev)
- Visual Studio version: 2015

__What happened__ (with steps, logs and screenshots, if possible)

1. Open https://github.com/grokys/PullRequestSandbox/ in VS
2. Open details of PR 29 in GitHub pane
3. `View Changes in Solution` on `Guard.cs`
4. Try to add comment on line 15

After clicking `Comment`, the inline-comment doesn't  show up immediately.
If I close and reopen `Guard.cs`, the comment appears on the correct line.

I believe this regression was introduced with #1230.

//cc @grokys

**Comment by meaghanlewis** [comment]
Hey @jcansdale im unable to repro this issue as well. I'm wondering what's different about our machines. Can you still repro this?

What about you @grokys?

**Comment by jcansdale** [comment]
Hi @meaghanlewis,  yes I'm still seeing this. I think it might be specific to `View Changes in Solution` (which requires the PR branch to be checked out). In my description above, I'd written `Open Changes in Solution`, which was wrong! Maybe that's why you couldn't repro it?

**Comment by meaghanlewis** [comment]
Okay, thanks @jcansdale 👍 . This does seem to be specific to `View Changes in Solution`.

**Comment by meaghanlewis** [comment]
I believe this issue is fixed by: https://github.com/github/VisualStudio/pull/1269
