### ISSUE TITLE
Remove option to connect to GitHub when already connected

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1235]
__Version__
- GitHub Extension for Visual Studio  version: 2.3.3.38 (and earlier)
- Visual Studio version: 2015 & 2017

__What happened__ 
- When you're already connected to GitHub, from Team Explorer- Connect go to Manage Connections > Connect to GitHub
- The connect modal opens with the option set to GitHub Enterprise. The GitHub option is not able to be selected

![cant select github](https://user-images.githubusercontent.com/10103121/30565547-883dfbe0-9c7d-11e7-8bed-309f2cf08b71.gif)

__What I expect__
Don't show the option to Connect to GitHub under the Manage Connections menu.

**Comment by shana** [comment]
This is by design, you can be connected to both at the same time, and many users are.
