### ISSUE TITLE
Why is the VisualStudio version saved in the solution file

### ISSUE THREAD

**Issue by Danthar** [github/VisualStudio#1245]
Its concerning the line:

`VisualStudioVersion = 15.0.26730.15` Which can differ based on whatever VS version you are using.

I am working on projects with multiple people, and there is a difference between which visual studio versions are used between the team members. Some use the Community edition, others Professional or Enterprise. And ofcourse not everyone is updated to the latest version of their respective edition (in so far thats applicable).

However this causes for constant solution file updates when doing commits. Because every time someone opens the solution Visual Studio saves its current version string in the solution file. And frankly its highly annoying. Can't you simply remove this version line from the solution file format?

I mean (and this might be naive :P) how many schema versions of the solution file can there be ?

**Comment by jcansdale** [comment]
Hi @Danthar,

This is the repository for the GitHub Extension for Visual Studio, not for Visual Studio itself. You're not the first person to post a Visual Studio issue here. 😉 

We do feel your pain. This is definitely an issue and .sln files don't tend to merge very well!

> However this causes for constant solution file updates when doing commits. Because every time someone opens the solution Visual Studio saves its current version string in the solution file.

Is it every time, or just when someone adds/removes a project form the solution?

**Comment by jcansdale** [comment]
Closing, but I'm still interested to know when this happens.

**Comment by Danthar** [comment]
Well im using the visual studio community edition. And it seems opening the solution and saving changes in a file is enough. 

But sorry about misposting. Ill ask around on where to best report this issue.

**Comment by jcansdale** [comment]
I'm sure that must be annoying! For us it only seems to happen when adding/removing a project from the solution. We have a VS 2015 solution that some developers work on using VS 2017.
