### ISSUE TITLE
Keybinding

### ISSUE THREAD

**Issue by joshuaquiz** [github/VisualStudio#128]
There is no way to attach custom keybindings to any action. Or at least if there is, it isn't named anything remotely close to anything that makes sense.

**Comment by shana** [comment]
@joshuaquiz What keybindings would be useful for you? What actions do you use often?

**Comment by joshuaquiz** [comment]
I would like to set one for Ctrl+Alt+Shift+P for pending changes and Ctrl+Alt+Shift+L or something like that to trigger a sync.

**Comment by Haacked** [comment]
@joshuaquiz Thanks for the suggestions. The Git extension is created by Microsoft. We only work on the GitHub part of things. I'll forward your request to Microsoft by mentioning @acangialosi. There might be other channels such as [their UserVoice site](https://visualstudio.uservoice.com).
