### ISSUE TITLE
Automatically detect and run all test dll's

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1289]
**Background:**
In the past, we have not updated our tests to execute as new directories of tests were added. Because of this, some tests were not being run regularly.

**Goal:**
As a way to remedy forgetting which tests to run, it would benefit to have test dll's follow a similar convention so that they can be detected and run automatically without having to update the test commands and scripts in the future.

This task will require updating:
- test dll's to end in something like `\*.tests.dll` so that they can be recursively searched
- scripts that run the tests to tell them how to locate these test dll's
  - `scripts/test.ps1`
  - `appveyor.yml`

**Comment by grokys** [comment]
If we're going to with only building in AppVeyor, there is the "auto" testing mode: https://www.appveyor.com/docs/running-tests/#selecting-assemblies-andor-categories-to-test
