### ISSUE TITLE
Support for self signed certificates in GitHub enterprise

### ISSUE THREAD

**Issue by TobiasBreuer** [github/VisualStudio#1290]
- GitHub Extension for Visual Studio  version: 2.3.4.54
- Visual Studio version: 15.4.2

When trying to push changes to a repository on our local GitHub enterprise server, this push fails with the following message (see screenshot of output window):

![image](https://user-images.githubusercontent.com/17617068/32330936-e0176752-bfe1-11e7-8308-bea43476b57c.png)

When using the git command line (in my case git for windows) you will also get this message the first time. But - in contrast to the GitHub extension for VS - for the git command line, I can solve this by adding appropriate configuration to the .gitconfig file:

    [http "https://github.*******************.com"]
        sslCAInfo = "path\\to\\selvSignedCerts\\fileName.pem"
        sslCAPath = "path\\to\\selvSignedCerts\\"
        sslVerify = true

Hereby telling git, to - for this certain server - look into this pem file for information about the certificates found along the way. Using the command line now works without the issue.

Now the GitHub Extension obviously uses some other sort of configuration file (e.g. username and email have not been taken from the already existing .gitconfig).

Now my question is, how can I configure the extension to accept the self signed certificate the same way as I can do it for git...

Thanks and best regards,

Tobias

**Comment by TobiasBreuer** [comment]
After using Sysinternals Process Monitor, to figure out, which files are being processed when I trigger the push operation using the extension, I was able to figure out, that the extension actually uses a config file at

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\etc

and not the one used by the git-for-windows installation.

It would be nice, to be able to configure the git.exe and gitconfig to use, from within the options in VisualStudio. Currently it is not very obvious which exe and config is being used.

Best regards,

Tobias

**Comment by shana** [comment]
This is something that VS controls, not us, since MS is the one that builds the Git integration into VS 😢 
That said, it *should* be inheriting these settings from your .gitconfig, not just from the one in the installation directory.

@AArnott Do you know who best to ping about this?

**Comment by shana** [comment]
@TobiasBreuer This might be better logged in the VS support channel at https://www.visualstudio.com/vs/support/ and/or the vs community space at 
https://developercommunity.visualstudio.com/spaces/8/index.html, given that this is a VS Git issue and I don't think we can do much about it.

**Comment by AArnott** [comment]
Agreed. If you file the ticket at the developer community, we can route it to the right folks.

**Comment by grokys** [comment]
Closing as it looks like it's a VS problem.
