### ISSUE TITLE
GitHub Enterprise Repo Links are always SSL

### ISSUE THREAD

**Issue by Jaben** [github/VisualStudio#13]
First of all, thanks! Really liking the plugin so far!

But, one minor issue is our internal github enterprise install is not SSL and the repo in Visual Studio 2015 is http://, but the plugin converts all the links "Pull Request", "Pulse", "Graphs", "Issues" to https:// breaking the feature for us.

**Comment by Haacked** [comment]
Ah! Yeah, we need to use the scheme of the Enterprise URL and not just hard-code it to https.

**Comment by Haacked** [comment]
I'll fix this.

**Comment by Jaben** [comment]
Awesome! Thanks Phil!

**Comment by shana** [comment]
Fix released in v1.0.12.1 (website and VS gallery)

**Comment by fabriciogs** [comment]
Awesome! Thanks for this!
