### ISSUE TITLE
Pull error

### ISSUE THREAD

**Issue by carlossilva-tesco** [github/VisualStudio#131]
Hi,

At Tesco we have a private GitHub.
When I press "Sync or Push" from Visual Studio it fails and the output just shows:
<hr>
Opening repositories:
C:\git\repo
Error encountered while pushing to the remote repository: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

Inner Exception:
    An existing connection was forcibly closed by the remote host
<hr>
But if I do a "Pull" or "Fetch" works fine.

Can someone give me a clue what I'm doing wrong?

TY

**Comment by shana** [comment]
Feels like your remote host is killing your connection, maybe because of credentials? If you can pull and fetch but not push, perhaps you don't have permissions to commit in the repository or branch you're trying to push to?

**Comment by carlossilva-tesco** [comment]
How can I check which credentials this VS extension is using?

NOTE: I'm owner of the repository and the repository is private. In the past, if I did a pull request the sync works, but not anymore.

**Comment by shana** [comment]
Are you logged in to the GitHub extension? VS uses the credentials store in the credential manager that correspond to the address of your server, so perhaps these credentials have expired. Try logging out and in again to your enterprise github server via the Team Explorer Connect page, that might do the trick.

**Comment by carlossilva-tesco** [comment]
Just tried and happens the same.

In the meanwhile I installed Tortoise Git and works fine on the same PC :S

<hr>
Error encountered while pushing to the remote repository: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

Inner Exception:
    An existing connection was forcibly closed by the remote host
Error encountered while pushing to the remote repository: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

Inner Exception:
    An existing connection was forcibly closed by the remote host

**Comment by Haacked** [comment]
The push functionality is part of the Git extension proper. @acangialosi is there logging we could look at to see what's going on here?

@carlossilva-tesco Since the problem involves a private repository, you might want to contact [our support team](https://github.com/contact) to look at it from the GitHub.com side of things. We have logging we can look at to see if the problem is on our end.

**Comment by Bananas-Are-Yellow** [comment]
@carlossilva-tesco Did you find a solution to this? It's just started happening to me today. My git repository is in Visual Studio Online. The Push operation inside Visual Studio 2015 fails, saying:

`Failed to push to the remote repository. See the Output window for more details.`

The Output windows shows:

```
Error encountered while pushing to the remote repository: Error while copying content to a stream.

Inner Exception:
    Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

    Inner Exception:
        An existing connection was forcibly closed by the remote host
```

Tried signing out and signing in again, but no difference.

**Comment by lackovic** [comment]
Same problem here: "Pull" and "Fetch" works fine, but "Push" returns the message "Failed to push to the remote repository. See the Output window for more details.".

```
Error encountered while pushing to the remote repository: Local push doesn't (yet) support pushing to non-bare repos.
Failed to read index: 'C:/Dev/Project/.git/index' no longer exists
```
As for now I have resorted to using [SourceTree](https://www.sourcetreeapp.com/) for the pushes.

**Comment by Bananas-Are-Yellow** [comment]
I managed to get it to work using the command line:

```
git config http.postBuffer 524288000
git push --all
```

It seemed to be something to do with that particular set of changes to push. Once I got that pushed, everything has been fine pushing from inside Visual Studio since.

**Comment by SscSPs** [comment]
Just faced this problem, fixed it by using the github desktop to push the commits made.
