### ISSUE TITLE
Add GitHub option back to start page in VS2017

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1310]
__Tested on:__
Visual Studio version: VS2017, 15.4.3

This option was apparent in the last GHfVS release `v2.3.4.54` but stopped working after that. 
I notice the icon disappear after https://github.com/github/VisualStudio/pull/1282 was merged to master, but am not sure about the exact commit

__What happened__ 
Open VS2017 with the latest dev build on master and look on the start page.

**Expected: GitHub option is present**
![screen shot 2017-11-09 at 10 25 45 am](https://user-images.githubusercontent.com/10103121/32636973-332e8c7e-c56c-11e7-8f1e-f05db3277ffe.png)

**Actual: GitHub option is not present**
![screen shot 2017-11-09 at 10 23 13 am](https://user-images.githubusercontent.com/10103121/32636975-344fbd30-c56c-11e7-99eb-56573b94a7b7.png)

**Comment by grokys** [comment]
Ok, strange - just tried this on master in the experimental instance and it's working here.

**Comment by grokys** [comment]
One thing I notice is that in the experimental instance the Start Page package is listed under Extensions and Updates:

![image](https://user-images.githubusercontent.com/1775141/32674322-0884181c-c653-11e7-8b93-a199cf2496ae.png)

However in the main instance it _isn't_:

![image](https://user-images.githubusercontent.com/1775141/32674349-1b01ac02-c653-11e7-8c2c-260b581925ab.png)

My guess is that something in #1282 broke installing the secondary package.

**Comment by shana** [comment]
Likely this was broken by the fact that the `GitHub.StartPage.pkdgef` file was no longer included in the vsix. @meaghanlewis Could you test https://ci.appveyor.com/project/github-windows/visualstudio/build/2.3.5.307 and see whether this guess is correct and the start page is indeed fixed?

**Comment by meaghanlewis** [comment]
Yes, this issue is indeed fixed in build 2.3.5.307. Thanks @shana 🎉
