### ISSUE TITLE
Use Mads Kristensen's VSIX Gallery for GHfVS Beta feed

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1317]
Mads Kristensen (probably the most prolific creator of VS extensions) has created the VSIX Gallery for automatically publishing extension builds.

All a consumer of extensions needs to do is install the VSIX Gallery extension (yes, it's all very meta 😉).
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VSIXGallery-nightlybuilds

They then have access to automatic updates of extensions published to the site.

Here is how extensions get submitted to the VSIX Gallery:
http://vsixgallery.com/guide/dev/

**Comment by meaghanlewis** [comment]
Closing out this PR because we don't want every one of our AppVeyor builds to be uploaded to the VSIX Gallery
