### ISSUE TITLE
Configuring multi-enterprise sign-in

### ISSUE THREAD

**Issue by newmerator** [github/VisualStudio#132]
basically [customer] would love to access multiple GH:E instances with the VS plugin - anyone know if that's possible?

:bowtie:

**Comment by shana** [comment]
It isn't possible right now. It's something we can certainly add in the future, however. Is there a way of estimating how important this feature might be to our enterprise users? Is this a common thing, running more than one enterprise instance?

**Comment by Haacked** [comment]
@newmerator This is a public repository. Did you mean to post that information to the public?
