### ISSUE TITLE
User images not appearing next to viewed Pull Requests

### ISSUE THREAD

**Issue by awbushnell** [github/VisualStudio#1323]
- GitHub Extension for Visual Studio  version: 2.3.5.277
- Visual Studio version: Visual Studio Pro 2017 15.4.4

__What happened__ (with steps, logs and screenshots, if possible):

I noticed that the "profile" images appearing next to all the pull requests I see from our repo only ever shows the default image and not what I can see when on GitHub and viewing pull requests in our browser. The attached screen shot is that I see in github in Visual studio for all my PR's for example, yet on GitHub I do have a profile image that does appear...

![githubextensionimages](https://user-images.githubusercontent.com/11314686/32864327-c3fdd8bc-ca2c-11e7-8513-0bab3a7bff86.JPG)

**Comment by meaghanlewis** [comment]
Hi @awbushnell thanks for reporting this. I notice the missing user avatars as well while using an enterprise account. Do you also happen to be using GitHub Enterprise?

**Comment by awbushnell** [comment]
@meaghanlewis  Yes, this is an Enterprise account. :-)

**Comment by grokys** [comment]
This is happening on Enterprise because Enterprise doesn't seem to serve images over a Basic Auth connection for some reason. We'll need to get SSO working to fix this I think.

**Comment by grokys** [comment]
I've marked this issue as being fixed by #1373 as the best we can do is to allow the user to login to enterprise instances using SSO.

**Comment by grokys** [comment]
Related issue for desktop: https://github.com/desktop/desktop/issues/821

**Comment by sguthals** [comment]
Should we close this issue then?

**Comment by meaghanlewis** [comment]
Yes, i believe we can close this issue @sguthals . It wil automatically be closed once #1373 is merged.
