### ISSUE TITLE
Microsoft Edge downloads a .zip file of the current release from visualstudio.github.com

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1335]
- GitHub Extension for Visual Studio  version: 2.3.5.346 and up

__What happened__ (with steps, logs and screenshots, if possible)
1. Using Microsoft Edge, go to visualstudio.github.com
1. Download the latest release

**Actual behavior**
The release downloads as a .zip file

**Expected behavior**
The release downloads as a .vsix file

**Workarounds:**
- Use Chrome to download the latest release from the website
- Install the latest extension from the marketplace
- Install the latest extension from the gallery feed: https://github.com/github/VisualStudio#installing-beta-versions

**Comment by meaghanlewis** [comment]
Seems like an anti-malware thing: https://answers.microsoft.com/en-us/windows/forum/apps_windows_10-msedge/microsoft-edge-download-saves-under-wrong/18dc390d-0804-49cf-bae3-ac175d2b2510?auth=1

**Comment by jcansdale** [comment]
@meaghanlewis I'm using `Microsoft Edge 42.17134.1.0` and this now appears to be handled correctly.

I can now either open/install the .visix directly or save it as a .vsix.

![image](https://user-images.githubusercontent.com/11719160/43770618-d5293a72-9a34-11e8-89a4-349e5fac127c.png)

Shall we close this?

**Comment by meaghanlewis** [comment]
Yep @jcansdale let's close this out.
