### ISSUE TITLE
Unable to add comment to pull request

### ISSUE THREAD

**Issue by fzhangddt** [github/VisualStudio#1338]
Environment:
- GitHub Extension for Visual Studio  version: 2.2.0.10
- Visual Studio version: Visual Studio Professional 2017, version 15.4.3

I opened a pull request and clicked a file to compare the change, I didn't see the little icon "+" on the left to allow me to add a comment. Right click on the file, i didn't see any menu related with adding a comment. Please see the screen below. 

Also I read a msdn document about adding comments to pull request, the features to collaborate with comments are rich, such as setting the status as "Pending", "Resolved", but it looks like it is only available for VSTS, not github? https://docs.microsoft.com/en-us/vsts/git/pull-requests

![image](https://user-images.githubusercontent.com/33635024/33186701-74eece38-d040-11e7-9882-0168d2e66706.png)

**Comment by fzhangddt** [comment]
Ok, after i upgrade github extension to 2.3.6.991, I can see the icon "+" on the left. So this case is no longer an issue.

A side question, can we approve the pull request in visual studio github extension? I can't find the option.

**Comment by grokys** [comment]
Hi @fzhangddt - yes you needed to upgrade your extension to get the PR comment functionality.

Approving PRs isn't yet available, that should be coming soon however - we just need to decide how to bring proper PR reviews over to the client-side.
