### ISSUE TITLE
PR Details: Changed files list doesn't display deleted files correctly

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#1347]
**Version**: 2.3.6.391

Looking at PR https://github.com/haf/DotNetZip.Semverd/pull/104 in VS, the changed files list isn't rendering all the deleted files correctly.

Most of the contents of the src/Tools directory have been deleted:
![image](https://user-images.githubusercontent.com/310137/33321363-b6575b66-d445-11e7-89cc-436105b6496d.png)

But they're showing up as changed:
![image](https://user-images.githubusercontent.com/310137/33321345-abd3d796-d445-11e7-98dd-9ac8d6b1ca25.png)

**Comment by grokys** [comment]
This seems to be fixed on `master`:

![image](https://user-images.githubusercontent.com/1775141/33890735-5fd49b40-df54-11e7-96a0-aca464457cc0.png)

I suspect it was another libgit2sharp problem that was fixed by #1337.
