### ISSUE TITLE
Potential bug with upgrading from version 2.3.1.30 to version 2.3.6.391

### ISSUE THREAD

**Issue by sguthals** [github/VisualStudio#1358]
We've received a message in Halp regarding an error when upgrading from version 2.3.1.30 to version 2.3.6.391.

This is our newest release, so I'm not sure if this is user error, VS, or us. 

Seems to be on Visual Studio Enterprise 2017.

Logs are [here](https://gist.github.com/sguthals/5cfd9e3aa6cc6953626d2d2371b82c0e)

Ideas?

**Comment by jcansdale** [comment]
@sguthals This looks like #1295. 😞

I have a horrible feeling we're only seeing the tip of the iceberg. It's an installer issue and I'm not sure what can be done from our end. Unscrambling it can be a real pain for the user (see some of the comments).

**Comment by sguthals** [comment]
The user followed #1295 and it worked for them!
