### ISSUE TITLE
Creating pull request fails with: "Request failed with status code: 403"

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1361]
- GitHub Extension for Visual Studio version: 2.3.7 (dev)
- Visual Studio version: 2015

1. Clicked on `Pull Requests`, `Create New`:

![image](https://user-images.githubusercontent.com/11719160/33492765-fc73f83a-d6b5-11e7-8833-d01513cf6a45.png)

2. Entered title and description:

![image](https://user-images.githubusercontent.com/11719160/33492731-e55ee114-d6b5-11e7-8a5c-18df4711717e.png)

3. Request fails with `Request failed with status code: 403`.

Same happened after branch was created and pushed.

**Comment by grokys** [comment]
@jcansdale are you able to repro this still? 403 is a HTTP Forbidden, which suggests either:

1. You were logged in with another account that doesn't have access to the repo
2. There was a GitHub problem

**Comment by jcansdale** [comment]
Logging out and back in fixed this.  It has happened before. Leaving this issue open for the moment.

**Comment by barretot** [comment]
erases the axios dependency and reinstalls
