### ISSUE TITLE
Do not export IServiceProvider

### ISSUE THREAD

**Issue by AArnott** [github/VisualStudio#137]
VS extensions should not export `System.IServiceProvider` (without an explicit, non-default contract name). This is because this is a globally shared type name and if two folks exported it, it would cause everyone who imports it to fail since they expect only one export but got more than one. Generally speaking, you should only export your own types, or BCL types with an explicit contract name that has your namespace in it. 

For example, this is wrong:

```csharp
[Export(typeof(IServiceProvider))]
```

But this is OK:

```csharp
[Export("Github.ExtensionForVS.IServiceProvider", typeof(IServiceProvider))]
```

This is where [GitHub's extension violates this rule](https://github.com/github/VisualStudio/blob/master/src/GitHub.VisualStudio/Services/UIProvider.cs#L25).

Now in this particular case, if the `IServiceProvider` that you actually want is the VS global service provider, you don't need to export anything, but simply import `SVsServiceProvider` (which derives from IServiceProvider):

```csharp
[Import]
SVsServiceProvider GlobalServiceProvider { get; set; }
```

**Comment by Haacked** [comment]
It doesn't look like we ever import `IServiceProvider` anyways. We already import `SVsServiceProvider` in a couple of places. I have a fix coming.

**Comment by Haacked** [comment]
Ok, not so trivial. If I just remove that `Export`, the extension does not load. I'll need to defer to @shana to remind me of why we're exporting that interface directly.

**Comment by shana** [comment]
@Haacked Yeah, it'll require a few tweaks to things. We export that interface directly because the Desktop code does and we grabbed a lot of code directly off of it. But the desktop app controls its environment and we don't, so our constraints are different. I'll whip up a PR with the needed changes.

**Comment by AArnott** [comment]
Thank you, @Haacked

**Comment by Haacked** [comment]
@AArnott no problem, but it was @shana who did the actual work and deserves all the credit. :sparkles:

**Comment by AArnott** [comment]
Ah yes, Thanks @shana

**Comment by shana** [comment]
:smile:
