### ISSUE TITLE
GitHub pane displays text that is unreadable in the dark theme

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1382]
- GitHub Extension for Visual Studio  version: all
- Visual Studio version: VS2015 & VS2017

__What happened__
The GitHub pane shows unreadable text when a repo needs to be published and when not connected to a repository

**screenshot1: Repo is not on GitHub**
<img width="442" alt="screen shot 2017-12-12 at 4 25 37 pm" src="https://user-images.githubusercontent.com/10103121/33915939-1ca3e75c-df5b-11e7-85b0-bcad476cbccc.png">

**screenshot2: No repository**
<img width="385" alt="screen shot 2017-12-12 at 4 35 17 pm" src="https://user-images.githubusercontent.com/10103121/33915916-fed12c76-df5a-11e7-9020-47d5a71e7fd9.png">

**Comment by grokys** [comment]
In addition, the error message pane has a white background and unreadable text in the dark theme:

![image](https://user-images.githubusercontent.com/1775141/33936651-894ebf44-e000-11e7-8b2e-436054de65e8.png)
