### ISSUE TITLE
i  have no clue

### ISSUE THREAD

**Issue by oz90210** [github/VisualStudio#1395]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio  version:
- Visual Studio version:

__What happened__ (with steps, logs and screenshots, if possible)

**Comment by meaghanlewis** [comment]
Hi @oz90210 im going to close this issue now as it has no content. If you are experiencing a problem with the extension, feel free to open a detailed issue.

**Comment by oz90210** [comment]
> <https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf?changes=latest_minor&amp;language=objc>
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556123450000300)</sub>

**Comment by oz90210** [comment]
> 
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556221677000100)</sub>

**Comment by oz90210** [comment]
> 
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556221677000100)</sub>

**Comment by oz90210** [comment]
> <https://developer.apple.com/design/human-interface-guidelines/>
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556123898001200)</sub>

**Comment by oz90210** [comment]
> <https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf?changes=latest_minor&amp;language=objc>
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556123450000300)</sub>

**Comment by oz90210** [comment]
> Metal 2 - Apple Developer
<https://developer.apple.com/metal/>
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556232464003100)</sub>

**Comment by oz90210** [comment]
> pod install
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556234790000500)</sub>

**Comment by oz90210** [comment]
> pod 'iPhone-AR-Toolkit', '~&gt; 0.0'
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556234777000400)</sub>

**Comment by oz90210** [comment]
> <http://CocoaPods.app>
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556235293000900)</sub>

**Comment by oz90210** [comment]
> 
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556123450000600)</sub>

**Comment by oz90210** [comment]
> add a Facebook login button to your app add the following code snippet to a view controller.

import FacebookLogin

func viewDidLoad() {
    let loginButton = LoginButton(readPermissions: [ .publicProfile ])
    loginButton.center = view.center

    view.addSubview(loginButton)
}
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556236315002000)</sub>

**Comment by oz90210** [comment]
>PULL RUN INSTALL
<sub>[View in Slack](https://oz411.slack.com/archives/DJ4G8P6A2/p1556235529000800)</sub>

**Comment by oz90210** [comment]
> <https://gist.githubusercontent.com/alloy/62326fcbc5b8ef987c17/raw/8fa201cf402244466d63b50dc7aeeaf90b898e8f/README.markdown>
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW7204/p1556247754000500)</sub>

**Comment by oz90210** [comment]
> 
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556256763000100)</sub>

**Comment by oz90210** [comment]
Mnzka

**Comment by oz90210** [comment]
> 
<sub>[View in Slack](https://oz411.slack.com/archives/DJ4G8P6A2/p1556282577000100)</sub>

**Comment by oz90210** [comment]
> added an integration to this channel: <https://oz411.slack.com/services/BJ6KU2CMA|Zoom.ai>
<sub>[View in Slack](https://oz411.slack.com/archives/DJ2BJPGL8/p1556259169000100)</sub>

**Comment by oz90210** [comment]
> 
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556314756000100)</sub>

**Comment by oz90210** [comment]
> e EdEGhevz3osp6aLR18LDeQ, C9lgIhiPEVLPdQcWxruHmg, 69KccO9ChjF2ysRH8hszEw, cOjbTPExWRcIVUMW6FPV0A, qBUHZG87kFtDFXWFF1R_cw, NIrz7MjbtuHSvuvMpMD69w, T47--cKrR_OzeWlaJL7MSw, b6lPX22ZQNkKnScuuUsfIQ, ZO4KVpTuxLW1y7fatOFRig, lM1097VWBBsrrszow3hRyg, DFpIkE0J-B-vviNFVJCsjA, K8qSVrIWT9EZHAbhrGECmQ EdEGhevz3osp6aLR18LDeQ, C9lgIhiPEVLPdQcWxruHmg, 69KccO9ChjF2ysRH8hszEw, cOjbTPExWRcIVUMW6FPV0A, qBUHZG87kFtDFXWFF1R_cw, NIrz7MjbtuHSvuvMpMD69w... 
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556315360000500)</sub>

**Comment by oz90210** [comment]
PULL FORK

**Comment by oz90210** [comment]
> There are many different ways to style code with GitHub's markdown. If you have inline code blocks, wrap them in backticks: `var example = true`.  If you've got a longer block of code, you can indent with four spaces:

    if (isAwesome){
      return true
    }

GitHub also supports something called code fencing, which allows for multiple lines without indentation:

```
if (isAwesome){
  return true
}
```

And if you'd like to use syntax highlighting, include the language:

```javascript
if (isAwesome){
  return true
}
```
There are many different ways to style code with GitHub’s markdown. If you have inline code blocks, wrap them in backticks: var example = true. If you’ve got a longer block of code, you can indent with four spaces:

if (isAwesome){
  return true
}
GitHub also supports something called code fencing, which allows for multiple lines without indentation:

if (isAwesome){
  return true
}
And if you’d like to use syntax highlighting, include the language:

if (isAwesome){
  return true
}
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1556367864000500)</sub>

**Comment by oz90210** [comment]
> 
<sub>[View in Slack](https://oz411.slack.com/archives/CJ1PW71L4/p1557133781000100)</sub>

**Comment by oz90210** [comment]
> 
<sub>[View in Slack](https://oz90210.slack.com/archives/DHLP2LY64/p1554419912000200)</sub>
