### ISSUE TITLE
Open in Visual Studio within chrome isn't working

### ISSUE THREAD

**Issue by naveensrinivasan** [github/VisualStudio#140]
I have VS2015 installed on my machine and when I browse to a repo in chrome the button `Open in Visual Studio` is available. When I click on the button nothing happens.But where was `Clone in Desktop` works.

I was able to identify the issue. The `Open in Visual Studio` used the application launch url `git-client://clone?repo=https%3A%2F%2Fgithub.com%2Fakkadotnet%2Fakka.net`  
 The `clone in desktop` used this `github-windows://openRepo/https://github.com/akkadotnet/akka.net`

To debug the issue I looked at the registry for these keys

Here is the key for github-windows
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\github-windows]
@="URL:github-windows Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\github-windows\DefaultIcon]
@="C:\\Users\\nsrinivasan\\AppData\\Local\\Apps\\2.0\\70JOP006.JE2\\MPMCGQNV.LPW\\gith..tion_317444273a93ac29_0003.0000_12384c781d7f8ad4\\GitHub.exe,-1"

[HKEY_CLASSES_ROOT\github-windows\shell]

[HKEY_CLASSES_ROOT\github-windows\shell\open]

[HKEY_CLASSES_ROOT\github-windows\shell\open\command]
@="\"C:\\Users\\nsrinivasan\\AppData\\Local\\Apps\\2.0\\70JOP006.JE2\\MPMCGQNV.LPW\\gith..tion_317444273a93ac29_0003.0000_12384c781d7f8ad4\\GitHub.exe\" -u=\"%1\""

```

And here is registry setting for `git-client`
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\git-client]
@="URL:git-client"
"URL Protocol"=""


```
 
It is because there isn't a shell open command key provided for git-client.

**Comment by shana** [comment]
Thanks for the report!

@clboles @prasethu Sounds like VS is failing to register the handlers for git-client?

**Comment by prasethu** [comment]
@naveensrinivasan which OS is this?

**Comment by naveensrinivasan** [comment]
Windows 7

**Comment by prasethu** [comment]
ok there is a known issue with the registration of this protocol on Win7. This should be fixed in an upcoming update in Visual Studio.

Thanks for reporting.

**Comment by shana** [comment]
Thanks @prasethu! :smile:

**Comment by SamB** [comment]
@prasethu: Got a reference for that issue being known/expected to be fixed? I can't seem to get google to realize the importance of the dash in the URL scheme name ...

**Comment by prasethu** [comment]
Unfortunately, this issue didn’t make the bar to be fixed.

**Comment by SamB** [comment]
Do you by any chance know what the command is supposed to be for the `open` verb?

**Comment by osya** [comment]
This issue still exists. Visual Studio 2015. Windows 10 x64
