### ISSUE TITLE
Authentication Error VS2015 V2.3.6

### ISSUE THREAD

**Issue by sguthals** [github/VisualStudio#1404]
We have a user who is having trouble logging in through our extension. This message came from Halp:

Have Visual studio 2015 installed with windows 10 environment. Also have the 2.3.6 extension for GitHub installed.
In visual studio, see the GitHub login but keep getting a ' must authenticate to use this api error'.

I've asked the following:
Have you been able to login before at all through our extension? 
Did you have a previous version that had worked?

**Comment by grokys** [comment]
Not sure what's happening here but as a wild guess I'd say that going into Windows Credential Manager and deleting all git credentials may well solve the problem.

**Comment by sguthals** [comment]
Followed up again today to see if that solved their problem.

**Comment by meaghanlewis** [comment]
Going to close this out for now as we haven't heard back from the user and haven't been able to repro this problem ourselves.

Please reopen if this error is encountered again.
