### ISSUE TITLE
PR session doesn't get cleared when user leaves the PR branch

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1440]
- GitHub Extension for Visual Studio version: 2.4.0 (dev)

__What happened__ (with steps, logs and screenshots, if possible)

This issue is most obvious when using #1396.

1. Open a PR branch
2. Move to non-PR branch of solution that isn't in Git
3. Status bar continues to show original PR

### Related

[Feature] Show current PR on status bar #1396

**Comment by meaghanlewis** [comment]
Thanks for opening this @jcansdale!
