### ISSUE TITLE
Missing information in metrics

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#1466]
All the non-int fields are missing in the metrics that are being sent, caused by https://github.com/github/VisualStudio/blob/master/src/GitHub.Exports/Models/UsageModel.cs#L51. This means we're missing `appVersion`, `vsVersion`, `lang`, `isEnterpriseUser` and `isGitHubUser`.

**Comment by meaghanlewis** [comment]
This was fixed in release 2.4.2
