### ISSUE TITLE
Prompted for "token" when signing into GitHub enterprise...

### ISSUE THREAD

**Issue by awbushnell** [github/VisualStudio#1474]
- GitHub Extension for Visual Studio  version: 2.4.1.1219
- Visual Studio version: Microsoft Visual Studio Professional 2017 Version 15.5.5

__What happened__ (with steps, logs and screenshots, if possible):

When trying to log into our Enterprise server, upon entering our sever, and it correctly identifying it, I get prompted for a personal access token, instead of my username/password as I am typically prompted for to access our server....   See screenshot:

![capture](https://user-images.githubusercontent.com/11314686/35983904-25476e4a-0cc1-11e8-8902-a9b74c8fabc1.PNG)

**Comment by grokys** [comment]
If you're needing to login in the meantime, we're in the process of adding instructions for creating a token here: https://github.com/github/VisualStudio/blob/abff93d8c387c34e18b0fc5e3097893c2719f474/docs/getting-started/authenticating-to-github.md#authenticating-to-github

**Comment by awbushnell** [comment]
@grokys  We are currently on version 2.11.6 but "soonish" will be moving to 2.12

**Comment by awbushnell** [comment]
@grokys I managed to generate a token and am logged in now. thanks

**Comment by shana** [comment]
@awbushnell Just to confirm, you used to login with just username/password before and now it's always asking for a token, correct?

**Comment by awbushnell** [comment]
@shana Yes that is correct, I do not ever recall getting prompted for a token.

**Comment by grokys** [comment]
Yes, I think this should be considered a bug. We're querying the server metadata to see if it accepts a username and password. If it doesn't accept a username and password we prompt for a token.

The bug comes about because enterprise instances <2.12 don't actually return that metadata, in which case we assume that the server doesn't accept a username and password. We should instead assume it does.

**Comment by DaleGardner** [comment]
I just encountered the same issue. As it happens, our enterprise is updating to 2.12.4 tomorrow. Planning to try logging in then and see if it works. :)

**Comment by grokys** [comment]
Hi @awbushnell - if you have a moment could you try the vsix [here](https://ci.appveyor.com/project/github-windows/visualstudio/build/2.4.3.1481/artifacts) and see if it fixes your login problem? 

I'd advise switching back to the stable vsix once you've tested, as this version has not been through our testing process.

**Comment by awbushnell** [comment]
@grokys  Thank you, I gave that a try, and yes that worked, prompted me for username and password and token as expected with our current enterprise server/version etc..
