### ISSUE TITLE
Sections should remember last state (collapsed or expanded)

### ISSUE THREAD

**Issue by OsirisTerje** [github/VisualStudio#149]
When one open the Manage Connection hub in Team Explorer, the github node comes up at top, which is fine, but it always comes up expanded, which can be sort of annoying if one wants quickly to see what is further down.
The github node should either:  1) start collapsed  or 2) remember if one sets it collapsed or expanded for the next time the same hub is opened.

**Comment by shana** [comment]
Thanks for the report!

All sections in Team Explorer are expanded by default, but it should definitely remember if it was last expanded or collapsed whenever you go to the Connect hub, so you don't have to keep closing it. I'll add it to the bug list :blush:

**Comment by OsirisTerje** [comment]
Thanks !

One comment to this is that the github node places all repositories in a long list, but they could have been split the same way as TFS does, having a github organisation equal to a Team Project.  Then it would be easier to have open only the nodes of interest, the rest collapsed, as one can do with the TFS nodes. 
 
Anyway, having it remember the state, as the Team Project nodes seems to do, will obviously help and make it consistent.

**Comment by shana** [comment]
I'm not sure I understand what you mean by having a github organisation equal to a Team Project. Do you mean having separate (collapsable) sections per user/organizations that you're a part of?

**Comment by OsirisTerje** [comment]
Exactly !

**Comment by shana** [comment]
Sounds like a great idea!

**Comment by OsirisTerje** [comment]
Should it stay here, or be a separate issue ?

**Comment by shana** [comment]
@OsirisTerje Separate issue, I've logged it :smile:
