### ISSUE TITLE
Scrollbar only on hover can be confusing

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#15]
Imported from https://github.com/github/VisualStudioInternal/issues/412

User noticed a bunch of repositories were "missing".

![image](https://cloud.githubusercontent.com/assets/19977/8016966/0f394a4e-0ba0-11e5-977e-b0acddedbca4.png)

It turns out, the user hadn't scrolled down.

![image](https://cloud.githubusercontent.com/assets/19977/8016969/1816f6de-0ba0-11e5-9105-c647ad2345bc.png)

The UI is a bit confusing in this case. The scrollbar isn't visible until you hover and even then, in some cases, it isn't very noticeable.

**Comment by meaghanlewis** [comment]
The scrollbar is always present now in the clone dialog.
