### ISSUE TITLE
branch list wont sync with the repo

### ISSUE THREAD

**Issue by yvz5** [github/VisualStudio#1504]
- GitHub Extension for Visual Studio version: 2.4.2.1331
- Visual Studio version: Visual Studio Professional 2017 (Version 15.5.7)

if a branch is added outside of visual studio (on github for example), the list of branches in visual studio wont show this new branch. refresh button does nothing. probably a cache issue. deleting the db file under %APPDATA%\GitHubVisualStudio did not help.

**Comment by grokys** [comment]
Hi @yvz5,

The branch list is actually part of Visual Studio Team Explorer and not the GItHub for Visual Studio extension, so you'll need to report this to microsoft. The best way to do this is via the "Send Feedback" button in Visual Studio, next to the Quick Launch text box or the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) site

Closing this as we can't do anything about it, but hopefully MS can point you in the right direction!
