### ISSUE TITLE
How to post colored codes?

### ISSUE THREAD

**Issue by MkazemAkhgary** [github/VisualStudio#1505]
I don't like to see this code all black. how can I make this colored when posting on GitHub?

    public class MyClass
    {
        int foo; // comment
    }

---

 for example I'd like to see red keywords and green comments. but any style is better than plain black.

looks ugly. please help 😭

**Comment by jcansdale** [comment]
@MkazemAkhgary,

You can start a code block with ```c# to get C# highlighting, like this:

```c#
    public class MyClass
    {
        int foo; // comment
    }
```

This works with a bunch of other languages as well. I hope that helps.

**Comment by MkazemAkhgary** [comment]
```c#
    public class MyClass
    {
        int foo; // comment
    }

**Comment by MkazemAkhgary** [comment]
@jcansdale WOW thank you. you are life saver. 😄
