### ISSUE TITLE
Dismiss the warning message after logging in from the Sync page

### ISSUE THREAD

**Issue by Haacked** [github/VisualStudio#151]
Repro steps:
1. Log out of both GitHub and GitHub Enterprise.
2. Open a solution that's in a repository that has its remote "origin" pointing to a GitHub repository.
3. Navigate to the "Sync" tab in Team Explorer.
4. You should see a warning that tells you you are not logged in. Click the link to log in.
5. Log in with proper credentials.

Expected: The warning message goes away.
Actual: The message remains until you dismiss it manually.

**Comment by gitexperience** [comment]
I think this bug is solved , it now goes away automatically :+1:
