### ISSUE TITLE
Load last loaded solution not working 

### ISSUE THREAD

**Issue by big-green-gecko** [github/VisualStudio#1514]
I have changed the startup setting to 'Load last loaded solution', but everytime I close and reopen Visual Studio (am using Community edition) a blank screen appears with nothing loaded.  

![visual studio nothing loaded](https://user-images.githubusercontent.com/29667348/36921969-25a9b04c-1e5e-11e8-9a99-e01e1f565117.png)

A lot of people seemed to be having the same issue a couple of years ago but it seems like it was fixed with new updates.  Don't know if there has been a recent update that made it revert back to having this issue or whether I'm just doing something wrong.

**Comment by meaghanlewis** [comment]
👋 @big-green-gecko. This repo is specifically for the GitHub for Visual Studio extension and the problem you are experiencing is with Visual Studio itself. You should submit this feedback with them. The best way to do that is to use the feedback tool in Visual Studio, or reach out to Microsoft for support at: https://www.visualstudio.com/support/
