### ISSUE TITLE
GitHub pane not updated after adding repo to GitHub

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1519]
- GitHub Extension for Visual Studio version: 2.4.3 (dev)
- Visual Studio version: 2017

1. Clicked on the `Get Started` button from the `GitHub` pane:
![image](https://user-images.githubusercontent.com/11719160/37031301-2c850490-2136-11e8-801d-09c8e7359b2b.png)
2. Created a name and description for my repository and published.
3. It changed to `Team Explorer - Home` which appears correctly.
![image](https://user-images.githubusercontent.com/11719160/37031380-714c856c-2136-11e8-9ded-18d9b5d2250b.png)
4. Click on `Pull Requests` button.
5. The `GitHub` pane still says: "This repository is not on GitHub".

There is no option to refresh, so I reloaded Visual Studio. The `GitHub` pane appears correctly with an empty Pull Request list.

It would be nice if we could show them a welcome/getting started page.

**Comment by meaghanlewis** [comment]
I've been noticing this whenever I'm not signed in to GitHub and I'm on the GitHub pane. After clicking `Get Started` the Sign in dialog box opens.  Once I authenticate, the pane loads with the Pull Requests. 
![shows repo is not on github](https://user-images.githubusercontent.com/10103121/38906078-50e7bd42-4269-11e8-903f-e249e317d203.gif)


Also noticed that after sign out and sign in this appears correctly, but once VS is restarted the `Get Started` content is displayed in the pane.
![shows sign in option](https://user-images.githubusercontent.com/10103121/38906123-7c3630e6-4269-11e8-9e31-48986428c3ab.gif)

**Comment by grokys** [comment]
> Also noticed that after sign out and sign in this appears correctly, but once VS is restarted the Get Started content is displayed in the pane.

@meaghanlewis are you still able to repro this? If I'm understanding correctly, you're saying that starting VS while logged in shows "Sign in to GitHub"?

**Comment by grokys** [comment]
@jcansdale just tried your original repro and it seems to work now. I suspect this was fixed by the changes to `TeamExplorerContext`? Could you try again and confirm?

**Comment by jcansdale** [comment]
> @jcansdale just tried your original repro and it seems to work now. I suspect this was fixed by the changes to TeamExplorerContext? Could you try again and confirm?

Yes, this seems to work great now! 🎉 

@meaghanlewis can we close this issue and create a new one with the issue you're seeing?

**Comment by meaghanlewis** [comment]
New issue opened here: https://github.com/github/VisualStudio/issues/1848

Will close this out.
