### ISSUE TITLE
Login prompt appears on primary monitor, not the current monitor VS is running in.

### ISSUE THREAD

**Issue by blowdart** [github/VisualStudio#1525]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio version: 2.4.2.1331
- Visual Studio version: 2017 / 15.6.0

I cycled my TFA codes last week and finally went to commit something from home and it "hung", or at least appeared to. VS was on the secondary monitor. The GitHub plugin login window was on the primary monitor. I didn't notice it all tucked away on the left for a few minutes, instead I cursed out Visual Studio, unfairly, poor VS.

If the login window could appear on the same monitor that VS is running in that'd be a nice thing, assuming VS gives you that information of course.

**Comment by sguthals** [comment]
Hi @blowdart 

Thanks for letting us know! We will check this out and try to repro it!

**Comment by StanleyGoldman** [comment]
Hey @blowdart, I tried my best to reproduce this issue, but I was unable to.

![gif](https://i.imgur.com/BXqqT9Q.gif)

Could you send a `gif` of you reproducing this?

**Comment by blowdart** [comment]
I finally got a repo. Kind of. The same thing happened in the Github desktop app this morning, so I believe this is a Windows bug, as I assume you're the built into windows authy browser control thing. So I'll go talk to them :)

![Finally](https://user-images.githubusercontent.com/796298/38682237-6f31bbde-3e1f-11e8-92d6-d5b0630e79d6.png)

**Comment by grokys** [comment]
Ah, that makes more sense. That login dialog is actually part of https://github.com/Microsoft/Git-Credential-Manager-for-Windows not GitHub for Visual Studio. It appears when you try to push/pull and are not logged into github.

We really should try to make those dialogs look more different!
