### ISSUE TITLE
Cannot delete remote branch after updated to 15.6

### ISSUE THREAD

**Issue by Magentaize** [github/VisualStudio#1526]
- GitHub Extension for Visual Studio version: it doesn't tell me that
- Visual Studio version: 15.6.1

__What happened__ (with steps, logs and screenshots, if possible)

Switched to "Branches" tab, right click "remotes/origin" and select "Delete Branch From Remote", it works well in the past, however, after updated to VS 15.6, it stops work and says:
>Failed to delete the branch from the remote repository. See the Output window for more details.

But output window says:
>Error encountered while deleting branch from the remote repository: Git failed with a fatal error.
PushCommand.ExecutePushCommand

**Comment by meaghanlewis** [comment]
Hi @Magentaize, thanks for reporting this issue. I just tried to repro this on 15.6.1.

At first, I saw the same error as you, and was prompted to login.
> Error encountered while deleting branch from the remote repository: Git failed with a fatal error.
PushCommand.ExecutePushCommand

After re-authenticating, I was able to delete branches under **remotes/origin** just fine. Could you try to sign in with GitHub again and then delete a remote branch?

**Comment by Magentaize** [comment]
@meaghanlewis Thanks for your patient replay, I tried to sign out and sign in again, and git works well.
