### ISSUE TITLE
Funky Highlight issue in Windows 10

### ISSUE THREAD

**Issue by bchavez** [github/VisualStudio#1541]
Hello,

Regarding #1539, /cc @meaghanlewis

- GitHub Extension for Visual Studio version:
![37543945-8812eca4-2920-11e8-8501-48c954dc7375](https://user-images.githubusercontent.com/478118/37581465-079457ce-2b06-11e8-805c-0f1c75472de6.png)

- Visual Studio version:
![37498873-ee9cfc9c-287d-11e8-964c-0c90fe7b2042](https://user-images.githubusercontent.com/478118/37581471-0b42907a-2b06-11e8-918e-551ec92d6241.png)

------
Screen Recording:
------

![37554855-eb660b1c-299b-11e8-90ef-c5ef4b82e9ea](https://user-images.githubusercontent.com/478118/37581864-91bc3f56-2b07-11e8-9841-5b2eb88dccd7.gif)

---

I exported the **Windows 10** theme I used to test this.

* Download exported theme file: [`BROKEN_THEME.zip`](https://github.com/github/VisualStudio/files/1823943/BROKEN_THEME.zip)
* Unzip `BROKEN_THEME.zip` on a **Windows 10** VM and extract `BROKEN_THEME.deskthemepack`.
* Double-click on the `BROKEN_THEME.deskthemepack` inside **Windows 10**.  `BROKEN_THEME` should activate.
* Also, ensure you're using **Visual Studio 2017** standard ***Dark Theme***.
![vmware_1355](https://user-images.githubusercontent.com/478118/37581714-fe3e89dc-2b06-11e8-9bcf-fca7cb68e0c6.png)
* Reboot. Then test.

For reference, here is the color of a normal drop-down menu item in **Visual Studio** with `BROKEN_THEME`:

![vmware_1357](https://user-images.githubusercontent.com/478118/37582196-042e5898-2b09-11e8-8bbe-4a90152d30f4.png)

----

:art: :dash: **[Marshmello - CoLoUR](https://www.youtube.com/watch?v=6UhNJC8OyVA)**

**Comment by jcansdale** [comment]
@donokuda would it make sense to change the GitHub pane menus to use the same colors as the VS menu? What colors are we using at the moment?

**Comment by grokys** [comment]
This was fixed by the rework of the PR list 🎉
