### ISSUE TITLE
Doubleclicking GitHub project should take me to the local repo, not prompt for a solution

### ISSUE THREAD

**Issue by jessehouwing** [github/VisualStudio#155]
I often use Visual Studio alongside other tools, and when part of my project is synced through visual I may as well use its git tools. But with the recent change to always prompt to open a solution when I doubleclick the github project in Visual Studio.

This is contra-intuitive to users of the Team Explorer interface (as TFVC and Git on VSTS behave differently) and blocks me from using the GitHub tools without a solution (unless I scroll down to the bottom and open the local repo from there, which will bring me to the place I expected the doubleclick to take me.

**Comment by shana** [comment]
@clboles Yes, pretty much that. As far as I can tell, there's no way to switch the source control context programmatically (all of the calls that the Connect page's local repo list does are internal and private), but maybe I missed an API somewhere?

**Comment by tocsoft** [comment]
There is an alternative to always showing a open solution dialog, I propose:

1. If there is one solution in the repo just open it without prompt (probably the case most of the time)
2. If there are multiple solutions ;
 1. if they have opened a solution before open whichever on they previously opened.
 2. show the solution dialog and cache which solution they opened.

Also you should also add a context menu to allow you to choose any solution even if they only have one in the repo, just in case they still want to choose something different anyway.

**Comment by jessehouwing** [comment]
With the new open folder feature, when there is no sln file, open the
folder as if it were a solution in Visual Studio 15.

**Comment by meaghanlewis** [comment]
this appears to have been fixed in: https://github.com/github/VisualStudio/pull/834
