### ISSUE TITLE
Can't push

### ISSUE THREAD

**Issue by pri7851** [github/VisualStudio#1551]
This is the error message I am getting in visual studio: 

HttpRequestException encountered.
   An error occurred while sending the request.
cannot spawn askpass: No such file or directory
could not read Username for 'https://github.com': terminal prompts disabled
Pushing to https://github.com/pri7851/RecruitPursuit.git

I can pull, but I can't push.  I've uninstalled and reinstalled everything and have deleted and then added my credentials in Windows Credential Manager.  I've checked different forums, but I'm not seeing anything that relates to my problem.

**Comment by grokys** [comment]
Hi @pri7851, a couple of weeks ago GitHub turned off support for TLSv1 and 1.1. To fix this issue update your Visual Studio to 15.5.7 or later.

Many users have reported this issue [here](https://github.com/github/VisualStudio/issues/949)
