### ISSUE TITLE
PR viewed in Visual Studio only shows 300 of 702 files changed 

### ISSUE THREAD

**Issue by mattnewport** [github/VisualStudio#1553]
- GitHub Extension for Visual Studio version: 2.4.3.1737
- Visual Studio version: 15.5.6

__What happened__ (with steps, logs and screenshots, if possible)

When opening a PR with 702 files changed with the GitHub Extension for VS, only 300 changes are shown and no message is shown indicating that some changes are not being displayed. The screenshots below show the PR as seen on the GitHub site with all 702 changes and the same PR viewed in the VS Extension with only 300 changes shown.

![github-pr-all-changes](https://user-images.githubusercontent.com/1325985/37751047-60b71370-2d4d-11e8-8632-2357e4274b53.PNG)
![github-vs-missing-changes](https://user-images.githubusercontent.com/1325985/37751053-656415f8-2d4d-11e8-98e1-3a4f25f6a43c.PNG)

**Comment by meaghanlewis** [comment]
Hi @mattnewport, this is a limitation of the GitHub API where the response we get of pull request files has a maximum of 300. Because this is enforced by the API there is nothing we can do about it.

You can read more about that here: https://developer.github.com/v3/pulls/#list-pull-requests-files

**Comment by mattnewport** [comment]
Well that's a remarkably dumb limitation and makes the API rather useless. Is there somewhere I can fire a bug against the API?

**Comment by mattnewport** [comment]
It seems like it should at least be possible to compare the actual number of files received to the number reported in the changed_files field of the PR description and show a warning that the results displayed have been truncated.

**Comment by meaghanlewis** [comment]
@mattnewport you can feel free to reach out to https://github.com/contact and give them your feedback about this.
