### ISSUE TITLE
Changed files in PRs font color is unreadable in dark theme

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1557]
I noticed while testing #1549 that the dark font was unreadable in the dark theme:
<img width="330" alt="screen shot 2018-03-22 at 7 59 41 am" src="https://user-images.githubusercontent.com/10103121/37773278-8e9bb71c-2db3-11e8-9dad-46e692f33e43.png">

but the font color appears correct on the latest release version (2.4.3.1737)
<img width="330" alt="screen shot 2018-03-22 at 9 26 51 am" src="https://user-images.githubusercontent.com/10103121/37773322-a930a524-2db3-11e8-9dab-073d2316a100.png">

So this was changed in development somewhere, but not sure yet exactly what commit changed this.

**Comment by grokys** [comment]
This should have already been fixed in #1492, but it's not yet propagated up the jengapile of PRs to the end yet!

**Comment by meaghanlewis** [comment]
Ah, thanks @grokys! I'll close this issue out then and wait for the jenga pile to clear up!
