### ISSUE TITLE
Incoming commits always blank

### ISSUE THREAD

**Issue by Doofitator** [github/VisualStudio#1564]
- GitHub Extension for Visual Studio version: [v2.4.3.1737](https://github.com/github/VisualStudio/tree/v2.4.3.1737)
- Visual Studio version: VS 2017 Community (v15.6.2)

When there are new commits on the Github repo that are not stored locally, I would have assumed that they would appear in the 'incoming commits' section the same way that outgoing commits appear:
![someout](https://user-images.githubusercontent.com/4780013/37888946-d84d3f88-3115-11e8-8035-368444b1f3f9.PNG)

This is not the case, however, as the incoming commits section is always blank:
![noin](https://user-images.githubusercontent.com/4780013/37888951-dcbb14f0-3115-11e8-8229-c5f31bd0ef65.PNG)

Even though, clicking 'Pull' still updates the project:
![Repo updates regardless](https://user-images.githubusercontent.com/4780013/37888962-e4831dd6-3115-11e8-85bf-6a3c55a1e4de.PNG)

I've got the same issue and configuration on a Windows 8 box, as well as a Windows 10 laptop and a Windows 7 laptop. This issue occurs on both public and private repos.

**Comment by meaghanlewis** [comment]
👋 @Doofitator thanks for reporting this issue.

I just tried to repo this using Visual Studio 2017 and do see a list of incoming commits similar to outgoing commits.
![2 4 4 1970- incoming commits](https://user-images.githubusercontent.com/10103121/37997537-f00b0d20-31cf-11e8-9682-a3598453e855.png)

I'm not really sure what's going on here, but it looks like this will require some more investigation.

**Comment by Doofitator** [comment]
I agree that it is odd - it's never worked for me, however if it were a widespread issue i would have thought more people would have reported it.

**Comment by meaghanlewis** [comment]
Hi @kaylangan @clboles @jeremyepling, we were wondering if you might be able to help debug the issue reported here about incoming commits not showing up in Team Explorer.

**Comment by kaylangan** [comment]
@Doofitator do you have a tag with the same name as the branch, per chance?

**Comment by Doofitator** [comment]
As in a version I've labeled as 'master' and such? No I don't. Should I?

**Comment by kaylangan** [comment]
@Doofitator no, I wouldn't expect you to. Does this issue occur with all repositories, or only a specific one?

**Comment by Doofitator** [comment]
@kaylangan It happens with all repositories, public and private, on all my computers.

**Comment by Doofitator** [comment]
Yeah sure. I'm traveling today but as soon as I get where I'm going, I'll get that data for you.

**Comment by Doofitator** [comment]
Well @kaylangan, I did that, but I don't know how you would get diagnostics out of it - I don't know that I did it right.

It is located here: https://developercommunity.visualstudio.com/content/problem/229191/github-incoming-commits-wont-show.html

**Comment by grokys** [comment]
Closing this here as it's not a problem with GitHub for Visual Studio, and seems you've reported the problem to MS but feel free to keep talking here ;)

**Comment by Doofitator** [comment]
@grokys how is this not a problem? And why is it closed because I reported it to microsoft? I'm only following instructions from @kaylangan and trying to get this resolved - otherwise I may as well go back to git bash!

**Comment by grokys** [comment]
No problem - I know it's hard to know sometimes what is Team Explorer and what is GitHub for Visual Studio!

If you're even in doubt, our [docs](https://github.com/github/VisualStudio/tree/master/docs) describe our features and we link to Microsoft's docs for their features, so you should be able to tell what's what from that.

**Comment by kaylangan** [comment]
Thanks @Doofitator. I'll get that ticket routed to the right team.
