### ISSUE TITLE
Troubles uploading from regular GitHub and Visual Studio 

### ISSUE THREAD

**Issue by tbdmb41** [github/VisualStudio#1566]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio version: 2.4.3.1737
- Visual Studio version: 15.6.1

I am having issues with Visual Studios and GitHub. When I go to connect to a project, there is no information loaded even though I am connected. When I try and go thru the settings, it gives me a 401 Error that I do not have access even though I am the admin. 

Any thoughts or ideas on what could be going on? 

Thanks!

**Comment by grokys** [comment]
Hi @tbdmb41 - could give a more detailed description of what you're doing?

- What do you mean by "connect to a project"?
- What information do you expect to be loaded?
- Which settings (there are various different settings in Visual Studio)
- Which repository are you trying to access?

If you could give detailed descriptions, or even better screenshots, that would be really helpful.

**Comment by grokys** [comment]
Hi @tbdmb41. The screenshot you pasted is of the Source Control Explorer, which is used for [Team Foundation version control](https://docs.microsoft.com/en-us/vsts/tfvc/use-source-control-explorer-manage-files-under-version-control?view=vsts), not git - this is what the message is telling you.

It looks like you've opened the `BookService` solution in Visual Studio - if you go to the Solution Explorer, do you see your files there? Also, if you want to push and pull from the repository you should click the "Home" button in Team Explorer and then Sync.

You may want to read [the github for Visual Studio documentation](https://github.com/github/VisualStudio/tree/master/docs). Not all of the Microsoft's Visual Studio git documentation is relevant when you're using GitHub but we've linked to the parts that are relevant [on this page](https://github.com/github/VisualStudio/blob/master/docs/contributing/index.md) under the section "Operations provided by Visual Studio".
