### ISSUE TITLE
QA for Version 1.0.15.5

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#157]
*Might* be bumped to 1.0.16.0. 
TestPad: https://github.ontestpad.com/script/77#2/1/

**Comment by amytruong** [comment]
For: Line 83: 
- [ ] Team Explorer view changes to Home page after repo is published 
![screen shot 2015-12-01 at 2 32 59 pm](https://cloud.githubusercontent.com/assets/10725993/11516523/91f2c8d2-9838-11e5-81aa-578efca8071e.png)

The screen stays on the current page. I _don't_ think this a bug but just a change to the test manifest?

**Comment by shana** [comment]
Nope, that's definitely a bug, or perhaps a regression. I vaguely remember talking about this before.

EDIT: yup, it's a regression: https://github.com/github/VisualStudio/issues/48

**Comment by shana** [comment]
# Release Notes

## Bug fixes

- https://github.com/github/VisualStudio/issues/107 - Path field doesn't have default cloning path of C:\Users\[user]\Source\Repos 
- https://github.com/github/VisualStudio/issues/143 - Cloning from the non-GitHub section shows GitHub message
- https://github.com/github/VisualStudio/issues/147 - Path is not correct when creating a new project after cloning/creating repo

## Enhancements

- When a GitHub repo is open and the user is not logged in, a message shows up in the Sync area with a quick link to login to GitHub, so that git operations won't fail.

**Comment by amytruong** [comment]
Thanks @shana I'll put it as failed with existing issue #48. 

We talked about this in slack but I _think_ this link is broken. :point_down: 
The evilamyt/beer-is-cool (i think it's a link to the repo on .com since the tooltip says
> u:http://github.com/evilamyt/beer-is-cool

![screen shot 2015-12-01 at 3 47 13 pm](https://cloud.githubusercontent.com/assets/10725993/11518216/673cf1c4-9844-11e5-9132-cce191d2d665.png)

I'll also test those bug fixes above and take a look at that new feature.

**Comment by amytruong** [comment]
@shana I was testing out #107 for correct default cloning paths and noticed something a little strange. Wanted to confirm with you first. When logged out, I click on "Clone" and it brings up the Sign In screen. Sign in and I _think_:
Expected Results: The clone pop up displays and I can select/choose and clone as usual
Actual Results: The clone pop up displays but I also see a notification in the Window Explorer window. 
![weird](https://cloud.githubusercontent.com/assets/10725993/11539041/e215ba3a-98d9-11e5-87c4-ccfca0e592c3.gif)

**Comment by shana** [comment]
Ooooh, that looks very wrong. Does that `GitHub-Visual-Studio-PRIVATE-` repo actually exist and did it actually clone it?

**Comment by amytruong** [comment]
The repo already exists so I _think_ it's just pulling that notification up again and looks like it's cloning it but it's not. Will try to dive a bit deeper in it. :grin:

**Comment by amytruong** [comment]
IIRC, I don't think this section is related to GitHub/anything of ours but if you're in Local Git Repositories and click on the "..." The Browse For Folder window should open up to the default local path but it's opening up to Desktop. It might be me on a VM but wanted to write down just in case. 

![screen shot 2015-12-02 at 10 10 39 am](https://cloud.githubusercontent.com/assets/10725993/11539633/fd02f922-98dc-11e5-9f1f-ef8ff805d0ad.png)

**Comment by shana** [comment]
Ok, so it's just showing the message wrongly because when you login it triggers populating the list of repos and somewhere there it triggers the message. Darn.

**Comment by amytruong** [comment]
@shana ah ok. :cool: I'd say better triggering a wrong message than it actually cloning a repo or something. :wink:
