### ISSUE TITLE
Known issues in PR reviews beta

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#1570]
Known issues:

- [ ] Some comments won't open inline https://github.com/github/VisualStudio/pull/1549#issuecomment-375278440
  - Appears to be the same as #1469 - needs an update to libgit2sharp
- [x] Each time I click a comment the entire diff view reloads https://github.com/github/VisualStudio/pull/1549#pullrequestreview-107912375
  - Fixed by #1585
- [x] No client-side validation for body on "Request Changes" https://github.com/github/VisualStudio/pull/1562#issuecomment-376625258
  - Fixed by #1582
- [x] Cancel button not working https://github.com/github/VisualStudio/pull/1562#issuecomment-376625258
  - Fixed by #1572
- [x] Quotes in review body not escaped: https://github.com/github/VisualStudio/pull/1562#issuecomment-377092232
  - Octokit.GraphQL fix is here https://github.com/grokys/Octokit.GraphQL/issues/72
  - Fixed by #1581
- [x] Feature does not work with GitHub Enterprise (trying to open PR's shows: "Object reference not set to an instance of an object.")
  - Fixed by #1578
- [x] Navigate from diff view to editor feature is missing
  - Fixed by #1580
- [x] Approve/Comment/Request Changes links need a disabled visual state
  - Fixed in #1582 (see HACK section ;) )

Ongoing discussions:

- [ ] A user can comment on their own PR but dotcom will never show a user as a reviewer of their own PR under Reviewers explicitly. So I'm just wondering if the goal for the reviewers section is to behave like dotcom behaves or not. https://github.com/github/VisualStudio/pull/1523#issuecomment-376183673 
  - Because we don't yet have a conversation view, there would be no way to see these reviews if we didn't include them here, so we think we need to keep this behavior, at least for now
- [ ] I wonder if we should display the total number of comments (for what it's worth, once someone has reviewed or commented on a PR, then they will always appear in the list.) https://github.com/github/VisualStudio/pull/1523#issuecomment-376228940
  - Dogfooding this, being able to see the x file comments is kind of useful. I wonder if that could be incorporated in a more condensed way?
https://github.com/github/VisualStudio/pull/1523#issuecomment-377020594
  - Definitely! 😄I wanted to remove that for now because it wasn't clear that the number of comments was for last review and not total comments. However, I think what would be really useful is tracking how many comments still needs to be addressed (and maybe across a number of files.) We should consider researching more into this. https://github.com/github/VisualStudio/pull/1523#issuecomment-377023951
  - Possibly, though other information like submitted date would also be useful. As mentioned comment count is unclear because it only refers the the latest review, when user may be expecting the total number of comments. Needs investigation, but we're not going to block on this.
- [ ] Ordering the comments starting with most recent might make this a more manageable (given that you can't dismiss comments, if I've understood correctly). https://github.com/github/VisualStudio/pull/1523#issuecomment-376456534
  - I think I'm fine with the ordering as-is. If we want to order by most recent here, we should surface more information so that this is clear. That said, there's an opportunity for us to understand how developers determine which set of reviews to address first (e.g., based on review status, number of file comments, date the review was left.) https://github.com/github/VisualStudio/pull/1523#issuecomment-376966070
  - Again, something we can explore going forward.
- [ ] With this format the ✔️ or 💬 can end up a long way from the username/avatar. Could this be flowed with as many as fit? https://github.com/github/VisualStudio/pull/1523#issuecomment-376861833
  - Yes, this can look a bit strange, but not sure of decent alternatives at the moment. Needs some @donokuda experimentation.
- [ ] What do you think of moving the Reviewers above the Description? To me it doesn't feel right having is sandwiched between the Description and Changes tree. https://github.com/github/VisualStudio/pull/1523#issuecomment-376861833
  - Consensus was that putting reviewers above description felt a bit strange, that one expects Description to be first. A possible solution to this might be to remember the expanded state of the sections so that once read the description can be collapsed and the reviewers will be immediately visible?
- [x] Could we make it so you can click on either the avatar or the ✔️ / 💬? https://github.com/github/VisualStudio/pull/1523#issuecomment-377020594
  - Fixed in #1586
- [ ]  I don't see any differentiation between outdated and new reviews https://github.com/github/VisualStudio/pull/1549#pullrequestreview-107912375
  - @donokuda wants to explore options for this, though will probably be for a later release.
- [ ] When I click on the comment, if it is in a thread of comments for that line, there is no indication of this. Maybe we don't want one, but it was just interesting that I had to search through to find it. That being said, it might make sense for that functionality. 
https://github.com/github/VisualStudio/pull/1549#pullrequestreview-107912375
  - We could pulse the clicked comment when shown. This might be difficult at the moment because the diff view is janky, can maybe investigate when we try to fix that. cc: @donokuda 
- [ ] For other errors don't we usually have a banner at the top? https://github.com/github/VisualStudio/pull/1562#issuecomment-376648185
  - We should investigate this in general
- [ ] Should pending reviewers be shown like they are in dotcom? https://github.com/github/VisualStudio/pull/1523#issuecomment-375662883
  - Meant "requested reviewers" - this should be added, but it's a separate feature.

**Comment by sguthals** [comment]
https://twitter.com/dotMorten/status/980862151932784640

No GHE Support?

**Comment by meaghanlewis** [comment]
Yeah @sguthals just tried to repro this and it doesn't appear to be working with Enterprise. I'll add it to the list of known issues above.

**Comment by grokys** [comment]
Closing as PR reviews has now shipped.
