### ISSUE TITLE
Clicking on PR number link does nothing

### ISSUE THREAD

**Issue by awbushnell** [github/VisualStudio#1576]
- GitHub Extension for Visual Studio version:  2.4.3.1737
- Visual Studio version: Visual Studio 2017 15.6.4

__What happened__ (with steps, logs and screenshots, if possible)

I am finding that when looking at the list of PR's in the GitHub extension in Visual Studio, that clicking on the PR Number link does nothing. According to the tooltip, it should open the PR out on GitHub for me..  Screenshot of where I mean:

<img width="319" alt="githubbug" src="https://user-images.githubusercontent.com/11314686/38211956-20e3264e-368a-11e8-825b-54aabab71aae.PNG">

I find that if I click to open the PR in the extension then click the view conversation on GitHub, it works fine, so from this location in the extension:

<img width="308" alt="githugbug2" src="https://user-images.githubusercontent.com/11314686/38211960-240e071c-368a-11e8-8ae8-eb6359b1632b.PNG">

FYI, this is via GitHub enterprise.

**Comment by meaghanlewis** [comment]
👋 @awbushnell thanks for this bug report. Yes, this appears to be a regression that is affecting both GitHub and GitHub Enterprise
