### ISSUE TITLE
"This document is opened by another project" - when navigating to PR file

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1583]
- GitHub Extension for Visual Studio version: 2.4.99
- Visual Studio version: All

__What happened__ (with steps, logs and screenshots, if possible)

1. Open a file in the Solution
2. View file using PR detail pane (e.g. `View Changes`)
3. Press `Enter` to navigate to file
4. The following dialog appears:

![image](https://user-images.githubusercontent.com/11719160/38307142-ab768770-380a-11e8-94d8-7905aebc8836.png)

There are many other ways to repro this, including right clicking on PR file and `Open File in Solution`.

### What cases it

It appears to be a back/forward-class issue. Navigate to editor isn't converting all slashes to back-slashes! See:
![image](https://user-images.githubusercontent.com/11719160/38307114-96d3212a-380a-11e8-89d3-510893df54ac.png)

**Comment by meaghanlewis** [comment]
Thanks for fixing this!

**Comment by jcansdale** [comment]
This bug won't have made it into the wild, so removing the `bug` label.

**Comment by meaghanlewis** [comment]
Fixed by #1491
