### ISSUE TITLE
VS 15.6.6 Live Player based Android Debugging doesn't work

### ISSUE THREAD

**Issue by IoTFier** [github/VisualStudio#1594]
- GitHub Extension for Visual Studio version: 
- Visual Studio version: 15.6.6
- Windows 10 Pro 64 bit | April 10, 2018—KB4093112 (OS Build 16299.371)

__What happened__ (with steps, logs and screenshots, if possible)
* Upgraded Visual Studio from 15.6.5 to 15.6.6.
* Created a Xamarin Form based hello app | Master Detail + .Net Standard + MobileAppService (not created but not deployed )
I had same type of Xamarin form based app created in 15.6.4 which I could deploy and debug in VS 15.6.5 using Live Player. With 15.6.6 , using LivePlayer, the same app created in 15.6.4 as well as one created in 15.6.6 is not getting deployed / failing with error during debug (after pressing F5).
Log as attached below.

_**Please not the deployment does work when I connect my android device via USB cable to my PC.**_

**Output of the log attached below -**
[VS15.6.6-LivePlayerDeploymentDoesntWork.txt](https://github.com/github/VisualStudio/files/1896491/VS15.6.6-LivePlayerDeploymentDoesntWork.txt)

**Comment by meaghanlewis** [comment]
Hi @IoTFier this is the repository for the GitHub extension for Visual Studio, and not Visual Studio itself. You might want to reach out to [Xamarin Support](https://www.xamarin.com/support) for help on this.

**Comment by IoTFier** [comment]
Hi @meaghanlewis, thank you.
