### ISSUE TITLE
AspNET5 Empty Project Creation

### ISSUE THREAD

**Issue by blink2linkme** [github/VisualStudio#160]
After choosing empty project template of ASPNET 5 Templates and adding gulpfile.js I am continuously getting error. Error is due to creation of multiple node_modules folder i.e. node_modules folder contains another node_modules folder within in and so on. It worked after I copied node_modules folder after copying from another project which was created by choosing basic template.

**Comment by shana** [comment]
Is this on Visual Studio Code? You should report that in https://github.com/Microsoft/vscode/issues, this is the repository for the GitHub Visual Studio extension.

**Comment by blink2linkme** [comment]
Hey Shana this is issue in Visual Studio 2015 not on Visual Studio code. I can distinguish what's visual studio and visual studio code.

**Comment by shana** [comment]
@blink2linkme In that case, you should send feedback to Microsoft via the Visual Studio feedback reporter. Visual Studio is not open source, so I can't help you with this issue.

**Comment by blink2linkme** [comment]
Thank you @shana
