### ISSUE TITLE
UX Improvement: HiDPI Avatars for HiDPI users

### ISSUE THREAD

**Issue by NickCraver** [github/VisualStudio#1603]
- GitHub Extension for Visual Studio version: Pull Request Reviews Beta 1
- Visual Studio version: 15.7 Preview 3

For high DPI screen,s avatars are currently very fuzzy. Not sure this'll come across in a picture due to dPI being oh so fun, but screenshot:
![image](https://user-images.githubusercontent.com/454813/38770694-12fafc5a-3fe5-11e8-83b9-c3fb1e162d71.png)

cc @sguthals

**Comment by grokys** [comment]
@NickCraver this should be fixed in the latest 2.5.4 release, so I'm going to close this. Please let us know if it's not fixed for you!
