### ISSUE TITLE
Remove text "Pull request" from PR button on status bar

### ISSUE THREAD

**Issue by justcla** [github/VisualStudio#1621]
- GitHub Extension for Visual Studio version: 2.5.1.2234
- Visual Studio version: 15.7.0 Preview 5.0 (27619.1.d15.7)

PR #1519 introduced text on the status bar that reads "Pull requests".

The text on this button is very distracting. So much so, I had to disable the GitHub extension in Visual Studio.

**It draws my attention, when my attention should not go to it**
It was very effective at drawing my attention to it, but I did not need it at the time. I had just opened a clean project on master branch and had no changes or commits, no previous PRs and no other contributors to tat project. I can see it being useful later on - particularly when I have commits worth pushing and a branch to merge. But until then, and even after then, the text "Pull requests" is very distracting.

**It's not consistent with similar/neighboring icons**
There is no text on the commit and push icons (to the right of the Pull request button), and by the nature of commits, branches and PRs, they would be used more often - and yet they don't take up space with distracting text.

**Once you know what the button is, you don't need the text to tell you**
The tooltip is effective, if a user bothers to hover over it.
Alternatively, you could try advertising it with some point-in-time notification/spotlight. (Though, I don't know how you would achieve that.)

Can I politely ask that you remove the "Pull request" text from the status bar button?

Then I can turn my GitHub extension back on again.

Thanks! :-D

**Comment by jcansdale** [comment]
> Can I politely ask that you remove the "Pull request" text from the status bar button?
> Then I can turn my GitHub extension back on again.

I've created a very quick spike PR for you here #1622. There's the .vsix artifact:
https://ci.appveyor.com/api/buildjobs/3bx4bobpobc8apdx/artifacts/2.5.1.2270%2FGitHub.VisualStudio.vsix

This is just so you can turn it back on. 😉 I'll discuss the rest of your feedback with the team.
