### ISSUE TITLE
Loading a private repo does not show the login screen

### ISSUE THREAD

**Issue by Vannevelj** [github/VisualStudio#1623]
- GitHub Extension for Visual Studio version: 2.5.1.2234
- Visual Studio version: 15.6.6

__What happened__ 

1. Installed the Github extension
2. Enabled Git as the source control provider in Visual Studio
3. Opened a git .sln that uses a private organization repo

This showed a Github pane saying that no such repository exists.
I had to load a public (non-organization) repo in order for it to show me the login screen. After logging in, both the public and private repos worked fine with the extension.

Potentially useful: I have 2F enabled.

**Comment by meaghanlewis** [comment]
Hi @Vannevelj it seems you were experiencing what was described in this issue: https://github.com/github/VisualStudio/issues/1519.

It appears that whenever you are not signed in, we do not display the content on the GitHub pane.

**Comment by Vannevelj** [comment]
@meaghanlewis That looks about right, yeah. I don't recall whether I actually clicked "Get Started" or just sought for a different way since the message on it threw me off (I didn't realize I still had to log in).

**Comment by meaghanlewis** [comment]
Ok, cool @Vannevelj. I'm going to close this issue out here in favor of #1519 which is already marked as a bug. Thanks for reporting this to us.
