### ISSUE TITLE
UX Improvement: Don't show diff window for new files in PR workflow

### ISSUE THREAD

**Issue by sandermvanvliet** [github/VisualStudio#1624]
First of all: Awesome work on the Pull Request feature! 

I've been using this functionality for a while now and it's great to be able to review from inside Visual Studio. However if I review PRs that have new files it opens them in the diff viewer which takes up a lot of screen real estate that is empty because there is no previous version.

It would be great if for new files it would open a regular editor view instead so I can more easily review the file.

Again: great work! 👍

**Comment by jcansdale** [comment]
@sandermvanvliet thanks for the suggestion.

I wonder if we could lock the diff view to show `Left view only` when viewing a new file? Alas, the diff window mode (see below), is a global option for all diff viewers. I think it is however possible to lock a diff window to a particular mode. Would you ever want to view a new file in anything other than `Left view only`?

![image](https://user-images.githubusercontent.com/11719160/39521833-1e47c6d4-4e08-11e8-97ee-041ff5d04cb5.png)

**Comment by jcansdale** [comment]
@sandermvanvliet could you try the .vsix build below and let me know what you think?
https://ci.appveyor.com/project/github-windows/visualstudio/build/2.5.1.2305/artifacts

When the extension sees that either the left of the right side is empty, it will hide that side in the diff view (by automatically selecting `Left/Right file only`).

It doesn't use the regular editor view as you suggested, but it should still open up a lot more space. I thought by keeping it in the diff view, it gives the user a visual cue that the file isn't editable (it defaults to showing the PR file as seen on github.com). You can easily hit `Enter` to navigate to the editable/working file.
