### ISSUE TITLE
The 'GitHubPackage' package did not load correctly.

### ISSUE THREAD

**Issue by sebastianferrari** [github/VisualStudio#1625]
- GitHub Extension for Visual Studio version: 2.5.1.2234
- Visual Studio version: Microsoft Visual Studio Enterprise 2017 Version 15.6.6

### Each time that I load a solution under a git repo, I'm getting the following message:

![github_error](https://user-images.githubusercontent.com/8184074/39313704-44870366-4938-11e8-86c7-9af716f754ec.png)

### This is the ActivityLog.xml file content:

1 |   | Microsoft Visual Studio 2017 version: 15.0.27428.2037 |   |   | VisualStudio | 2018/04/26 14:11:48.304
...
838 |   | Begin package load [GitHubPackage] | {C3D3DC68-C977-411F-B3E8-03B0DCCF7DFC} |   | VisualStudio | 2018/04/26 14:28:26.399
839 |   | End execution cost summary for SolutionLoad scenario and VSPackage component |   |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.415
840 |   | Component: 7fe30a77-37f9-4cf2-83dd-96b207028e1b, Inclusive Cost: 1451.8722, Exclusive Cost: 1330.171, Top Level Inclusive Cost: 1451.8722 | {7FE30A77-37F9-4CF2-83DD-96B207028E1B} |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.415
841 |   | Component: 5f2e5e42-4192-4d79-a0d8-1d881e808829, Inclusive Cost: 344.3748, Exclusive Cost: 344.3748, Top Level Inclusive Cost: 344.3748 | {5F2E5E42-4192-4D79-A0D8-1D881E808829} |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.415
842 |   | Component: 5e56b3db-7964-4588-8d49-d3523ab7bdb9, Inclusive Cost: 226.4601, Exclusive Cost: 226.4601, Top Level Inclusive Cost: 226.4601 | {5E56B3DB-7964-4588-8D49-D3523AB7BDB9} |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.415
843 |   | Component: b483c4e7-43a6-4f7b-a9a1-79e2c5d12148, Inclusive Cost: 127.0958, Exclusive Cost: 120.1464, Top Level Inclusive Cost: 127.0958 | {B483C4E7-43A6-4F7B-A9A1-79E2C5D12148} |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.415
844 |   | Component: 00000000-0000-0000-0000-000000000000, Inclusive Cost: 3002.0236, Exclusive Cost: 1414.6563, Top Level Inclusive Cost: 0 | {00000000-0000-0000-0000-000000000000} |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.415
845 |   | Component: 87569308-4813-40a0-9cd0-d7a30838ca3f, Inclusive Cost: 246.3491, Exclusive Cost: 246.3491, Top Level Inclusive Cost: 246.3491 | {87569308-4813-40A0-9CD0-D7A30838CA3F} |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.415
846 |   | Component: 480d29df-2b3d-445f-b055-fe2c74913a83, Inclusive Cost: 653.7676, Exclusive Cost: 580.5707, Top Level Inclusive Cost: 653.7676 | {480D29DF-2B3D-445F-B055-FE2C74913A83} |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.415
847 |   | End execution cost summary for SolutionLoad scenario and VSPackage component |   |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.415
848 |   | End execution cost summary for SolutionLoad scenario and ToolWindow component |   |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.416
849 |   | Component: e1b7d1f8-9b3c-49b1-8f4f-bfc63a88835d, Inclusive Cost: 461.8305, Exclusive Cost: 461.8305, Top Level Inclusive Cost: 461.8305 | {E1B7D1F8-9B3C-49B1-8F4F-BFC63A88835D} |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.416
850 |   | End execution cost summary for SolutionLoad scenario and ToolWindow component |   |   | Manage Visual Studio Performance | 2018/04/26 14:28:26.416
851 |   | End package load [Tab Designer Launcher] | {B4E787A4-A9FC-4579-945E-D71AFEC4DD90} |   | VisualStudio | 2018/04/26 14:28:26.507
**852 | ERROR | SetSite failed for package [InlineReviewsPackage]Source: 'System.ComponentModel.Composition' Description: No exports were found that match the constraint: 	ContractName	GitHub.Commands.INextInlineCommentCommand	RequiredTypeIdentity	GitHub.Commands.INextInlineCommentCommand | {248325BE-4A2D-4111-B122-E7D59BF73A35} | 80131500 | VisualStudio | 2018/04/26 14:28:26.623
853 | ERROR | End package load [InlineReviewsPackage] | {248325BE-4A2D-4111-B122-E7D59BF73A35} | 80131500 | VisualStudio | 2018/04/26 14:28:26.639
854 | ERROR | SetSite failed for package [PullRequestStatusBarPackage]Source: 'System.ComponentModel.Composition' Description: No exports were found that match the constraint: 	ContractName	GitHub.InlineReviews.Services.PullRequestStatusBarManager	RequiredTypeIdentity	GitHub.InlineReviews.Services.PullRequestStatusBarManager | {5121BEC6-1088-4553-8453-0DDC7C8E2238} | 80131500 | VisualStudio | 2018/04/26 14:28:26.645
855 | ERROR | End package load [PullRequestStatusBarPackage] | {5121BEC6-1088-4553-8453-0DDC7C8E2238} | 80131500 | VisualStudio | 2018/04/26 14:28:26.650
856 | ERROR | SetSite failed for package [GitHubPackage]Source: 'System.ComponentModel.Composition' Description: No exports were found that match the constraint: 	ContractName	GitHub.Commands.IAddConnectionCommand	RequiredTypeIdentity	GitHub.Commands.IAddConnectionCommand | {C3D3DC68-C977-411F-B3E8-03B0DCCF7DFC} | 80131500 | VisualStudio | 2018/04/26 14:28:26.714
857 | ERROR | End package load [GitHubPackage] | {C3D3DC68-C977-411F-B3E8-03B0DCCF7DFC} | 80131500 | VisualStudio | 2018/04/26 14:28:26.718**
858 |   | End package load [ConnectedServicesPackage] | {8E15F3DA-B303-4AF9-814A-1DC5C2583398} |   | VisualStudio | 2018/04/26 14:28:26.723

**Comment by sebastianferrari** [comment]
It has been solved after installed the latest VS v15.6.7

**Comment by Mike-EEE** [comment]
I am getting this after installing 15.8.1

**Comment by Calabonga** [comment]
Visual Studio 15.8.1 
me getting too...

**Comment by rjgotten** [comment]
Same problem with 15.8.1 here as well.
Any way to just flat out uninstall the entire package?

**Comment by softlion** [comment]
It's back !!

**Comment by oylp1988** [comment]
Hi,

The dialog was asking continue to show the error msg? What if I clicked no? would that continue show the error msg when next load?

I did some fix, but I m not sure if the fix was done. or could some let me know how this error would affect the github extension?
