### ISSUE TITLE
Visual Studio 2017 Preview Version 4

### ISSUE THREAD

**Issue by davidbuckleyni** [github/VisualStudio#1626]
Hi I am trying to get Winforms Forms Control sdk installed now I have selected the windows desktop development ok in visual studio installed but its still not showing in the porject items I wish to create a custom control for the toolbox.

![capture](https://user-images.githubusercontent.com/5619229/39317496-9e24ce5e-4973-11e8-9bde-072b64f137e0.PNG)

And as you can see here I am not finding it in the new project items
![capture2](https://user-images.githubusercontent.com/5619229/39317548-c168706e-4973-11e8-87f0-436dae23b886.PNG)

**Comment by davidbuckleyni** [comment]
I am trying to follow the guide here 

https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-windows-forms-toolbox-control

**Comment by meaghanlewis** [comment]
Hi @davidbuckleyni this is the repository specifically for the GitHub extension in Visual Studio. To report the feedback for the problem you are experiencing please reach out to the Visual Studio Developer Community [here](https://developercommunity.visualstudio.com/spaces/8/index.html).
