### ISSUE TITLE
Project level "Add to source control"

### ISSUE THREAD

**Issue by zax-ftw** [github/VisualStudio#1627]
I'm not sure if it can be implemented on 'extension' level or it's more of Visual Studio's issue, but it would be nice to have an option to "add source control" to projects separately from solution.

It would be especially useful in situations where some third party libraries or shared projects are kept as part of solution and we don't want to source control them. I saw several google results about this issue, so it could be quite popular and wanted enhancement.

**Comment by meaghanlewis** [comment]
Hi @zax-ftw this is the repository specifically for the GitHub extension for Visual Studio and we do not cover the "add to source control" bit. You might want to share this feedback with the Visual Studio Developer Community: https://developercommunity.visualstudio.com/spaces/8/index.html
