### ISSUE TITLE
Visual Studio 2017 missing the Winforms Form Control For Custom Control Development from Project Items

### ISSUE THREAD

**Issue by davidbuckleyni** [github/VisualStudio#1628]
Hi I am trying to get Winforms Forms Control sdk installed now I have selected the windows desktop development ok in visual studio installed but its still not showing in the porject items I wish to create a custom control for the toolbox. I am using Visual Studio 2017 and sometimes 2015 same thing occourse cannot find the control 

![39317496-9e24ce5e-4973-11e8-9bde-072b64f137e0](https://user-images.githubusercontent.com/5619229/39352970-4556ae88-49fe-11e8-813e-6671e7baefaa.PNG)

![39317548-c168706e-4973-11e8-87f0-436dae23b886](https://user-images.githubusercontent.com/5619229/39352973-480b2cb2-49fe-11e8-94a7-25c300f83e92.PNG)

**Comment by meaghanlewis** [comment]
Hi @davidbuckleyni this is the repository specifically for the GitHub extension for Visual Studio. You might want to reach out the the Visual Studio Developer Community [here](https://developercommunity.visualstudio.com/spaces/8/index.html).
