### ISSUE TITLE
r

### ISSUE THREAD

**Issue by InfallibleProgrammer** [github/VisualStudio#1629]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio version:
- Visual Studio version:

__What happened__ (with steps, logs and screenshots, if possible)

**Comment by meaghanlewis** [comment]
Hi @InfallibleProgrammer if you are having an issue with the GitHub Extension for Visual Studio please fill out the issue template.
