### ISSUE TITLE
Path too long error

### ISSUE THREAD

**Issue by SetTrend** [github/VisualStudio#163]
I can't connect to my local GitHub repository using my project path:

```
Opening repositories:
D:\Documents\Visual Studio-Projekte\Visual Studio 2015\Projects\IdentitySamples
invalid path '\\?\D:\Documents\Visual Studio-Projekte\Visual Studio 2015\Projects\IdentitySamples\AngularClient\node_modules\gulp-less\node_modules\accord\node_modules\uglify-js\node_modules\yargs\node_modules\cliui\node_modules\right-align\node_modules\align-text\node_modules\kind-of' (path too long)
```

**Comment by Haacked** [comment]
Hi @SetTrend, could you describe the exact set of steps you took to get that error and where you saw the error?

**Comment by SetTrend** [comment]
I cloned a solution from Github (in fact, any solution will do) and added a "HTML Application with TypeScript" project (any ASP.NET project will do, too).

Then I added this **package.json** file:

````JSON
{
	"name": "AngularClient",
	"version": "0.0.1",
	"dependencies":
	{
		"angular": "^1.4.8",
		"angular2": "^2.0.0-alpha.52"
	},
	"devDependencies":
	{
		"gulp": "^3.9.0",
		"gulp-watch": "^4.3.5",
		"gulp-less": "^3.0.5",
		"gulp-minify-css": "^1.2.2",
		"gulp-requirejs-optimize": "^0.3.0"
	}
}
```

Any of those will create a path that's too long for GitHub.

**Comment by Haacked** [comment]
> Any of those will create a path that's too long for GitHub.

But what do you mean by that? At this point, you're not using the GitHub extension and are probably running into problems with Visual Studio itself and long path handling.

**Comment by SetTrend** [comment]
I'm referring to the Visual Studio Output panel. It reads: "Source Control - Git":

![path too long error2](https://cloud.githubusercontent.com/assets/9283914/11731451/cac28232-9f9b-11e5-8449-fa7276746cec.gif)

**Comment by Haacked** [comment]
@SetTrend Ah! Ok, that's not the GitHub Extension. Visual Studio comes with a Git Extension (I know, it's confusing) which is responsible for the Git functionality. The GitHub Extension adds the GitHub specific features on top of it such as authentication and cloning.

I'm going to close this, but I'll mention the folks on the Visual Studio team so they have awareness of the issue.

/cc @acangialosi @clboles ^^^ check that long path issue out. :)

**Comment by raymono** [comment]
I was just searching to solve this issue Where i found Long Path tool during my search which is very easy to use and make the path shorter within no time.

**Comment by hunterwyatt** [comment]
You can try to using long path tool for google searching. Already i have solved my problem too.

**Comment by SetTrend** [comment]
`NPM` in its latest edition (3+) stores node modules (mostly) flat instead of recursive. That solved many of my problems (though not all of them).

**Comment by JackGrinningCat** [comment]
And landed googling on the way might try following:

Anyone that falling in an Path to long problem might also check for the core.longPaths Git Settings.
That is used by underlying git scm 
git config core.longpaths true

https://github.com/git-for-windows/git/issues/1177
