### ISSUE TITLE
Empty PR filter dropdowns show as a thin grey line

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#1632]
If one opens a repository with no Pull Requests then the Assignee and Author dropdowns display as a thin grey line:

![image](https://user-images.githubusercontent.com/1775141/39524973-fdec1616-4e1a-11e8-8c3a-4e1292fb204c.png)

This is confusing, it's not clear what clicking the "Assignee" or "Author" button is doing when this happens.

Related: Consider swapping position with Author (?)

**Comment by meaghanlewis** [comment]
The Assignee and Author dropdowns don't exist any longer with the latest PR list improvements: https://github.com/github/VisualStudio/pull/1737 and now there is a single searchable list for "Assignable Users" to filter by that will always have at least one user.
