### ISSUE TITLE
Open filter dropdown in PR list is ambiguous

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#1636]
From Justin Clareburt via email:

> Opened the GitHub pane
> The first thing I saw was the "Open" link. I thought, OK - I'll try to open a new Pull Request.
> But it offered a drop-down box that confused me, so I backed out.

> I went back to inspect the Open/Closed/All dropdown. "Closed" implies a state. Makes me think this is a filter. The word "Open" is both a state and an Action. There is the problem. If only there was a way to be clear that "Open" was a state, not an action. One option would be to label the dropdown. Eg. "State: Open". Another would be to choose a different word. Eg. "Current".

> I might not have been confused by "Open" if "Create New" was on the left (instead of the right).

**Comment by meaghanlewis** [comment]
I believe the suggestion here is now complete that `Create New` has been moved to the left.
