### ISSUE TITLE
Pull Request summary Cancel button needs confirmation

### ISSUE THREAD

**Issue by StanleyGoldman** [github/VisualStudio#1653]
The Cancel button noted here will remove all of a user's in progress review comments.
The user may not be aware of the effect and may simply be trying to leave the screen because they are not ready to complete their review.

The effect of the cancel button should be clearly explained with a dialog/confirmation before allowing the user to continue.

![image](https://user-images.githubusercontent.com/417571/39841396-95f59316-53b0-11e8-8360-55b70514f11d.png)

**Comment by meaghanlewis** [comment]
On dotcom, there is a confirmation for the `Cancel review` option explaining that all pending comments will be lost and this is really helpful.

<img width="987" alt="confirm cancel" src="https://user-images.githubusercontent.com/10103121/41428567-52c4c672-6fbf-11e8-8702-8e4afa5dbb14.png">
