### ISSUE TITLE
My app

### ISSUE THREAD

**Issue by crazy222** [github/VisualStudio#1658]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio version:
- Visual Studio version:

__What happened__ (with steps, logs and screenshots, if possible)

**Comment by crazy222** [comment]
H

**Comment by crazy222** [comment]
Help

**Comment by sguthals** [comment]
Hi @crazy222 👋 

Are you having trouble with the GitHub for Visual Studio extension? If so, could you please provide us with some information:
- GitHub Extension for Visual Studio version:
- Visual Studio version:
- What happened (with steps, logs and screenshots, if possible)
