### ISSUE TITLE
MEF parts should initialize with all-free-threaded code

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1688]
@AArnott wrote https://github.com/github/VisualStudio/pull/1663#issuecomment-389632127:

> MEF parts should ideally not be making any assumptions about the thread that their importer is on. One design point of MEF is to provide IoC-like benefits, but you lose those when you make assumptions that you know who all your importers are and have an implicit contract that they always activate you on a particular thread. Similarly, MEF parts should not have thread affinity (i.e. they shouldn't try to switch to the thread they require) during activation, since that can lead to deadlocks. MEF parts should initialize with all-free-threaded code, and do any thread affinitized initialization later when the importer calls one of its methods explicitly (preferably asynchronously).

Some of our MEF services only work properly when they're constructed on the Main thread. This makes MEF initialization error prone and potentially dependent on the order in which components are used. We should ensure that all of our shared MEF components are free-threaded.

**Comment by meaghanlewis** [comment]
@jcansdale can this be closed now that #1689 has been merged?

**Comment by jcansdale** [comment]
@jcansdale ah yes, well spotted! I forgot a `Fixes` comment. 😊
