### ISSUE TITLE
"Cannot checkout as your working directory has uncommitted changes" appearing without pending changes

### ISSUE THREAD

**Issue by matt-neubert** [github/VisualStudio#1691]
- GitHub Extension for Visual Studio version: 2.5.1.2234 & previous version
- Visual Studio version: 15.7.1 & previous

I am not able to checkout a branch from the pull request.  When I hover over the link, it a help text pops up that reads, "Cannot checkout as your working directory has uncommitted changes."  I do not have any pending changes in my current directory.  I have checked multiple times.  Could it be that it is not looking at the gitIgnore?  This seems to only be an issue with one repository.  It does allow me to checkout the branch on a sample and another small repo I have for another project, but not sure why it doesn't allow me on our main repo.  Any ideas?

![image](https://user-images.githubusercontent.com/8632262/40243820-d53ae0b2-5a86-11e8-9c35-c71921a60998.png)

**Comment by matt-neubert** [comment]
This can be labeled "help wanted".

**Comment by jcansdale** [comment]
Hi @matt-neubert,

Is the repo you're working on public and would you be able to share it?  If you were able to zip it up and drop the file here, that would likely save time attempting to repro. Alternatively you could email it to my username @ github.com.

**Comment by meaghanlewis** [comment]
Hi @matt-neubert I noticed this as well. If you press the refresh button at the top of the page does that help?

![checkout with changes](https://user-images.githubusercontent.com/10103121/40253978-8979f4fa-5a7d-11e8-8e93-0dc52972a158.gif)

**Comment by matt-neubert** [comment]
@meaghanlewis, the refresh button does not work for me.  Is there something I can do to debug what it thinks is pending?

**Comment by jcansdale** [comment]
@matt-neubert Thanks! I was able to reproduce and will investigate further tomorrow....

**Comment by jcansdale** [comment]
Hi @matt-neubert,

Some work in progress debugging for you. These files appear to be the issue:
![image](https://user-images.githubusercontent.com/11719160/40535840-2ef41c9c-6002-11e8-9cdf-6954b98cc066.png)

I think it might be related to this:
https://stackoverflow.com/questions/4610561/untracked-files-not-shown-in-git-status

I'll continue to investigate.

**Comment by jcansdale** [comment]
@matt-neubert,

I've submitted a PR with a fix/workaround for this #1706. I'm still fuzzy as to why these files are showing as being deleted from working directory. It's maybe something about the `.gitignore` file, but even if delete `.gitignore` the files doesn't show up in `git status`. Very strange!

Here is a `.vsix` installer for you to try: [GitHub.VisualStudio.zip](https://github.com/github/VisualStudio/files/2039617/GitHub.VisualStudio.zip)

Please comment on #1706 is it does/doesn't' work.

Thanks for submitting the issue.

**Comment by matt-neubert** [comment]
The PR #1706 seems to fix this issue for me.
