### ISSUE TITLE
Localization: Make the extension localizable

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#17]
Move strings into resources, make things nice and ready for translation/localization

**Comment by jau228** [comment]
Are you looking at static binding? or will you need dynamic switching languages?

**Comment by Haacked** [comment]
> Are you looking at static binding? or will you need dynamic switching languages?

Whatever Visual Studio supports, which I assume is static binding. For example, we probably won't let people pick their language, but instead will reflect the language of the Visual Studio installation.

**Comment by shana** [comment]
Fixed on #75
