### ISSUE TITLE
Open on GitHub and Blame is extremely slow

### ISSUE THREAD

**Issue by Neme12** [github/VisualStudio#1707]
When I click GitHub -> Blame or Open on GitHub, it takes more than 10 minutes until the website pops up in my browser.

**Comment by Neme12** [comment]
It's possible this has to do with the size of the repo. I tried to do this on small repos and it appears instantly. But if I try on dotnet/roslyn, it takes a very long time which makes it completely unusable. Repro:
1. clone https://github.com/dotnet/roslyn and open Roslyn.sln
2. open any file and use Open on GitHub or Blame

**Comment by Neme12** [comment]
This code looks highly suspicious to me:
https://github.com/github/VisualStudio/blob/b9939d2314c251614b096673418a1214c08fc6ca/src/GitHub.Exports/Services/GitService.cs#L106-L113

**Comment by Neme12** [comment]
Ok I can't repro this anymore... But I remember this happening to me almost every time I tried to use this feature.

**Comment by Neme12** [comment]
Thanks. Sorry for posting without a repro or more info, it was just a bit frustrating. I don't use the product regularly (only when contributing) but I've experienced this consistently when I tried to use this feature so I thought it would be easy to reproduce. I'll try to find a repro.

**Comment by Neme12** [comment]
If I create a new commit (with one-line change), that increases the time by 2 more minutes.

**Comment by Neme12** [comment]
An empty commit works too, and it looks like every commit adds almost 2 minutes.

Here's a repro:
After cloning, open any file and click GitHub->Open on GitHub on any line. It's fast. Then run following commands:
```
git checkout -b newBranch
git commit --allow-empty -m "hello 1"
git commit --allow-empty -m "hello 2"
git commit --allow-empty -m "hello 3"
git commit --allow-empty -m "hello 4"
git commit --allow-empty -m "hello 5"
```
After doing this and trying to use Open on GitHub, it took 9 minutes 20 seconds for the website to popup.

**Comment by Neme12** [comment]
@meaghanlewis Is this repro good? I'm sorry it requires opening dotnet/roslyn but I'm not able to reproduce this with a smaller repo. I hope this helps. Thank you very much for investigating this.

**Comment by Neme12** [comment]
I'm sorry you are right... I just finished deleting my repo and then cloning from scratch (the original repo, not my fork) and I do only see a delay of about 20 seconds... 😕  I don't know what this could have been caused by... the fact it's a fork? having more custom branches? more remotes? having something in stash? I'll have to investigate more...

**Comment by meaghanlewis** [comment]
Hmm...I'm honestly not sure why it would take 10 minutes either. Yes, please let us know if you find out any more details about why this is happening. I'll do some more investigation as well. Thanks @Neme12 !

**Comment by Neme12** [comment]
@meaghanlewis I found out that adding a few additional remotes and fetching from them adds significantly more time.

After running these commands:
```
git remote add Neme12 https://github.com/Neme12/roslyn.git
git remote add CyrusNajmabadi https://github.com/CyrusNajmabadi/roslyn.git
git remote add jcouv https://github.com/jcouv/roslyn.git
git remote add gafter https://github.com/gafter/roslyn.git
git remote add jaredpar https://github.com/jaredpar/roslyn.git

git fetch Neme12
git fetch CyrusNajmabadi
git fetch jcouv
git fetch gafter
git fetch jaredpar
```

I recorded a time of over 6 minutes after clicking "Open on GitHub" in `newBranch`.

**Comment by meaghanlewis** [comment]
@Neme12 thanks for reproducing this issue some more! I'm still not experiencing a lag of more than 15-20 seconds personally, but this is something we can definitely look into. I'll leave this issue open and we'll add any more detail that we discover.
