### ISSUE TITLE
VSIXAutoUpdate.exe missing

### ISSUE THREAD

**Issue by knom** [github/VisualStudio#1710]
Hi,
I'm using VS 2017, with all the latest update installed (15.7).

Looking at EventLog, I keep getting errors from the VSIX Auto Update Task Scheduler Task.
(it NEVER ran successfully in fact., looking at the "last successfull run" property)

The task is configured to use `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXAutoUpdate.exe`, which is non existent on my machine!

Any idea on what's wrong here and how can I fix it?

Thanks, knom.

**Comment by grokys** [comment]
Hi @knom ,

This looks like a problem with Visual Studio rather than the GitHub extension.

@tinaschrepfer any ideas?

**Comment by jcansdale** [comment]
@knom no problem, east mistake to make. I'm guessing this will happen even more in future.... 😉
