### ISSUE TITLE
Remember last repository

### ISSUE THREAD

**Issue by MichaelRumpler** [github/VisualStudio#172]
My solution and most of its projects are in one repository, but I also include some projects from a different one. When I open the solution, then it always selects the wrong repository. I have to click on the top / Projects / Manage Connections and then double click the correct repository in the Local Git Repositories list.

The selected repository should be remembered and used the next time when I load the solution.
Or it should at least use the repository where the .sln file is located. This would solve my use case, but might be a problem for others. Remembering and using the last repository should be good for everybody.

**Comment by shana** [comment]
Git support in VS is handled by Microsoft and not by the GitHub extension, so we can't do much about this I'm afraid. You should report this to Microsoft via the VS feedback tool.

/cc @clboles @prasethu
