### ISSUE TITLE
Package.nuspec file is presented as deleted in Visual Studio 2015, undo doesn't have any effect and git status shows working dir is clean

### ISSUE THREAD

**Issue by jficarapi** [github/VisualStudio#173]
As seen by the screen shot attached Visual Studio is reporting that Package.nuspec is deleted, however a git status shows the working directory is clean. SourceTree also shows everything is clean.  
We are using the GitHub Extension for Visual Studio version 1.0.16.2. 

We also tried verifying things with the GitHub Desktop. It also reports No local changes.

When we try to undo he change to the Package.nuspec file from within visual studio 2015 with Update 1, nothing happens. The file remains as it had, marked as if it was deleted.
![githubforvisualstudioissue](https://cloud.githubusercontent.com/assets/14874295/11968145/1753ef0c-a8d7-11e5-8949-1323e6b1fa48.PNG)

**Comment by shana** [comment]
Looks like you're hitting an issue with the built-in git support in VS. Git support is built by Microsoft and is separate from the GitHub extension (which handles GitHub-specific tasks), so we can't do much on our side. You should report this to Microsoft via the VS feedback tool.

/cc @clboles @prasethu
