### ISSUE TITLE
Make sure we're doing Splat.ModeDetector.Current.SetInUnitTestRunner(true) once per test project

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1732]
Some of our tests appear to be failing depending on the order in which they're run. This is because `SetInUnitTestRunner(true)` isn't always getting called before a test is executed.

Since we're no longer using Fody, we should add the following to the `AssemblyInfo.cs` for each of our test projects:

```cs
[SetUpFixture]
public class SplatModeDetectorSetUp
{
    [OneTimeSetUp]
    public void RunBeforeAnyTests()
    {
        Splat.ModeDetector.Current.SetInUnitTestRunner(true);
    }
}
```

We should also remove `IEntryExitDecorator` and any other calls to `SetInUnitTestRunner(true)` in our test projects.

@meaghanlewis It might make sense to do this as part of #1721?

**Comment by meaghanlewis** [comment]
@jcansdale yes, I think it makes sense to do this in #1721. 

I'll make sure to to add the snippet to `SetInUnitTestRunner(true)` to each test project and will also remove the `IEntryExitDecorator` calls and other Fody references.
