### ISSUE TITLE
What's the future of this extension?

### ISSUE THREAD

**Issue by Neme12** [github/VisualStudio#1741]
It looks like Visual Studio will soon support pull requests for GitHub out of the box:

https://channel9.msdn.com/Shows/Visual-Studio-Toolbox/Future-of-Visual-Studio-Part-2 (PRs start at 17:33 in the video)

From the comments:
> @kendrahavens
@leetickett: It will definitely work with GitHub and VSTS out of the box. We may eventually provide extensibility points for other hosts as well. We are still testing the Create/Review a PR tools internally and it may ship in Update 15.8 RTM or later. This was a very much a *future* of VS talk. 

Wouldn't this replace many if not most of the features of this extension?

**Comment by sguthals** [comment]
Hi @Neme12!

First, thank you for opening the issues that you did today! We really appreciate it 🎉 

It's super exciting all of the things the Visual Studio team at Microsoft are coming out with integrated into the core of Visual Studio! We are unsure exactly what level of support for all of the features that we're interested in they are planning on implementing, and on what timeline. 

In the meantime, we will continue to iterate on our extension, and communicate with their team around how we might come together to offer a really rich experience for our collective customers ✨ 

We on the GitHub for Visual Studio team will also be working on our transparency for features we have coming out and will keep you and the rest of our community up to date on where we are going!

Thank you for your continued support and engagement with us! 😄

**Comment by Neme12** [comment]
Thanks. I'm still not sure what this means for the future, but it's exciting to see all the improvements on both sides and the desire to work together to make a great experience 🎉
