### ISSUE TITLE
A way of browsing tags

### ISSUE THREAD

**Issue by rsheptolut** [github/VisualStudio#175]
This may be a new page "Tags" which lists all of the tags in the repository. It's next to impossible to get exactly the ASP.NEt 5 rc1 with this extension, but it's straightforward with SourceTree, for example, which has "Tags" in its tree, I just select rc1 tag and that's that.

**Comment by shana** [comment]
Thanks for the feedback! Git support in VS is built and shipped by Microsoft, and separate from the GitHub extension, so there's not a lot we can do, but I'm sure Microsoft would appreciate the feedback. You can send it via the feedback tool in VS.

/cc @cathysull @clboles
