### ISSUE TITLE
Stuck at Two-Step Authentication

### ISSUE THREAD

**Issue by haider-kazal** [github/VisualStudio#176]
After updating the extension to the latest, it gets stuck after I give the token. Tried in 4 pcs, happens in all of them.

![image](https://cloud.githubusercontent.com/assets/11274411/11975771/69193ee0-a99b-11e5-9750-8c5538ccc77c.png)

**Comment by shana** [comment]
There's nothing in the latest release that would affect the login, so not sure what's going on here. If it's still happening, you can try uninstalling the extension and installing earlier releases from the releases page at https://github.com/github/VisualStudio/releases, to see if you can find one that works (and where it broke)

**Comment by haider-kazal** [comment]
Ok... Thanks, I'll roll back to previous version then.

Date: Mon, 28 Dec 2015 02:40:42 -0800

**Comment by anthonychu** [comment]
This happened to me on 2 separate VS2015 installs as well. As we can see in the screenshot above, the login is actually completed (GitHub repos are showing in Team Explorer). But the modal stays open with the "Verify" spinner going forever. Closing the modal manually by clicking the X seems to work fine.

**Comment by Haacked** [comment]
I think I know what this bug is. It's tricky. I can look into it later.

**Comment by haider-kazal** [comment]
Thanks everyone... And another thing, I get logged out each time I close Visual Studio after these bug occured... Please look onto tha too... Thanks

**Comment by timsneath** [comment]
Getting the same issue here with Visual Studio 2015 Update 1, although as @anthonychu says, you can close the dialog box and everything still seems to work.

**Comment by WillBuik** [comment]
Running into this as well on VS 2015 Update 1.  Manually closing the dialog worked around the issue for me.

**Comment by jakenuts** [comment]
I found a solution from several articles on the subject, though [this one](http://www.anilsezer.com/connecting-github-from-visual-studio-after-twofactor-authentication-enabled) had the right combination (for me). In short, you generate a [Personal Access Token](https://github.com/settings/tokens) in GitHub and when the authentication window appears enter your GitHub username and the token as your password. I haven't seen the dialog since.

**Comment by shana** [comment]
Thanks for the reports everyone. We're working on this, it feels like the dialog just isn't closing properly even though it completes the authentication successfully (but not every time, so it's annoying to debug).

@jakenuts The authentication dialog already handles 2FA, so using personal tokens is not the solution to this particular issue.

**Comment by shana** [comment]
Hey everyone!

#202 is the reason why some of you keep getting logged out. I'll get a new release out asap to fix that as well as the login dialog not going away, will let you know when it's out.

**Comment by shana** [comment]
Hi again!

I just published a beta that includes a fix for this - v1.0.16.3. It's still undergoing testing, but if you want to try it out, you can configure a gallery in Visual Studio to get access to beta, current and older versions of the extension. You can also download the beta from the [releases](https://github.com/github/VisualStudio/releases) page.

To configure the beta gallery, go to `Tools / Options / Extensions and Updates` and add a new gallery with the url https://visualstudio.github.com/releases/feed.rss. You'll be able to access it in `Tools / Extensions and Updates` in the Online or Updates tab, and you'll be able to install the beta version (or older versions, if you want).
