### ISSUE TITLE
Gists

### ISSUE THREAD

**Issue by Hudsonville** [github/VisualStudio#1762]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio version:
- Visual Studio version:  diing assistance to non-profit organizations and envirnment

__What happened__ (with steps, logs and screenshots, if possible)

**Comment by meaghanlewis** [comment]
Hi @Hudsonville please fill out the issue template if you have feedback about the GitHub Extension for Visual Studio.
