### ISSUE TITLE
GIT Pull Message Dialog is unnecessarily repetitive

### ISSUE THREAD

**Issue by r0bfr** [github/VisualStudio#1769]
- GitHub Extension for Visual Studio version:
- Visual Studio version: 15.6.7

1. In VS, with a GIT repo open, pull changes on the currently checked out build.  The following dialog will show up.  On the dialog the title and message are exactly the same.)

![git](https://user-images.githubusercontent.com/30732880/42244709-e7afc6dc-7eca-11e8-8829-b797b95fa061.PNG)

I feel like the title should be "Git".

**Comment by meaghanlewis** [comment]
Hi @r0bfr the pull functionality is provided by the Git integration built by Microsoft. This is the repository for the GitHub for Visual Studio extension. To provide this feedback to Microsoft, you'll want to reach out to their support here: https://www.visualstudio.com/support/
