### ISSUE TITLE
Proposal: Number formatting when cloning

### ISSUE THREAD

**Issue by SetTrend** [github/VisualStudio#177]
It would be nice to have the number of files being formatted using true Number formatting (i.e. group separator character, etc.). That would make it easier to read the information:

![cloning](https://cloud.githubusercontent.com/assets/9283914/12088474/ec92ace0-b2db-11e5-83de-787fd16f280e.png)

**Comment by shana** [comment]
Thanks for the feedback! The progress report area is shipped with Team Explorer and not a direct part of the GitHub extension, so we can't do anything on our side I'm afraid. You can send feedback to MS via the feedback tool in Visual Studio so they're aware of this.

/cc @cathysull @clboles @prasethu

**Comment by SetTrend** [comment]
Ah, I see ... Thanks for clarifying :smile:
