### ISSUE TITLE
Extension ships with a newer Newtonsoft.Json than Visual Studio 2017

### ISSUE THREAD

**Issue by kzu** [github/VisualStudio#1774]
The currently published extension ships with Json.NET version `10.0.x` whereas VS ships built-in with `9.0.x`. It's strongly advised that you do not ship newer versions of built-in VS assemblies, since that can cause incompatibilities or breakages in other packages. 

Might be related to https://developercommunity.visualstudio.com/content/problem/287648/xamarin-android-and-ios-projects-will-not-load-aft.html.

**Comment by grokys** [comment]
The reason we're now doing this is that one of our dependencies uses 10.0. I can check whether that dependency is happy with 9.0, but if not, what is the recommended way of fixing this?

**Comment by jcansdale** [comment]
@kzu 👋 should we treat `Newtonsoft.Json` as a Visual Studio assembly and not package it at all?

**Comment by kzu** [comment]
That's tricky. We had package load failures in some cases if we didn't distribute it, so we always make sure we distribute the same version as the VS we ship with :(

**Comment by kzu** [comment]
Also of interest: VS ships with binding redirects for this, currently:

```
			<dependentAssembly>
				<assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral"/>
				<bindingRedirect oldVersion="1.0.0.0-9.0.0.0" newVersion="9.0.0.0"/>
			</dependentAssembly>
```

So you can build against any older version, but not newer.

**Comment by jcansdale** [comment]
@kzu,

It appears VS 2015 only knows about 4.5.0.0-6.0.0.0:
```xml
                <dependentAssembly>
                    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral"/>
                    <bindingRedirect oldVersion="4.5.0.0-6.0.0.0" newVersion="6.0.0.0"/>
                </dependentAssembly>
```

Do you know what is happening to cause the breakage? I can't immediately think of a scenario short of an extension calling `Assembly.Load("Newtonsoft.Json")` and assuming a particular version. I'd like to understand what's going on here.
 
I'm wondering if we should be using a `[ProvideCodeBase]` attribute for `Newtonsoft.Json`? We're now using `ProvideBindingPath` to make sure that our assemblies can be resolved (including from `.imagemanifest`, see #1236).

This will have the side effect of making our version of `Newtonsoft.Json` available via `Assembly.Load("Newtonsoft.Json")`. We could put it on a different path and explicitly specify its code base.
