### ISSUE TITLE
Repository creation failed with control characters in description

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1777]
- GitHub Extension for Visual Studio version: 2.5.4
- Visual Studio version: 2017

![image](https://user-images.githubusercontent.com/11719160/42603946-f608282a-8567-11e8-872e-055a773ed99c.png)

Looking at fiddler, it appears there are some restrictions in what chars are allowed in the description:

![image](https://user-images.githubusercontent.com/11719160/42604115-0126fbb8-8569-11e8-91cd-aedfb0af9c5a.png)

### What I expected to happen

Maybe it should show the error message?
```
message=description control characters are not allowed
```

**Comment by meaghanlewis** [comment]
Nice find @jcansdale. The message `description control characters are not allowed` is still a bit vague because it's not clear which character isn't allowed but I think it's better than a general repository creation failure.

Also, I tried the same description when creating a repository on dotcom and it was able to be created just fine. I'm wondering why the control characters are allowed there but not in Visual Studio.

**Comment by grokys** [comment]
@jcansdale any idea what the control characters were in the description? I can't see any in the fiddler screenshot that you posted.

**Comment by grokys** [comment]
> Also, I tried the same description when creating a repository on dotcom and it was able to be created just fine. I'm wondering why the control characters are allowed there but not in Visual Studio.

I suspect .com may just be stripping control characters? Assuming that's the case, it would make sense for us to do the same.

**Comment by jcansdale** [comment]
I think the control char in question might be `\r`. 😆

**Comment by Kartik210798** [comment]
You should try adding a description without any line break ie. **Type your whole description in just a single line.** 
Type all of it without pressing [ENTER KEY.]

--Hope it helps.

**Comment by kamau-mbugua** [comment]
422 Unprocessable Entity - Repository creation failed. [Repository; description]custom: description control characters are not allowed
This characters might be lets say Including Uppercases in your description.

**Comment by rafaelramonalves** [comment]
You need to type all the description in one line, 
no line breaks

**Comment by abdessamadjadid** [comment]
> I think the control char in question might be `\r`. 😆

yes it is , make no sense , we are in 2020 and still having this issue

**Comment by damien-roche** [comment]
This came up when attempting to edit the description for a repo. Awful. Sort it out.

**Comment by OMIII1997** [comment]
**Type whole description without pressing ENTER key. It helped for me.**

**Comment by nquayson** [comment]
Why are we still having this problem in 2020? A simple **line break** lol

**Comment by jcansdale** [comment]
@nquayson this should have been fixed in https://github.com/github/VisualStudio/pull/1845

Is this not the case? 🤔

**Comment by nquayson** [comment]
Probably @jcansdale. Anyway, Im doing this directly on github. I'm just unhappy it doesn't accept my linebreak with an error message that is so not clear.

**Comment by lestgabo** [comment]
this isn't just a visualstudio issue. It also happens in the github webapp. thanks for the `don't press enter` solution, it works.

**Comment by flaviocr2012** [comment]
> You should try adding a description without any line break ie. **Type your whole description in just a single line.**
> Type all of it without pressing [ENTER KEY.]
> 
> --Hope it helps.

It worked for me. Thanks!

**Comment by Abhishek12345679** [comment]
In my case it happened because of intentional returns(enters).

**Comment by 7yl4r** [comment]
This is an issue that should be opened on the github API. It's an annoyingly vague error message that pops up even when using the web UI.

**Comment by tripathi-abhishek** [comment]
> You should try adding a description without any line break ie. **Type your whole description in just a single line.**
> Type all of it without pressing [ENTER KEY.]
> 
> --Hope it helps.

This helped. SPOT ON. THANKS

**Comment by badripaudel77** [comment]
If someone is having multiple lines, make sure it is one line.

**Comment by pavk55** [comment]
> You should try adding a description without any line break ie. **Type your whole description in just a single line.**
> Type all of it without pressing [ENTER KEY.]
> 
> --Hope it helps.

this one helps my side. everything on one line and after update it worked ;)

**Comment by Shashi242** [comment]
> You should try adding a description without any line break ie. **Type your whole description in just a single line.** Type all of it without pressing [ENTER KEY.]
> 
> --Hope it helps.

thanks a lot bro

**Comment by DhRiTiD** [comment]
i figured.... it says so when you use 'enter key'

**Comment by godwin-c** [comment]
When I removed "version" from the description I made, it went through.
