### ISSUE TITLE
Only allows me to commit if my solution is closed.

### ISSUE THREAD

**Issue by MulleDK19** [github/VisualStudio#178]
After updating Visual Studio to Update 1, it also installed the latest version of the GitHub extension, and ever since I've been unable to commit.

I've had to start up VS 2013 and commit from that. Then committing works like one time in VS 2015, and then it goes back to pretending there are no changes.

Today I discovered that if no solution is open in VS 2015, then all of a sudden the GitHub extension works, and shows all changes in the Changes panel. But as soon as I re-open my solution, it goes back to showing no changes, no exclusions and no untracked files, and I can't commit.

Solution open:
![image](https://cloud.githubusercontent.com/assets/3169809/12141802/0b91e1f4-b473-11e5-9edf-59d93573bed2.png)

Solution closed:
![image](https://cloud.githubusercontent.com/assets/3169809/12141806/150fdc86-b473-11e5-8a32-bb318a97404d.png)

I don't have to open then close the solution for the second image. The extension starts in this state, when I launch VS 2015.

**Comment by shana** [comment]
It looks like you're having problems with the built-in git support that ships with Visual Studio. This is not a part of the GitHub extension (which only handles GitHub-specific tasks like cloning and such). For these issues, you should send feedback to Microsoft directly from the feedback tool inside Visual Studio

/cc @clboles @prasethu
