### ISSUE TITLE
In Git web organization shows repository was updated but repo was not touched from long period

### ISSUE THREAD

**Issue by DeepakInvenger** [github/VisualStudio#179]
We have organization, when I open it in web I see some of the repositories are recently modified however when I open the particular repository there are no changes in any of the branch from long time. I have cloned that repo to locally recently but never made changes in it. what could be the issue?

**Comment by shana** [comment]
Are you synchronizing your local clone? You need to pull changes that have happened remotely to be able to see them locally, this doesn't happen automatically. You can do this in the Sync area, there are sync and pull actions there that will do the job.
