### ISSUE TITLE
Status bar downloading/building icons alignment issue

### ISSUE THREAD

**Issue by pushqrdx** [github/VisualStudio#1792]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio version: n/a
- Visual Studio version: 15.7.5

__What happened__ (with steps, logs and screenshots, if possible)
When building a project while downloading nuget packages both these icons show none aligned also when you hover either of them there isn't any tooltip to clarify what they're doing.

![image](https://user-images.githubusercontent.com/25884937/43024255-ff4143e2-8c6d-11e8-8dfc-b74ce485347e.png)

The above behavior adds up to a less pleasant user experience which is unexpected from Visual Studio.

**Comment by grokys** [comment]
Hi @pushqrdx - this is a problem with Visual Studio, but this is the repository for GitHub for Visual Studio.

As such we can't do anything about this problem (I know it's irritating, it irritates me too! ;) ) - you'd be better logging it over at https://developercommunity.visualstudio.com.
