### ISSUE TITLE
Delete comment icon is very close to close window icon

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1797]
- GitHub Extension for Visual Studio version: 2.5.4

The ✖️ icon to delete an inline-comment is very close to the icon used to close the inline-comment window and also appears in the top right hand corner of a box.
![image](https://user-images.githubusercontent.com/11719160/43134910-85f7be28-8f3b-11e8-9c85-79b664d9478d.png)

If a user accidentally clicks on the delete icon, there is no confirmation to correct their mistake.

Maybe we could change it to be a `...` drop down menu with a `Delete` option like .com relatively recently changed to.

![image](https://user-images.githubusercontent.com/11719160/43135252-a91cbe66-8f3c-11e8-9ebd-1e917a55ea52.png)

**Comment by StanleyGoldman** [comment]
Related to #1713

**Comment by donokuda** [comment]
I'm going to take a quick stab at this and https://github.com/github/VisualStudio/issues/1713.

I'll focus on two things:

1. Increasing the spacing between the ✏️ and the ❌ octicon
2. Popup a dialog when a user clicks on the ❌ asking them to confirm if they want to delete the comment. (and clicking "Delete" should delete the comment.)

**Comment by meaghanlewis** [comment]
I think we can close this out now. Please re-open if I'm incorrect 😄
