### ISSUE TITLE
GitHub VS extension is loaded for all C# apps

### ISSUE THREAD

**Issue by PooyaZv** [github/VisualStudio#1799]
(Writing from VS platform team)

GitHub extension reads in 2.5 MB off of disk when I create a basic C# app (with just an empty Main method) that doesn't use GitHub. This is with a full install of Visual Studio 15.8 Preview 3.0 (all workloads/packages installed). Disk access especially during solution load can be costly. Therefore, it should be avoided if the project doesn't use a feature. For more information please see [this page](https://msdn.microsoft.com/en-us/library/mt750411.aspx).

Below, please find the breakdown by DLL:

Name | Bytes | Page Ct
-- | -- | --
System.Reactive.Linq.dll (C:\Program   Files (x86)\Microsoft Visual Studio   15.0\Common7\IDE\Extensions\GitHub\GitHub) | 552,960 | 135
GitHub.App.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 319,488 | 78
Octokit.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 270,336 | 66
ReactiveUI.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 225,280 | 55
LibGit2Sharp.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 204,800 | 50
GitHub.InlineReviews.dll (C:\Program   Files (x86)\Microsoft Visual Studio   15.0\Common7\IDE\Extensions\GitHub\GitHub) | 159,744 | 39
Akavache.Sqlite3.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 114,688 | 28
System.Reactive.Core.dll (C:\Program   Files (x86)\Microsoft Visual Studio   15.0\Common7\IDE\Extensions\GitHub\GitHub) | 106,496 | 26
rothko.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 94,208 | 23
SQLitePCL.raw.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 81,920 | 20
Akavache.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 81,920 | 20
GitHub.Exports.Reactive.dll (C:\Program   Files (x86)\Microsoft Visual Studio   15.0\Common7\IDE\Extensions\GitHub\GitHub) | 77,824 | 19
GitHub.TeamFoundation.15.dll (C:\Program   Files (x86)\Microsoft Visual Studio   15.0\Common7\IDE\Extensions\GitHub\GitHub) | 69,632 | 17
Splat.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 57,344 | 14
GitHub.Api.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 40,960 | 10
GitHub.VisualStudio.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 36,864 | 9
System.Reactive.PlatformServices.dll   (C:\Program Files (x86)\Microsoft Visual Studio   15.0\Common7\IDE\Extensions\GitHub\GitHub) | 32,768 | 8
sqlite3.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub\x86) | 32,768 | 8
GitHub.Exports.dll (C:\Program Files   (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\GitHub\GitHub) | 28,672 | 7
System.Reactive.Windows.Threading.dll   (C:\Program Files (x86)\Microsoft Visual Studio   15.0\Common7\IDE\Extensions\GitHub\GitHub) | 24,576 | 6
GitHub.Services.Vssdk.dll (C:\Program   Files (x86)\Microsoft Visual Studio   15.0\Common7\IDE\Extensions\GitHub\GitHub) | 20,480 | 5
System.Reactive.Interfaces.dll   (C:\Program Files (x86)\Microsoft Visual Studio   15.0\Common7\IDE\Extensions\GitHub\GitHub) | 20,480 | 5

Please do not hesitate to let us know if any further information is needed.

Thank you

**Comment by jcansdale** [comment]
@PooyaZv,

Thanks for letting us know. We do try to be good Visual Studio citizens, but it's easy for things to get out of hand. I'm tackling this issue here #1802.

You can find the .vsix from this PR here:
https://ci.appveyor.com/api/buildjobs/3btwu6yp23x3y960/artifacts/2.5.4.3390%2FGitHub.VisualStudio.vsix

If you were up for confirming this fix, that would be much appreciated!

We're using MEF so we can't eliminate the assembly loads entrirely, but we can make it a lot better (see the PR/`How to test` for what to expect).
