### ISSUE TITLE
Localization: Localize the extension to {insert language here}

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#18]
Imported from https://github.com/github/VisualStudioInternal/issues/35

**Comment by shana** [comment]
Depends on https://github.com/github/VisualStudio/issues/17

**Comment by elbaloo** [comment]
I can help with es-MX but I'm not following the implementation... I'm looking at [this](https://msdn.microsoft.com/en-us/library/system.resources.resourcemanager(v=vs.110).aspx#CultureSpecific).

**Comment by shana** [comment]
@elbaloo There are several resx files in the solution which contain strings. Adding translations is a matter of editing the resx files, adding a new language and the translated strings. There's an extension for Visual Studio called Resx Manager (http://resxresourcemanager.codeplex.com/) that makes this easier.

**Comment by romanoza** [comment]
Hi there, I can translate string resources to Polish.

**Comment by austin94** [comment]
@shana is this issue available?  I can use the resxresourcemanager listed above _(which if I remember correctly just uses Bing Translate if you ask it to translate as well as read)_.  I am also currently at a University and know several native speakers of the bigger languages so I can double check with them.

What are your target languages?

**Comment by Haacked** [comment]
> What are your target languages?

ALL OF THEM! :stuck_out_tongue: 

In all seriousness, we'll take all the languages people are willing to contribute as long as we can reasonably ensure the translations are of good quality.

**Comment by austin94** [comment]
The languages provided in the [Microsoft Visual Studio 2015 Language Pack](https://www.microsoft.com/en-us/download/details.aspx?id=48157) are:

- Chinese (Simplified) - **known native speaker**
- Chinese (Traditional) - **possibly known native speaker**
- Czech
- English - **I hope this one is right**
- French - **known native speaker**
- German - **known native speaker**
- Italian - **known native speaker**
- Japanese
- Korean
- Polish
- Portuguese (Brazil)
- Russian - **known native speaker**
- Spanish - **known native speaker**
- Turkish

This should be a good start since most people using VS will be stuck with these.

Also, randomly heard your DotNetRocks podcast the other day.  It was a good talk!

**Comment by shana** [comment]
> is this issue available?

All issues are available :smile:

Software translation should probably not be done with Bing, though :wink:

Microsoft has excellent resources for translation at https://www.microsoft.com/Language/en-US/Default.aspx, including style guides and terminology collections.

**Comment by Haacked** [comment]
> Software translation should probably not be done with Bing, though

It's _probably_ fine to use automated translation (such as Bing or Google) to get  started as long as the translation is checked and corrected by a native speaker, which is what I think @austin94 suggested. :smile:

> Also, randomly heard your DotNetRocks podcast the other day. It was a good talk!

Thanks! :sparkles:

**Comment by austin94** [comment]
Here is a google spreadsheet of all the resx keys that I found along with Translations: https://docs.google.com/spreadsheets/d/1zE-KmrVhSQy3bgJ0Fmaxid-5ImGtEyQzFGaLZZwQ-cI/edit?usp=sharing

So far I have only used Google Translate for Chinese (Simplified), Czech, and German.  I hope to have all of these languages double checked by native speakers by the end of this weekend before I move on to others.

One questions on branding though.  For the phrase 'GitHub Enterprise' would you prefer that to be left in English for branding?  Or would 'GitHub <translation>' work?

**Comment by shana** [comment]
@austin94 Brand names need to be double-checked internally, so leave them as is.

**Comment by austin94** [comment]
I have a completed translation from a native Korean speaker so I will be bringing that in soon.  From what he described Google Translate got pretty close, but he gave some grammatical fixes and added some git terminology that it struggled with.  Also, the string lengths are pretty close across all of the phrases so we shouldn't have much of an issue with under-over flow of text.

**Comment by maikebing** [comment]
@shana  I am Chinese! So can i translate it?

**Comment by austin94** [comment]
@maikebing Unfortunately, I never completed updating the locale files.  I am no longer implementing this feature, but I will leave the google sheet up and give you write access if you still want to translate.

We can leave it here if anyone eventually wants to finish.

**Comment by Gabrux5** [comment]
I am italian, I can translate it if you want :)

**Comment by austin94** [comment]
I am no longer acitvely working on this PR.

If anyone else would like to give it a shot please feel free to take over!

**Comment by wenz** [comment]
Who is maintaining this? I have a set of German translations ready to be used ;)

**Comment by maikebing** [comment]
I started to do this thing. I hope everyone will support it.

**Comment by wenz** [comment]
@maikebing could you set up the Google Doc (or something similar) again, so that I can dump the German translations?

**Comment by maikebing** [comment]
@wenz  OK, I will have all the statements extracted after the completion, sent to everyone.

**Comment by maikebing** [comment]
[GitHubVS_English.xlsx](https://github.com/github/VisualStudio/files/2066761/GitHubVS_English.xlsx)
@wenz   @Gabrux5

**Comment by wenz** [comment]
shoud we put it up on Google Sheets or something similar, so that we can edit simultaneously?

**Comment by maikebing** [comment]
@wenz  This looks better. 
    https://crowdin.com/project/githubvs

**Comment by meaghanlewis** [comment]
@maikebing [this crowdin page](https://crowdin.com/project/githubvs) is great, thanks! It's really nice to visualize the progress of the localizations by language

**Comment by meaghanlewis** [comment]
Closing out since this work was completed in #1968
