### ISSUE TITLE
Extra line included when `Open on GitHub` is called with a selection

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1843]
- GitHub Extension for Visual Studio version: 2.5.5

*NOTE: Use the keyboard rather than the mouse to select:*

1. Select a range in the code editor
![image](https://user-images.githubusercontent.com/11719160/43834353-b222e9b6-9b05-11e8-9d27-dae1cb9ca234.png)
2. Right-click, `GitHub > Open on GitHub`

- Browser opens with extra line selected
![image](https://user-images.githubusercontent.com/11719160/43834444-08e68a5a-9b06-11e8-8884-07fa70e08056.png)

Alternatively:

1. Select a range in the code editor
![image](https://user-images.githubusercontent.com/11719160/43834353-b222e9b6-9b05-11e8-9d27-dae1cb9ca234.png)
2. Right-click, `GitHub > Copy link to clipboard`
3. Right-click, `GitHub > Open from clipboard`

- An extra line is selected
![image](https://user-images.githubusercontent.com/11719160/43834575-71dcc47a-9b06-11e8-9d2d-8aced3a58cad.png)

**Comment by meaghanlewis** [comment]
Good catch!

**Comment by meaghanlewis** [comment]
Actually, I'm having a hard time reproducing this behavior. The right lines always seem to be highlighted for me.

**Comment by grokys** [comment]
@meaghanlewis i was able to repro by selecting the lines in @jcansdale's screenshots (https://github.com/github/VisualStudio/blob/8651fe83e6fba841f1d21279c04027e10828f203/src/GitHub.VisualStudio/Commands/CopyLinkCommand.cs#L49-L53)

**Comment by jcansdale** [comment]
> Actually, I'm having a hard time reproducing this behavior. The right lines always seem to be highlighted for me.

You'll probably find this happens when using the keyboard rather than the mouse to select. The reason is that you'll tend to start (or end) the selection on the line below the selected area. If you start your selection at the bottom, this extra line will be completely invisible. If you start your selection at the top, this extra line will be obscured by the blinking caret.

Does that make sense?
