### ISSUE TITLE
Localization of GHfVS

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1858]
Localization work started. So far Chinese (Simplified) and Chinese (Traditional) have been completed thanks to @maikebing 🎉. 
 
Let's all translate together here: https://crowdin.com/project/github-visual-studio

Add your name to any localization you are working on.

- [x] [Chinese (Simplified)]
- [x] English - 
- [ ] German -  @wenz
- [ ] Russian - 
- [ ] Spanish -

**Comment by maikebing** [comment]
localize the package metadata which is used by VS 'Extensions and Update'  #1860

**Comment by meaghanlewis** [comment]
Related localization issues:
#17
#18

**Comment by robertlluberes** [comment]
Hello @meaghanlewis

I joined in GitHubVS Spanish translation on Crowdin and I suggested 100+ new translations in the followings files:

````
GitHub.App/Resources.resx
GitHub.VisualStudio.UI/Resources.resx
GitHub.VisualStudio/GitHub.VisualStudio.en-US.vsct
````

Thats the correct way to do it? I hope so.

Any guide or susgestion to help me to translate it is welcome. Thanks

**Comment by robertlluberes** [comment]
Hello again :sweat_smile: @meaghanlewis 

Today I joined on this Crowdin project: [GitHub Visual Studio](https://crowdin.com/project/github-visual-studio) that is integrated with the GitHub repository and made more than 200 suggestions in Spanish.

it's almost done.

**Comment by meaghanlewis** [comment]
Thank you for your contributions @robertlluberes! We will start to review and approve your translations which will automatically create a Pull Request in this repository similar to this one: https://github.com/github/VisualStudio/pull/1892. 

Once all the translations are complete and approved we can merge them. Let us know if you have any other questions.

**Comment by rgomez90** [comment]
@meaghanlewis I have a question. In some languages (like spanish or german) when referring to a person (in this case the reader) we can use two forms, a formal and an informal one (both means "you" in english) When translating wich form should be used here?

**Comment by meaghanlewis** [comment]
👋 @rgomez90 good question! We want our extension to be friendly and approachable to all, so I would suggest to use informal pronouns.

**Comment by wenz** [comment]
IIRC Visual Studio itself is using the more formal pronouns, so I'd recommend sticking to that.

**Comment by meaghanlewis** [comment]
👋 @wenz I was going off of what our localization team at GitHub recommended for the language of our extension itself.

**Comment by StanleyGoldman** [comment]
I also update4d the body of the issue, I looked at our statistics and the only languages in use are English, Simplified Chinese, Spanish German and Russian

**Comment by rgomez90** [comment]
@meaghanlewis any updates?

**Comment by meaghanlewis** [comment]
Hi @rgomez90 we decided it's best to use with formal pronouns to follow the standard Visual Studio sets.

**Comment by rgomez90** [comment]
@meaghanlewis nice! 😄  I think you should put this info somewhere in Readme or sth.

**Comment by meaghanlewis** [comment]
Closing out since this work was completed in #1968

**Comment by eriawan** [comment]
@meaghanlewis 

Could I add additional translation for Indonesian language (in Bahasa Indonesia)?

**Comment by meaghanlewis** [comment]
👋@eriawan we localized to support the 13 languages that Visual Studio does. I don't think you'll be able to provide translations for the Indonesian language since they will not be supported by Visual Studio itself.

**Comment by eriawan** [comment]
@meaghanlewis 

> we localized to support the 13 languages that Visual Studio does. I don't think you'll be able to provide translations for the Indonesian language since they will not be supported by Visual Studio itself.

ah, this is quite understandable. makes sense, but I hope VS team will provide Indonesian language support in VS.

Thanks!
