### ISSUE TITLE
Initial loading of repository does not show it's name and URL

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1869]
## Version

- GitHub Extension for Visual Studio version: I've seen this across multiple versions from 2.5.2 - 2.5.5
- Visual Studio version: reproduced on VS2017

## What happened
Instead of showing the repositories name and URL on Team Explorer - Home, a warning icon is shown instead

**Steps to Reproduce**

1. Open up Visual Studio
2. Connect to a repository
3. Go to Team Explorer - Home

**Expected behavior:**
Under the GitHub section I see the repo name and URL.

**Actual behavior:**
I see a warning icon for a minute until the connection is made. After a minute or so this resolves itself.

This doesn't reproduce 100% of the time but I have seen it multiple times on startup of Visual Studio today. Sometimes pressing refresh will show this icon.

**Screenshot:**

![screen shot 2018-08-21 at 10 32 12 am](https://user-images.githubusercontent.com/10103121/44418591-af6bf780-a52d-11e8-9cda-be5eab336fba.png)

**Comment by grokys** [comment]
Is there anything that might look relevant in the log?

**Comment by meaghanlewis** [comment]
No, I didn't notice anything relevant in the log @grokys. And I'm having a hard time reproducing this today. I'll observe this over the next few days and close this issue if I don't see this happening at all anymore.

**Comment by meaghanlewis** [comment]
I haven't been able to repro this so I'll close this issue out.
