### ISSUE TITLE
NPM dependencies and Task Runner Explorer integration missing with Angular template in VS 2017

### ISSUE THREAD

**Issue by jitterbox** [github/VisualStudio#1874]
When you create a new project using the ASP.NET Core Angular project template, the Angular app (and its package.json) are placed within a /ClientApp folder. But apparently Visual Studio 2017 only enumerates your NPM packages and lists them under your project Dependencies in Solution Explorer when the package.json is in the project root (?). Same goes for the auto-detection of NPM scripts within Task Runner Explorer.

I [opened an issue](https://github.com/aspnet/Templating/issues/697) with the aspnet/Templating team, but they closed it and recommended I start one here instead.

**Comment by meaghanlewis** [comment]
👋 @jitterbox this is an issue with Visual Studio itself - and this is the repository for the GitHub extension for Visual Studio. You can go here: https://visualstudio.microsoft.com/support/ and open up an issue.
