### ISSUE TITLE
Annotations for Visual Studio and GitHub.com

### ISSUE THREAD

**Issue by sguthals** [github/VisualStudio#1878]
# Overview
Now that checks and statuses are integrated into the `GitHub Extension for Visual Studio`, we'd like to start exploring how to integrate annotations into the author and reviewer workflow for pull requests within Visual Studio and on GitHub.com. 

@StanleyGoldman has begun prototyping how to use MSBuild log files to inform the build status of .NET projects. You can check out the GitHub App [here](https://github.com/justaprogrammer/MSBuildLogOctokitChecker) and a prototyped version of this in action on GitHub.com [here](https://github.com/justaprogrammer/TestConsoleApp1). 

## Team
@StanleyGoldman @donokuda and @sguthals are designing the first prototype of this experience, in order to test it out with some Beta users and decide how to formally integrate it into the workflow for `GitHub Extension for Visual Studio` users.

### Beta Release
On October 1, 2018 we plan to release a beta experience of viewing annotations for `GitHub Extension for Visual Studio` users. Here is an abridged outline of what needs to be completed prior to Beta release:
- A list of the files that have annotations (errors/warnings)
- A way for users to open the diff of the file and see the annotation inline on the right side of the diff
- Metrics/UXR learn:
  - How often do users go from diff, immediately to editor and modify code near the annotation?
  - How often do users view the annotations in the diff?
  - How often do users view the list of annotations inside Visual Studio?
  - How often do users view the list of annotations on GitHub.com?
  - What role are people serving when viewing the annotations inside Visual Studio? GitHub.com?

| Item | Assigned To | Deliverable Date | PR |
| ---- | ------------- | ---------------- | --- | 
| Design for listing the the files that have annotations | @donokuda | | |
| Ability to go from the annotation list to diff view | @StanleyGoldman  | | |
| Usability Study | @sguthals @StanleyGoldman @donokuda | | |

### Public Release
On November 5, 2018 we plan to release our prototype to general use. This version will include any changes based on what we learned for the October 1, 2018 release.

**Comment by sguthals** [comment]
<img width="1421" alt="screen shot 2018-08-29 at 11 08 53 am" src="https://user-images.githubusercontent.com/1314285/44806523-0e5bed00-ab7c-11e8-8ed2-dfaac09170aa.png">

<img width="1344" alt="screen shot 2018-08-29 at 11 09 17 am" src="https://user-images.githubusercontent.com/1314285/44806536-14ea6480-ab7c-11e8-9eee-200257e77bba.png">

**Comment by meaghanlewis** [comment]
Update: we are planning to 🚢 the Beta release for this on December 10th, 2018.
