### ISSUE TITLE
2FA dialog stays busy when network connection is down

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#19]
Imported from https://github.com/github/VisualStudioInternal/issues/346

Repro steps:
1. Login with an account that has 2fa enabled.
2. Disconnect internet access from your computer.
3. Enter 2fa code and hit verify.

Expected: 2fa dialog shows an error message.
Actual: The verify button stays disabled and busy. Note, the dialog is still responsive, the operation just never completes.

<img src="https://cloud.githubusercontent.com/assets/19977/7335383/7468394a-eb6e-11e4-8a09-33c6685a75f9.png" width="365" />

**Comment by shana** [comment]
Not sure if this one is actually valid any more, it's from April 25. Needs testing.

**Comment by JoshDobbin** [comment]
I'm also running into the same issue as of the latest version (1.0.18.6).

**Comment by brezho** [comment]
Same here with 2.0.14.4

**Comment by grokys** [comment]
I think this is the same issue as #829 - the 2FA dialog doesn't catch any non-2FA exception and just sits there spinning.
