### ISSUE TITLE
Notify the user once a new Gist has been created

### ISSUE THREAD

**Issue by georgebearden** [github/VisualStudio#196]
To further refine the `Gist` creation work being done in #194, it would be nice to automatically copy the URL returned from the GitHub API to the clipboard, and also generate a VS notification to notify the user using one of the `VSServices` methods [here](https://github.com/github/VisualStudio/blob/master/src/GitHub.Exports/Services/VSServices.cs#L29-L30).

To get the URL needed to copy to the clipboard one can subscribe to the `IReactiveCommand` [here](https://github.com/github/VisualStudio/blob/feature/gist-support/src/GitHub.Exports.Reactive/ViewModels/IGistCreationViewModel.cs#L12).

**Comment by shana** [comment]
I'm adding an API for showing notifications in the status bar, Team Explorer notifications are way too intrusive imo (and requires Team Explorer to be visible, which might or might not be true)

**Comment by georgebearden** [comment]
Now that #201 has been merged into master, would now be a good time to implement this feature, targeting the feature/gist-support branch?

**Comment by shana** [comment]
@georgebearden Indeed! It's already implemented by the `Copy link` feature, so should be an easy addition.

**Comment by paladique** [comment]
Fixed in #572
