### ISSUE TITLE
am not getting the option of push to remote or git repo

### ISSUE THREAD

**Issue by jharnadave** [github/VisualStudio#1991]
## Version

- GitHub Extension for Visual Studio version:
- Visual Studio version:

## What happened

**Steps to Reproduce**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Screenshot or GIF:**

**Log file:**

![capture2](https://user-images.githubusercontent.com/43570774/46993271-ed4f5b80-d12b-11e8-8e14-706dd854b104.PNG)

**Comment by meaghanlewis** [comment]
👋@jharnadave it would be helpful if you could clearly specify what you expect to be able to do that you are unable to do currently.

This git functionality is provided by Visual Studio itself that our team, which builds the GitHub extension, does not support. With more context we might be able to help, but it's probably best that you contact the support team for Visual Studio at: https://visualstudio.microsoft.com/vs/support/
