### ISSUE TITLE
Cloning doesn't change repository context when solution already open

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#2002]
## Version

- GitHub Extension for Visual Studio version: v2.5.8
- Visual Studio version: 2017

## What happened

**Steps to Reproduce**

1. Open a solution
2. Open `Clone` dialog
3. Clone a repository
4. Team Explorer opens but repository doesn't change

**Expected behavior:**

Team Explorer and repository changes when clone completes.

**Actual behavior:**

Repository only changes (consistently?) if there is no solution (or folder) already open.

**Comment by meaghanlewis** [comment]
👋 @jcansdale it looks like this is the same as #2003. Closing this out.
