### ISSUE TITLE
Repository context doesn't change after clone if solution already olpen

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#2003]
## Version

- GitHub Extension for Visual Studio version: v2.5.8
- Visual Studio version: 2017

## What happened

**Steps to Reproduce**

1. Open a solution
2. Open `Clone` dialog
3. Clone a repository
4. Team Explorer pane becomes visible and clone progress is shown
5. Repository doesn't change when clone completes

**Expected behavior:**

Repository should change when clone completes.

If the current solution has unsaved changed, a dialog should appear with the option to save changes or ignore (the same as when user opens a new solution).

**Actual behavior:**

Repository only changes (consistently?) when there is no solution / folder already open. This works fine on Visual Studio 2015.

**Comment by grokys** [comment]
What should happen if a solution is open with unsaved changes?
