### ISSUE TITLE
Make sure extension works in Visual Studio 2019

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#2010]
## Version

- GitHub Extension for Visual Studio version: 2.5.5.4354 / 2.5.8.5165
- Visual Studio version: 2019 (preview)

## What happened

**Steps to Reproduce**

1. Attempt to open `GitHub` pane
2. Package did not load correctly dialog:
![image](https://user-images.githubusercontent.com/11719160/47420476-70009800-d776-11e8-8b0e-21acf63ff2d0.png)
3. MEF err log from `<USER>\AppData\Local\Microsoft\VisualStudio\16.0_824e3d46\ComponentModelCache`
[Microsoft.VisualStudio.Default.err.txt](https://github.com/github/VisualStudio/files/2509826/Microsoft.VisualStudio.Default.err.txt)

**Expected behavior:**

I hoped it would work. 😭 

**Actual behavior:**

💥 

Updating to latest version then fails.

![image](https://user-images.githubusercontent.com/11719160/47420950-7c392500-d777-11e8-918f-6daf2defe3a2.png)

[VSIXInstaller_355cc1bc-f779-41f7-89b0-61f856d42dc2.log](https://github.com/github/VisualStudio/files/2509855/VSIXInstaller_355cc1bc-f779-41f7-89b0-61f856d42dc2.log)

Installer got itself into an unhappy state. The extension is no longer showing up on the extension manager. Still can't install after a reboot:

[VSIXInstaller_355cc1bc-f779-41f7-89b0-61f856d42dc2.log](https://github.com/github/VisualStudio/files/2509960/VSIXInstaller_355cc1bc-f779-41f7-89b0-61f856d42dc2.log)

Removed the folder from `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\GitHub`. Install now completes:

![image](https://user-images.githubusercontent.com/11719160/47423047-03889780-d77c-11e8-903f-d2344362eefd.png)

Still getting the MEF errors with GitHub for Visual Studio `v2.5.8.5165`. 😢

**Comment by meaghanlewis** [comment]
I also confirmed that the extension does not work in VS 2019 at all.

It seems all entry points are broken or non-existent:
- View > Other Windows > GitHub
- Start Page > GitHub
- Manage Connections > Connect to GitHub
- No GitHub section for repositories in Team Explorer - Connect
- No GitHub selection in context menu when viewing files

**Comment by jcansdale** [comment]
@meaghanlewis could you try updating the extension as well (via `Tools > Extensions and Updates... > Updates`)? If the auto-update works the extension can be fixed, but if not we're out of luck. 😟

**Comment by meaghanlewis** [comment]
The installer failed initially when I tried to revert the extension, but then that was successful and updating to the latest version went smoothly.
