### ISSUE TITLE
Update icon is broked

### ISSUE THREAD

**Issue by macOneOone** [github/VisualStudio#2012]
## Version

- GitHub Extension for Visual Studio version:
- Visual Studio version: 1.28.2

## What happened

**Steps to Reproduce**

1. Open a visual Studio Code
2. Search for update Vscode button
3. Wait to change the icon and you will see the image below

<img width="408" alt="captura de ecra 2018-10-13 as 13 54 24" src="https://user-images.githubusercontent.com/16170629/47494608-fdf98300-d849-11e8-9694-d5f1c10964a5.png">

**Comment by meaghanlewis** [comment]
👋 this is the repository for the GitHub extension for Visual Studio. You can open up an issue here instead: https://github.com/Microsoft/vscode instead.

**Comment by macOneOone** [comment]
Sorry
