### ISSUE TITLE
Clone/create message is showing before cloning/creating actually runs

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#203]
From https://github.com/github/VisualStudio/issues/157#issuecomment-161386161

When showing the cloning/create dialog, if the authentication dialog runs first and the user logs in, the code watching for new repositories registered in VS will kick in because the list of repositories is populated on login, and it assumes that cloning/creating is done so the cloning/creating message is shown before the user has actually cloned or created anything.

![](https://cloud.githubusercontent.com/assets/10725993/11539633/fd02f922-98dc-11e5-9f1f-ef8ff805d0ad.png)

**Comment by amytruong** [comment]
If the user has 2fa set, the fix is fine. If you use a user without one 2fa set up, the message still displays.
![screen shot 2016-01-20 at 2 23 51 pm](https://cloud.githubusercontent.com/assets/10725993/12463565/7661c3f0-bf81-11e5-959a-31f778aaefcf.png)

**Comment by shana** [comment]
orly! Interesting...
