### ISSUE TITLE
Unable to fork repositories

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#2036]
## Version

- GitHub Extension for Visual Studio version: 2.5.9
- Visual Studio version: all

## What happened

**Steps to Reproduce**

1. Connect to a repo
2. Select `Fork`
3. Select organization to fork to

**Expected behavior:** 
After selecting which organization to fork to, the dialog should advance to the next screen where the fork can be complete

**Actual behavior:**
Dialog doesn't advance past selecting an organization

**Screenshot or GIF:**
![screen shot 2018-11-05 at 2 19 24 pm](https://user-images.githubusercontent.com/10103121/48030604-78f25180-e106-11e8-8778-7f7c637139bf.png)

**Comment by jcansdale** [comment]
I can confirm this. I wonder if it was since updating to a newer version of ReactiveUI? I'm missing this feature. 😢
