### ISSUE TITLE
"Commit Changes" -green button not working on my side

### ISSUE THREAD

**Issue by akehsanz** [github/VisualStudio#2043]
HELLO EVERYONE...
A SERIOUS issue now facing...
@nov 18.
I can't make any "commit changes" in master branch
for my project forks..
wht seems to be the issue ??
anyone pls HELP !!

**Comment by grokys** [comment]
Hi @akehsanz ,

This is the repository for the GitHub Extension for Visual Studio - it's unclear if you're experiencing a problem with our extension or something else. Could you maybe post a screenshot of what you're seeing?

**Comment by meaghanlewis** [comment]
Going to close this out for now. @akehsanz if you have more details please comment in the issue and reopen.

**Comment by Abhijit-singh04** [comment]
same issue
