### ISSUE TITLE
Nothing happens when I click `Create pull request` on public repository

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#2058]
## Version

- GitHub Extension for Visual Studio version: `v2.5.9.5485`
- Visual Studio version: All

## What happened

**Steps to Reproduce**

1. Clone a public repository (_update:_ that isn't one of yours or your organization's)
2. Create a branch and make some commits
3. Click `Create` button on `GitHub` pane
4. Enter pull request title/description and click `Create pull request`

**Expected behavior:**

- Minimum: Show an error
- Better: Let user know how to fork and create a pull request
- Best: Automatically fork and create a pull request

**Actual behavior:**

Nothing happens when `Create pull request` is clicked.

**Screenshot or GIF:**

![image](https://user-images.githubusercontent.com/11719160/48615631-57f0f280-e989-11e8-8742-6562a84fdf71.png)

### Related

- Partial fix - #2173: Fix displaying errors in GitHub pane.

**Comment by PriyadharsiniJ** [comment]
Facing the same issue, any update or resolution available?
