### ISSUE TITLE
Visual Studio freezes when "GitHub" connect button is pressed

### ISSUE THREAD

**Issue by chongchin** [github/VisualStudio#2065]
Hi ,
 
1) Versions:
     Visual Studio 2015 Professional, 14.0.25431.01 Update 3
     GiHub Extension for Visual Studio 2.5.9.5485
     GitHub Enterprise on premise 2.13
2)  In Team Explorer, under Github, when I press "Connect", the screen freezes and I have to restart Visual Studio 2015 Professional. The result is I do not see the GitHub connect form, that allows me to choose url of GitHub Enterprise on premse, and hence display all the repositories that I can access. This error repeats each time, and in multiple VMs.
3) Please see the attached a) word document with the screen shots b) %LocalAppData%\GitHubVisualStudio\extension.log. 

[GitHub Extension for Visual Studio Error.docx](https://github.com/github/VisualStudio/files/2595262/GitHub.Extension.for.Visual.Studio.Error.docx)

[extension.log](https://github.com/github/VisualStudio/files/2595263/extension.log)

Thank you
Chong Chin

**Comment by jcansdale** [comment]
@chongchin, I'm working a fix for this issue here #2066. I've added a build to the PR description. Could you confirm whether or not this fixes it?

**Comment by chongchin** [comment]
Hi Jamie,
    I installed your fix https://ci.appveyor.com/api/buildjobs/blbeldj1d4lkkofe/artifacts/2.6.0.5790%2FGitHub.VisualStudio.vsix

1) 1st attempt. The GitHub Login page appeared, After I key in my GITHUB enterprise url, it accepted, but did not the list of repositories that I have access to 
2) 2nd attempt. The GitHub Login page appeared. When I press the option "GitHub Enterprise", there was no response.
 
In both cases, VS 2015 did not freeze
 
  Chong Chin

**Comment by jcansdale** [comment]
@chongchin,

Unfortunately there was a problem with the previous attempted fix. Is issue is that the extension can't find version of `System.ValueTuple.dll` used by `ReactiveUI`.

Could you let me know if you have any more luck with this version:
https://ci.appveyor.com/api/buildjobs/7n5w8p5bksgd8cst/artifacts/2.6.0.5799%2FGitHub.VisualStudio.vsix

Thanks!

**Comment by chongchin** [comment]
Hi Jamie,
    
I installed, 
https://ci.appveyor.com/api/buildjobs/7n5w8p5bksgd8cst/artifacts/2.6.0.5799%2FGitHub.VisualStudio.vsix
When I press "Connect to GitHub", the form appeared. But clicking on the tab "GitHub Enterprise" (to choose the url to our GitHub Enterprise on premise), did not work - there was no response at all.

![image](https://user-images.githubusercontent.com/18568097/48774637-c45f4f00-ed05-11e8-9481-face965ffd78.png)

Regards
Chong Chin

**Comment by grokys** [comment]
Hi @chongchin,

Could you try the fix described here: https://github.com/github/VisualStudio/issues/1094#issuecomment-334406719

- Open Credential Manager from the Windows Start Menu
- Click on Windows Credentials
- Select the credentials related to your Enterprise server
- Click on Remove

If that doesn't work, could you try deleting the `ghfvs.connections` file from `C:\Users\grokys\AppData\Local\GìtHubVisualStudio` while VS is closed?

**Comment by chongchin** [comment]
Hi Steven,

 

Please let me know if you are referring to one in brown rectangle, which is the VM that Visual Studio 2015 is installed or are you referring to the one of those in the blue rectangle, where GitHub Enterprise on premise is installed. If it is the 2nd one, which one of the 4 should I remove.

                

                Thank you.

 

                

 

Best Regards,

Chong Chin

Senior Technical Consultant

Inecom Business Solutions - Singapore

mailto:  <mailto:chin.chong@inecomworld.com> chin.chong@inecomworld.com

 

Inecom Pte Ltd – Registration No: 200402768K – 12 Tannery Road, 02-02 HB Centre 1, Singapore 347722              

Tel: +65 6225 9255 Fax: +65 6743 9255 www.inecomworld.com <http://www.inecomworld.com/> 

 

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by meaghanlewis** [comment]
Fixed by #2068
