### ISSUE TITLE
Resource is not accessible by integration

### ISSUE THREAD

**Issue by MrVitaly** [github/VisualStudio#2069]
## Versions
 - GitHub Extension for Visual Studio version: 2.5.9.5485 and the experimental extension from the sources
 - Visual Studio version: 2017 (15.9.1)

## What happened
The following message is displayed on GitHub panel after re-installation: **`Resource is not accessible by integration`**

### Steps to Reproduce
1. Uninstall the extension (I did this because the experimental extension threw exception during launching. _Original installation of the extension worked well_);
2. Start Experimental Instance of Visual Studio with the project (sources: master, latest commit: 9175b2f) without changes (except adding values [clientId](https://github.com/github/VisualStudio/blob/9175b2f293bbbc362f774112a7e95eb141573fd4/src/GitHub.Api/ApiClientConfiguration_User.cs#L7) and [clientSecret](https://github.com/github/VisualStudio/blob/9175b2f293bbbc362f774112a7e95eb141573fd4/src/GitHub.Api/ApiClientConfiguration_User.cs#L8) in [ApiClientConfiguration_User.cs](https://github.com/github/VisualStudio/blob/master/src/GitHub.Api/ApiClientConfiguration_User.cs));
3. See message **`We couldn't find a git repository here. Open a git project or click "File -> Add to Source Control" in a project to get started.`** on GitHub panel;
4. Go to `Team Explorer` and open a solution;
5. _The issue happened_: **`Resource is not accessible by integration`** message is on GitHub panel;
6. Install the extension back;
7. Open Visual Studio;
8. See message **`We couldn't find a git repository here. Open a git project or click "File -> Add to Source Control" in a project to get started.`** on GitHub panel;
9. Go to `Team Explorer` and open a solution;
10. _The problem hasn't disappeared_: **`Resource is not accessible by integration`** message on GitHub panel.

### Expected behavior
 - See all of the Pull Requests for opened project in the GitHub panel

### Screenshots
 - GitHub Panel
![githubpanel](https://user-images.githubusercontent.com/7189888/48735629-f1562800-ec59-11e8-8af4-f78efa9c7b8a.png)

### Logs
 - [extension.log](https://github.com/github/VisualStudio/files/2597036/extension.log)

### Additional context
 - Re-installation didn't help
 - Installed extension
![githubextention](https://user-images.githubusercontent.com/7189888/48735782-5742af80-ec5a-11e8-84f4-f5d2a766ff6e.png)
 - Visual Studio components
![vsinstaller](https://user-images.githubusercontent.com/7189888/48735962-e64fc780-ec5a-11e8-8ce9-5b7c46d5dbaa.png)

**Comment by meaghanlewis** [comment]
👋 @MrVitaly thanks for submitting such a detailed bug report. We should definitely keep an eye on this issue and understand what's be causing it. I'm glad you were able to find a workaround.

**Comment by romil07** [comment]
@MrVitaly Did you get a resolution on this issue? I don't see any activity on this for sometime now.

**Comment by MrVitaly** [comment]
@romil07, I have reinstalled my Visual Studio. The issue didn't recur.
