### ISSUE TITLE
can not install Microsoft.VisualStudio.Community.Msi,version=15.9.28307.53

### ISSUE THREAD

**Issue by Messilimeng** [github/VisualStudio#2075]
安装出现问题。

可通过以下方式排查包故障问题:

    1. 使用以下搜索 URL 来搜索针对每个包故障的解决方案
    2. 针对受与影响的工作负荷或组件修改选项，然后重新尝试安装
    3. 从计算机上删除产品，然后再次安装

如果 Developer Community 上已报告了此问题，则可在此处找到解决方案或变通方法。如果未报告此问题，我们鼓励你创建新问题，以便其他开发者可以找到解决方案或变通方法。可使用“提供反馈”按钮从右上角的 Visual Studio 安装程序中创建新问题。

================================================================================

未能安装包“Microsoft.VisualStudio.Community.Msi,version=15.9.28307.53”。
    搜索 URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.VisualStudio.Community.Msi;PackageAction=Install;ReturnCode=1402
    详细信息
        MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.VisualStudio.Community.Msi,version=15.9.28307.53\Microsoft.VisualStudio.Community.Msi.msi，属性:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  MSIFASTINSTALL="7"  VSEXTUI="1"  PIDKEY="NGKBDRWKQFTT82MTRMPKRM6XM"  VS7.3643236F_FC70_11D3_A536_0090278A1BB8="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"  FEEDBACKOPTIN="1" 
        返回代码: 1603
        返回代码详细信息: 安装时发生严重错误
        消息 ID: 1402
        消息详细信息: Could not open key: UNKNOWN\Components\C9F56276DB255D115AE4000972A8B18B\242D06C4930BBBD42A20EB5574E85800.   Verify that you have sufficient access to that key, or contact your support personnel.
    日志
        C:\Users\pcdalao\AppData\Local\Temp\dd_setup_20181121091403_072_Microsoft.VisualStudio.Community.Msi.log
    工作负荷受到影响
        .NET Core 跨平台开发 (Microsoft.VisualStudio.Workload.NetCoreTools,version=15.8.27906.1)
        ASP.NET 和 Web 开发 (Microsoft.VisualStudio.Workload.NetWeb,version=15.8.27906.1)
        Node.js 开发 (Microsoft.VisualStudio.Workload.Node,version=15.9.28107.0)
    组件受到影响
        .NET Core 2.1 开发工具 (Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1,version=15.8.27924.0)
        .NET Core 2.1 开发工具 (Microsoft.NetCore.ComponentGroup.Web.2.1,version=15.8.27924.0)
        .NET Framework 4.6.1 开发工具 (Microsoft.Net.ComponentGroup.DevelopmentPrerequisites,version=15.8.27825.0)
        .NET 可移植库目标包 (Microsoft.VisualStudio.Component.PortableLibrary,version=15.6.27309.0)
        ASP.NET 和 Web 开发工具 (Microsoft.VisualStudio.Component.Web,version=15.8.27825.0)
        ASP.NET 和 Web 开发工具先决条件 (Microsoft.VisualStudio.ComponentGroup.Web,version=15.9.28219.51)
        C# 和 Visual Basic (Microsoft.VisualStudio.Component.Roslyn.LanguageServices,version=15.8.27729.1)
        ClickOnce 发布 (Microsoft.Component.ClickOnce,version=15.8.27825.0)
        Cloud Explorer (Microsoft.VisualStudio.Component.CloudExplorer,version=15.9.28230.55)
        Developer Analytics Tools (Microsoft.VisualStudio.Component.AppInsights.Tools,version=15.8.27825.0)
        Entity Framework 6 工具 (Microsoft.VisualStudio.Component.EntityFramework,version=15.6.27406.0)
        F# 语言支持 (Microsoft.VisualStudio.Component.FSharp,version=15.8.27825.0)
        IIS Express  (Microsoft.VisualStudio.Component.IISExpress,version=15.0.26208.0)
        IntelliTrace (Microsoft.VisualStudio.Component.IntelliTrace.FrontEnd,version=15.8.27729.1)
        JavaScript 和 TypeScript 语言支持 (Microsoft.VisualStudio.Component.JavaScript.TypeScript,version=15.9.28125.51)
        JavaScript 诊断 (Microsoft.VisualStudio.Component.JavaScript.Diagnostics,version=15.8.27729.1)
        Live Unit Testing (Microsoft.VisualStudio.Component.LiveUnitTesting,version=15.0.26720.2)
        Microsoft Azure WebJobs 工具 (Component.Microsoft.VisualStudio.Web.AzureFunctions,version=15.7.27617.1)
        Microsoft Azure WebJobs 工具 (Microsoft.VisualStudio.ComponentGroup.AzureFunctions,version=15.7.27617.1)
        Node.js 开发支持 (Microsoft.VisualStudio.Component.Node.Tools,version=15.8.27825.0)
        NuGet 包管理器 (Microsoft.VisualStudio.Component.NuGet,version=15.9.28016.0)
        Razor 语言服务 (Component.Microsoft.VisualStudio.RazorExtension,version=15.0.26720.2)
        Snapshot Debugger (Microsoft.VisualStudio.Component.Debugger.Snapshot,version=15.8.28010.0)
        SQL Server Data Tools (Microsoft.VisualStudio.Component.SQL.SSDT,version=15.9.28107.0)
        SQL Server 支持的数据源 (Microsoft.VisualStudio.Component.SQL.DataSources,version=15.0.26621.2)
        Windows Communication Foundation (Microsoft.VisualStudio.Component.Wcf.Tooling,version=15.8.27924.0)
        测试工具核心功能 (Microsoft.VisualStudio.Component.TestTools.Core,version=15.7.27520.0)
        连接和发布工具 (Microsoft.VisualStudio.Component.Common.Azure.Tools,version=15.9.28107.0)
        适用于 Web 开发的云工具 (Microsoft.VisualStudio.ComponentGroup.Web.CloudTools,version=15.8.27729.1)
        数据源和服务引用 (Microsoft.VisualStudio.Component.VisualStudioData,version=15.6.27406.0)
        托管桌面工作负载核心 (Microsoft.VisualStudio.Component.ManagedDesktop.Core,version=15.8.27729.1)
        针对 Web 项目的 F# 语言支持 (Microsoft.VisualStudio.Component.FSharp.WebTemplates,version=15.8.27705.0)

**Comment by meaghanlewis** [comment]
👋 @Messilimeng if you are having problems installing Visual Studio itself, then you'll want to reach out to their support for help on this as we offer support for the GitHub for Visual Studio extension only.

You can reach out to them here: https://visualstudio.microsoft.com/vs/support/#talktous
