### ISSUE TITLE
Intellicode is crashing visual studio 2019 and 2017

### ISSUE THREAD

**Issue by rlamba89** [github/VisualStudio#2109]
## Versions
Tried in both the versions
Visual studio 2017
Visual studio 2019

## What happened
After installing the intellicode in VS2017 and VS2019, visual studio crashes when it tries to bring intelli-sense dropdown.

**Comment by meaghanlewis** [comment]
👋 @rlamba89 this repository is specifically for the GitHub extension for Visual Studio. To get support about this Intellicode issue I recommend you contact [Visual Studio Support](https://visualstudio.microsoft.com/support/).
