### ISSUE TITLE
GitHub Extension Merge Error

### ISSUE THREAD

**Issue by berdank** [github/VisualStudio#211]
Hi guys,

I do not know it is right place to say this problem. 
I want to merge two branch. When I try to resolve conflict I get this [error.](http://imgur.com/hpP6Ly3) 

I try to look ActivityLog.xml and I see a error about argument null exception. I write some part of log file. Maybe it helps.

*Window 8.1 - Visual Studio 2015 Community - Last version of GitHub Extension

<entry>
    <record>827</record>
    <time>2016/01/26 21:02:13.679</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
    <guid>{4CA58AB2-18FA-4F8D-95D4-32DDF27D184C}</guid>
  </entry>
  <entry>
    <record>828</record>
    <time>2016/01/26 21:02:13.679</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Unexpected system error mode before loading package [Microsoft.VisualStudio.TeamFoundation.VersionControl.HatPackage]</description>
    <guid>{4CA58AB2-18FA-4F8D-95D4-32DDF27D184C}</guid>
  </entry>
  <entry>
    <record>829</record>
    <time>2016/01/26 21:02:13.679</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Microsoft.VisualStudio.TeamFoundation.VersionControl.HatPackage]</description>
    <guid>{4CA58AB2-18FA-4F8D-95D4-32DDF27D184C}</guid>
  </entry>
  <entry>
    <record>830</record>
    <time>2016/01/26 21:02:13.726</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Microsoft.VisualStudio.TeamFoundation.VersionControl.HatPackage]</description>
    <guid>{4CA58AB2-18FA-4F8D-95D4-32DDF27D184C}</guid>
  </entry>
  <entry>
    <record>831</record>
    <time>2016/01/26 21:02:14.054</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
    <guid>{CF49EC7D-92B1-4BBD-9254-9CC13978E82E}</guid>
  </entry>
  <entry>
    <record>832</record>
    <time>2016/01/26 21:02:14.054</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Unexpected system error mode before loading package [HtmlPackage]</description>
    <guid>{CF49EC7D-92B1-4BBD-9254-9CC13978E82E}</guid>
  </entry>
  <entry>
    <record>833</record>
    <time>2016/01/26 21:02:14.054</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [HtmlPackage]</description>
    <guid>{CF49EC7D-92B1-4BBD-9254-9CC13978E82E}</guid>
  </entry>
  <entry>
    <record>834</record>
    <time>2016/01/26 21:02:14.101</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [HtmlPackage]</description>
    <guid>{CF49EC7D-92B1-4BBD-9254-9CC13978E82E}</guid>
  </entry>
  <entry>
    <record>835</record>
    <time>2016/01/26 21:02:14.585</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: key&#x000D;&#x000A;   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Package.Extensions.ExtensionsManager.OnTextViewCreated(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.Web.Editor.Controller.TextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Package.Commands.Html.VsHtmlTextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.Web.Editor.Controller.TextViewConnectionListener.&lt;&gt;c__DisplayClass24_0.&lt;OnTextViewConnected&gt;b__0(Object sender, EventArgs eventArgs)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)</description>
  </entry>
  <entry>
    <record>836</record>
    <time>2016/01/26 21:02:14.882</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function VBDispatch::GetTypeLib</description>
  </entry>
  <entry>
    <record>837</record>
    <time>2016/01/26 21:02:14.882</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Leaving function VBDispatch::GetTypeLib</description>
    <guid>{80CC9F66-E7D8-4DDD-85B6-D9E6CD0E93E2}</guid>
  </entry>
  <entry>
    <record>838</record>
    <time>2016/01/26 21:02:14.882</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function VBDispatch::GetTypeLib</description>
  </entry>
  <entry>
    <record>839</record>
    <time>2016/01/26 21:02:14.882</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Leaving function VBDispatch::GetTypeLib</description>
    <guid>{80CC9F66-E7D8-4DDD-85B6-D9E6CD0E93E2}</guid>
  </entry>

**Comment by Haacked** [comment]
Hmm, the GitHub Extension doesn't handle merges. This looks like a problem in the Git extension. /cc @acangialosi

**Comment by berdank** [comment]
Hi @shana 

This problem is continues. I have been waiting for help but you closed this issue.

**Comment by shana** [comment]
Hi @berdank 

Sorry, I don't mean to minimize how this issue is affecting you, or to imply that it doesn't exist, I know how frustrating it is to fight the software when it doesn't work right. However, the error is happening in an area that is not handled by the GitHub Extension for Visual Studio.

The error seems to be originating from the extension that deals with html syntax highlighting, from what I can tell from the screenshot and the log, which is something that's built in to VS. We really can't do anything about it. You can submit a bug report to Microsoft about this via the feedback reporting tool in Visual Studio.

**Comment by berdank** [comment]
Hi @shana 

Thank you for your explanation. When I open the issue, I sad that "I do not know it is right place...".

I try to send feedback about the issue.
