### ISSUE TITLE
Null reference exception after opening any pull request

### ISSUE THREAD

**Issue by MilosAuder** [github/VisualStudio#2117]
## Versions
 - GitHub Extension for Visual Studio version: 2.6.0.6187
 - Visual Studio version: VS Professional 2017, Version 15.9.3

## What happened
When I try to open any PR I get null reference exception. This started happening only after update to new GitHub extension version. This happens also to my colleagues that updated to new version, we all work on the same repository. After reverting to older version 2.5.2.2500 it works again.

### Steps to Reproduce
1. Go to GitHub tab
2. Double-click on any pull request
3. See error

### Expected behavior
Pull request is open.

### Screenshots
![github_nullreference](https://user-images.githubusercontent.com/45784262/49788058-9e3b3680-fd28-11e8-9fa4-4a5d1436aea4.PNG)

### Logs
[GIST](https://gist.github.com/MilosAuder/386c1e97707f5578daecf27141e0b24a)

Stack trace leading to exception is clearly visible in attached _extension.log_

**Comment by grokys** [comment]
Hi @MilosAuder, thanks for getting in touch. Is this happening on GitHub.com or an enterprise instance?

**Comment by grokys** [comment]
Thanks for the info. I've been able to reproduce this here. Looks like the following GraphQL query:

```
query ($owner: String!, $name: String!, $number: Int!) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
      commits(last: 1) {
        nodes {
          statuses: commit {
            status {
              contexts {
                state
                context
                targetUrl
                description
              }
            }
          }
        }
      }
    }
  }
}
```

When run on enterprise returns:

```json
{
  "data": {
    "repository": {
      "pullRequest": {
        "commits": {
          "nodes": [
            {
              "statuses": {
                "status": null
              }
            }
          ]
        }
      }
    }
  }
}
```

i.e. the `status` is null, and we're not handling this.

@StanleyGoldman ☝️

**Comment by grokys** [comment]
Hi @MilosAuder - we've just pushed a new release that should fix this!

**Comment by MilosAuder** [comment]
> 
> 
> Hi @MilosAuder - we've just pushed a new release that should fix this!

It works! Thanks again for quick fix.
