### ISSUE TITLE
VS2015.1 crashes when file is edited

### ISSUE THREAD

**Issue by natelowry** [github/VisualStudio#212]
I've narrowed down the cause of my crash to this extension (which is :frowning: because I love it so much), so I want to help figure out what's going on.

It seems to usually happen 2-3 times at the start of my day, then rarely after that.  

It generally lets me open the solution and even select a file, but as soon as I add a line to that file, it will crash.  It usually has a lot of "The Visual Studio component cache is out of date. Please restart Visual Studio." messages before it crashes too.

Microsoft Visual Studio Enterprise 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Using latest version of the extension: 1.0.16.3

Let me know what other debug info I can pull that might be useful.

**Comment by natelowry** [comment]
I think I misidentified the bad add-on.  I just had it crash again with this disabled.  Sorry about that!

**Comment by shana** [comment]
@natelowry 

If VS is still crashing for you, you can try opening a VS developer prompt and running `devenv /updateConfiguration` and then run VS in the usual way. If that still doesn't stop the crash (and/or it still complains about stale cache), you can try `devenv /setup` and then runing VS. This one will take a bit longer to run, that's normal. Both of these commands will just run silently and return to the command line (they won't launch VS).
