### ISSUE TITLE
Add a "Repository Reference" feature to manage multiple repositories in one solution

### ISSUE THREAD

**Issue by fishingry** [github/VisualStudio#2125]
**Is your feature request related to a problem? Please describe.**
As a very old c# developer,  in past 2 years I worked for 3 totally different projects that are using git as source control, but all of them have same problems: **libraries are split to their own repositories**, but there is a debug solution to reference all projects from other repositories, the purpose is to let developers debug full solution. I tried to use sub-tree or sub-module or folder-restriction to build the debug environment, but no matter how, all of them have different issues, as parts or all of followings:
1. detecting changes cross all repositories,  we have to open repositories all to see if it has changes
2. switch between branches, it's painful especially when numbers of repositories are more then 20, 
3. committing code, it's very unhappy to find changes one by one by opening all repositories
4. pull requests, it's unhappy to create pull requests one by one
5. track commit between repositories: we could have a breaking change effecting on 10+ repositories, but they got no linked together, and don't why it's changed if we don't track changes manually.

**Describe the solution you'd like**
I think a lot on handling this, it could be resolved by multiple products, but the most important work should be done from Visual Studio side.
I could provide 2 options:
1. We could use a new concept: "repository reference", which is similar like nodejs packages, because when we use a nodejs package, we could also get its source code to folder, we could do totally same design for .NET projects: **we should be able to reference a project from source control, not only from a nuget package.**, and the advantage of "repository reference" is : we could do changes in those references and commit back to its defined source code location, more over, all commits could be done once and linked together cross repositories for tracking purpose.

2. We could use a new concept: "workspace", which is used to config how many repositories should be working together with current repository, which is a temporary solution. if we have a workspace, all those repository could be managed by 1 repository, including creating branches, merge code, commit and so on.
- it could be a json or xml file 
- it could be setup within .sln file with project reference, like: **when we reference a project, we reference it from a remote repository but not a local folder**, just like what nodejs packages are doing

after this, we get many benefits:

1. When we clone a repository, all related repositories should be cloned to root path at same time.
2. For those related repositories, the workspace could setup which branch is used for current repository and branch
3. Visual studio could show all changes in all related repositories, but not like now, we have to go to each repository to see changes
4. When we commit code, we commit them all with a summary notes and separated notes
5. Git server should be able to link all commits together, so we could know/track how many changes are related together.

**Describe alternatives you've considered**
as alternatives,
1. we could have a project.json file to setup how many projects and which branch will be loaded to solution
2. when we change the solution config file, repositories and branches could be switched as well

**Additional context**
I cannot provide any screenshot for my complex projects, but I believe similar structures are existing in many teams, especially for those that are products, but not just a project.

but the following solution could be used for "RepositoryReference"

for example, MainReposotory:
json format:
```
{
    "RepositoryReferences": {
        "RootPath": "../",
        "BranchPattern": "",
        "References": [{
            "Repository": "ProjectA",
            "Branch": "release/1.2/master",
            "Projects": [{
                "Name": "ProjectA",
                "Path": "src/ProjectA/ProjectA.proj"
            },{
                "Name": "ProjectB",
                "Path": "src/ProjectB/ProjectB.proj"
            }]

        }, {
            "Repository": "ProjectC",
            "Branch": "release/1.2/master",
            "Projects": [{
                "Name": "ProjectC",
                "Path": "src/ProjectC/ProjectC.proj"
            }]
        }]
    }
}
or
{
    "RepositoryReferences": {
        "RootPath": "../",
        "BranchPattern": "release/1.2/master",
        "References": [{
            "Repository": "ProjectA",
            "Projects": [{
                "Name": "ProjectA",
                "Path": "src/ProjectA/ProjectA.proj"
            },{
                "Name": "ProjectB",
                "Path": "src/ProjectB/ProjectB.proj"
            }]

        }, {
            "Repository": "ProjectC",
            "Projects": [{
                "Name": "ProjectC",
                "Path": "src/ProjectC/ProjectC.proj"
            }]
        }]
    }
}
```

As default all repositories are in same source control, but we could also extend if easy.

**Comment by meaghanlewis** [comment]
Hi @fishingry thanks for your detailed suggestion for this feature! This is the repository specifically for the GitHub extension for Visual Studio and this feature is something that would have to be implemented in Visual Studio itself. 

You can go here: https://developercommunity.visualstudio.com/spaces/8/index.html to suggest a feature in Visual Studio.
