### ISSUE TITLE
Don't leave behind empty directory when a clone fails

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#2126]
## Versions
 - GitHub Extension for Visual Studio version: 2.6.0
 - Visual Studio version: 2015 (probably all)

## What happened
1. Attempted to clone `grokys/PullRequestSandbox3` (which doesn't exist)
2. Attempted to clone `grokys/PullRequestSandbox` to the `grokys\PullRequestSandbox3` folder
3. Was block because there's an empty directory in the target destination

### Expected behavior
- User should be able to clone into empty directory
- When a clone fails, the empty directory created for the clone should be deleted.

### Screenshots
![image](https://user-images.githubusercontent.com/11719160/49868923-b1243880-fe06-11e8-931e-dd0479242abc.png)

_Note: The logic that the new Visual Studio 2019 `Get to Code` feature uses is that a directory must be empty or not exist on order to clone. I think we should be consistent with this and allow cloning to empty directories._

![image](https://user-images.githubusercontent.com/11719160/49877314-0e2ae900-fe1d-11e8-820b-e1f8f0c13a2f.png)

**Comment by jcansdale** [comment]
> Note: The logic that the new Visual Studio 2019 `Get to Code` feature uses is that a directory must be empty or not exist on order to clone. I think we should be consistent with this and allow cloning to empty directories.

Yes, I definitely agree.

**Comment by jcansdale** [comment]
@YuPeiHenry,

>  Note: The logic that the new Visual Studio 2019 `Get to Code` feature uses is that a directory must be empty or not exist on order to clone. I think we should be consistent with this and allow cloning to empty directories.

Could you open a new issue with this so we don't forget it when your pull request is merged? 🙂

**Comment by YuPeiHenry** [comment]
@jcansdale I have opened a new issue #2250 to address cloning into empty directories.
