### ISSUE TITLE
Draging Visual Code is not working 

### ISSUE THREAD

**Issue by rajat29gupta** [github/VisualStudio#2141]
## Versions
 - Visual Studio version: ... 1.30

### Steps to Reproduce
1. Go to 'Visual code'
2. Click on 'Minimise the tab to make it dragable'
3. Scrolling from the box show in the image is not working 

### Screenshots

![restfulapitutorial-password-reset - visual studio code 2018-12-18 13 43 55](https://user-images.githubusercontent.com/34648003/50140579-38702100-02cb-11e9-8e4e-6d0d753b63fa.png)

![usercontroller js - restfulapitutorial-password-reset - visual studio code 2018-12-18 13 35 39](https://user-images.githubusercontent.com/34648003/50140324-5ab56f00-02ca-11e9-8ca8-cbe7d13564dc.png)

**Comment by meaghanlewis** [comment]
👋  @rajat29gupta you should open an issue in https://github.com/Microsoft/vscode to report this. The repository is for the GitHub extension for Visual Studio.
