### ISSUE TITLE
VS2017 run wrong project in debugging after update to 15.9.4

### ISSUE THREAD

**Issue by died** [github/VisualStudio#2151]
## VS2017 15.9.4
Win10 Pro 1809

## What happened
I have a solution with 2 web project, after VS2017 update to 15.9.4, F5 debug only send 2nd project to IIS Express, even set 1st project as startup project. 

### Steps to Reproduce
1. Have a solution with 2 ASP.NET MVC project
2. Update to 15.9.4
3. Set first project as startup project.
4. F5
5. It open //localhost:port/ with "localhost refused to connect"

### Expected behavior
It should open the project that I selected.

### Screenshots
Set first project(GoDigital) as startup project, F5 to debug
![img1](https://i.imgur.com/F1J3XZe.png)

VS still send 2nd project(Connectivity) to IIS Express 
![img2](https://i.imgur.com/ADACz2q.png)

.vs/config/applicationhost.config
![img3](https://i.imgur.com/uvCk0EE.png)

### QuickFix
Downgrade ( mean uninstall and install an eariler version ) to 15.8.9, then it work.
[Installing an Earlier Release of Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017)

**Comment by StanleyGoldman** [comment]
Hello @died,

You are having a problem with Visual Studio itself. This repository is for the GitHub plugin for Visual Studio. You should report the problem with Visual Studio. [How to report a problem with Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017)

Happy New Year.
