### ISSUE TITLE
Visual Studio test explorer capturing different screenshots for single test execution and playlist test execution

### ISSUE THREAD

**Issue by ishah09** [github/VisualStudio#2155]
I am facing issue with Visual studio NUnit test execution via VS playlist(Test Explorer). 

I came across to found something mismatch for Screenshot utility, according to research there were already many bugs with Screenshot from VS playlist. As of now, it is capturing screenshot but act differently. 

Issue which I found,

When I execute single test from playlist it is capturing as expected and working fine. 

Here is full screenshot of web page, when it is executed as single test

[![][1]][1]

Here what it has captured, when executed as playlist(Took screenshot as Responsive Page)

[![][2]][2]

**This is the code of screenshot utility:**

        //To take screenshot
        Screenshot file = ((ITakesScreenshot)driver).GetScreenshot();
        //To save screenshot
        file.SaveAsFile(parentDirName + "\\Screenshots\\" + " - " + SSName + ".png", ScreenshotImageFormat.Png);
        //To log screenshot in Report
        testlog.Info("Details of " + SSName, MediaEntityBuilder.CreateScreenCaptureFromPath(parentDirName + "\\Screenshots\\" + " - " + SSName + ".png").Build());

> Visual Studio 2017 <br>
> NUnit 3.6.1 <br>
> Selenium 3.14

Found issue with all screenshots those are executed from VS Playlist test. I do have couple of scripts which I need to execute from VS playlist, And those scripts verified by Reports. Reports acknowledge with screenshots. And so far I meant to refer it. I can't execute single test. 

If there is some resolution, Please help !

  [1]: https://i.stack.imgur.com/Zr5ae.png
  [2]: https://i.stack.imgur.com/rHyom.png

**Comment by meaghanlewis** [comment]
Hi @ishah09 this repository is for the GitHub extension for Visual Studio and we are unable to help with the problem you reported. I believe you'll have to reach out to Visual Studio for support with this here: https://visualstudio.microsoft.com/vs/support/
