### ISSUE TITLE
Github free account now allows unlimited private repositories, buy VS extensions don't

### ISSUE THREAD

**Issue by luisllamasbinaburo** [github/VisualStudio#2164]
Hello. Starting from 2019/01/08, Github free edition allows unlimited private repositories
https://blog.github.com/changelog/2019-01-08-pricing-changes/

Unfortunatelly, the Github Visual Studion Extension is not prepared for this.
It doesn't allow free users to create private repositories, neither to publish to one existing (creating from the web directly)

**Comment by meaghanlewis** [comment]
Thanks @luisllamasbinaburo for reporting this and thanks @grokys for the fix. This will go out in our release next week.
