### ISSUE TITLE
F# Projects AssemblyInfo.fs details not being applied to output dlls 

### ISSUE THREAD

**Issue by kevinneufeld** [github/VisualStudio#2168]
## Effected Versions
 - Visual Studio 2017 `15.9.4` & `15.9.5`

## What happened
For F# projects Visual Studio is no longer adding the specified assembly details from `AssemblyInfo.fs` on the project's output `dlls`; they are stamped with defaults; with the exception of 
`[<assembly: AssemblyCopyright("Copyright ©  2019")>]`

```f#
namespace Test.Server.Util.AssemblyInfo

open System.Reflection
open System.Runtime.CompilerServices //needed despite the compiler's opinion
open System.Runtime.InteropServices

[<assembly: AssemblyTitle("Test.Server.Util")>]
[<assembly: AssemblyDescription("")>]
[<assembly: AssemblyConfiguration("")>]
[<assembly: AssemblyCompany("")>]
[<assembly: AssemblyProduct("Test.Server.Util")>]
[<assembly: AssemblyCopyright("Copyright ©  2019")>]
[<assembly: AssemblyTrademark("")>]
[<assembly: AssemblyCulture("")>]

[<assembly: ComVisible(false)>]
[<assembly: Guid("bf44ed42-2261-4e56-bae6-02e9c57aaa5d")>]

[<assembly: AssemblyVersion("0.2.1.0")>]
[<assembly: AssemblyFileVersion("0.2.1.0")>]
[<assembly: AssemblyInformationalVersion("0.2.1.197+e866c41a")>]

do()
```

No hard errors, build completes without issues; just .dlls file information is not as expected. 

### Steps to Reproduce
New F# project and add an `AssemblyInfo.fs` build and confirm the output. 

### Expected behavior
Output `.dlls` should have file information matching expected values from `AssemblyInfo.fs`

**Comment by grokys** [comment]
Hi @kevinneufeld this repository is for the GitHub extension for Visual Studio and we are unable to help with the problem you reported. I believe you'll have to reach out to Visual Studio for support with this here: https://visualstudio.microsoft.com/vs/support/

**Comment by kevinneufeld** [comment]
Apologies. Thanks.

**Comment by IlyaFinkelshteyn** [comment]
@aarnott can you please help with the right repository to open this issue? We in AppVeyor are risking to break a customer with the next image update if workaround not found.

**Comment by IlyaFinkelshteyn** [comment]
@AArnott apparently @kevinneufeld already got the attention from VS team with this issue. Sorry for randomization/duplication and thanks for the reply :)

**Comment by domenichelfenstein** [comment]
I have the same problem @IlyaFinkelshteyn
 How did you solve it?
