### ISSUE TITLE
Latest Visual Studio Github Extension update crashes Visual Studio

### ISSUE THREAD

**Issue by tsimmons1987** [github/VisualStudio#2195]
## Versions
 - GitHub Extension for Visual Studio version: 2.7.0.6566
 --  Connecting to GitHub Enterprise with Personal Access Token
 - Visual Studio version: 15.9.5

## What happened
I was prompted to upgrade my GitHub Extension from 2.6.0.6193 to 2.7.0.6566.  I did so.   After restarting VS, I double-clicked a repo to open it and after about 10 seconds, Visual Studio hard-crashes with the message "Visual Studio needs to close".   Reverting back to 2.6.0.6193 corrects this problem, but now I cannot open pull requests.  I can see all pull requests but when I double-click the pull request, I get "Object reference not set to an instance of an object." error.   

### Steps to Reproduce
1. After updating GitHub extenstion, Go to 'Team Explorer'
2. Click on either a local or remote Repository
3. Visual Studio crashes with "Needs to close" error message

### Expected behavior
It should've opened the repository as normal

### Screenshots
N/A

[VSCrash.zip](https://github.com/github/VisualStudio/files/2784894/VSCrash.zip)

**Comment by meaghanlewis** [comment]
Hi @tsimmons1987 I believe you are experiencing the same issue as reported in: #2189, #2188, #2186, #2185.

@jcansdale on our team worked on a fix for this in: #2190 and we will be releasing a patch to release this fix tomorrow.

**Comment by jcansdale** [comment]
@tsimmons1987 you can find a PR with the fix here #2191. Please comment on the PR if it fixes it for you. 🤞
