### ISSUE TITLE
GitHub extension stopped reporting progress when cloning from the Start Page

### ISSUE THREAD

**Issue by prasethu** [github/VisualStudio#2196]
In all recent versions of the GitHub extension, I've noticed that a clone from the Start Page does not show progress on the status bar of Visual Studio.

On debugging the Clone API call in Team Explorer I found that a null IProgress<ServiceProgressData> was being sent and hence progress cannot be reported.

We're planning to add this feature to the Start Window and this lack of progress will cause experience gaps.

**Comment by prasethu** [comment]
@jcansdale  / @meaghanlewis looping you in based on the history 😄  

I'm on the VS team and noticed this on the debugger. I think progress is currently broken in the clone api that the GitHub extension calls, so if you could validate that when IProgress<T> passed to the clone API is non-null, that would help a lot.

I'm happy to talk more if needed.

**Comment by jcansdale** [comment]
Hi @prasethu,

I disabled this when working on a VS 2019 compatible version before the VS preview was out.
https://github.com/github/VisualStudio/blob/e98aa41ce490208e85e130d75252e893a0b0cea3/src/GitHub.TeamFoundation.14/Services/VSGitServices.cs#L82-L98

Now that I've got the VS 2019 assemblies to target, I should  be able to reinstate it. 🤞   I'll keep you posted!

**Comment by prasethu** [comment]
Thanks @jcansdale ! There's a chance that this experience will ship in the next preview, so if you could make this work and build me a private VSIX I can try it on my side.
