### ISSUE TITLE
Re-clone uses old clone dialog

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#2199]
### Steps to Reproduce
1. Click on a repository link in `Recent`
2. Old re-clone dialog appears rather than `Open from GitHub`

_Note, I don't know exactly when/why these links get added. We should investigate and find out if these links are part of the `Get to Code` workflow._

![image](https://user-images.githubusercontent.com/11719160/51717996-0aed6480-203b-11e9-85a7-cab3ba8d57b6.png)

### Expected behavior
- Show `Open from GitHub` dialog with URL field populated.

### Screenshots
![image](https://user-images.githubusercontent.com/11719160/51717966-e5605b00-203a-11e9-95f5-33b769d27c7e.png)

**Comment by prasethu** [comment]
@jcansdale - If you clone a repo through the Start Page, then that repos remote information roams to other devices you are signed into and are available on your MRU.

**Comment by jcansdale** [comment]
@prasethu thanks for the explanation, that makes sense. I'll be sure to prioritize these flows.
