### ISSUE TITLE
Visual Studio Closes after opening.

### ISSUE THREAD

**Issue by FloteFuertes** [github/VisualStudio#2205]
Hi, 

Just got this Error in Visual Studio both my private and public repo  doesn't show up.  for the public repo it just close after opening it while for the private repo it just sit there but it's empty and If I clicked somewhere in visual studio on my private repo it will display a message "a key has already been added".  I have this log under %appdata% local and not roaming cause I cannot see any logs in roaming.
Logs in GitHubVisualStudio /Extension.log
![image](https://user-images.githubusercontent.com/21190507/51897885-b1928600-23ea-11e9-8bd9-f027d60fd351.png)

I tried also git reset --hard but still no luck. Please help Thank you

**Comment by meaghanlewis** [comment]
@jcansdale @StanleyGoldman @grokys from looking at this log snippet does anything stand out to you that could be potentially causing repos to not show up?

**Comment by FloteFuertes** [comment]
Btw I was using Vs2015 that time and now I am using and installed 2017 and it's all working right now.  Thank you for the reply.

**Comment by jcansdale** [comment]
This does look like a MEF error, which unfortunately can happen randomly when installing extension for VS 2015. 😞

@FloteFuertes If this is continuing to happen, I'll reopen and investigate. Thanks for the report.
