### ISSUE TITLE
Parameter Hint

### ISSUE THREAD

**Issue by jarizast** [github/VisualStudio#2206]
**Is your feature request related to a problem? Please describe.**
I hard to know what the parameter means, specially when is string/bool/int. 

**Describe the solution you'd like**
I would like the code to be able to detect those parameters and match the function and show me a hint of what the name of the parameter is.

**Describe alternatives you've considered**
We can either write the parameter name or create a variable and named accordingly. 

**Additional context**
I see this it is a new feature of Rider/ReSharper but I don't use neither. 

e.g. The developer write this code: `return Regex.Split(sentence, "\\s")`
and Ideally with this feature, it will look like: `return Regex.Split(sentence, pattern:"\\s")`

Here a screenshot:
![dta8js0xgaap3cp](https://user-images.githubusercontent.com/34106843/52003029-48595400-2478-11e9-8161-54db932d7f1e.jpg)

**Comment by meaghanlewis** [comment]
👋 @jarizast, thanks for writing in with this feature request. Unfortunately, this repo is only for the GitHub extension for Visual Studio and your request is something that Visual Studio itself would have to support. You can suggest a Visual Studio feature from [here](https://developercommunity.visualstudio.com/spaces/8/index.html).
