### ISSUE TITLE
Create signed VSIX for Visual Studio with Fix to code acquisition

### ISSUE THREAD

**Issue by prasethu** [github/VisualStudio#2210]
Create signed VSIX for Visual Studio with Fix to code acquisition so the VS installer can install the bits.

**Comment by prasethu** [comment]
@jcansdale

**Comment by prasethu** [comment]
@jekelly, @prnadago

**Comment by jcansdale** [comment]
The following version has been passed to Microsoft for insertion:
[ghfvs-2.8.0.6762-vsinstaller (1).zip](https://github.com/github/VisualStudio/files/2851344/ghfvs-2.8.0.6762-vsinstaller.1.zip)

No further action required.
