### ISSUE TITLE
Support for client side hooks

### ISSUE THREAD

**Issue by merrycoder** [github/VisualStudio#222]
It would be great to have client side hooks respected by the extensions. It looks like libgit2  [won't add support for it](https://github.com/libgit2/libgit2/issues/964) as they think it's the business of the IDE to support hooks.
Do you have any plans in that direction?

**Comment by shana** [comment]
The GitHub extension for VS doesn't handle git-related operations, that's a part of the git support that's shipped with VS itself, so we can't really do much about commit hooks :-/
