### ISSUE TITLE
Can't install extension on Visual Studio 2019 preview 3

### ISSUE THREAD

**Issue by Lupusa87** [github/VisualStudio#2232]
## Versions
 - GitHub Extension for Visual Studio version: 16.0.1230
 - Visual Studio version: Visual Studio 2019 preview 3

## What happened
Was not able to install extension.

### Screenshots
![untitled](https://user-images.githubusercontent.com/40779557/52926675-c6d14500-3304-11e9-9fae-e39de4fb6036.png)

### Logs
[dd_VSIXInstaller_20190217221929.log](https://github.com/github/VisualStudio/files/2873962/dd_VSIXInstaller_20190217221929.log)

**Comment by NickCraver** [comment]
The same stack is happening here - happy to help test any proposed fixes!

**Comment by Huy-Nguyen-MSFT** [comment]
This is one of the rare case when GitHub Extension for Visual Studio online has a lower version (2.7.1.6591) than the one shipped with VS 2019 Preview (2.8.0.6762).

If we can get a new release of the online extension with a higher version, this should work. In the mean time, a work-around is to install the one shipped with VS.

![capture](https://user-images.githubusercontent.com/19274119/53196120-0a110980-35cc-11e9-9dd6-50e33ec16a2e.PNG)

**Comment by meaghanlewis** [comment]
@Huy-Nguyen-MSFT thanks for providing that workaround.

We are planning to ship a new version of the extension on 02/25.

**Comment by meaghanlewis** [comment]
This should be fixed now. @Lupusa87 @NickCraver hope that you will try to install the extension again!

**Comment by NickCraver** [comment]
@meaghanlewis Works great now, thanks for the fix and the poke!

**Comment by AbolfazlSanandaji** [comment]
thank you

**Comment by saqibsb** [comment]
thank boss

**Comment by JustinLuuu** [comment]
thx
