### ISSUE TITLE
Visual Studio Docker support not compatible with a CI pipeline from repository

### ISSUE THREAD

**Issue by GuerrillaCoder** [github/VisualStudio#2235]
I have a solution that has the following projects:

ServiceStackDockerTest
ServiceStackDockerTest.ServiceModel
ServiceStackDockerTest.ServiceInterface

When I add docker support inside visual studio this is the docker file that is added.

	FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
	WORKDIR /app
	EXPOSE 80

	FROM microsoft/dotnet:2.1-sdk AS build
	WORKDIR /src
	COPY ServiceStackDockerTest/ServiceStackDockerTest.csproj ServiceStackDockerTest/
	COPY ServiceStackDockerTest.ServiceModel/ServiceStackDockerTest.ServiceModel.csproj ServiceStackDockerTest.ServiceModel/
	COPY ServiceStackDockerTest.ServiceInterface/ServiceStackDockerTest.ServiceInterface.csproj ServiceStackDockerTest.ServiceInterface/
	RUN dotnet restore ServiceStackDockerTest/ServiceStackDockerTest.csproj
	COPY . .
	WORKDIR /src/ServiceStackDockerTest
	RUN dotnet build ServiceStackDockerTest.csproj -c Release -o /app

	FROM build AS publish
	RUN dotnet publish ServiceStackDockerTest.csproj -c Release -o /app

	FROM base AS final
	WORKDIR /app
	COPY --from=publish /app .
	ENTRYPOINT ["dotnet", "ServiceStackDockerTest.dll"]

It adds the docker file to `ServiceStackDockerTest/Dockerfile`.

Visual studio does something magical behind the scenes with drive mapping to make this work because the Dockerfile is inside the `ServiceStackDockerTest` folder.

This means if you try to run `docker build .` manually it cannot copy the `.csproj` files because they are scoped from the parent directory which the build command doesn't have access to.  This is a real problem because CI pipelines work directly from git repository so they don't have the magical behind the scenes trick that visual studio employs to build the image.

This seems to leave us with 2 choices.

1) add docker file to solution root and break docker support.  VS will no longer recognise the dockerfile and wont debug the container, hit breakpoints and automatically rebuild it on change from debug button.

2) Dont use CI

Why has this been implemented this way?  Is there anyway to have visual studio docker support in a format that will build in a CI pipeline from the repo?

**Comment by GuerrillaCoder** [comment]
The answer was actually very simple.  I just had to change the build context in pipeline task

**Comment by StanleyGoldman** [comment]
Glad you fixed your issues, but... this repo is for the GitHub extension for Visual Studio.
I wouldn't have been able to help you anyway. 🐑 😄

**Comment by GuerrillaCoder** [comment]
Lol sorry, I guess I shouldn't blindly post to first google result
