### ISSUE TITLE
Opening Package Manager Console restarts Visual Studio

### ISSUE THREAD

**Issue by Iliyan7** [github/VisualStudio#2237]
## Versions
 - Visual Studio version: Visual Studio version: Visual Studio 2019 preview 3

## What happened
When open Package Manager Console tab, Visual Studio interaction is fully blocked (you can't click anywhere) and after few seconds it got restarted by its own.

### Steps to Reproduce
1. Go to View > Other Window
2. Click on Package Manager Console

### Additional context
All projects (11) are building withour errors or warnings. Restarting PC solve the problem. Obviously this error doesn't happen often at all, I use Visual Studio 2019 since preview 1 and that's happened today for first time, but I don't know what could caused this. I was doing usual work, editing code, added new ef core model and decided to add a migration and update db, but when when I opened PMC that happened.

**Comment by meaghanlewis** [comment]
Hi @Iliyan7 this repository is specifically for the GitHub extension for Visual Studio. To report this issue you can go to the Visual Studio Support here: https://visualstudio.microsoft.com/vs/support/
