### ISSUE TITLE
Links to outdated comments in pull request reviews don't work

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#2247]
## Versions
 - GitHub Extension for Visual Studio version: 2.8.0
 - Visual Studio version: All

## What happened
I opened a pull request review and clicked on link to an outdated comment. Nothing happened.

### Steps to Reproduce
1. Open `github/VisualStudio` pull request 2241 on GitHub pane
2. Click on `Reviewers > jcansdale`
3. Expand `Outdated comments`
4. Click on one of the outdated comment links
5. Nothing happens

### Expected behavior

File diff appears with selected comment.

If this can't be made to work, maybe we could open the comment on dotcom?

### Screenshots
![image](https://user-images.githubusercontent.com/11719160/53498986-5615ef80-3a9f-11e9-9b2c-0c2e042341cd.png)

### Research

The issue appears to be that that the `PullRequestSessionFile` doesn't have any associated `InlineCommentThreads`.

![image](https://user-images.githubusercontent.com/11719160/53500298-f8cf6d80-3aa1-11e9-82bf-b4d6696abcbd.png)

**Comment by grokys** [comment]
If you debug into `PullRequestReviewCommentViewModel.DoOpen` and click on one of the comments, you can see that it gets the file at the comment's commit SHA but the file's `InlineCommentThreads` is empty.
