### ISSUE TITLE
Localization: Please enter a repository path

### ISSUE THREAD

**Issue by StanleyGoldman** [github/VisualStudio#2264]
Created for @maikebing 

## Language

Chinese (Simplified)

## English source

```
Please enter a repository path
```

## Original Translation

```
請輸入存放庫路徑
```

## Suggested Translation

```
請輸入存儲庫路徑
```

**Comment by StanleyGoldman** [comment]
cc: @mihalyv01mor

**Comment by johnliu2016** [comment]
On linguistic review

**Comment by johnliu2016** [comment]
@StanleyGoldman, is it possible to provide some screenshot for context review?

**Comment by maikebing** [comment]
Chinese Simplified：
> 请输入存储库路径

Traditional Chinese (Taiwan or Hong Kong)

> 請輸入存儲庫路徑

**Comment by StanleyGoldman** [comment]
![image](https://user-images.githubusercontent.com/417571/55253504-e32d9f00-522b-11e9-9b8d-c6ad9d655ee2.png)

![image](https://user-images.githubusercontent.com/417571/55253560-196b1e80-522c-11e9-8244-81ae6c50d074.png)

![image](https://user-images.githubusercontent.com/417571/55253643-4ae3ea00-522c-11e9-82e9-ea1baa535a8b.png)

**Comment by lukaschal** [comment]
Fixed. New tgt "請輸入存放庫路徑".
