### ISSUE TITLE
Localization: Create a {0} Repository

### ISSUE THREAD

**Issue by StanleyGoldman** [github/VisualStudio#2268]
Created for @maikebing 

## Language

Chinese (Simplified)

## English source

```
Create a {0} Repository
```

## Original Translation

```
建立 {0} 存放庫
```

## Screenshot
![image](https://user-images.githubusercontent.com/417571/53967880-0b5e2e00-40c4-11e9-9975-70ae4b1c9b69.png)
![image](https://user-images.githubusercontent.com/417571/53967939-2761cf80-40c4-11e9-8268-a3b90da27a00.png)

## Suggested Translation

```
創建 {0} 存儲庫
```

**Comment by StanleyGoldman** [comment]
cc: @mihalyv01mor

**Comment by johnliu2016** [comment]
On linguistic review
