### ISSUE TITLE
Localization: Open from GitHub

### ISSUE THREAD

**Issue by StanleyGoldman** [github/VisualStudio#2269]
Created for @maikebing 

## Language

Chinese (Simplified)

## English source

```
Open from GitHub
```

## Original Translation

```
從 GitHub 開啟
```

## Screenshots
![image](https://user-images.githubusercontent.com/417571/53966410-1cf20680-40c1-11e9-816f-840257dac97f.png)

## Suggested Translation

```
從 GitHub 打開
```

**Comment by StanleyGoldman** [comment]
cc: @mihalyv01mor

**Comment by johnliu2016** [comment]
On linguistic review
