### ISSUE TITLE
[Localization][VendorContextQuery] Translator needs more context

### ISSUE THREAD

**Issue by mihalyv01mor** [github/VisualStudio#2271]
## Description
Dear Developer Team!  

Please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability we raise a question to the core team.

Please re-assing back to use in case you are not the proper contact person.

## Details

  | Full Source   String | Extended   Description
-- | -- | --
1 | Update your local repository's | Would you please   provide the full context for this truncated string?          (02-21-19) This query might have been resolved by mistake because I   couldn't find any answer. So here I cloned it again.          [#8193401]
2 | added some commits | Please provide the   full string.
3 | and others | What does   "others" refer to in this context?
4 | and others | Would you please give   me the full context for this truncated string?          I translated this fuzzy string strictly following the source structure for   now.          Original translation: 및 기타 {0}의 연결 문자열을 검색하는 동안 오류 발생          [#8297271]
5 | Open Conversation | Is "open" a   verb or an adjective here? We assumed the former for now, please advise.
6 | added some commits | Does anything precede   "added" here? Translated as standalone string for now, please   advise.

## Answers

- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6

**Comment by mihalyv01mor** [comment]
@StanleyGoldman Could you please help us out?

**Comment by StanleyGoldman** [comment]
Sure thing! I'll work on getting you guys some context in a bit.

**Comment by StanleyGoldman** [comment]
1. "Update your local repository's"

The user is being informed that we are going to change their `origin` "to point to" a different location.

![image](https://user-images.githubusercontent.com/417571/53960038-2d9b8000-40b3-11e9-9c66-4872beddd19a.png)

**Comment by StanleyGoldman** [comment]
@mihalyv01mor I'm going to close this. Please feel free to re-open if you have more questions.
