### ISSUE TITLE
Context-menu (right-click) in code editor and solution explorer are very very slow

### ISSUE THREAD

**Issue by DoCode** [github/VisualStudio#2279]
## Versions
 - GitHub Extension for Visual Studio version: latest
 - Visual Studio version: 15.9.9 and 16.0.0 RC2

## What happened
Context menu (right-click) shown very very slow!

### Steps to Reproduce
1. Right-click inside the code editor and on files in solution explorer

### Expected behavior
A fast and smooth opening of the context menu!

### Screenshots
See it here:  
[![Watch the video](https://i.imgur.com/vKb2F1B.png)](https://developercommunity.visualstudio.com/storage/attachments/63159-vs2019-rc2-slow-editor-right-click-context-menu.mp4)

### Additional context
Additional, linked issues:
[JetBrains ReSharper](https://youtrack.jetbrains.com/issue/RSRP-473330)
[Visual Studio](https://developercommunity.visualstudio.com/content/problem/478451/right-click-to-open-in-code-editor-is-very-slow.html)

**Comment by meaghanlewis** [comment]
Hi @DoCode you can provide this feedback to: https://visualstudio.microsoft.com/vs/support/

This is the repo specifically for the GitHub extension for Visual Studio.

**Comment by DoCode** [comment]
@meaghanlewis sorry but I think that's here, because it's only when the GitHub extension is active!

**Comment by StanleyGoldman** [comment]
Hey @DoCode If you are sure about this, include a single video where you disable the extension, demonstrate the speed. Enable the extension and demonstrate the speed.
Also it would help if you used a smaller project, and be sure disable other extensions.

**Comment by StanleyGoldman** [comment]
Re-open the issue when you are ready.

**Comment by DoCode** [comment]
@StanleyGoldman thanks. We found the issue in the ReSharper extension.
Today with so many extensions it's very difficult in the first place to find the appropriate tool! 😒
