### ISSUE TITLE
Visual Studio 2017  for Xamarin still not working “out of the box”

### ISSUE THREAD

**Issue by zhulin802** [github/VisualStudio#2280]
### What happened
Xamarin installed with Visual Studio 2017 still not working “out of the box”:
https://stackoverflow.com/questions/55038300/xamarin-installed-with-visual-studio-2017-still-not-working-out-of-the-box
when install Xamarin with VS 2017 ，a lot of different things are happening,
for example :"Android_Accelerated_x86_Oreo on Hyper-V needs the Windows Hypervisor Platform installed and enabled."
### Hope
have a full installation documentation demo,able to “out of the box”

**Comment by gzuckerman** [comment]
@zhulin802 This repo is for the GitHub Visual Studio extension and not Visual Studio or Xamarin.
