### ISSUE TITLE
GitHub v4 Octokit.NET library problem

### ISSUE THREAD

**Issue by SimpleSamples** [github/VisualStudio#2283]
I tried the GitHub v4 Octokit.NET library. I installed it using NuGet into a console project. I know it is still beta software. I had a problem as I described in [Sample does not rock · Issue #193 · octokit/octokit.graphql.net](https://github.com/octokit/octokit.graphql.net/issues/193). I just want to know if the problem is something I did wrong or if it is a bug. If it is a bug then I guess that  GitHub API v4 is not ready for use.

**Comment by jcansdale** [comment]
See my reply https://github.com/octokit/octokit.graphql.net/issues/193#issuecomment-476134296 😄
