### ISSUE TITLE
Security tenet: Signing

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#2287]
The following items need to be addressed as it relates to signing:

**- Add an authenticate signature to files: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802025**

Files with StrongName signatures must also be signed with an Authenticode signature.

**- Sign all applicable files with an embedded signature: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802023**

Files that can be, must be signed with an embedded signature.  

**- Sign external releases with an external certificate: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802022**

Files shipping in external releases must be signed with a certificate that is managed by PRSS or Microsoft Mobile. The signing certificate must not be designated as "MSIT" or "Internal".

Applications that are released solely via a Microsoft application store that signs all required files on your behalf (for example: non-desktop applications released through the Store or drivers submitted to the Hardware Developer Dashboard) automatically satisfy this requirement.

**Comment by jcansdale** [comment]
Our VSIX is signed with the following certificate:

![image](https://user-images.githubusercontent.com/11719160/54746567-6748ac80-4bc4-11e9-9866-ec4ff42fe435.png)

Individual assemblies with StringName signatures aren't currently signed:
![image](https://user-images.githubusercontent.com/11719160/54746703-c1e20880-4bc4-11e9-9c0b-dfbfe7d7642c.png)

**Comment by meaghanlewis** [comment]
Im going to close this issue out since it was discovered we do not need to change the way we sign our extension.
