### ISSUE TITLE
Bring GitHub PR toolwindow into Team Explorer Page

### ISSUE THREAD

**Issue by acangialosi** [github/VisualStudio#2298]
VS' primary home for Version control experiences is the Team explorer tool window. That is the location for the Azure Repos Pull Request expereince as well as all other Git VC experiences. To maintain consistency and help users learn how to find similar experiences the GitHub PR experiences an also live as a page in the Team Explorer window that can be torn out as a stand alone window by the user when needed. 

![image](https://user-images.githubusercontent.com/5457010/55012397-9be1ad00-4fa4-11e9-8d92-c26e4cbbec0b.png)

**Comment by jcansdale** [comment]
@acangialosi it looks like this was a close call! 😉

I'm happy to report the PR experience appears to still work without Team Explorer. 😄
