### ISSUE TITLE
Hit access violation when opening VS

### ISSUE THREAD

**Issue by abuchholtzau** [github/VisualStudio#230]
Environment:
VS Enterprise Full installation on Win10 x64

Repro steps:
Enable full heap page tracking for devenv.exe in AppVerifier
Steps:
1.Open Application Verifier(x64) as a admin.
2.File->Add Application(Ctrl+A)->devenv.exe(under path C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE)
3.Only choose Heaps on Tests-Basics and save.
4.Open VS.
5.Copy \\vsdbgqa\SetupScripts\Prism\CollectionTools\windbg.exe to desktop & open windbg.exe as admin.
6.File->Attach to a Process(F6) ,choose devenv.exe.
7.Type "g" on the bottom of windbg on and click enter , then showing "Debuggee is running"  on the bottom of windbg
8.Wait one minute and create a C# project 

Observe: Hit access violation

CallStacks:
``` 
GitHub.Exports.dll!GitHub.Services.VSServices.PokeTheRegistryForRepositoryList() Line 117 C#
  GitHub.Exports.dll!GitHub.Services.VSServices.GetKnownRepositories() Line 98 C#
  GitHub.VisualStudio.dll!GitHub.VisualStudio.ConnectionManager.RefreshRepositories.AnonymousMethod__20_0() Line 132 C#
  mscorlib.dll!System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<GitHub.Models.ISimpleRepositoryModel>>.InnerInvoke() Line 680 C#
  mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498 C#
  mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861 C#
  mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954 C#
  mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902 C#
  mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827 C#
  mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767 C#
  mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 2704 C#
  mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820 C#
  mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161 C#
  [Native to Managed Transition] 
  kernel32.dll!BaseThreadInitThunk(unsigned long RunProcessInit, long(__stdcall*)(void *) StartAddress, void * Argument) Line 64 C
  ntdll.dll!__RtlUserThreadStart(long(__stdcall*)(void *) StartAddress, void * Argument) Line 997 C
  ntdll.dll!_RtlUserThreadStart(long(__stdcall*)(void *) StartAddress, void * Argument) Line 914 C
```

**Comment by shana** [comment]
I'm sorry, I'm not quite clear on what you're testing here. Is the GitHub repository list that is shown in the Team Explorer Connect page not loading for you (which uses the data from this codepath) so you're trying to debug it?

**Comment by BlairWangzhifang** [comment]
The purpose of this testing is to double check see if there any heap corruption on our Diagnostics basic scenarios , e.g. we found Access violation on stating VS and creat projects scenarios which seems like caused by your team (GitHub.VisualStudio.dll).

**Comment by shana** [comment]
@BlairWangzhifang @abuchholtzau The access in question is a registry access value read, done inside a using block holding the registry key whose value is being read (https://github.com/github/VisualStudio/blob/master/src/GitHub.Exports/Services/VSServices.cs#L117).
If this is throwing an access violation, the immediate scenario that comes to mind is that something else concurrently accessed and changed that subkey while we're enumerating the values, causing the underlying win32 registry pointer to become invalid for that particular block.

Do you happen to have information on the exception that gets thrown on the managed side after the access violation is triggered?

**Comment by BlairWangzhifang** [comment]
Sorry , only have callstack information which has been given to you at the top .

**Comment by shana** [comment]
This looks to be an issue in the win32 registry api that .NET calls. There's not really much we can do beyond handling the exception like we already do.
