### ISSUE TITLE
GitHub dialogs use common VS Styles and themes

### ISSUE THREAD

**Issue by acangialosi** [github/VisualStudio#2300]
GitHub dialogs currently use a unique set of styles, colors, fonts and themes from the rest of Visual Studio. Suggestion is to move these dialogs to use VS' color service, themes and other elements to delver an experience that is visually integrated with the IDE bu maintains GitHub's brand.

![image](https://user-images.githubusercontent.com/5457010/55013050-9a64b480-4fa5-11e9-86af-d39632931f49.png)

**Comment by jcansdale** [comment]
This is being worked on in #2261.

![image](https://user-images.githubusercontent.com/11719160/55013833-da498d00-4fe1-11e9-9dc4-505370fdd548.png)
