### ISSUE TITLE
More than one item highlighted in the connect page repositories list

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#231]
When

- there's no solution open
- there is a git repo context set
- the repo has a remote
- there's more than one local clone of the same repo
- more than one of these clones has been opened in VS before (so they're known local repositories)

The repositories list in the Connect page is highlighting both clones, which probably means there's a missing path check somewhere (and since both remote urls match the current git repo, both get highlighted).

<img width="474" alt="screen shot 2016-03-01 at 8 28 48 pm" src="https://cloud.githubusercontent.com/assets/310137/13439215/dc812c12-dfec-11e5-8907-697969c49793.png">

**Comment by paladique** [comment]
Line that's causing problems resides in `GitHubConnectContent.xaml.cs`:
`return item != null && context != null && context.ActiveRepoUri == item.CloneUrl;`
