### ISSUE TITLE
Distinguish Find Results by user code

### ISSUE THREAD

**Issue by ortund** [github/VisualStudio#2311]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but this would be a "nice to have" feature. I think it would be really cool if there was a way I could limit Find Results to only show me results found in user code.

**Describe the solution you'd like**
Currently, Find Results returns every instance of a thing whether it was added to the project as part of the project template, the developer, or a 3rd party library. Try searching for "TODO" and you'll find that most of the results aren't even in files you've ever seen before.

When I search for "TODO", what I'd like is an option to limit my search to include only files that I've added to the project.

**Describe alternatives you've considered**
There aren't any. Currently if I need to TODO something, I write the comment as "OTODO" or something similar that I'm pretty sure other people wouldn't have used in their code so that only the TODOs that I wrote in show up.

**Comment by meaghanlewis** [comment]
@ortund thanks for your suggestion, but this is the wrong repo to report this. This repo is only for the GitHub extension for Visual Studio, not Visual Studio itself.

You can report a problem or suggest an enhancement from Visual Studio here:
https://developercommunity.visualstudio.com/spaces/8/index.html
