### ISSUE TITLE
Right-click to open in code editor is very slow

### ISSUE THREAD

**Issue by jasongin** [github/VisualStudio#2313]
When I right-click in a code editor then the context menu show very, very delayed! When I disable the MS GitHub extension everything works fine!

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/478451/right-click-to-open-in-code-editor-is-very-slow.html
VSTS ticketId: 810339_
_These are the original issue comments:_

Visual Studio Feedback System on ‎3‎/‎5‎/‎2019, 10:38 PM (20 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on ‎3‎/‎6‎/‎2019, 06:50 PM (19 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

Rock Li [MSFT] on ‎3‎/‎10‎/‎2019, 06:42 PM (15 days ago): <p>Hi Manuel, Could you please disable the Resharper? does the issue still repro?</p>

Manuel on ‎3‎/‎10‎/‎2019, 06:53 PM (15 days ago): <p>Hi Rock Li, no it's the same.</p><p>When I disable the preview feature 'Add support for displaying differences in the editor' then it's a little bit faster!</p>

Visual Studio Feedback System on ‎3‎/‎10‎/‎2019, 11:50 PM (15 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

Rock Li [MSFT] on ‎3‎/‎10‎/‎2019, 11:57 PM (15 days ago): <p>I guess it is the Resharper caused the slow, and please give us some screenshots to repro this issue if there is no useless after disabling the extension. we look forward to hearing from you.</p>

Manuel on ‎3‎/‎12‎/‎2019, 01:33 PM (14 days ago): <p>So I tested many combinations also with the new Visual Studio 2019 RC2, but see no difference when I disable the ReSharper extension!</p><p>And also when I right click inside the code editor it was horrible slow. With and without ReSharper!</p><p>What can we do?</p>

Manuel on ‎3‎/‎12‎/‎2019, 02:12 PM (14 days ago): <p>Please look at this, this is horrible and a show stopper:<br><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/63159-vs2019-rc2-slow-editor-right-click-context-menu.mp4">vs2019-rc2-slow-editor-right-click-context-menu.mp4</a></p>

Visual Studio Feedback System on ‎3‎/‎14‎/‎2019, 01:23 AM (12 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

Rock Li [MSFT] on ‎3‎/‎14‎/‎2019, 01:33 AM (12 days ago): <p>Have you installed other extensions? I noticed that there was a &quot;Format XAML&quot; item on your right-click menu. In order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario? </p><p>  </p><p>We look forward to hearing from you! </p>

Visual Studio Feedback System on ‎3‎/‎14‎/‎2019, 06:43 PM (11 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_

Manuel solved on ‎3‎/‎14‎/‎2019, 02:57 AM (12 days ago), 0 votes: 
<p>I have severals extensions installed yes. And yes also the XAML Styler.</p>
<p>But I found the issue and I think you should verify this also. The ReSharper team work also on verification. When I disable the MS GitHub extension everything works fine! </p>

**Comment by jcansdale** [comment]
@jasongin thanks for opening this issue. We'll investigate!

**Comment by jcansdale** [comment]
I've investigated this issue, but can't seem to reproduce it or figure out what might be going wrong. Any more information would be much appreciated. 😢

**Comment by jcansdale** [comment]
@DoCode Thanks for letting me know! I was beginning to wonder if it was caused by an interaction with some other extension. I'm relieved to hear that it was. 🎈
