### ISSUE TITLE
Reinstalling GitHub for Visual Studio extension doesn't restore the git-client protocol handler

### ISSUE THREAD

**Issue by tiesmaster** [github/VisualStudio#2317]
## Versions
 - GitHub Extension for Visual Studio version: latest
 - Visual Studio version: 2017/2019

## What happened
A couple days ago I got a ton of notifications in Windows 10, that the "default app" for `xyz` got reset to the _default_ value. I just discovered that the "Open in Visual Studio" is now broken, because of this. In order to fix this, I tried to uninstall, and install the extension, with the expectation that the protocol handler would be installed again.

### Steps to Reproduce
_These are the steps I did, but the starting point is of course the situation that the protocol handler is missing. I don't know how to reproduce **that**_.

1. Uninstall GitHub Extension for Visual Studio
2. Install GitHub Extension for Visual Studio

### Expected behavior
Protocol handler for `git-client` is restored.

### Actual behavior
Protocol handler stays absent. Checked both Windows Settings, as well as, the registry.

### Additional context
Timeline: I got a ton of notifications from Windows that this "default app" reset happened, Double digit numbers, so not really feasible to check which programs were among them. This was before April 2nd). Then I installed VS 2019 on April 3rd; you would expect that installing VS 2019 would install a fresh copy of the extension, and also add the protocol handler. And today, I uninstalled, and reinstalled the extension for the VS 2019 installment.

**Comment by MV10** [comment]
Firefox is prompting me to select a handler and devenv.exe isn't it -- does anyone know the EXE that I should point it to? (VS2019)

**Comment by jcansdale** [comment]
The `git-client` protocol handler is actually installed with Visual Studio as part of Team Explorer. It's completely independant to GitHub for Visual Studio.

Closing as can't fix.
