### ISSUE TITLE
Github 500 Error if send a Bug in internal Issue Reporter

### ISSUE THREAD

**Issue by cschoeni** [github/VisualStudio#2321]
## Versions
 - GitHub Extension for Visual Studio version: ...
 - Visual Studio version: 1.30.2 (1.30.2)

### Steps to Reproduce
1. Go to Help
2. Click on Report Issue
3. Fill out the Form
4. Click preview on Github

### Expected behavior
Oops Servererror 500

### Screenshots
![Screenshot](https://user-images.githubusercontent.com/11288662/55862416-b4db8800-5b78-11e9-86d5-d0f04a98303d.png)

**Comment by StanleyGoldman** [comment]
Hey @cschoeni 
This GitHub Repo is for the GitHub Extension for Visual Studio.

![image](https://user-images.githubusercontent.com/417571/55872763-c6626700-5b5b-11e9-81e7-0ce1bb927fae.png)
You are looking for this: https://github.com/microsoft/vscode
