### ISSUE TITLE
Clone and create dialogs need to be updated to follow VS dialog guidelines

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#2324]
Corresponding work item: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/843576

VS design standards guideline: https://vsuiguide.azurewebsites.net/

Items that need to be addressed:

- Padding for search
- Centered layout content
- Link tabs 
- Padding between path and browse link

**Comment by vesarautiainen** [comment]
New VS guideline: aka.ms/d3guide
