### ISSUE TITLE
pull dialog not pulling the default pull dialog of git extension

### ISSUE THREAD

**Issue by Nazgaul** [github/VisualStudio#2325]
## Versions
 - GitHub Extension for Visual Studio version: 3.1.0.5602
 - Visual Studio version: 2017

## What happened
When clicking on the pull dialog in visual studio the default pull behavior i set in git extensions is not honored.
### Steps to Reproduce
1. open git extension
2. Click on the arrow next the pull dialog icon
3. Set default pull action button action to pull - merge
4. Click on git extension pull dialog arrow and click open pull dialog
![image](https://user-images.githubusercontent.com/3366179/55936504-31389e80-5c3f-11e9-8b52-60760de675b1.png)

5. Go to visual studio open the pull dialog merge options not changed
![image](https://user-images.githubusercontent.com/3366179/55936559-52998a80-5c3f-11e9-85fc-7c40da6a195e.png)

**Comment by StanleyGoldman** [comment]
Hey @Nazgaul I'm not sure what extension you are talking about here, but it's not ours.
That pull dialog does not belong to us.

**Comment by meaghanlewis** [comment]
@Nazgaul you might be looking for this repository: https://github.com/gitextensions/gitextensions
