### ISSUE TITLE
The project .Droid needs to be deployed before it can be started. Verify the project is selected to be deployed in the Solution Configuration Manager.

### ISSUE THREAD

**Issue by Rajeswari06** [github/VisualStudio#2328]
## Versions
 - Visual Studio version: Visual Studio 2019 - 16.0.1

## What happened
The project .Droid needs to be deployed before it can be started. Verify the project is selected to be deployed in the Solution Configuration Manager.

Even though deploy is selected for .droid project

### Steps to Reproduce
1. Go to visual studio 2019 and open a project
2. Click on Run 
3. Build was success and installed in device, but debugging is not working control was stopped with the above error

### Expected behavior
App should open and able to debug the project.

**Comment by StanleyGoldman** [comment]
Hi @Rajeswari06 this repo is for the GitHub Extension for Visual Studio.
Since you are having a problem with Visual Studio itself: [How to report a bug with Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
