### ISSUE TITLE
Is VS2019 compiled with /LARGEADDRESSAWARE

### ISSUE THREAD

**Issue by rolandh** [github/VisualStudio#2340]
is VS2019 compiled with /LARGEADDRESSAWARE to enable usage of more than 4gb of memory?

https://docs.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses?view=vs-2019

If not is there any reasons to not use binedit and enable it myself?

**Comment by StanleyGoldman** [comment]
Hey @rolandh this repo is for the GitHub extension for Visual Studio. Not for Visual Studio itself.
You might be able to find an answer to your question here: https://developercommunity.visualstudio.com/spaces/8/index.html
