### ISSUE TITLE
VS Crash when we try Comment section

### ISSUE THREAD

**Issue by olkuziv** [github/VisualStudio#2349]
## Versions
  - Visual Studio version: 16.1.0 Prewiew 3.0

## What happened
When we try Comment(Tougle Block Comment Ctrl+Shift+/ ,  Section Comment Ctrl+K+C) on selected section, VS will crash

### Steps to Reproduce
1. Select block of code
2. Press Ctrl+shift+/ or Ctrl+K+C

### Expected behavior
Section will commented

### Screenshots
![image](https://user-images.githubusercontent.com/33831834/57558482-7bb85280-7386-11e9-8c71-d5e22e96d5fa.png)
![image](https://user-images.githubusercontent.com/33831834/57558492-8a9f0500-7386-11e9-9618-c3dcb7622ad0.png)
![image](https://user-images.githubusercontent.com/33831834/57558508-97bbf400-7386-11e9-9294-e58b58b021a1.png)
![image](https://user-images.githubusercontent.com/33831834/57558522-aacec400-7386-11e9-8cc5-70b314cc3128.png)

**Comment by meaghanlewis** [comment]
👋 @olkuziv this is the repository for the GitHub extension for Visual Studio, and the commenting functionality is provided by Visual Studio itself. You can report an issue from here: https://developercommunity.visualstudio.com/spaces/8/index.html
