### ISSUE TITLE
Adding Ignored .exe to source project still ignores

### ISSUE THREAD

**Issue by UVLabs** [github/VisualStudio#235]
I'm trying to add a compiled version of the app to the repo: https://github.com/UVLabs/Livecoding.tv-Desktop-Chat

And I added the .exe by creating a new folder in the solution then adding an existing item...selecting "Add to source control"...I committed and pushed..commit message shows on my repo but I don't see my actual .exe and compiled folder

**Comment by shiftkey** [comment]
@UVLabs this is the repository for the GitHub for VS addin - the local source control operations for Git are done by a different part of Visual Studio.

Regarding your specific issue - I suspect the build outputs are being excluded by [these rules](https://github.com/UVLabs/Livecoding.tv-Desktop-Chat/blob/master/.gitignore#L13-L22)

If you don't believe that's the case, I'd recommend using the feedback tool in VS to put the problem you're seeing in front of the right people at Microsoft.
