### ISSUE TITLE
high contrast theme no scrollbar button

### ISSUE THREAD

**Issue by ShadyGaDa** [github/VisualStudio#2379]
Using windows high contrast theme obscures the scrollbar thumb button in visual studio.
Movint the scrollbar becomes impossible.

**Comment by meaghanlewis** [comment]
@ShadyGaDa could you attach a screenshot or GIF here? I'm not exactly sure what "scrollbar thumb button" is referring to.

**Comment by ShadyGaDa** [comment]
OK.
![vs-hc-noscroll](https://user-images.githubusercontent.com/5815779/59233037-b78d4480-8bde-11e9-8151-6d66b4b93c77.png)
There is no way to grip the bar to move the scroll bar in my high contrast theme.

**Comment by ShadyGaDa** [comment]
The light blue has no slider.

**Comment by ShadyGaDa** [comment]
Hope you're still on this. Very infuriating.
By the way closed this by accident  then re-opened.

**Comment by meaghanlewis** [comment]
@ShadyGaDa this is not something that we are responsible for. We build the GitHub extension for Visual Studio. This appears to be a problem with Visual Studio itself so you have to report the issue to them. You can go submit an issue here: https://visualstudio.microsoft.com/support/
