### ISSUE TITLE
Bad clone window layout

### ISSUE THREAD

**Issue by xperiandri** [github/VisualStudio#238]
<img width="311" alt="github clone" src="https://cloud.githubusercontent.com/assets/2365592/13686098/bc547502-e71c-11e5-8a55-7113ac27d8e7.png">

1. Please, never restrict height of elements because with larger font all the text will be cut.
2. Not all text elements use VS font settings
3. It is better to name this window "Clone my GitHub Repository" because it is very confusing how to clone someone's else repository

**Comment by shana** [comment]
Thanks for the feedback! There's definitely issues we need to fix here.

> Not all text elements use VS font settings

Do you mean in terms of font sizes that you've set up in VS?

> It is better to name this window "Clone my GitHub Repository" because it is very confusing how to clone someone's else repository

Not all repos that you can clone here are your repos - if you're a part of an org, you'll see those repos here as well (also repos that someone else added you to).

When you want to clone someone else's repository, how would you go about it? Is your first instinct to search for the repository in this interface, or to grab the url from github.com?

/cc @donokuda

**Comment by xperiandri** [comment]
The same about font
<img width="311" alt="github create" src="https://cloud.githubusercontent.com/assets/2365592/13686346/f4809130-e71d-11e5-9876-508bbd1bd8e4.png">

Settings to test
[CurrentSettings.zip](https://github.com/github/VisualStudio/files/168075/CurrentSettings.zip)

You use some hardcoded settings on TextBlocks and TextBoxes instead a style

**Comment by xperiandri** [comment]
>  all repos that you can clone here are your repos - if you're a part of an org, you'll see those repos here as well (also repos that someone else added you to).

I need to understand that this window does not support cloning from URL.

>  When you want to clone someone else's repository, how would you go about it? Is your first instinct to search for the repository in this interface, or to grab the url from github.com?

Yes I just opened it first time and was wonder what to do with GitHub URL. I put URL into search box.

**Comment by shana** [comment]
BTW, the UI styles on these dialog windows follow the GitHub desktop styles, they're not VS dialogs, which is why they look different from normal VS toolwindows. This is by design.
The text being cut is definitely a problem (that's not by design).

**Comment by xperiandri** [comment]
OK, you need to use font size resource

**Comment by donokuda** [comment]
Related issue regarding font size: https://github.com/github/VisualStudio/issues/159

@xperiandri I agree that it should be a little clearer that you can't clone with a URL.

Since the search text box is specifically for the list of repos under it, I wonder if we can improve the wording inside the text box.

In GitHub Desktop, we use "Filter repositories" in the text box, which might be clearer about the intent of the text box:

![image](https://cloud.githubusercontent.com/assets/1174461/13687504/84840a94-e6d0-11e5-80b0-c51d6081a993.png)

In this case, were you trying to clone a repo that belongs to another person?

**Comment by xperiandri** [comment]
I have never used GitHub Desktop. However this description is not clear to.
It should be something like "Filter repositories by my account".

And default size of the "Clone my GitHub Repository" window is too small.
For "Create a GitHub Repository" window I can't see any reason to allow to resize it vertically at all. I think that MaxHeight should be equal MinHeight.

Also this windows do not remember last used size.
Could you preserve it if I resized a window? Because current behavior is very annoying.
