### ISSUE TITLE
Search for Files not working (VS2019)

### ISSUE THREAD

**Issue by joshua-lehmann** [github/VisualStudio#2389]
When you use the search (CTRL+F) and try to find a file for example "test.txt" that is stored in your local workspace of a SC Repository, no results are shown, even if you select "Entire Solution" for the Look in property. 
![SearchExample](https://user-images.githubusercontent.com/23728611/59909272-9236dc80-940f-11e9-8d1e-d27423bb488a.png)

**Comment by StanleyGoldman** [comment]
This project is for the GitHub Extension for Visual Studio.

[How to report a problem with Visual Studio or Visual Studio Installer](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
