### ISSUE TITLE
VS 2017 keep losing connection to Azure DevOps TFVC Repository

### ISSUE THREAD

**Issue by joshua-lehmann** [github/VisualStudio#2390]
I connected to an TFVC repo that is on azure DevOps which worked fine. But when I try to check in or any other action in VS2019 after being inactive for some time, I always get following error message: 
![Visual Studio loosing connection to devops repo](https://user-images.githubusercontent.com/23728611/59921135-0df35200-942d-11e9-85dc-44c89dd102ed.png)

**Comment by StanleyGoldman** [comment]
This project is for the GitHub Extension for Visual Studio.

[How to report a problem with Visual Studio or Visual Studio Installer](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
