### ISSUE TITLE
500 Error when running asp.net core app in vs2019

### ISSUE THREAD

**Issue by FrikkinLazer** [github/VisualStudio#2394]
## Versions
VS 2019 16.1.4
dotnet: 3.0.100-preview5-011568

## What happened
I have a asp.net core solution. I can open this solution in VS2017, and run it, and the web app runs, can can be debugged etc.
When I open the exact same app in VS2019, and run it, I get the following error:

HTTP Error 500.0 - ANCM In-Process Handler Load Failure 

### Steps to Reproduce
I do not have reproduction steps at this time. 

### Expected behavior
Opening up a solution in VS2019 should behave the same as in VS2017.

I think the first step would be to get our hands on some logs. The documentation said I need to make some changes to web.config to write logs, however, this project does not have a web.config. The template does not create one when creating a new asp.net core app. I can try adding one, but what is a web.config in asp.net core even supposed to look like?

**Comment by StanleyGoldman** [comment]
This project is for the GitHub Extension for Visual Studio.

[How to report a problem with Visual Studio or Visual Studio Installer](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
