### ISSUE TITLE
In Visual Studio 2019, what GitHub branch am I working in?

### ISSUE THREAD

**Issue by CLIRResearch** [github/VisualStudio#2398]
I created a new GitHub branch in Visual Studio 2019 under Team Explorer.  I see the branch appear in Team Explorer.  No changes at all appear in my GitHub account online.  No additional folders appear on my hard-drive. 

I created the branch and supposedly checked out the new branch.  When I make changes to my solution in Visual Studio 2019, am I working in the newly created branch?  How do I know what branch I am working on?  The context menu has a menu item: "New Local Branch From...".  Do I need to use this before making changes to the solution?

I need something that shows my local drive compared to my remote repositories.  GitHub syntax is far too counter-intuitive and confusing to rely on alone.  I need to visually see the state of source control.  

I need something that tells me where changes will be saved and committed.  

Also, the GitHub tab adjacent to the "Team Explorer" tab seems to only deal with pull requests.  Why not call it "Pull Requests"?  It does not seem to do anything else.

We have spent a great deal of time trying to figure out very basic source control tasks - more time than actual coding.  While in the learning stage, GitHub is a massive impediment to development. Basic tasks are too difficult and cryptic.

**Comment by StanleyGoldman** [comment]
> I created a new GitHub branch in Visual Studio 2019 under Team Explorer. I see the branch appear in Team Explorer. No changes at all appear in my GitHub account online. No additional folders appear on my hard-drive.

You mean to say: "I created a new **git** branch in Visual Studio...". Such an action wouldn't do anything in your account online.

You seem to be confused between `git` and GitHub. My suggestion is to start learning the difference.
[Difference between Git and GitHub](https://stackoverflow.com/questions/13321556/difference-between-git-and-github)

> I created the branch and supposedly checked out the new branch. When I make changes to my solution in Visual Studio 2019, am I working in the newly created branch? How do I know what branch I am working on? The context menu has a menu item: "New Local Branch From...". Do I need to use this before making changes to the solution?
> 
> I need something that shows my local drive compared to my remote repositories. GitHub syntax is far too counter-intuitive and confusing to rely on alone. I need to visually see the state of source control.
> 
> I need something that tells me where changes will be saved and committed.

Again, I think you mean "**git** syntax" here. You don't have to use the command line, there are plenty of clients to use, you just have to invest some time in learning how to use them.

Two popular ones that I can think of are [GitHub Desktop](https://desktop.github.com/) and [TortoiseGit](https://tortoisegit.org/).

Also, in the [Git Online Book](https://git-scm.com/book/en/v2) there is a light introduction to git clients you will encounter in popular ides. As well as an introduction section for [Visual Studio](https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Visual-Studio#vs_home)

![image](https://user-images.githubusercontent.com/417571/61389238-8d3a4100-a886-11e9-963a-038962831937.png)

> Also, the GitHub tab adjacent to the "Team Explorer" tab seems to only deal with pull requests. Why not call it "Pull Requests"? It does not seem to do anything else.

That's a little mean. 🤕 
It also helps you authenticate to GitHub and publish repositories.
We also have a roadmap where we plan to make it do more. 🤷‍♂ 

> We have spent a great deal of time trying to figure out very basic source control tasks - more time than actual coding. While in the learning stage, GitHub is a massive impediment to development. Basic tasks are too difficult and cryptic.

Again, I think you mean "**git**" here. 🤷‍♂ 
All of our functionality is [documented](https://github.com/github/VisualStudio/blob/master/docs/using/index.md) and it provides links to the parts that are handled by Team Explorer.

There are also a lot of resources to help you learn git online.
Good luck.
