### ISSUE TITLE
Insert parentheses on Autocomplete method

### ISSUE THREAD

**Issue by robiharid** [github/VisualStudio#2399]
Is there any way for VS 2019 to add parentheses once methods are autocompleted using the enter shortcut?

**Comment by StanleyGoldman** [comment]
This project is for the GitHub Extension for Visual Studio.

[How to report a problem with Visual Studio or Visual Studio Installer](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
