### ISSUE TITLE
There's no way to refresh the list of repositories

### ISSUE THREAD

**Issue by fubar-coder** [github/VisualStudio#24]
It seems that there is no way to refresh the list of GitHub repositories which is annoying, because sometimes only a sign out and sign in allows me to see newly forked repositories (not even a VS restart seems to help).

**Comment by Haacked** [comment]
Thanks for the report! Yeah, we need to periodically check for this. I think I have some code I can steal from GHfW for this.

**Comment by Haacked** [comment]
This is a dupe of #6
