### ISSUE TITLE
Issues with Undo command

### ISSUE THREAD

**Issue by calloncampbell** [github/VisualStudio#240]
I have uncommitted changes that I want to undo. When I go to the Changes view in Team Explorer, right click on the file(s) I want to undo and press the Undo command. I'm prompted and click Yes. Now what I expect to see if those files removed from the Changes view in Team Explorer. Instead I still see them and I can still right click to Undo.

What's interesting is that if I right click on a file I already undid and show difference with previous...my changes are actually undone.

If I go to command line and run git status, it too shows me uncommitted changes.

Thoughts?

**Comment by shana** [comment]
@calloncampbell The git support in VS isn't a part of the GitHub Extension, it's maintained by Microsoft, so you should direct your feedback to them via the feedback tool in VS.
