### ISSUE TITLE
.net create a windows service

### ISSUE THREAD

**Issue by lichen19951127** [github/VisualStudio#2401]
I am using Visual Studio 2019 to create a windows service based on the .net framework. Add the installer. No display controls.

![image](https://user-images.githubusercontent.com/43132899/61258513-bc7a8080-a7a8-11e9-8326-14d7b1c4fe4a.png)

![image](https://user-images.githubusercontent.com/43132899/61258518-c1d7cb00-a7a8-11e9-95b9-3fc1cc8d2d8a.png)

![image](https://user-images.githubusercontent.com/43132899/61258519-c603e880-a7a8-11e9-9d88-5d41317cec16.png)

**Comment by StanleyGoldman** [comment]
This project is for the GitHub Extension for Visual Studio.

[How to report a problem with Visual Studio or Visual Studio Installer](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
