### ISSUE TITLE
Create a new MasterDetailsPage in xamarin project does not work .

### ISSUE THREAD

**Issue by luczha** [github/VisualStudio#2402]
## Versions
 - GitHub Extension for Visual Studio version: ...
 - Visual Studio version: ...VS for windows 

## What happened

When I add a new MasterDetailPage in Xamarin project . The name of new classes wrong by doubling up the last section. For example "MasterDetailPageMainMenuItemMenuItem" instead of "MasterDetailPageMainMenuItem", and "MasterDetailPageMainMasterMaster" instead of "MasterDetailPageMainMaster". Same with the Detail page.

This issue only appears on VS for windows .On mac it works fine .

**Comment by StanleyGoldman** [comment]
This project is for the GitHub Extension for Visual Studio.

**Comment by StanleyGoldman** [comment]
[How to report a problem in Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019)
