### ISSUE TITLE
Question: GitHub Temporary location

### ISSUE THREAD

**Issue by Rajkumar28269** [github/VisualStudio#2412]
Question: What is the temporary location where the code changes are stored for different branches in github. I did create a new branch using visual studio github from local branch and did few changes to new branch. Unfortunately i deleted the folder and got the folder back from recycle bin and could not find the newly created branch.

**Comment by jcansdale** [comment]
This sounds like a Git question. Git stores everything in the `.git` folder. Try doing `git branch` and see if your branch is visible there. If it is, you can do `git checkout <branch-name>`.

Closing because this isn't a GitHub for Visual Studio specific issue.
