### ISSUE TITLE
Entity Framework 6.3 / .NET Core 3.0 migration commands not working

### ISSUE THREAD

**Issue by marchy** [github/VisualStudio#2415]
## Versions
 - Visual Studio version: 16.3.0 Preview 3.0

## What happened
The migrations command are not working for a .NET Core 3.0 / EF 6.3 project.
How are we supposed to upgrade to .NET Core 3.0?

This is a majorly blocking show-stopper.

### Steps to Reproduce
1. Go to Tools > NuGet Package Manager > Package Manager Console
2. Issue `get-migrations` command
3. Get error:
```
Project 'Libraries\World.NET.Data' targets framework '.NETStandard'. The Entity Framework Package Manager Console Tools don't support this framework.
```

### Expected behavior
The Package Manager 'get-migrations' command should list EF 6 migrations in project.

### Additional context
The project containing the EF 6 migrations & DbContext is updated to being a netstandard2.1 project and running on .NET Core 3.0 Preview 9 / EF 6.3 Preview 9 ('6.3.0-preview9-19423-04').

**Comment by jcansdale** [comment]
Hi @marchy, I'm afraid this is the GitHub for Visual Studio repository, not the repository for Visual Studio itself.
