### ISSUE TITLE
Validation Adornment persists after error is corrected

### ISSUE THREAD

**Issue by Haacked** [github/VisualStudio#242]
In the Repository Creation Dialog, if you specify a repository name and a path that points to an existing repository on disk, we mark the Repository name as being in error and you can see the Create button is disabled.

<img src="https://cloud.githubusercontent.com/assets/19977/7308792/4bbdd98a-e9cc-11e4-9a7d-7b43033bb4da.png" width="365" />

If instead of changing the repository name, we change the Local Path, you can see that the button becomes enabled because we corrected the error, but the adornment remains on the repository name field because we haven't changed it.

<img src="https://cloud.githubusercontent.com/assets/19977/7308791/4bbd218e-e9cc-11e4-9e41-19313c5a0a2d.png" width="365" />

**Comment by shana** [comment]
Fixed in #285 (and why the heck wasn't this closed automatically when that one was merged??)
