### ISSUE TITLE
Allow multiple accounts

### ISSUE THREAD

**Issue by dotMorten** [github/VisualStudio#2425]
We use both GitHub Enterprise for internal development, as well as Github.com for Open Source work, but currently you can only be signed in with one account.
Please add support signing in to both enterprise and github.

**Comment by jcansdale** [comment]
@dotMorten 👋 

You should be able to sign in to GitHub Enterprise and Github.com at the some time.

On the clone dialog, can you see and change between the `GitHub.com` and `Enterprise` tabs?

![image](https://user-images.githubusercontent.com/11719160/66813095-0c91ec00-ef2c-11e9-935b-ffcedb002fc0.png)

Could you elaborate a little on the steps to reproduce this?

**Comment by jcansdale** [comment]
This should be working See https://github.com/github/VisualStudio/issues/2425#issuecomment-542095176.
