### ISSUE TITLE
Add option to the Create Repository dialog to add a README

### ISSUE THREAD

**Issue by Haacked** [github/VisualStudio#243]
In the create repository dialog,

<img src="https://cloud.githubusercontent.com/assets/19977/13961393/a53943ba-f019-11e5-9682-8089c4d8dff9.png" width="420" />

We should have a checkbox to add a README like we do on github.com. /cc @pmn for thoughts. @donokuda for design.

**Comment by paladique** [comment]
Will need to check if creating READMEs is implemented in Octokit.net first!

**Comment by Haacked** [comment]
Good news, it does! :tada: 

When you call `CreateRepository` just make sure to set [`AutoInit`](https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Request/NewRepository.cs#L28) to `true` on the `NewRepository` object.

**Comment by donokuda** [comment]
I created a GitHub repo with Visual Studio and it added a README automatically. Is this more about making the README creation optional?

**Comment by pmn** [comment]
> We should have a checkbox to add a README like we do on github.com

Sorry I missed the ping on this one, @Haacked. :100: to creating a README. 

@donokuda, @shana and I just walked through the repository creation process to verify when README.md is being created automatically (it happens when the repository is created by clicking the "Create" button from the GitHub pane). 

We also talked a little bit about creating the README automatically as well, in order to encourage best-practices when working with projects on GitHub. Thoughts about that?

**Comment by Haacked** [comment]
> We also talked a little bit about creating the README automatically as well, in order to encourage best-practices when working with projects on GitHub. Thoughts about that?

I'm a little confused. In the previous paragraph you said we already create the README automatically.

**Comment by shana** [comment]
@Haacked Meaning just always doing it automatically and not letting the user have the option of not creating one.

**Comment by Haacked** [comment]
> @Haacked Meaning just always doing it automatically and not letting the user have the option of not creating one.

Oh, I'm cool with that. I remember now that after you create the Repo, we clone it. So we need an initial commit or things just get weird.

**Comment by shana** [comment]
So I guess we leave the dialog as-is, since it's already creating the README and we really want it always created - both to make sure we always have content for the first commit (in case the user doesn't want a .gitignore or a license), and to encourage best practices. Closing this one out!
