### ISSUE TITLE
"Release Notes" Link for Extension leads to web page that has not been updated since May 2019

### ISSUE THREAD

**Issue by jefmes** [github/VisualStudio#2440]
## Versions
 - GitHub Extension for Visual Studio version: 2.10.7.8114
 - Visual Studio version: VS Pro 2017 version 15.9.17

## What happened
Received the extension update available flag in Visual Studio, saw that it was, "An update to 'GitHub Extension for Visual Studio' is available"".  Clicked extension to see what was new, then clicked on "Release Notes" in the "Extension and Updates" tool. Link took me to https://visualstudio.github.com/release-notes.html which looks to be the right place, but the last entry is v2.9.1.

### Steps to Reproduce
1. Go to Tools in Visual Studio, and click "Extensions and Update"
2. Find "GitHub Extension for Visual Studio" extension.
3. Click on "Release Notes" in the detail pane for extension.
4. Browser opens to https://visualstudio.github.com/release-notes.html
5. See that version listed is not version you are currently running.

### Expected behavior
Release notes should be updated when a new version is made available? :)

### Additional context
Submitting to check if someone has simply been forgetting to add the Release notes, or if the release notes have been moved to a new location, the URL in the extension should be updated.

**Comment by jefmes** [comment]
Editing my horrible typos.

**Comment by jcansdale** [comment]
@jefmes thanks for the heads up!

You're right this page is no longer being updated. I'm going to point at the GitHub releases page instead.
