### ISSUE TITLE
"Create" Button doesn't work And dotnet crashed in MacOS 10.15.2 (19C57)

### ISSUE THREAD

**Issue by qxchen6** [github/VisualStudio#2452]
# problem 1 ( about Visual Studio IDE )
## Versions
 - Visual Studio version: 8.3.11(build 1)
- Mac OS X 10.15.2 (19C57)
- runtime and sdks are

![image](https://user-images.githubusercontent.com/25380801/71539478-750f3780-2977-11ea-90a7-11af1b4b0b3c.png)

## What happened

cannot create a new project .

### Steps to Reproduce
steps are
new -> .NET Core -> Application -> Api(C #) -> select .NET Core 3.1 -> give a project name -> create button is available but giving no response when being clicked

### Screenshots

![image](https://user-images.githubusercontent.com/25380801/71539423-edc1c400-2976-11ea-9702-d78fe61d32a6.png)

no feedback when i click the blue button "创建" , which means "create" .

# problem  2 (about dotnet sdk or runtime)

because of problem 1 . I try to start a project using [Rider](https://www.jetbrains.com/rider/) with configs below .

![image](https://user-images.githubusercontent.com/25380801/71539520-15655c00-2978-11ea-9a50-c8bac3b34443.png)

it works . I successfully created a new Project with`WeatherForecast` module .

But  , When i try to run this project , it crash down .

so I try to run in debugger mode .

build succeed . Chrome is opened automatically . but the project went to A Exception .

![image](https://user-images.githubusercontent.com/25380801/71539550-a76d6480-2978-11ea-8943-a1fd30ae2744.png)

I'm very sure that the port 5001 is not in used before build .
i `lsof` the port . only the chrome using the 5001 . opened by building process .
Then I close the chrome browser and click `Resume` in Rider and I got `dotnet` crashed unexpectedly .

![image](https://user-images.githubusercontent.com/25380801/71539569-2cf11480-2979-11ea-8195-ae36420d22dd.png)

the Chinese words in white window means ,
"dotnet" crashed
press "reopen" to open again . click "report" to see more information or report to Apple .
[ignore] [report...] [reopen]

here is a the part of apple application crash logs .

```
Process:               dotnet [6366]
Path:                  /usr/local/share/dotnet/dotnet
Identifier:            dotnet
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        mono-sgen [6361]
Responsible:           rider [4624]
User ID:               501

Date/Time:             2019-12-28 13:50:11.753 +0800
OS Version:            Mac OS X 10.15.2 (19C57)
Report Version:        12
Bridge OS Version:     4.2 (17P2551)
Anonymous UUID:        28F14997-B7ED-72A3-E73A-9EB0F8055038

Sleep/Wake UUID:       498C5909-BAE4-479B-9AA2-D26968C351DC

Time Awake Since Boot: 19000 seconds
Time Since Wake:       9000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff656aa7fa __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff65767bc1 pthread_kill + 432
2   libsystem_c.dylib             	0x00007fff65631a1c abort + 120
3   libcoreclr.dylib              	0x0000000102f810e9 PROCAbort + 25
4   libcoreclr.dylib              	0x0000000102f81032 PROCEndProcess(void*, unsigned int, int) + 226
5   libcoreclr.dylib              	0x0000000103264e9d UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*) + 893
6   libcoreclr.dylib              	0x0000000103264f25 DispatchManagedException(PAL_SEHException&, bool) + 133
7   libcoreclr.dylib              	0x00000001031c855e IL_Throw(Object*) + 750
... ...
```

**Comment by jcansdale** [comment]
Hello 👋 

I think this is what you were looking for:
https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019
