### ISSUE TITLE
EMPTY CODE

### ISSUE THREAD

**Issue by ndekere254** [github/VisualStudio#2453]
Visual studio is pushing empty Cpp file to my github repository! Tried debugging but I couldn't find the problem. 

[This file](https://github.com/ndekere254/MySecondGame/blob/master/index.cpp)  should be 
containing some code as my local repository. Instead, it is blank! I pushed the entire project to github
using visual studio.

Please help.

**Comment by jcansdale** [comment]
I don't think this is a GitHub for Visual Studio issue.

You can use this to report an issue with Visual Studio:
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019
