### ISSUE TITLE
Push failed when update GitHub workflow file

### ISSUE THREAD

**Issue by hoffe86** [github/VisualStudio#2455]
## Versions
 - GitHub Extension for Visual Studio version: 2.10.8.8132
 - Visual Studio version: VS 2019 ENT (16.4.2)

## What happened
When I try to updated a GitHub workflow file (yaml file) the push will fail with following error:

Error encountered while pushing to the remote repository: rejected features/cicd -> features/cicd (refusing to allow an OAuth App to create or update workflow `.github/workflows/main.yml` without `workflow` scope)

### Steps to Reproduce
1. Modify GitHub workflow file in a non master branch
2. Push changes to repository

### Expected behavior
Visual Studio Github extensions has enough rights to create or update a workflow

### Logs
Error encountered while pushing to the remote repository: rejected features/cicd -> features/cicd (refusing to allow an OAuth App to create or update workflow `.github/workflows/main.yml` without `workflow` scope)

### Additional context
N/A

**Comment by JakenVeina** [comment]
Seconding this issue.

This issue is referenced ]here](https://github.community/t5/GitHub-Actions/Refusing-to-allow-an-integration-to-create-or-update/td-p/32472). It seems that the application simply needs to be updated to request use of the `workflow` scope when it requests tokens.

**Comment by RehanSaeed** [comment]
I mainly use VS + Windows Terminal to perform git operations. It's been weeks now and this issue is still very annoying. Would be nice to get some sort of ETA.

**Comment by jcansdale** [comment]
@RehanSaeed any chance you could open a ticket here:
https://support.github.com/contact

I now work in developer support rather than on this extension. If you open a ticket, I'll be able to track it there and hopefully get it fixed!

Please mention @jcansdale so it will be routed to me. 😄

**Comment by RehanSaeed** [comment]
@jcansdale Done

**Comment by jcansdale** [comment]
Hey folks 👋  could you try installing the `vsix/GitHub.VisualStudio.vsix` artifact from here:
https://github-editor-tools.visualstudio.com/VisualStudio/_build/results?buildId=2246&view=artifacts&type=publishedArtifacts

This should request the `workflow` scope when authenticating. After installing it, you can re-authenticate by clicking on `Add/Change Accounts`:

![image](https://user-images.githubusercontent.com/11719160/74882848-bca6b400-5367-11ea-9940-268a310dc29f.png)

Please let me know how you get on!

**Comment by RehanSaeed** [comment]
If I install this version, will it continue to receive updates?

**Comment by jcansdale** [comment]
@RehanSaeed you will. This version should simply be ahead of any new releases.

**Comment by seanke** [comment]
I'm still getting the same error.

**Comment by jcansdale** [comment]
@seanke have you re-authenticated using a recent version of GitHub for VS? That _should_ fix the issue.

**Comment by seanke** [comment]
> @seanke have you re-authenticated using a recent version of GitHub for VS? That _should_ fix the issue.

Thanks, I deleted the Visual Studio Application from my github settings and that did the trick.

**Comment by bakaufman** [comment]
> > @seanke have you re-authenticated using a recent version of GitHub for VS? That _should_ fix the issue.
> 
> Thanks, I deleted the Visual Studio Application from my github settings and that did the trick.

What does this mean?

**Comment by seanke** [comment]
@bakaufman I needed to remove Visual Studio from here https://github.com/settings/applications

**Comment by bakaufman** [comment]
Literally “visual studio” or "Github for VSCode”?

**Comment by seanke** [comment]
@bakaufman I believe it was 'Visual Studio'.

**Comment by jcansdale** [comment]
@seanke I didn't know this was possible!

I'm guessing it was the `Revoke access` button on this page that you clicked?
https://github.com/settings/connections/applications/a200baed193bb2088a6e

Did this force a fresh login next time you went to use GitHub for VS?

**Comment by seanke** [comment]
@jcansdale Yes, that's the one. Yes it forced a fresh login.

**Comment by maxnis** [comment]
Revoke access for VS Code in Github applications helped fixing this issue.
