### ISSUE TITLE
Zoom sync function for de-attached windows

### ISSUE THREAD

**Issue by tomfrenzel** [github/VisualStudio#2456]
### Problem
If I drag an open File to my second screen which is only 13" and zoom in so the code easier to see, the main Window on my 27" screen also zooms in which results in the code being displayed way too big.

### Solution/Feature
It would be nice having the possibility to zoom in to a de-attached window without the zoom factor being applied to the main window. A switch located somewhere at the bottom of VS that enables/disables the "zoom sync" function might be the solution for that.

**Comment by jcansdale** [comment]
Hello,

This repository is GitHub for Visual Studio, not Visual Studio itself. 😄
