### ISSUE TITLE
Indefinite downloading of IntelliSense - why?

### ISSUE THREAD

**Issue by WrongBit** [github/VisualStudio#2457]
On the VS 2019 (16.4.2) I permanently see annoying ANIMATED ICON with background tasks. And the last task "Downloading IntelliSense index for nuget.org" never finishes, forcing me to switch attention to that icon.

1. I don't need your animation. Please don't make VS "fancy" and **always** make settings "Switch animation OFF" if you make so questionable "improvements". Yes, they are NOT "improvements" for everybody!
2. You deploy buggy code which never stops "downloading", but even worse: you don't offer any ability to STOP this background task!

So you have to debug your "IntelliSense downloading" AND give ability to stop background task AND ability to switch animations OFF. Our attention is in code, we don't want to be disturbed with all those "notifications", "animations", etc.

Thanks!

**Comment by jcansdale** [comment]
Hello,

This repository is GitHub for Visual Studio, not Visual Studio itself.

You can report Visual Studio issues here:
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019
