### ISSUE TITLE
ionic plugin issue

### ISSUE THREAD

**Issue by Reham98** [github/VisualStudio#2464]
hello all ,

acually I'm using  Visual Studio Code 2019 to develop an ionic application.Actually i want to link my app to a PDF file so I have to install sveral plugin such as file opener , file , file transfer , document viewer. well while installing those plugin in cmd I'm getting npm warn and after that when I'm importing file , filetarnsfer , fileopener and documentviewer and adding them o the providers in app module.ts I'm getting errors 'type FileOrginal not assignable to the type provider'.I'm getting this comment for filetrasfer and documentViewer as well. please help me i do not know how to fix this problem , and yaa I have re install the all the plugin more than once and i have add '/ngx' while importing them as well.

![issue1](https://user-images.githubusercontent.com/61291000/75040280-3b3a4900-546f-11ea-906a-516f6c46f89d.PNG)
![issue2](https://user-images.githubusercontent.com/61291000/75040292-41c8c080-546f-11ea-8b98-973d82b1b17f.PNG)

**Comment by jcansdale** [comment]
Hello 👋 

I think this is the repository you're looking for:
https://github.com/microsoft/vscode/issues
