### ISSUE TITLE
"extension/package.json" missing?

### ISSUE THREAD

**Issue by HerBenSte** [github/VisualStudio#2466]
### package.json missing in .vsix file

**I downloaded this extension from here:** [Marketplace - Visual Studio](https://marketplace.visualstudio.com/items?itemName=GitHub.GitHubExtensionforVisualStudio&ssr=false#review-details)
and tried to install the VSIX but it's not working because.

> extension/package.json was not found in ZIP

**See:**
https://i.imgur.com/ZerEoHD.png
(_That's the error message I get._)

**Why do I not found this extension inside VSCode Extension Store?**
Like I can find this extension from you: [GitHub Pull Requests](https://github.com/Microsoft/vscode-pull-request-github)

```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Datum: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
Betriebssystem: Windows_NT x64 10.0.18362
```

**Comment by jcansdale** [comment]
I think this is the extension you're looking for. 😄 
https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

**Comment by HerBenSte** [comment]
Nevermind it's a VS not a VSCode plugin...
My bad.
