### ISSUE TITLE
Visual studio github profile trouble

### ISSUE THREAD

**Issue by v4a26** [github/VisualStudio#247]
I do not understand something. When I send a commit from VS community that commit looks as if it sent someone with an invalid account with my name (in VS). Changing the name in VS creates a new account.

Of course, I connected to the same account in VS with which I write here. 
![default](https://cloud.githubusercontent.com/assets/9762164/14084191/4a44818c-f522-11e5-9535-a4a07b848b5c.PNG)
All commits at the image is mine.

Am I doing something wrong? Or is it the way it should be?

**Comment by shiftkey** [comment]
@v4a26 my psychic debugger suspects you're using a different email address under your Global Git Settings to what's set in your GitHub account.

You can associate [multiple email addresses](https://help.github.com/articles/adding-an-email-address-to-your-github-account/) with your GitHub account, and then everything should work.
