### ISSUE TITLE
Remote not added when creating multiple repositories

### ISSUE THREAD

**Issue by mponce1** [github/VisualStudio#248]
Steps to reproduce:
1. Open visual studio and click team explorer
2. Home > Projects > Manage connections
3. Local Git Repositories > New > Create new repository 
4. Publish repository: Double-click new repository > Sync > Publish to GitHub > Get Started > Publish 
5. Repeat steps 1-4 with a new repository 

Expected result: Users are unrestricted to the amount of repositories they create locally and publishing. 
Actual result: Creating multiple repositories on the same instance causes remote to not get added to repository settings.

**Comment by grokys** [comment]
Tried this and can't reproduce, so I assume it's fixed.
