### ISSUE TITLE
Field 'timeline' doesn't exist on type 'PullRequest'

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#2481]
Reported by @parto:

> @jcansdale it has another problem though when trying to open a PR: 
<img width="680" alt="Screen Shot 2020-03-17 at 12 59 52 PM" src="https://user-images.githubusercontent.com/2138860/76896558-45255100-684f-11ea-9151-d91f81572fc1.png">

### Notes

Here is the problem code:
https://github.com/github/VisualStudio/blob/f3f8dee8f3a4af561f30a78e89f0dd8c87b57f7a/src/GitHub.InlineReviews/Services/PullRequestSessionService.cs#L387

See discussion here:
https://github.slack.com/archives/C44NVGUBB/p1584477659296100

@xuorig said:
> We're going to be reverting that change for now while we investigate who got affected. But the field will go away soon again!

@nplasterer said:
> the new timelineItems allows you to filter for just the events that you want
> so you can say give me just the pr comments for the timeline

```
timelineItems(first: 20, itemTypes: [ISSUE_COMMENT]) 
```

I'll let people know when it has been changed to use `timelineItems`!

**Comment by brvaland** [comment]
I have updated to latest version (2.11.96.24460) and getting know getting an error `Field 'timelineItems` doesn't exist on type 'PullRequest'
