### ISSUE TITLE
git-client protocol stays after uninstalling

### ISSUE THREAD

**Issue by stefnotch** [github/VisualStudio#2487]
## Versions
 - GitHub Extension for Visual Studio version: 2.10.8.8121 
 - Visual Studio version: 16.5.1

## What happened
I uninstalled the GitHub for Visual Studio extension, but the `Open in Visual Studio` button when cloning a repository is still visible.

![image](https://user-images.githubusercontent.com/10220080/77829879-25cad580-7125-11ea-9267-0f4ad72b57a4.png)

### Steps to Reproduce
1. Install GitHub for Visual Studio
2. Uninstall GitHub for Visual Studio
3. Open a browser
4. Make sure to clear the browser caches
5. Open a GitHub repository in the browser
6. Click on `Clone or download`
7. The `Open in Visual Studio` button is still there

### Expected behavior
I expected the button to be gone. The GitHub extension is gone after all

**Comment by jcansdale** [comment]
@stefnotch,

This feature is actually part of Team Explorer and is unrelated to GitHub for Visual Studio. We would have loved to improve how this works, but unfortunately we don't control the protocol handler and how it's implemented.

Thanks for reporting this. I'm going to close as can't fix. 😢
