### ISSUE TITLE
Retrive DbContext and Model types ofr existing blazor project in VisualStudio Extensions Project

### ISSUE THREAD

**Issue by kalirajanganesan** [github/VisualStudio#2490]
We are developing VisualStudio Extensions for Blazor Project we have to get the ModelTypes and DbContexts which was existing in that Blazor Project in Visual Studio Extensions Project(VSIX Project)

We already try below code in Scaffolding Project and can able to get the  list of Db Context and Model Type

```
ICodeTypeService codeTypeService = (ICodeTypeService)Context
                    .ServiceProvider.GetService(typeof(ICodeTypeService));
var Dbcontexts = codeTypeService.GetAllCodeTypes(Context.ActiveProject)
                        .Where(codeType => codeType.IsValidWebProjectEntityType())
                       .Select(codeType => new ModelType(codeType));

```

We can try to get like same but we can't get that ICodeType service was return as null. Could you please suggest any alternative way to get that?

```
IServiceProvider serviceProvider = (IServiceProvider)this;
            DTE dte = (DTE)serviceProvider.GetService(typeof(DTE));
            Project project = dte.ActiveDocument.ActiveWindow.Project;
            CodeGenerationContext Context = new CodeGenerationContext(project, dte.ActiveDocument.ProjectItem, serviceProvider);

            ICodeTypeService codeTypeService = (ICodeTypeService)Context
                    .ServiceProvider.GetService(typeof(ICodeTypeService));
```

**Comment by jcansdale** [comment]
This is the repo for the GitHub for Visual Studio extension, not general VS. 😉 

I'd recommend you ask about this here:
https://gitter.im/Microsoft/extendvs
