### ISSUE TITLE
Duplicate "Pull Requests" button in visual studio tool

### ISSUE THREAD

**Issue by orbitbyrd** [github/VisualStudio#2494]
Check the image below. Note the duplicate "Pull Requests" button. 
![DuplicatePullRequests](https://user-images.githubusercontent.com/63358824/78814173-15b3c100-7983-11ea-8b59-83a361769fc6.PNG)

**Comment by jcansdale** [comment]
@orbitbyrd ,

> Check the image below. Note the duplicate "Pull Requests" button.

One of them is part of Visual Studio and is non-functional AFAIK. 😢

I've heard it will be going away soon. 🤞
