### ISSUE TITLE
Make bug report easier!

### ISSUE THREAD

**Issue by peni4142** [github/VisualStudio#2495]
Is your feature request related to a problem? Please describe.
I have an error but I am too lazy to report that because I can't copy that in Visual Studio message from a message box.
Why the heck I can not copy an error message?

Describe the solution you'd like
Make the messages in message boxes of Visual Studio copyable.

**Comment by jcansdale** [comment]
I think you can copy/paste from default Windows dialog boxes (which isn't exactly very discoverable). I've forever copying dialog boxes, pasting into notepad and extracting the information I need (often a URL).

BTW, this is the GitHub for Visual Studio repo not general Visual Studio. In hindsight we should have named the repo differently. 😉
