### ISSUE TITLE
Checkout a specific commit

### ISSUE THREAD

**Issue by MintPlayer** [github/VisualStudio#2499]
**Provide a more straightforward way to checkout a specific commit from the past**
If at some point a bug has been introduced in my application, I want to revert to a previous state in my master/release branch to track the bug. But...

It appears that Git for VS (Team Explorer -> [branch] -> View History) does not have an options menu to checkout a specific commit.

**Current method**
The only way I can think of now to checkout a commit from the past is by
- Right clicking the commit
- View Details
- Copy the commit ID
- Open a console in your repo-folder
- git checkout [commit-id]

**Current method 2**
- Create a tag on the commit
- Home
- Tags
- Checkout the tag

If a bug is introduced than you have to checkout one commit after another. Checking out commits like this would be a tedious work.

**Describe the solution you'd like**
Add a context-menu item to checkout a specific commit from a branch's history.

(Keeping in mind that the repository is in a detached state after this)

![image](https://user-images.githubusercontent.com/48772716/79839834-6381ed80-83b5-11ea-9420-30d3802d01d6.png)

**Similar issues**
There already are requests like this, but they aren't conclusive.
- https://github.com/microsoft/vscode/issues/55086 (VS Code)
- https://github.com/eamodio/vscode-gitlens/issues/463 (VS Code)
- https://developercommunity.visualstudio.com/idea/648233/i-want-to-be-able-to-git-checkout-an-old-commit-fr.html (Visual Studio)

**Comment by olifantix** [comment]
The function you are looking for is:   
* Reset + Delete Changes (--hard)
or 
* New Branch ...   and give it a new name, it will be based on that revision.

**Comment by keithalewis** [comment]
Why create a new branch instead of calling git checkout? This seems like a nonintuitive workaround instead of making a standard git command available in the UI.

**Comment by olifantix** [comment]
> Why create a new branch instead of calling git checkout? This seems like a nonintuitive workaround instead of making a standard git command available in the UI.

>> If at some point a bug has been introduced in my application, I want to revert to a previous state in my master/release branch to track the bug.

If you have a bug and want to track/handle it, you should create a new bugfix branch. The UI can do that ("New branch..."). If you just want to roll back to that ref, the UI can do that: ("Reset hard...") - I do not see why either would be a "nonintuitive workaround".

**Comment by keithalewis** [comment]
git checkout <rev>
...copy a chunk of code no longer in master...
git checkout master
...paste it back in...
I don't want to create a branch and I don't want to reset, just peek at an older revision.
Why not expose checkout in the UI?

**Comment by EmilAlipiev** [comment]
@olifantix I have a case now there is bug in my latest commit but I don't know which recent commit caused this bug. I went to 10 commit earlier with your suggestion using new branch reset and found out that 10 commit before it was working. Now i have to find out which of those 9 commits in between caused this error. I have to do 9 times a new branch and reset if use VS2019. 
It may sound for you can you just now find through the file but when code base is too big and there can be many factors causing this bug and if i cannot simply found out and this is the only way. 
A simple checkout can save my time dramatically.

**Comment by GF-Huang** [comment]
We need checkout a tag, not reset.

**Comment by firehorseuk** [comment]
I've got about 30 commits since I've to re-examine this bit of code that was working fine before. But somewhere along the way it's now not behaving as it should. Would be great to have checkout a commit. It would save me having to use something else.

**Comment by willemgons** [comment]
Just ran into this - again!

**Comment by jweschenfelder** [comment]
I would love to have this feature, too.

**Comment by feland207** [comment]
I also would love to have this feature in vs code. 
My current workaround was: 
1. open a terminal console 
2. run git log to find the commit-id
3. copy id of the commit I want to checkout 
4. Do git checkout <commit-id>

**Comment by fededim** [comment]
Is it possibile to reopen this issue and reconsider it ?

**Comment by lucaspsilveira** [comment]
I would like to see this issue resolved too

**Comment by arctouch-sergeymetlov** [comment]
That seems to be a very basic feature to have. Can we reopen the request please?

**Comment by awhig** [comment]
This is sorely needed

**Comment by Camenwolf** [comment]
Please add this.

**Comment by HappyNomad** [comment]
This issue was closed without explanation.  I'm not sure how this repo works, but seems odd that it was closed by a non-Microsoft person.  Can someone reopen it?  Otherwise, how about we create a new issue?

**Comment by pjmlp** [comment]
It will be coming on the next Visual Studio release, https://developercommunity.visualstudio.com/t/i-want-to-be-able-to-git-checkout-an-old-commit-fr/648233

As side note, for this kind of issues the Developer Community is a better place to complain.

**Comment by kabua** [comment]
@olifantix you wrote "I do not see why either would be a "nonintuitive workaround". How would do it using checkout instead?"

The fact that several other developers and I had to come to this page looking for answers clear states this is **not** a `nonintuitive workaround`
