### ISSUE TITLE
Visual Studio Code automatically adds Https to my URL

### ISSUE THREAD

**Issue by tal19987** [github/VisualStudio#2501]
## Technical details
OS: Ubuntu 18.04
VSC: latest version

## What happened
I'm trying to configure VSC to integrate with my Jenkins server.
I downloaded the extension 'Jenkins Status'.
I created a file called- '.jenkins' in my root directory so i can configure my URL, Username, Password. When I save the file, i get a pop-up saying that the URL: https://http://(jenkins-aws-dns) doesn's exists.
My Jenkins server is working on HTTP protocols.
How can i remove the default https at the beginning? This is really frustrating 

### Expected behavior
Would work without https because i didn't type it

### Screenshots

![image](https://user-images.githubusercontent.com/58375349/79925265-a342e680-8442-11ea-85da-79b5c2dfee01.png)

![image](https://user-images.githubusercontent.com/58375349/79925280-ae961200-8442-11ea-9353-7dc9d625b11a.png)

**Comment by jcansdale** [comment]
I think this is a VS rather than GitHub for VS issue. Closing.
