### ISSUE TITLE
GitHub "Pull Requests" button is confusing by being very similar to the other one

### ISSUE THREAD

**Issue by liviriniu** [github/VisualStudio#2504]
## Versions
 - GitHub Extension for Visual Studio version: 2.11.96.24460 (probably typo on 2460)
 - Visual Studio version: Community 2019 v16.5.4

## What happened
Confusion about what each of the two identically named (and having the same tooltip) "Pull Requests" buttons is exactly for. A distinction is made only through their icons but this is not evident for all the users (especially beginners).
While I was connected only to `GitHub`, the other button (on the left - see screenshot below), who I understood later that it's for `Azure DevOps (TFS)` repositories, was not helping me at all understand what is it's purpose - only informed me of the fact that I'm not connected (where? Did not specified). Reconnecting to GitHub obviously changed nothing. I believed maybe the button on the left is also for GitHub but maybe I lack privileges or something to be able to use its associated view/page.

### Steps to Reproduce
1. Make sure in Visual Studio you are connected to `GitHub` but not connected to `Azure DevOps (TFS)`;
2. In the "Team Explorer" pane -> "Manage Connections" page: Select and open a cloned GitHub repository;
3. Go to the "Home" page of the "Team Explorer" pane;
4. See the two identically named (with the same tooltip) PR buttons in the "Project" section.
5. Also, click the left-side button (the one for `Azure DevOps (TFS)`) to open its page.
6. Observe the risk of confusion.

### Expected behavior
The button for GitHub pull requests to hint somehow better that it is for GitHub. (Microsoft / Visual Studio teams should clarify this as well with the other button, I think). The icon looks to me as a symbol for merge/pull request and nothing more.

### Screenshots
![buttons](https://user-images.githubusercontent.com/63544057/80502277-11bf0180-8979-11ea-8fb9-93dbba9d8e95.PNG)

### Additional context
**LE:** The counterpart report in Visual Studio Dev Community:
- https://developercommunity.visualstudio.com/content/problem/1010389/pull-requests-button-for-azure-devops-tfs-not-sugg.html

What I was able to find:
- https://developercommunity.visualstudio.com/content/problem/854944/visual-studio-is-displaying-2-buttons-for-pull-req.html
- https://developercommunity.visualstudio.com/content/problem/344645/pull-requests-in-visual-studio-you-are-not-connect.html

**Comment by jcansdale** [comment]
Thanks for opening the issue and the additional context. I've been in touch with the Visual Studio team and have been told this is going away in a future version. I agree it's confusing!

**Comment by jcansdale** [comment]
The duplicate Pull Requests button will be going away in a future version of VS. We just need to give it time!

Closing this issue.
