### ISSUE TITLE
Browser authentication not working - 'Authorize' button grayed out

### ISSUE THREAD

**Issue by GreenhazelStudio** [github/VisualStudio#2505]
## Versions
 - GitHub Extension for Visual Studio version: 2.11.96.24460
 - Visual Studio version: 2019 (16.5.4)

## What happened
When I attempt to sign in to GitHub with the Visual Studio extension it presents me one option: "Sign in with your browser".  When I click on it my browser opens to the following page...

https://github.com/login/oauth/authorize?client_id=blah&scope=blah&state=blah

... which displays big green button saying "Authorize github".  The problem is the button is grayed out.

### Steps to Reproduce
1. Click on the GitHub tab next to Solution Explorer
2. Click 'Sign in'
3. Click 'Sign in with your browser'
4. Web page opens with Authorize button disabled

### Expected behavior
The Authorize button I assume should be enabled.  And when I click it something should happen in Visual Studio.

### Screenshots
http://greenhazelstudio.com/images/github.png

### Additional info
I was unable to attach the screen shot due to being on a corporate network with policies and restrictions that seem to limit the functionality of this site.  Hence the URL.  Now that I mention it, my issue may be related to these company restrictions.

**Comment by jcansdale** [comment]
@GreenhazelStudio,

I've been told that the button is enabled with JavaScript as some king of security measure. If the browser is up to date, this issue is usually due to adblockers or some interfering extension. Would that make sense?

Please let me know how you get on!

**Comment by jcansdale** [comment]
I'm hoping this was an ad-blocker issue! Closing.

**Comment by SenzoNgele** [comment]
Lool after I struggled for years.. I have found a Solution to This
The course is. First I use my google chrome which I saved my Github account with.
So my VS was taking me to Microsoft Edge and get the button disabled.

All you have to do is to change you Default browser on your machine to the one u have signed is with on github

**Comment by mcmdothub** [comment]
Thank you very mutch "SenzoNgele" ....it worked.

**Comment by Zieu** [comment]
Just opened devtools and removed "disabled" attribute in html, and it worked!

**Comment by jdabenaza** [comment]
Try to copy the URL from your current browser to your other available browser and the button will be available to click.

**Comment by will-rebelo** [comment]
first i had to change the default browser to explorer, so it could redirect to github website.

then the authoryzed button was disabled, so had to paste the url into firefox (browser that i used to create the account)

**Comment by deepandra-singh** [comment]
Try to open in different browser - it worked for me.

**Comment by kkbear1985** [comment]
> Just opened devtools and removed "disabled" attribute in html, and it worked!

best solution ever

**Comment by broomfn** [comment]
+1 This is a pretty poor user experience and really should be fixed!

**Comment by broomfn** [comment]
I wasn't using IE or Edge, I was on Chrome, but it could have been that Fastly outage? Either way I'm sure there must be a better way to do this, to provide a better user experience than having to result to Chrome tools to remove the disable attribute.

**Comment by praneethrachumallu** [comment]
> Lool after I struggled for years.. I have found a Solution to This
> The course is. First I use my google chrome which I saved my Github account with.
> So my VS was taking me to Microsoft Edge and get the button disabled.
> 
> All you have to do is to change you Default browser on your machine to the one u have signed is with on github

What just happened :D  Thank you SenzoNgele

**Comment by adaam168** [comment]
> 
> 
> Lool after I struggled for years.. I have found a Solution to This The course is. First I use my google chrome which I saved my Github account with. So my VS was taking me to Microsoft Edge and get the button disabled.
> 
> All you have to do is to change you Default browser on your machine to the one u have signed is with on github

Thank you so much, I'm using mozilla firefox and it works well.

**Comment by harrybiddle** [comment]
Me too. Completely fresh install of Windows 10. Why is this issue closed?

Opening the developer tools and removing the disabled attribute worked for me. That's some pretty laughable UX, especially given that GitHub is now owned by Microsoft.

**Comment by jcansdale** [comment]
@harrybiddle which browser are you using?

**Comment by harrybiddle** [comment]
This was IE11 (more specifically, the [Windows testing VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)).

I would add though that this seems to have nothing to do with Visual Studio; it looks like an issue purely with github.com.

**Comment by tasnim0101** [comment]
> 

thank you sooo much you saved my life !!

**Comment by maya-devi-parameswaran** [comment]
> Lool after I struggled for years.. I have found a Solution to This The course is. First I use my google chrome which I saved my Github account with. So my VS was taking me to Microsoft Edge and get the button disabled.
> 
> All you have to do is to change you Default browser on your machine to the one u have signed is with on github
