### ISSUE TITLE
The new orange color of the commit message placeholder is distracting

### ISSUE THREAD

**Issue by detzt** [github/VisualStudio#2508]
**Is your feature request related to a problem? Please describe.**
The color of the commit message placeholder text ("Enter a commit message (required) or stash message (optional).") just changed to orange after an update. Maybe I can get used to it but it is currently quite distracting.

**Describe the solution you'd like**
Change the color back to the light gray it was before.

**Describe alternatives you've considered**
Not sure what to put here, but I already tried to configure the color in the VS settings and in the settings of the extension itself.

**Additional context**
VS is in the dark mode.

**Comment by jcansdale** [comment]
@detzt,

This is the repository for the GitHub for VS extension.

To report issues with VS itself, I'd suggest using:
https://developercommunity.visualstudio.com/content/problem/post.html?space=8

Good luck!
