### ISSUE TITLE
Unable to login with email on Dev15

### ISSUE THREAD

**Issue by mponce1** [github/VisualStudio#251]
Attempting to login with email on Dev15 produces following error in extension.log: 

`2016-03-28 17:06:10.4252|INFO|thread: 1|RepositoryHost|Log in from cache for login '(null)' to host 'https://api.github.com/' FAILED`

**Comment by mponce1** [comment]
No longer able to reproduce after 1.0.18.2

**Comment by shana** [comment]
Well that's just odd, I didn't change anything. :neutral_face:
