### ISSUE TITLE
Can't open files containing curly braces

### ISSUE THREAD

**Issue by michael-hawker** [github/VisualStudio#2510]
## Versions
 - GitHub Extension for Visual Studio version: 2.11.96.24460
 - Visual Studio version: 16.5.4

## What happened
Trying to open files from the GitHub PR explorer for [this PR](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3128). It contains files with curly braces `{}` which won't open in VS. Getting a `Error opening file: Input string was not in a correct format.` error.

### Steps to Reproduce
1. Open [PR](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3128) in GitHub extension.
2. Try to open any of the generic classes like `ArrayPoolBufferWriter{T}.cs`
3. See error in status bar
4. Note, if you pick another file (like the first one `AllocationMode.cs` it works fine, just fails on any file with curly brace).

### Expected behavior
File opens.

### Screenshots
![image](https://user-images.githubusercontent.com/24302614/81114395-d079a500-8ed6-11ea-99d2-4f672ae30fde.png)

**Comment by jcansdale** [comment]
Hi @michael-hawker 👋 

@davidwengier has kindly contributed a fix for this!

Could you try installing the artifact from this build and let us know if it works?
https://github.com/github/VisualStudio/pull/2512/checks?check_run_id=653837445

Thanks!
