### ISSUE TITLE
Github for Visual Studio failed to get online. In team explorer, it shows Sign out link in github section, but also shows Offline.

### ISSUE THREAD

**Issue by alberthe** [github/VisualStudio#2511]
## Versions
 - GitHub Extension for Visual Studio version: 2.11.96.24460
 - Visual Studio version: Professional 2019

## What happened
Github for Visual Studio failed to get online. 
In team explorer, it shows Sign out link in github section, but also shows Offline.

### Steps to Reproduce
1. Go to 'Connect'
2. Click on 'Connect To GitHub'
3. Click on Sign in with your browser under GitHub
4. Sign in success in browser, Team Explorer shows Sign out under GitHub section.
5. Connect section still shows Offline.
6. Actually, it is offline. All function links are grey out.

### Expected behavior
Expect to be online

### Screenshots
![connection](https://user-images.githubusercontent.com/6936044/81248272-f774cb80-8fe9-11ea-8224-e6d8cfb2b28f.png)
![synchronizaiton](https://user-images.githubusercontent.com/6936044/81248276-f93e8f00-8fe9-11ea-8fb9-83fccc5026dc.png)

### Logs
email sent.

### Additional context
n/a

**Comment by jcansdale** [comment]
Is this still happening? I couldn't sign in for a while last night. Hopefully it's a temporary thing!

**Comment by jcansdale** [comment]
Hoping this was just a temporary thing! Closing...

**Comment by alberthe** [comment]
Thanks, I recreated local repository then back to normal.
