### ISSUE TITLE
refusing to allow an OAuth App to create or update workflow `.github/workflows/greetings.yml` without `workflow` scope

### ISSUE THREAD

**Issue by isdanni** [github/VisualStudio#2516]
## Versions
Version: 1.45.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-99-generic

## What happened

Try to push a pull request but received the following error(The changed file is NOT related to yaml files at all):
```
 ! [remote rejected] HEAD -> gui_new (refusing to allow an OAuth App to create or update workflow `.github/workflows/greetings.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/isdanni/..."
```

### Steps to Reproduce
1. Change any files in a new branch;
2. Try push with `git push origin HEAD`;

### Expected behavior

`git push origin HEAD` should be working fine (as many times before)

### So far I tried

1. Referred to this issue #2455 , I tried to uninstall & install GitHub extensions;
2. Regenerating personal access token in developer settings and add it to VSCode config;

I know this is the auth issue but do not know how to resolve it other than steps I tried above, please let me know if you have any suggestions, thanks!

**Comment by isdanni** [comment]
Refer to issue #2455

**Comment by jcansdale** [comment]
@isdanni could you make sure you're using the lates version of GitHub for Visual Studio and then re-authenticate? You can do this using Team Explorer > Connections a then Connect to Github.

I hope that helps!

**Comment by isdanni** [comment]
> @isdanni could you make sure you're using the lates version of GitHub for Visual Studio and then re-authenticate? You can do this using Team Explorer > Connections a then Connect to Github.
> 
> I hope that helps!

@jcansdale Thank you for such quick response! Yes, it is the latest version. I just tried to purge `vscode` entirely from the system including `~/.config/Code` and installed it from snap again. And this time it worked like a charm. Closing the issue now ;-)
