### ISSUE TITLE
vscode installing from vsix gives error

### ISSUE THREAD

**Issue by hawkeye64** [github/VisualStudio#2517]
## Versions
 - GitHub Extension for Visual Studio version: v2.11.96
 - Visual Studio version: v1.45.1

## What happened

Installed downloaded GitHub.VisualStudio-v2.11.96.vsix inside VSCODE gives error

### Steps to Reproduce
1. In vscode, go to Extensions, then select "Install from VSIX..."
2. Select the "GitHub.VisualStudio-v2.11.96.vsix" that was downloaded from "https://marketplace.visualstudio.com/items?itemName=GitHub.GitHubExtensionforVisualStudio"
3. Immediately get error

### Expected behavior

The extension to install without error

### Screenshots

![image](https://user-images.githubusercontent.com/10262924/82832496-8140e780-9e78-11ea-8abc-c86d729914d7.png)

**Comment by jcansdale** [comment]
Hi @hawkeye64,

There are difference extensions for Visual Studio and VS Code. Here is the one for VS Code:
https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

Unfortunately their VSIX files are quite different and incompatible.

I hope that helps!

**Comment by hawkeye64** [comment]
@jcansdale I did not know that! Thanks for taking time to give me the proper link. :heart:

**Comment by jcansdale** [comment]
No problem, I'm glad that helped 😄
