### ISSUE TITLE
Error when creating a console project .

### ISSUE THREAD

**Issue by SAYAH-IMAD** [github/VisualStudio#2518]
Hello ,

Recently I downloaded the **.Net 5 SDK**, at the end of this installation when I tried to create a **Console Project .Net Core** I had an error.

Best Regards . 

**Error Message :** 

<img width="761" alt="error message" src="https://user-images.githubusercontent.com/27926843/83341433-638ddb00-a2db-11ea-85b3-dc83606e628e.png">

**Framework Target :** 

<img width="779" alt="framework target empty" src="https://user-images.githubusercontent.com/27926843/83341430-5a047300-a2db-11ea-9126-a5afba07e366.png">

**Framework Avaible :**
 
<img width="775" alt="framework avaible" src="https://user-images.githubusercontent.com/27926843/83341431-5c66cd00-a2db-11ea-90e3-af350252c8a2.png">

**VS Version :** 

<img width="575" alt="version VS" src="https://user-images.githubusercontent.com/27926843/83341432-61c41780-a2db-11ea-8d06-adb7a940fe31.png">

**.Net Version :** 

<img width="650" alt="dotnet version" src="https://user-images.githubusercontent.com/27926843/83341434-65f03500-a2db-11ea-925b-3e2e5bc5dd0d.png">

**Comment by jcansdale** [comment]
Hello,

This is the repository for the GitHub for Visual Studio extension.

I think this is the forum you're looking for! 😄 
https://developercommunity.visualstudio.com/spaces/8/index.html
