### ISSUE TITLE
Installer for VS Preview 15 Langpack exe ENU is displayed in spanish

### ISSUE THREAD

**Issue by surfmuggle** [github/VisualStudio#252]
Sorry if this does not belong here. 

If you go to [aka.ms/vsnext](https://www.visualstudio.com/downloads/visual-studio-next-downloads-vs) you will be redirected to a page that contains the `Visual Studio "15" Preview`. If you click on the link on the left `Visual Studio "15"` and then download the language pack `Visual Studio "15" Preview Language Pack` a file `vs_langpack.exe` is downloaded. 
Expected: executing this file shows a dialog in english
Actual: executing this file shows a dialog in spanish.

I canceled the installation because i assume that this file will install a spanish language pack instead of the english pack.

**Comment by shiftkey** [comment]
@surfmuggle sadly this isn't the right place, but I'm not sure where to send you.

Perhaps @shana or @haacked will know where to send that feedback so the team sees it.

**Comment by Haacked** [comment]
@acangialosi FYI^^^

**Comment by surfmuggle** [comment]
Since this is not the right place and only it is after all a preview i am closing my issue.
