### ISSUE TITLE
Two Pull Requests buttons are confusing

### ISSUE THREAD

**Issue by Alvin-Seville** [github/VisualStudio#2520]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/42812113/83374200-3c83f600-a40e-11ea-8cd8-aa0f5fa4fe63.png)

Two `Pull Requests` buttons are confusing. 

**Describe the solution you'd like**
Please remove one of them for instance and transfer existing functionality to another place. Or rename it.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by jcansdale** [comment]
Hi @Alvin-Seville,

The second button is a holdover from the `Team Explorer` tool window. It will be going away once `Team Explorer` has been replaced by the new `Git` tool window. You should find this in recent Visual Studio 2019 previews.

The 2nd `Pull Requests` button is annoying/non-functional. I wish they could have disabled it!
