### ISSUE TITLE
Creates remote repo under wrong GitHub account

### ISSUE THREAD

**Issue by allan-mobley-jr** [github/VisualStudio#2523]
## Versions
 - GitHub Extension for Visual Studio version: 2.11.104
 - Visual Studio version: 16.7.0 Preview 2.0

## What happened
Used GitHub dialog to push local git project to create a new repo under organization. Instead, GitHub extension created the new repo in my personal repo.

### Steps to Reproduce
1. Click "Get Started" button on GitHub extension
2. Fill out popup form, selecting organization as owner, not personal account
3. Verify the push path
4. Click "Push" button 
5. Find repo under personal account and not organization account

### Expected behavior
Expected to find it under organization account. I am owner and creator of both organization account and personal. Same login credentials. Never had this problem before with Visual Studio, although I admit it has been some time since I created a new repo from there. I mostly use vscode now, but the current project required Visual Studio.

### Screenshots
![vs-github-dialog](https://user-images.githubusercontent.com/38449003/84660727-46febf00-aee7-11ea-9ba0-4b835a901ec3.png)
![github](https://user-images.githubusercontent.com/38449003/84660728-47975580-aee7-11ea-8b51-98f62fbf4ad3.png)

**Comment by jcansdale** [comment]
Hey @daschult 👋  could you take a look at this one? ☝️

**Comment by daschult** [comment]
Hi Allan,

Sorry about this bug. We just committed a fix for this late last week, so the fix should appear in the next preview release of Visual Studio 16.7.

Sorry again!
