### ISSUE TITLE
GitHub for Visual Studio 2019 - 2/3 of project files deleted

### ISSUE THREAD

**Issue by jimmyhaggard** [github/VisualStudio#2524]
I use Windows 10 and Visual Studio 2019.

I decided to use the GitHub extension with Visual Studio 2019 to set up a local repository. I went through the process via the gui. I pushed all files from a Visual Studio WPF project folder to the local repository. The files consisted of forms and c# code.

When I checked the local repository activity history, only 1/3 of the project files were listed. I went to my main project location, and 2/3 of the files were gone. The only files in my main project folder were those that were listed in the github history. The local repository was on a different disk drive than the main project files. I checked the recycle bin, and the missing files were not there. I searched all local disk drives and the missing files were no where to be found.

While using the github extension for visual studio, at no time did I encounter any messages or prompts about disposing, deleting or removing any files. All I did was push the project files to a local repository.

As a result of using the Github extension for Visual Studio, 2/3 of my project files appear to have been permanently deleted (not sent to the recycle bin, but permanently erased).

The only good news is that I saved the entire project to a ZIP files and archived it about week ago. I was able to extract my project files, and it only set me back a week. However, it was a very productive week.

My conclusion is that there is a seriously bad bug in the github extension for Visual Studio.

Unless you can tell me where I can find my project files, I do not want to hear a word from anyone.

BTW, I will NOT attempt to recreate the issue, it already wiped out 2/3 of my projects files once and I have no intention of experiencing that again. What I will do is NEVER USE GITHUB again.

**Comment by BradleySewell** [comment]
I just had this exact same thing. First push with VS2019. Deleted my entire project.

**Comment by taurus228** [comment]
CBF50JOY

**Comment by Eskalante** [comment]
Just happened to me. New projekt, work of one day (about 13 hours) and gone, solution, project and code.

**Comment by DerekIHewitt** [comment]
Just happend to me. After going through a complex debugging extercise of a two week rush project, I decided it was time to keep the code safe so pushed to Git Hub. Just as the experience at the top of the thread - files removed from local disk and not in the repository either. To say I am unhappy would be an understatement. Yet this thread is just closed with no reponse. Never had thisproblem with SVN.

**Comment by mkaito** [comment]
Yeet yeet all your files are deleted. Closed with no response. Stay classy, Github ❤️

**Comment by cryptocomputingsystems** [comment]
Yeah I just lost a weeks work, thanks visual studio github integration.
