### ISSUE TITLE
GitHub extension installing error after reinstalling VS2019

### ISSUE THREAD

**Issue by jalu2112** [github/VisualStudio#2529]
## Versions
 - GitHub Extension for Visual Studio version: 2.11.104.25275
 - Visual Studio version: 2019

## What happened
I have reinstalled VS2019, now I am trying to reinstall the GitHub from within Visual Studio (Manage Extensions; I have also tried with a manual download https://visualstudio.github.com/). Everytime, I get an installation error with the log file below.

![image](https://user-images.githubusercontent.com/37363032/86889480-167ffe80-c0fc-11ea-928c-9a3652d163d7.png)

[dd_VSIXInstaller_20200708090939_49e8.log](https://github.com/github/VisualStudio/files/4889069/dd_VSIXInstaller_20200708090939_49e8.log)

Any suggestions where the error is?

**Comment by jcansdale** [comment]
@jalu2112,

```
7/8/2020 9:09:39 AM - -------------------------------------------
7/8/2020 9:09:39 AM - Microsoft VSIX Installer
7/8/2020 9:09:39 AM - -------------------------------------------
7/8/2020 9:09:40 AM - System.ComponentModel.Win32Exception (0x80004005): The call to DuplicateHandle failed
   at VSIXInstaller.UserImpersonationHelper.DuplicateSuppliedToken(IntPtr token, UInt32 callingProcessId)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Wow, I've never seen this before!

Could you try the following:

1. Open the Visual Studio / Developer command prompt as administrator

![image](https://user-images.githubusercontent.com/11719160/87015761-be153380-c1c5-11ea-94bb-32de13c087ba.png)

2. Execute the following

```
vsixinstaller /uninstall:c3d3dc68-c977-411f-b3e8-03b0dccf7dfc
```

3. Open and install the latest extension version
https://github.com/github/VisualStudio/releases/tag/v2.11.104

I'd be interested to know if any of these steps work!

**Comment by jalu2112** [comment]
Hi Jamie,

thank you for your answer. Itried the steps above but the uninstall (step 2) does not work:

![image](https://user-images.githubusercontent.com/37363032/87024069-ef4b2f00-c1d8-11ea-8e12-abe2c22f5428.png)

it gives this log file:

[dd_VSIXInstaller_20200709113459_2aa0.log](https://github.com/github/VisualStudio/files/4895872/dd_VSIXInstaller_20200709113459_2aa0.log)

Is it maybe another GUID that should be used in the uninstall?

**Comment by jcansdale** [comment]
What happened on step 3?

**Comment by jalu2112** [comment]
the same as error as in my first post.

**Comment by jcansdale** [comment]
@jalu2112,

I'm struggling to find anything similar to the "The call to DuplicateHandle failed" exception. Can you see if you can install any other extensions? I'd be surprised if this error was specific to GitHub for Visual Studio. 🤔

**Comment by jcansdale** [comment]
I'm going to close this issue because I don't _think_ it's specific to GitHub for Visual Studio. Feel free to comment or re-open! 🙂
