### ISSUE TITLE
You are not logged in to xxx, so certain git operations may fail. Login now

### ISSUE THREAD

**Issue by MarcusMM2** [github/VisualStudio#254]
We use Bonobo git server on server xxx and this message is constantly displaying and hiding important messages, how can we stop these messages in VisualStudio?

**Comment by shana** [comment]
@MarcusMM2 It looks like we're having some false positives when trying to identify which type of server you're connected to. I've pushed an update to the extension that disables this message, until we can figure out why these false positives are happening. If you update to version 1.0.18.2, this message should no longer appear.

**Comment by MarcusMM2** [comment]
thanks, message no longer appear!
Regards Marcus
