### ISSUE TITLE
Recursive component(razor) Cause a memory crash 

### ISSUE THREAD

**Issue by MhozaifaA** [github/VisualStudio#2551]
## Versions
 - GitHub Extension for Visual Studio version: 2.11.102.28613
 - Visual Studio version: 16.7.3

## What happened
Cause a memory crash even after shutting down the browser and iis

### Steps to Reproduce
1. Build Code like this with blazor  or any  Recursive components
```C#

@foreach (var comment in ChildComments)
{
<li>
    <div class="comment-list">
        <div class="bg-img">
            <img src="template/images/via/40x40.png" alt="">
        </div>
        <div class="comment">
            <h3>@comment.Commenter</h3>
            <span><img src="template/images/clock.png" alt="">@comment.Date</span>
            <p>@comment.Text</p>
            <a href="javascript:void(0)" title=""><i class="fa fa-reply-all"></i>@Translate["Reply"]</a>
        </div>
    </div><!--comment-list end-->
</li>
<ul>
    <Comment  ChildComments="ChildComments"/>
</ul>
}
@code {
    [Parameter] public JolijoberProject.Shared.SharedKernal.SharedModel.Comment[] ChildComments { get; set; } = new JolijoberProject.Shared.SharedKernal.SharedModel.Comment[]{ };

}

```
2. Call within a page
```C#
   @if (IsOpenComment)
{
   <ul>
                     <Comment ChildComments="Post.Comments"></Comment>
                 </ul>
}
```

3.  start ctrl+F5  and flip IsOpenComment to true 

Boooom RAM consumption increases terribly .. I have 12GB fill by 10 seconds

4.  Close the browser and the IIS did not help until I closed VS

### Additional context
Perhaps it is not a visual studio error. Rather, it is a mistake from me by coding .. but which seems to continue working Background after termination IIS ....   
```C#
<Comment  ChildComments="ChildComments"/>  //to   <Comment  ChildComments="comment.ChildComments"/>
```
but otherwise stuck

**Comment by jcansdale** [comment]
This is the repository for GitHub for Visual Studio repository rather than Visual Studio in general.

I think you'll have more luck here:
https://developercommunity.visualstudio.com/
