### ISSUE TITLE
Cannot sign in with github

### ISSUE THREAD

**Issue by CreeperPlanet26** [github/VisualStudio#2552]
When I try to sign in to GitHub to gain access to Visual Studio this happens and I can't login. 
![image](https://user-images.githubusercontent.com/51346607/94325182-2379f480-ff6b-11ea-98ce-38a711918e07.png)

**Comment by jcansdale** [comment]
Hello,

The problem is that this component uses an Internet Explorer based component to connect to github.com. GitHub is no longer compatible with Internet Explorer and login fails.

Can you login using you Microsoft rather than GitHub credentials?

Regards,
Jamie.
