### ISSUE TITLE
External Dependencies Misconfigured in nuget.config

### ISSUE THREAD

**Issue by rreichel3** [github/VisualStudio#2588]
In response to a recent security incident, we have been reviewing `nuget.config` files to ensure they have properly scoped the download of external dependencies. 

As part of this review, we determined that the `nuget.config` [here](https://github.com/github/VisualStudio/blob/824bab4ab2c3d8f6787cf38ff5ff9d4e9df00e98/nuget.config) needs to be updated to comply with the latest guidance [here](https://www.1eswiki.com/wiki/How_to_Securely_Configure_Package_Source_Files#Example_.28Good.29_2).
We have identified that your file requires the following:
- [ ] Remove dependency on multiple sources, converting the larger source (usually nuget.org) to an upstream of your private artifact feed.
- [ ] 🍨

Once the above is complete you can close out this issue and issue the chatops listed in further comments. 

Thanks! 

cc https://github.com/github/security/issues/4077

**Comment by sentinel** [comment]
@github/appsec please take the following action(s):
- [x] ~Assign a severity `.vuln severity <issue-link> <severity informational|low|medium|high|critical>`~
- [ ] Set the service catalog entry or reply with `unknown` to prompt the team to setup a service. Suggested  `.vuln catalog <issue-link> <service-name>`
- [ ] Assign a team `.vuln assign-team <issue-link> <assignee-team @github/...>`

---

*Vulnerability Lifecycle Progress*
... **:exclamation: Triaging (1/3)** -> WaitingOnFix -> ...

[What is this?](https://github.com/github/appsec/blob/master/docs/vulnerability-lifecycle/README.md)   [Feedback :bowing_man:](https://aka.ms/AA6vkzn)
