### ISSUE TITLE
Only pointer file cloned for LFS repositories on VS14 update 2

### ISSUE THREAD

**Issue by mponce1** [github/VisualStudio#259]
Visual Studio recently added support LFS. Please update GHfVS to support the change. 

Steps to reproduce:
1. Create a new repository in GHfW
2. Add LFS file types to gitattributes and commit
3. Sign into GHfVS
4. Clone repository 

Expected result: File sizes match on clone. 
Actual result: Only pointer file cloned, indicated by file size. 

Original Repo
![screen shot 2016-04-08 at 3 53 07 pm](https://cloud.githubusercontent.com/assets/6272408/14399521/497e59c0-fda2-11e5-8058-0784ac88fef7.png)

Cloned via VS
![screen shot 2016-04-08 at 3 52 53 pm](https://cloud.githubusercontent.com/assets/6272408/14399523/4fcd6b18-fda2-11e5-9883-e164b95c8a1c.png)

**Comment by shana** [comment]
@mponce1 GHfVS has nothing to do with this, git support is owned by Microsoft.
