### ISSUE TITLE
Staging a single file was easier before

### ISSUE THREAD

**Issue by af-mvo** [github/VisualStudio#262]
Now I have to right click on every file and stage it. Earlier I could use drag and drop (it's sometimes working). This is not working   as easy now. Also the staging button is bit confusing for me, as it could better stage (and unstage) only selected files.

**Comment by shana** [comment]
Hi! This repository is for the GitHub Extension, which only handles GitHub-specific bits, so I'm afraid we can't do much about this. This is really good feedback though, I'm sure the VS team at Microsoft would love to have it, you should send it using the feedback tool in Visual Studio.

/cc @acangialosi @clboles
