### ISSUE TITLE
Save Startup Project Combinations

### ISSUE THREAD

**Issue by bennimoser** [github/VisualStudio#2645]
Would be awesome to be able to save the Startup Project Combinations(Android + Host or Ios + Host for example) and then to select them from the Startup Projects at the Top.

**Comment by SafeArrow816** [comment]
Projet Microsoft : Organisation créée avec Azure Devops, Club Amiga ouvert au public.

**Comment by SafeArrow816** [comment]
Club Amiga disponible et ouvert aux discussions et appels de projets tels qu' avec Freelancer, VoyForums ou autres.
