### ISSUE TITLE
Property page doesn't load

### ISSUE THREAD

**Issue by LegalizeAdulthood** [github/VisualStudio#267]
![image](https://cloud.githubusercontent.com/assets/4270863/14654934/4298b576-063d-11e6-8503-bc49b11e3400.png)

Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA493
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA493
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA493
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   5.2.60328.3
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Atomineer Pro Documentation   1.0
Source-code documentation-comment creation and maintenance, and other documentation-related tools.

Clang with Microsoft CodeGen   14.0.25115
Clang with Microsoft CodeGen

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 10.0.2   Build 104.0.20151218.120627
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Node.js Tools   1.1.31117.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.31117.00
Profiling support for Node.js projects.

NuGet Package Manager   3.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

TypeScript   1.8.29.0
TypeScript tools for Visual Studio

VisualHG   1.1.7
Mercurial source contol provider.

**Comment by shana** [comment]
Thanks for reporting this!

@mponce1 @donokuda Can you repro this?

**Comment by LegalizeAdulthood** [comment]
Does it display anything normally?

**Comment by shana** [comment]
It should display a checkbox, yes.

What is the version on the extension you have installed (from Tools / Extensions and Updates)?

Also, can you run VS with the activity log on (`devenv /log` in the VS 2015 Developer Prompt command line) and post the log to a gist (or send it to support@github.com with a link to this issue if there's anything in there you'd rather keep private)

**Comment by LegalizeAdulthood** [comment]
I pasted the information from the about box above, it says:

GitHub.VisualStudio 1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

**Comment by LegalizeAdulthood** [comment]
Tools / Extensions and Updates says 1.0.18.1

**Comment by shana** [comment]
There should be 1.0.18.2 available, but before you update, if you could run VS with logging enabled so I can check what's up, that'd be great. There's nothing in 1.0.18.2 that relates to the property pages, so if it starts working after you update, it's a sign of some sort of corruption in VS or the extension installation.

**Comment by LegalizeAdulthood** [comment]
Not sure how to run with logging, but if you tell me what to do, I can follow instructions :smile_cat:

**Comment by shana** [comment]
Alrighty then! *rolls up sleeves*

1. Close Visual Studio if it's open 
2. Open a Developer Command Prompt for VS2015
3. Run `devenv /log`
4. Go to the property page that's failing
5. Close VS
6. The log is at `%appdata%\Microsoft\VisualStudio\14.0\ActivityLog.xml`. Grab that and send it to `shana at github dot com`. While you're at it, send the `%localappdata%\temp\extension.log` file, too.

**Comment by shana** [comment]
Found the problem! We'll have a fix out in the next release asap.

**Comment by shana** [comment]
To repro this is to set Solution Explorer as the focused pane and then restart VS, so that the next time it starts up it doesn't load Team Explorer by default (which means our assemblies won't get loaded beyond just the package initialization). Then go to Tools / Options and try to load the GitHub property page. It fails miserably.

@mponce1 Probably worth adding this to our test manifest 😛
