### ISSUE TITLE
Crash when selecting license with a different codepage/language

### ISSUE THREAD

**Issue by haiyuzhu** [github/VisualStudio#269]
Firstly, I did't test it on a new system, because it is very tedious.
Then, I try to use the cool software shared by you to create a repository, something like this:
![Uploading 1.jpg…]()

But, when I choose License like this:
![Uploading 2.png…]()
At this time VS2015 crashed.
I am not sure whether you can reproduce this problem. If the software on your environment runs well, I will try it on a new system again.Thank you for your attention.

**Comment by shana** [comment]
Is this when you try to publish the repository to GitHub? Can you post a screenshot of Visual Studio at the time you're choosing a license, before it crashes?

**Comment by haiyuzhu** [comment]
Dear Madam,
Thank you for your reply.
Firstly, I did't test it on a new system, because it is very tedious.
Then, I try to use the cool software shared by you to create a repository, something like this:
But, when I choose License like this:

At this time VS2015 crashed.
I am not sure whether you can reproduce this problem. 
If the software on your environment runs well, I will try it on a new system again.
Thank you for your attention.



Kind Regards,
------------------------------------------------------------
Haiyu Zhu （朱海宇）
Mobile：+86-159-9630-1232
E-mail：zhuhaiyu1991@163.com (primary)
E-mail：zhuhaiyu@smail.nju.edu.cn
Address：Nanjing University Xianlin Campus, Nanjing City, Jiangsu Provience, zip 210023
 
From: Andreia Gaita
Date: 2016-04-21 22:42
To: github/VisualStudio
CC: Haiyu Zhu; Author
Subject: Re: [github/VisualStudio] Bug Report (#269)
Is this when you try to publish the repository to GitHub? Can you post a screenshot of Visual Studio at the time you're choosing a license, before it crashes?

**Comment by shana** [comment]
@haiyuzhu Your screenshots are missing from your comment. Can you add them as a separate comment instead of replying to the email?

**Comment by haiyuzhu** [comment]
I have tried to upload my picture, but failed. However, I made it just then.
Back on our topic, the first picture illustrates what I want to do.
![1](https://cloud.githubusercontent.com/assets/9973435/14742393/96a820e6-08ce-11e6-94af-d1f44dd6010e.jpg)
The picture bellow shows that my vs crashes when i choose the License.
![2](https://cloud.githubusercontent.com/assets/9973435/14742394/96d02906-08ce-11e6-94a1-bde034bca659.png)

Thank you for your attention.

**Comment by shana** [comment]
@mponce1 @donokuda @paladique Can you repro this by any chance?

**Comment by paladique** [comment]
Just gave this a try by creating a repo doing with different configurations (private repo, public repo, different licenses) and it didn't crash.

**Comment by shana** [comment]
I wonder if it's the locale...

**Comment by shana** [comment]
@haiyuzhu The instructions below detail how to get the activity log from Visual Studio, so we can see what's going on. If you could go through them, that would be great.

1. Close Visual Studio if it's open 
2. Open a Developer Command Prompt for VS2015
3. Run `devenv /log`
4. Go to the property page that's failing
5. Close VS
6. Locate the following files on your system and email them to `windows@github.com`: 
  - `%appdata%\Microsoft\VisualStudio\14.0\ActivityLog.xml`
  - `%localappdata%\temp\extension.log`

**Comment by paladique** [comment]
Unfortunately we aren't able to reproduce this. I'm going to close this for now, please feel free to update this with a log and we'll repoen and investigate.
