### ISSUE TITLE
Strange Directory Creation

### ISSUE THREAD

**Issue by veccie** [github/VisualStudio#27]
I don't really know if this has anything to do with GitHub for VS, but since you guys know a lot about Git I thought I'd ask here. Maybe you've heard about this kind of behavior before :smiley:

I have this problem that every time I open a solution a strange looking empty directory is created in the folder where .sln is launched from. The directory name is always the same no matter what repo I launch a solution from: DTAR_08E86330_4835_4B5C_9E5A_61F37AE1A077_DTAR

Anyone know what's causing this?

**Comment by veccie** [comment]
Ok, well, I don't think it's related to Git. Tried repairing VS, but no change, still getting that strange directory and actually also an obj folder. I suspect an update might be causing it, oh well.

Nevermind me :smiley:

**Comment by jkolonko** [comment]
Hi Veccie, I have the same folder all over my disk inside git repositories. The name is not random - it is exactly as yours and it looks we are the only once experiencing it. Have you found what might be creating it?

**Comment by veccie** [comment]
@jkolonko I have not found out what's causing the problem, but I did notice that it only happens when opening a solution directly from windows explorer. Opening a solution from within VS doesn't create these directories so that's what I'm doing atm.

**Comment by rdskill-dev** [comment]
I also have the exact same directory name in vs 2015.

**Comment by takekazuomi** [comment]
I also have the exact same directory name in vs 2015.

**Comment by shiftkey** [comment]
I don't believe this is related to the GitHub extension for VS.

@Haacked @shana thoughts on where we should route this?

**Comment by shana** [comment]
Apologies folks, I could have sworn I had given feedback on this issue already! Thanks for the heads-up @shiftkey 

GitHub for VS is definitely not doing this. The best place to report this would be Microsoft, probably the VS feedback tool. It could be a number of different things triggering this (explorer or the VS git integration or Team Explorer or some third party extension), it's hard to guess. Regardless, MS will probably want to know about this.

/cc @acangialosi @MTBandolier

**Comment by WaltRitscher** [comment]
There is an open ticket for this issue on the Microsoft Connect site. Please post feedback there too. https://connect.microsoft.com/VisualStudio/feedback/details/1909707/getting-empty-folder-in-project-root-after-opening-sln-file-dtar-08e86330-4835-4b5c-9e5a-61f37ae1a077-dtar

**Comment by DaisyDave** [comment]
I also have this issue. I have some extensions loaded, but these only appear if I open the solution by double clicking the .sln file. If I open VS2015 and then open the solution from within the IDE these folders do not appear. (I have added this to the MS Connect site as well and even added it as a workaround)

I do not have ang Git related extensions but I do have the RedGate .NET Reflector extension installed.

**Comment by MTBandolier** [comment]
This is an issue in the VS SDK.  The fix should be available in the next VS update.

**Comment by adamralph** [comment]
The MS Connect issue is marked as a duplicate, with no clue as to where the duplicated issue is.
