### ISSUE TITLE
Visual Studio crashes when publishing new repository

### ISSUE THREAD

**Issue by mponce1** [github/VisualStudio#275]
Steps to reproduce: 
1. Sign into GH via manage connections
2. Create new local repository
3. Double click and go to Sync
4. Click publish to github and follow prompts

Expected result: New repository pushed to .com and remote is set. 
Actual result: VS crashes. 

Stacktrace: https://gist.github.com/MergeCity/e91eea9f8c2764d3d19a185bcb60f7fa

**Comment by Baneeishaque** [comment]
is the bug resolved - and in which version of vs 2017?
