### ISSUE TITLE
Publish to Github missing user icon

### ISSUE THREAD

**Issue by mponce1** [github/VisualStudio#278]
Steps to reproduce: 
1. Create local repository
2. Double click on new repository
3. Sync -> publish to github

![screen shot 2016-05-02 at 4 48 28 pm](https://cloud.githubusercontent.com/assets/6272408/14971275/b6a62b22-1085-11e6-85cd-979ca86fdb0d.png)

**Comment by grokys** [comment]
Unable to repro this on master. Could it have already been fixed accidentally?

**Comment by shana** [comment]
Maybe it's something to do with the image cache having corrupted data or something. If icons are showing up in most cases, then it's probably not a regression, just an issue we haven't stumbled upon before.

**Comment by grokys** [comment]
Fixed by #584
