### ISSUE TITLE
Auto translates extension options without demand

### ISSUE THREAD

**Issue by JuanGRomeo** [github/VisualStudio#281]
While I´m working with the extension, sometimes auto translates options into a Spanish. I´m working with Visual Studio Community English version (all the extensions and options appears in English) on Windows 8.1 Spanish version. I don´t know which are the steps to reproduce it.

To return to English, I have to restart Visual Studio.

![vsgithub](https://cloud.githubusercontent.com/assets/6495997/14985274/06929140-1147-11e6-9910-5ea727c47636.JPG)

![vsgithub2](https://cloud.githubusercontent.com/assets/6495997/14985298/33cd839a-1147-11e6-944d-2eb6c5ffe1d9.JPG)

**Comment by shana** [comment]
The english parts in your screenshot are the bits owned by the GitHub Extension, and the spanish parts are the bits owned by Microsoft's Team Explorer. We support localization but haven't added any translations yet, but it seems Team Explorer is picking up your Windows locale and switching to spanish for their bits. You should report this to Microsoft via the feedback tool in Visual Studio.

@acangialosi @clboles for visibility, this is probably something Team Explorer shouldn't be doing.
