### ISSUE TITLE
Reset and keep changes freezes VS

### ISSUE THREAD

**Issue by mponce1** [github/VisualStudio#287]
Steps to reproduce:
1. Create a new commit
2. Click SHA in success banner
3. Click Reset -> Reset and keep changes

Result: "Resetting Branch" pops up and sometimes populates the progress bar, but never closes. This leads to the entire VS window being non-interactable and needing to be closed in processes / task manager.

**Comment by shana** [comment]
@mponce1 Does this happen even when the extension is not installed? We don't have any UI in that area and don't do anything with commits, so it's very likely that's a VS bug.

**Comment by mponce1** [comment]
@shana turns out you are correct, this is broken even without GHfVS

**Comment by shana** [comment]
@acangialosi @clboles This might be something to look at on your side.
