### ISSUE TITLE
Solution Exporer Tree - refresh issue

### ISSUE THREAD

**Issue by playerx** [github/VisualStudio#296]
Hello,

When I've updated to latest version, there is an issue. When I add new items, commit them and Sync. Solution explorer isn't updated. If I'll restart VS everything is fine.

![img1](https://cloud.githubusercontent.com/assets/1698274/15096911/61808b38-151c-11e6-952d-aae0faed7e4d.png)

**Microsoft Visual Studio Professional 2015**
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01055

**Github Extension for Visual Studio**
Version 1.0.18.2

**Comment by paladique** [comment]
Hi @playerx! This repo is for the GitHub extension, which doesn't handle the git support in Visual Studio - that's owned by Microsoft. You should report this via the feedback tool in Visual Studio.
