### ISSUE TITLE
git-worktree support

### ISSUE THREAD

**Issue by diegose** [github/VisualStudio#300]
Currently, worktrees are not supported at all.

Repro:

- `git clone <some repo>`
- `git worktree add <worktree path> <branch>`
- Open sln from each path

Expected:
- Opening from the main folder shows all the git tools, specifying it's the master branch
- Opening from the other worktree shows all the git tools, specifying it's the selected `<branch>`

Actual:
- Main folder works
- Secondary worktree does not appear like a working directory at all.

**Comment by shana** [comment]
This is the repository for the GitHub Extension for Visual Studio. The git support in Visual Studio is maintained by Microsoft, not by us, so you should report this issue to them.

@Haacked Who would be the best person to cc on git support in VS?

**Comment by Haacked** [comment]
> @Haacked Who would be the best person to cc on git support in VS?

Let's start with @acangialosi. He's been our main point of contact there.

**Comment by diegose** [comment]
Thanks about the quick answers. I was probably confused about the scope of the extension.
