### ISSUE TITLE
GitHub context menus show up when in non-github repos

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#301]
Reported by @acangialosi

When working on a project hosted on VSTS, GitHub Create/Copy link context menus are showing up, and they shouldn't be.

**Comment by paladique** [comment]
I made a new project, uploaded that to VSTS and was able to reproduce this.
![2016-05-27 2](https://cloud.githubusercontent.com/assets/1414307/15615461/98b4e5aa-240c-11e6-815f-73d9ec3cfae8.png)

**Comment by femisimon** [comment]
I was able to reproduce this, hence re-opening the issue:

Steps to reproduce

Launch VS and log out if already logged in
Open a C# file that isn't hosted on GitHub
Select any text in c# file and Right-click.
Open on Github and Copy link to clipboard is visible in the context menu
Expected result - Open on Github and Copy link to clipboard should not be visible in the context menu

Actual result - Open on Github and Copy link to clipboard is visible in the context menu

**Comment by grokys** [comment]
Seems to be fixed.
