### ISSUE TITLE
Null reference exceptions when VS 2015 starts

### ISSUE THREAD

**Issue by MikhailArkhipov** [github/VisualStudio#306]
I get they are handled but it is extremely annoying to hit continue multiple times when Just My Code is disabled. Switching off breaking on null reference is not an option.

```
 	GitHub.Exports.dll!GitHub.Services.VSServices.PokeTheRegistryForRepositoryList() Line 117	C#
 	GitHub.Exports.dll!GitHub.Services.VSServices.GetKnownRepositories() Line 98	C#
 	GitHub.VisualStudio.dll!GitHub.VisualStudio.ConnectionManager.RefreshRepositories.AnonymousMethod__20_0() Line 132	C#
 	mscorlib.dll!System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<GitHub.Models.ISimpleRepositoryModel>>.InnerInvoke() Line 680	C#
```

**Comment by shana** [comment]
@MikhailArkhipov Yeah, I totally understand. It's fixed in master and it will be on the next release, which should be out next week (and a beta of it will be in the beta gallery and in the releases area of this repo tomorrow)

**Comment by MikhailArkhipov** [comment]
Thanks!
