### ISSUE TITLE
Username error icon displays by default

### ISSUE THREAD

**Issue by mponce1** [github/VisualStudio#307]
Steps to reproduce: 
1. Open visual studio
2. Go to connect page
3. Click on Github -> Connect

Expected result: Username error icon only displays after user tabs away from field or enters an invalid value. 
Actual result: Error displays immediately when it opens. Tabbing away from the field clears the icon. 

![screen shot 2016-05-18 at 3 24 48 pm 1](https://cloud.githubusercontent.com/assets/6272408/15376947/1410d094-1d0d-11e6-8c8d-548b771aeaf9.png)

**Comment by shana** [comment]
@grokys Could this be related to https://github.com/github/VisualStudio/pull/285?

**Comment by mponce1** [comment]
Also happens on Enterprise if you're already signed into Github and you go to Manage Connections -> Connect to Github.

![screen shot 2016-05-18 at 5 06 50 pm](https://cloud.githubusercontent.com/assets/6272408/15378783/489c1de2-1d1b-11e6-9102-468c07ab09f1.png)

**Comment by grokys** [comment]
@shana kinda related but a different problem I think - will prepare a PR.

**Comment by grokys** [comment]
Ignore my previous comment - yes I think this was caused by #285.
