### ISSUE TITLE
Duplicated repos in "Clone a repository" dialog

### ISSUE THREAD

**Issue by bc3tech** [github/VisualStudio#315]
eg:
![](http://content.screencast.com/users/bc3tech/folders/Snagit/media/dfccaf87-3caa-4ff4-9d95-1809d76de3b1/05.19.2016-11.39.png)

How do i know the difference between all the duplicates in this list?

**Comment by shana** [comment]
Hmmm, this feels like a bug, they're probably the same repos. If you clone two of the duplicates (to different places), do they have the same remote URL?

**Comment by bc3tech** [comment]
haven't tried that yet. Can give it a shot and find out. either way it needs cleanup, though ;)


Date: Fri, 20 May 2016 08:56:45 -0700

**Comment by paladique** [comment]
Looks like this is happening to repos that are part of orgs.

**Comment by grokys** [comment]
@paladique following on from yesterday I've added logging on the `grokys/repos-logging` branch - be interested to see what's happening on your machine.

**Comment by shana** [comment]
Fixed in #384
