### ISSUE TITLE
Clicking New collapses Local Git Repository

### ISSUE THREAD

**Issue by mponce1** [github/VisualStudio#317]
Steps to reproduce: 
1. Open GHfVS and go to manage connections
2. Click "New" Under local git repository when the text field is not present

Expected result: Text fields appear for path, url, etc
Actual result: Local Git repository collapses if the text fields aren't already present. 
![collapse](https://cloud.githubusercontent.com/assets/6272408/15439665/659195be-1e86-11e6-9738-15b3d42b722e.gif)

**Comment by mponce1** [comment]
Happens with any of the local git repository menu items

**Comment by shana** [comment]
I have no idea why this is happening. I can't repro it on my installation. Also, that section isn't ours, it's Microsoft's. Which VS version is this?

**Comment by mponce1** [comment]
14 enterprise, im still investigating but doesnt seem to repro on my windows 7, so maybe its just my instance 😭

**Comment by mponce1** [comment]
I can't repro it on a separate windows 10 VM, so I'm going to close this until I can figure out why it's happening.
