### ISSUE TITLE
Opening a new project doesn't update PR list

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#323]
If I open a solution, I can see the PRs in the PRs view:

![image](https://cloud.githubusercontent.com/assets/1775141/15548685/ce0ef9fc-22a9-11e6-971c-8ea8f98eef75.png)

However if I think switch to another solution, the header displays the new repository information, but the PRs from the old repository remain:

![image](https://cloud.githubusercontent.com/assets/1775141/15548753/1703122e-22aa-11e6-8b8e-a275b7f8ac26.png)

**Comment by grokys** [comment]
Now fixed.

**Comment by shana** [comment]
This was fixed by the PR I merged earlier, right? Could you add a comment on the PR with this issue number so that they're linked and we know what fixed what?

**Comment by grokys** [comment]
Do you mean #365? I'm not sure - that PR didn't aim to fix this issue, and I can't see how it did tbh.

**Comment by shana** [comment]
Oh yeah, you're right. Weeeird.
