### ISSUE TITLE
When can directly in the VisualStudio management Issues?just like TFS! 

### ISSUE THREAD

**Issue by oSilas** [github/VisualStudio#335]
Have this plan?

**Comment by grokys** [comment]
Hi @oSilas can you clarify what you mean?

Do you want issue management in the GitHub extension?

**Comment by paladique** [comment]
Hi @oSilas if you're curious about what features we are planning on supporting (which includes issues management!), check out our [roadmap](https://github.com/github/VisualStudio/blob/master/CONTRIBUTING.md#roadmap-and-future-feature-ideas) and if you're wondering what we're **currently** working on, feel free to take a look at what we are doing in our pull requests! Hope this helps.
