### ISSUE TITLE
Cancelling logout dialog proceeds to Create Gist

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#336]
@shana this is because cancelling the `UIViewType.LogoutRequired` calls `Go(Trigger.Cancel)`:

https://github.com/github/VisualStudio/blob/grokys/feature/gist-support/src/GitHub.App/Controllers/UIController.cs#L365

Which ends up at `End(false)`:

https://github.com/github/VisualStudio/blob/grokys/feature/gist-support/src/GitHub.App/Controllers/UIController.cs#L369

`End(false)` calls `Fire(Trigger.Next)`:

https://github.com/github/VisualStudio/blob/grokys/feature/gist-support/src/GitHub.App/Controllers/UIController.cs#L607

Which moves the flow to the first UI of the main flow:

https://github.com/github/VisualStudio/blob/grokys/feature/gist-support/src/GitHub.App/Controllers/UIController.cs#L408

I'm not entirely sure how this all should work so I'm hesitant to change anything here, but I will continue poking around. I suspect that `End(false)` shouldn't call `Fire(Trigger.Next)`?

**Comment by shana** [comment]
Aaaaaaaah. I figured it was something silly.

In line https://github.com/github/VisualStudio/blob/grokys/feature/gist-support/src/GitHub.App/Controllers/UIController.cs#L604 we only cancel the flow if it's either the main flow, or if it's the authentication subflow. Which made sense when we only had one subflow, only now we have another subflow, and so this silly if is failing.

I can't remember why I put that `activeFlow == UIControllerFlow.Authentication` condition in there explicitly. We only had one subflow at the time, so I can't think of a reason why `!Success` wouldn't be enough.
