### ISSUE TITLE
Team Explorer crashing and giving Errors

### ISSUE THREAD

**Issue by sbelassa** [github/VisualStudio#339]
does anyone know how to solve this problem?!

![prob](https://cloud.githubusercontent.com/assets/15706001/15678281/0c49472e-274e-11e6-97a2-89670b011a27.PNG)

**Comment by grokys** [comment]
Hi @sbelassa can you tell us what you did to get this error? Is it reproducible?

**Comment by sbelassa** [comment]
I tried to synchronize and commit my modifications, there were alot of errors and I don't know what happened, suddenly I can no longer Access to git and all I see is this error

**Comment by grokys** [comment]
Could you tell me which version of the extension you have installed?

To do this go to the Tools menu -> Extensions and Updates -> GitHub Extension for Visual Studio and look at the Version.

**Comment by sbelassa** [comment]
I didn't find it!!! I'm running a VS Entreprise 201

**Comment by grokys** [comment]
It's definitely there. We need to know what version you're on to help you.

Here's what it looks like on my machine:

![image](https://cloud.githubusercontent.com/assets/1775141/15678747/b3bde9c8-274f-11e6-94c5-5d70a4167145.png)

![image](https://cloud.githubusercontent.com/assets/1775141/15678785/d00cc270-274f-11e6-838a-05a21539b157.png)

**Comment by sbelassa** [comment]
yeah th thing is that I don't have the extention!

![image](https://cloud.githubusercontent.com/assets/15706001/15678873/24ed136c-2750-11e6-847b-e8269f2fdbeb.png)

**Comment by grokys** [comment]
Ok, well if you don't have the extension, the problem isn't with the GitHub extension for Visual Studio ;)

It looks to be a problem in VIsual Studio itself - please report it to Microsoft.
