### ISSUE TITLE
Help: How to disable UI localization?

### ISSUE THREAD

**Issue by wgebczyk** [github/VisualStudio#340]
"Accidentally" I've updated GitHub to newest version and Team Explorer UI got localized!
I've landed with VS2015 where some UI is in English (majority) and some in Polish (just here and there in Team Explorer). I'm really used to English names for actions/labels.
How can I change language to English OR how can I use older version?

Thanks!

**Comment by grokys** [comment]
Hi @wgebczyk the the Team Explorer is a part of Visual Studio itself, so I suspect that it wasn't the update that caused this, and in addition the GitHub for Visual Studio extension is only currently available in English!

I think this video may help you change your language back to English: https://channel9.msdn.com/Blogs/AldoNET/WR-Series-How-to-change-the-Display-Language-of-Visual-Studio

**Comment by wgebczyk** [comment]
I can see in VS2015 that the is only on language available - English.
At same time today I've installed a few updated from VS2015 - one of them Git Extensions.
Hmm.. After recheck and restart of VS twice in the meantime it reverted back to... English :)
As Polish language was displayed only in part of Git extensions in Team Explorer I think that there is some bug that might from time to time surface, but restarting a few times would discard that.
