### ISSUE TITLE
Link generation for Open/Link to GitHub should use the latest commit of the current file

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#343]
The "Open on GitHub" feature always seems to try to open the file on master - if I'm on a branch that file might not exist or be completely different. It would be good to open the file on the correct branch on the site.

**Comment by shana** [comment]
It's more that it generates the url based on the latest commit

**Comment by paladique** [comment]
> maybe what we should do is generate the link based on the latest commit for that particular file

Does this mean we should go back through the log and find the first commit present on the repo/remote? If so what we're thinking is using `git branch -r --contains TheSHA`  (via [libgit2sharp](https://github.com/libgit2/libgit2sharp/wiki/git-branch#displaying-local-branches-that-contains-specified-commit)) to find the latest commit on the remote and use that SHA if it exists.

**Comment by shana** [comment]
Yup, that sounds right :smile:
