### ISSUE TITLE
Repository creation button activation not enabled when Name text box filled

### ISSUE THREAD

**Issue by paladique** [github/VisualStudio#346]
Per the test checklist, this is supposed to be enabled once the text box is filled
Only seems to be enabled if you change focus from the text box.

![2016-06-06 3](https://cloud.githubusercontent.com/assets/1414307/15837255/73a97b5c-2c06-11e6-9f21-551aa9f8d19d.png)
![2016-06-06 4](https://cloud.githubusercontent.com/assets/1414307/15837254/73a90adc-2c06-11e6-9a5c-9c87baabba4b.png)

**Comment by shana** [comment]
I suspect this and #347 are the same bug... 😉

**Comment by paladique** [comment]
Heh, yeah I spent 10 minutes trying to decide if I should split them up :joy: I can group them together if that's better
