### ISSUE TITLE
git-lfs does not push files to repository

### ISSUE THREAD

**Issue by dwaterbly** [github/VisualStudio#361]
The git extension for visual studio does not push files tracked with git-lfs to the server.

Steps to reproduce:

Create new git repo.
Track a file for git-lfs (git lfs track *.dll)
Add a .dll file
Commit change
Push change using Git extension for visual studio.

Notice file contents are not pushed to remote repository.

**Comment by paladique** [comment]
Hi @dwaterbly, the Git Extension for VS is supported by Microsoft, so you'll have to contact them about support for lfs and lfs issues. [Here's their support page](https://www.visualstudio.com/en-us/support/support-overview-vs.aspx).
