### ISSUE TITLE
Crash in GitHub.Exports

### ISSUE THREAD

**Issue by kevinfansler** [github/VisualStudio#367]
Hi all,
Sorry for the broad posting. I work on the Visual Studio team at Microsoft as a Program Manager and we have some reported Watson crashes with this extension for Updates 1 and 2 (only 1 crash so far for Update 3, so perhaps the issue has been fixed. I would love to confirm) You can contact me here or at v-kefans@microsoft.com.

**Comment by paladique** [comment]
Hi @kevinfansler 
@shana, @grokys and myself are the GitHubbers working on this extension. If you have any screenshots or can provide us any log files ([info on where we put ours here](https://github.com/github/VisualStudio/blob/master/CONTRIBUTING.md#bug-reporting)) that would be super helpful. Also, if you'd rather be this internal discussion you can email support@github.com and reference this issue and we can continue discussion there.

 Thanks!

**Comment by kevinfansler** [comment]
I'll send mail to support@. I may need to share information that should be more private. Thanks!

**Comment by paladique** [comment]
Alrighty, I'll close this and we can continue from there.

**Comment by shana** [comment]
Stacktrace:

```
o Level . . . Symbol - InstructionPointer - FunctionOffset - SourceLine - SourceFile
§ 0 . . . mscorlib_ni!System.IO.__Error.WinIOError - 0x69720000 - 0x000000D9 - -
§ 1 . . . mscorlib_ni!System.IO.FileStream.Init - 0x69720000 - 0x0000052F - -
§ 2 . . . mscorlib_ni!System.IO.FileStream..ctor - 0x69720000 - 0x00000043 - -
§ 3 . . . mscorlib_ni!System.IO.StreamWriter.CreateFile - 0x69720000 - 0x0000004A - -
§ 4 . . . mscorlib_ni!System.IO.StreamWriter..ctor - 0x69720000 - 0x0000004A - -
§ 5 . . . mscorlib_ni!System.IO.StreamWriter..ctor - 0x69720000 - 0x00000019 - -
§ 6 . . . mscorlib_ni!System.IO.File.InternalAppendAllText - 0x69720000 - 0x00000037 - -
· 7 . . . mscorlib_ni!System.IO.File.AppendAllText - 0x69720000 - 0x00000029 - -
o 8 . . . GitHub_Exports!Unknown - 0x00000000 - 0x000000FC - - <<Failure related >>
§ 9 . . . mscorlib_ni!System.Runtime.CompilerServices.AsyncMethodBuilderCore+__c._ThrowAsync_b__6_1 - 0x69720000 - 0x00000035 - -
§ 10 . . . mscorlib_ni!System.Threading.QueueUserWorkItemCallback.WaitCallback_Context - 0x69720000 - 0x00000042 - -
§ 11 . . . mscorlib_ni!System.Threading.ExecutionContext.RunInternal - 0x69720000 - 0x000000A7 - -
§ 12 . . . mscorlib_ni!System.Threading.ExecutionContext.Run - 0x69720000 - 0x00000016 - -
§ 13 . . . mscorlib_ni!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem - 0x69720000 - 0x00000060 - -
§ 14 . . . mscorlib_ni!System.Threading.ThreadPoolWorkQueue.Dispatch - 0x69720000 - 0x0000012F - -
§ 15 . . . mscorlib_ni!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback - 0x69720000 - 0x0000000A - -
```

**Comment by paladique** [comment]
This has been resolved in [today's release](https://github.com/github/VisualStudio/releases/tag/v1.0.18.6)
