### ISSUE TITLE
npm causes gulp errors when windows is x64

### ISSUE THREAD

**Issue by BertCotton** [github/VisualStudio#380]
cmd.exe /c gulp --tasks-simple
C:\dev\project\application\src\Web\node_modules\node-sass\lib\index.js:15
    throw new Error(errors.missingBinary());
    ^
Error: Missing binding C:\dev\project\application\src\Web\node_modules\node-sass\vendor\win32-ia32-47\binding.node
Node Sass could not find a binding for your current environment: Windows 32-bit with Node.js 5.x
Found bindings for the following environments:
  - Windows 64-bit with Node.js 5.x
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.

Step to reproduce.  (Assuming a project with a node package.json and gulp file)

1) From command line run npm install
2) Open Visual Studio and open 'Task Runner Explorer'

The error 'Failed to load. See output' will direct you to this error.

**Comment by shana** [comment]
This repository is for the GitHub extension for Visual Studio, not for Visual Studio itself. To report VS problems to Microsoft, you should use the feedback tool available in the VS Help menu.

**Comment by BertCotton** [comment]
Sorry my mistake.
