### ISSUE TITLE
GitHub extension don't detect modifications on some occasions

### ISSUE THREAD

**Issue by vRITHNER** [github/VisualStudio#387]
Hi,
depending how I create a new file in VS, GitHub extension don't detect it.

If I create a new file from menu  -> add new item, it's working fine; 
if I press Ctrl+drag an existing file to create a copy of an existing file and then rename it, it consider this is the same file. (the lock icon is present at the left of the name). 
If I open the new file and make a modification inside like add a comment or reformat the file, the icon is now a (v) but as soon a I save it, the lock icon is shown again and I can't commit the file.

This is really annoying when we work a many contributors because often guys commit stuff and we don't get all modifications during Pull.

I insert below some screen captures which repro the steps to see the bug:
Thanks for reading me
Cheers
-Vince

Step1:
Duplicate a File:

![capture01](https://cloud.githubusercontent.com/assets/238842/16449234/782fa30c-3df6-11e6-8ab4-c8286a89288a.png)

Step2:
Open and do a small modification:

![capture02](https://cloud.githubusercontent.com/assets/238842/16449236/7b87ba30-3df6-11e6-8670-4d58a5d2a8d3.png)

Step3:
Save the file and :-(  :-1: 

![capture03](https://cloud.githubusercontent.com/assets/238842/16449237/7dda0d7e-3df6-11e6-96db-54de80c7928d.png)

**Comment by paladique** [comment]
Hi @vRITHNER, this repo is for the GitHub extension, and does not handle Visual Studio's git support, which is owned by Microsoft. You can report this via the [support page](www.visualstudio.com/support/support-overview-vs) for Visual Studio.
