### ISSUE TITLE
[None] Gets added twice to PR list filters

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#390]
To repro: open the VisualStudio repository, then go to PR list. Select "donokuda" as asignee. The [None] entry in the dropdown gets duplicated,

![image](https://cloud.githubusercontent.com/assets/1775141/16580552/53a864de-42a5-11e6-8503-8e96066041ba.png)

**Comment by shana** [comment]
What's up with the title?

**Comment by grokys** [comment]
Oops, I thought I edited that.

**Comment by paladique** [comment]
Seeing this too. An additional thing to note here is that if you end up selecting the first [None] in the list, the duplicated [None] disappears.
