### ISSUE TITLE
Add link to repo on main webpage.

### ISSUE THREAD

**Issue by IDisposable** [github/VisualStudio#4]
The page https://visualstudio.github.com/ doesn't have a easily flaunted link to this source repository. Right now the simplest discovery path (beyone URL guessing) is in the release notes.  It really should be a prominent link on the page itself.

**Comment by Haacked** [comment]
Great suggestion! I'll look into it.

**Comment by shana** [comment]
Fixed! :ice_cream:

**Comment by IDisposable** [comment]
Perfect!
