### ISSUE TITLE
Description left out in PR Creation

### ISSUE THREAD

**Issue by paladique** [github/VisualStudio#401]
Made a few test PRs and noticed that the description does not show up in the PR.

![2016-07-05](https://cloud.githubusercontent.com/assets/1414307/16593611/16617f16-42b4-11e6-906a-9625b0685498.png)

![2016-07-05 1](https://cloud.githubusercontent.com/assets/1414307/16593640/3ad0fc78-42b4-11e6-9b3d-84991b2f3420.png)

**Comment by grokys** [comment]
Yep, can confirm.
