### ISSUE TITLE
Clicking refresh in PR list sometimes makes PR icon disappear

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#408]
This one is a little difficult to reproduce, but sometimes when clicking the refresh button in the PR list, the icon disappears. Sometimes clicking it more makes it reappear, sometimes not.

**Comment by shana** [comment]
Which icon? Can we haz screenshot on this?

**Comment by grokys** [comment]
The user icon next to the PR in the list. I wasn't able to capture a screenshot because it stopped happening - as I said it can be difficult to reproduce. It was happening fairly regularly and then it stopped :(

**Comment by grokys** [comment]
Caught it!

![406b76d01c9d84c4780eba99a9ad1021](https://cloud.githubusercontent.com/assets/1775141/16614477/ce11489a-4371-11e6-9b44-8c74c9d9cac4.gif)

**Comment by shana** [comment]
Yeah, got that too when loading PRs for the first time.

![screen shot 2016-07-06 at 11 41 13 am](https://cloud.githubusercontent.com/assets/310137/16615331/3add8d0e-4376-11e6-9848-003912d711cc.png)

This is the avatar provider loading things from cache in one of the akavache threads. Any exceptions in the log file?

**Comment by grokys** [comment]
This is the only thing that looks like it could be relevant:

> 2016-06-15 00:29:52.8413|ERROR|thread: 1|ImageCache|Could not vacuum image cache
> System.ObjectDisposedException: The cache 'SqlitePersistentBlobCache' was disposed.

**Comment by shana** [comment]
I have some of those too, but that's in June, not today

**Comment by grokys** [comment]
I suspect this issue is caused by this line:

https://github.com/github/VisualStudio/blob/master/src/GitHub.App/Models/Account.cs#L35

I think that should be setting the property rather than the backing field.

**Comment by StanleyGoldman** [comment]
I'll check that out a bit later today.

**Comment by femisimon** [comment]
This was reproduced.

Cc @grokys @shana 

![snip20161108_2](https://cloud.githubusercontent.com/assets/17054747/20109988/6433ecd8-a597-11e6-9758-2f68101261ed.png)

**Comment by StanleyGoldman** [comment]
I'm unable to reproduce this issue anymore

**Comment by paladique** [comment]
Can't repro this either, closing!

**Comment by grokys** [comment]
Yeah, I think this was fixed!
