### ISSUE TITLE
Cannot publish or create a Private Repository

### ISSUE THREAD

**Issue by Peter-Schneider** [github/VisualStudio#436]
Right now on the create / publish Dialogs the Private Repository Checkbox is not updated correctly.

I have a user on a free plan (no private repositories) but I am owner of an organization with unlimited private repositories. If I change the accounts dropdown to that organization the Checkbox Private Repository is still disabled.

- GitHub Extension version: 1.0.18.6 (the same with the latest beta)
- Visual Studio version: VS 2015 Enterprise, Windows 10

**Comment by paladique** [comment]
Seeing this too

![octokit](https://cloud.githubusercontent.com/assets/1414307/17121840/62fceeb4-52a4-11e6-8452-a6ecd0bf0e47.PNG)

**Comment by lty83** [comment]
+1

**Comment by shana** [comment]
We're working on it, should have a fix soon. Sorry about the trouble!

**Comment by grokys** [comment]
The issue seems to be that we're getting the user orgs from the `https://api.github.com/user/orgs` API and that doesn't appear to return the `plan` as part of its response.
