### ISSUE TITLE
Opening Tools->Options with page "VS.ToolsOptionsPages.GitHub_for_Visual_Studio.General" can crash Visual Studio

### ISSUE THREAD

**Issue by JinzhouYang** [github/VisualStudio#444]
- GitHub Extension version: 1.99.0.1
- Visual Studio version: Visual Studio 2015 14.0.25123.00 Update 2

There isn't a static repro step but sometimes when opening with Tools->Options with page "GitHub For Visual Studio" Visual Studio could crash.
The exception info: PresentationSource.CriticalFromVisual is throwing ArgumentNull Exception

CallStack:

>   KERNELBASE.dll!RaiseException(unsigned long dwExceptionCode, unsigned long dwExceptionFlags, unsigned long nNumberOfArguments, const unsigned long \* lpArguments) Line 865  C
>     [Managed to Native Transition]  
>     PresentationCore.dll!System.Windows.PresentationSource.CriticalFromVisual(System.Windows.DependencyObject v, bool enable2DTo3DTransition) Line 659  C#
>     Microsoft.VisualStudio.Shell.14.0.dll!Microsoft.VisualStudio.Shell.UIElementDialogPage.DialogPageElementHost.OnHandleCreated(System.EventArgs e) Line 230   C#
>     System.Windows.Forms.dll!System.Windows.Forms.Control.WmCreate(ref System.Windows.Forms.Message m) Line 12965   C#
>     System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m) Line 13878    C#
>     WindowsFormsIntegration.dll!System.Windows.Forms.Integration.ElementHost.WndProc(ref System.Windows.Forms.Message m) Line 803   C#
>     Microsoft.VisualStudio.Shell.14.0.dll!Microsoft.VisualStudio.Shell.UIElementDialogPage.DialogPageElementHost.WndProc(ref System.Windows.Forms.Message m) Line 196   C#
>     System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m) Line 14231  C#
>     System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m) Line 14286    C#
>     System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam) Line 780 C#
>     [Native to Managed Transition]  
>     user32.dll!**InternalCallWinProc@20() Line 116  Unknown
>     user32.dll!UserCallWinProcCheckWow(_ACTIVATION_CONTEXT \* pActCtx, void \* pfn, HWND** \* hwnd, _WM_VALUE msg, unsigned int wParam, long lParam, void \* fEnableLiteHooks, int) Line 184    C
>     user32.dll!DispatchClientMessage(tagWND \* pwnd, _WM_VALUE message, unsigned int wParam, long lParam, unsigned long pfn) Line 3332   C
>     user32.dll!__fnINLPCREATESTRUCT(_FNINLPCREATESTRUCTMSG \* pmsg) Line 1576    C
>     ntdll.dll!_KiUserCallbackDispatcher@12() Line 517   Unknown
>     user32.dll!CreateWindowInternal(unsigned long dwExStyle, const wchar_t \* pClassName, const wchar_t \* pWindowName, unsigned long dwStyle, int x, int y, int nWidth, int nHeight, HWND__ \* hwndParent, HMENU__ \* hmenu, void \* hModule, void \* pParam, ZBID zbid, unsigned long dwFlags, unsigned long dwTypeFlags, unsigned short wWinVer) Line 1846 C
>     user32.dll!CreateWindowExW(unsigned long dwExStyle, const wchar_t \* lpClassName, const wchar_t \* lpWindowName, unsigned long dwStyle, int X, int Y, int nWidth, int nHeight, HWND__ \* hWndParent, HMENU__ \* hMenu, HINSTANCE__ \* hModule, void \* lpParam) Line 68   C
>     System.Windows.Forms.ni.dll!5094a61f()  Unknown
>     [Frames below may be incorrect and/or missing, no symbols loaded for System.Windows.Forms.ni.dll]  
>     [Managed to Native Transition]  
>     System.Windows.Forms.dll!System.Windows.Forms.UnsafeNativeMethods.CreateWindowEx(int dwExStyle, string lpszClassName, string lpszWindowName, int style, int x, int y, int width, int height, System.Runtime.InteropServices.HandleRef hWndParent, System.Runtime.InteropServices.HandleRef hMenu, System.Runtime.InteropServices.HandleRef hInst, object pvParam) Line 1512 C#
>     System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams cp) Line 740  C#
>     System.Windows.Forms.dll!System.Windows.Forms.Control.CreateHandle() Line 5710  C#
>     System.Windows.Forms.dll!System.Windows.Forms.Control.Handle.get() Line 2779    C#
>     Microsoft.VisualStudio.Shell.14.0.dll!Microsoft.VisualStudio.Shell.DialogPage.System.Windows.Forms.IWin32Window.Handle.get() Line 634   C#
>     Microsoft.VisualStudio.Shell.14.0.dll!Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.GetPropertyPage(ref System.Guid rguidPage, Microsoft.VisualStudio.Shell.Interop.VSPROPSHEETPAGE[] ppage) Line 2035   C#
>     [Native to Managed Transition]  
>     msenv.dll!CVsPropPage::HrLoadPage(_PROPSHEETPAGEA \* ppsp) Line 970  C++
>     msenv.dll!EnsurePageLoaded(_PSP \* hpage) Line 509   C++
>     msenv.dll!CreatePage(_PSP \* hpage, HWND__ \* hwndParent) Line 732    C++
>     msenv.dll!PageChange(PROPDATA \* ppd, int iAutoAdj) Line 1834    C++
>     msenv.dll!InitPropSheetDlg(HWND__ \* hDlg, PROPDATA \* ppd) Line 1499 C++
>     msenv.dll!PropSheetDlgProc(HWND__ \* hDlg, unsigned int uMessage, unsigned int wParam, long lParam) Line 2804    C++
>     user32.dll!**InternalCallWinProc@20() Line 116  Unknown
>     user32.dll!InternalCallWinProc(long(__stdcall*)(HWND** _, unsigned int, unsigned int, long) proc, HWND__ \* hwnd, _WM_VALUE message, unsigned int wParam, long lParam) Line 81   C
>     user32.dll!UserCallDlgProcCheckWow(_ACTIVATION_CONTEXT \* pActCtx, int(__stdcall_)(HWND__ _, unsigned int, unsigned int, long) pfn, HWND__ \* hwnd, _WM_VALUE msg, unsigned int wParam, long lParam, void \* pret, int *) Line 265 C
>     user32.dll!DefDlgProcWorker(tagWND \* pwnd, _WM_VALUE message, unsigned int wParam, long lParam, unsigned long fAnsi) Line 779   C
>     user32.dll!DefDlgProcW(HWND__ \* hwnd, unsigned int message, unsigned int wParam, long lParam) Line 1298 C
>     user32.dll!**InternalCallWinProc@20() Line 116  Unknown
>     user32.dll!UserCallWinProcCheckWow(_ACTIVATION_CONTEXT \* pActCtx, void \* pfn, HWND** \* hwnd, _WM_VALUE msg, unsigned int wParam, long lParam, void \* fEnableLiteHooks, int) Line 184    C
>     user32.dll!DispatchClientMessage(tagWND \* pwnd, _WM_VALUE message, unsigned int wParam, long lParam, unsigned long pfn) Line 3332   C
>     user32.dll!__fnDWORD(_FNDWORDMSG \* pmsg) Line 917   C
>     ntdll.dll!_KiUserCallbackDispatcher@12() Line 517   Unknown
>     user32.dll!InternalCreateDialog(void \* hmod, DLGTEMPLATE \* lpdt, unsigned long cb, HWND__ \* hwndOwner, int(__stdcall_)(HWND__ _, unsigned int, unsigned int, long) lpfnDialog, long lParam, unsigned int fSCDLGFlags) Line 1454 C
>     user32.dll!CreateDialogIndirectParamAorW(void \* hmod, const DLGTEMPLATE \* lpDlgTemplate, HWND__ \* hwndOwner, int(__stdcall_)(HWND__ _, unsigned int, unsigned int, long) lpDialogFunc, long dwInitParam, unsigned int fAnsi) Line 876   C
>     user32.dll!CreateDialogIndirectParamW(HINSTANCE__ \* hmod, const DLGTEMPLATE \* lpDlgTemplate, HWND__ \* hwndOwner, int(__stdcall_)(HWND__ _, unsigned int, unsigned int, long) lpDialogFunc, long dwInitParam) Line 844   C
>     msenv.dll!_RealPropertySheet(std::shared_ptr<PROPDATA> ppd) Line 3450   C++
>     msenv.dll!VsPropertySheet(const _PROPSHEETHEADERW_V2 \* ppsh) Line 3635  C++
>     msenv.dll!VBDialogCover2(int(__stdcall_)(void _) lpfnDialogBox, void \* lpvoid, HWND__ \* \* lphwndParent, int bUseOLEHost) Line 399   C++
>     msenv.dll!CVsPropPage::HrShowPages(const wchar_t \* pszCaption, const _GUID & rguidPage, unsigned long) Line 1694    C++
>     msenv.dll!HrShowToolsOptsDlg(const _GUID & rguidActivePage, int) Line 396   C++
>     msenv.dll!HandleToolsOptionsCommand(unsigned long nCmdexecopt, tagVARIANT \* pvaIn, tagVARIANT \* pvaOut) Line 451    C++
>     msenv.dll!HrShellExec(const _GUID \* pguidCmdGroup, unsigned long nCmdID, unsigned long nCmdexecopt, tagVARIANT \* pvaIn, tagVARIANT \* pvaOut) Line 3524  C++
>     msenv.dll!CVSCommandTarget::ExecCmd(const CIcmdGuidCmdId \* pCmdArg, const _GUID \* pguidCmdGroup, unsigned long nCmdID, unsigned long nCmdexecopt, tagVARIANT \* pvaIn, tagVARIANT \* pvaOut, _GUID \* pPackageGuid) Line 2256  C++
>     msenv.dll!`anonymous namespace'::ExecForController(const CommandUI::Models::IControllerRoot \* pController, const _GUID \* pCmdGroupGuid, unsigned long nCmdID, unsigned long nCmdexecopt, tagVARIANT \* pvaIn, tagVARIANT \* pvaOut, _GUID \* pPackageGuid) Line 355    C++
>     msenv.dll!CSurfaceCommandingSupport::ExecuteForController(const CommandUI::Models::IControllerRoot \* pControllerRoot, unsigned long nCmdexecopt, tagVARIANT \* pvaIn, tagVARIANT \* pvaOut, _GUID \* pPackageGuid) Line 2726   C++
>     msenv.dll!CExecuteVisitor::VisitButtonController(CommandUI::Models::IButtonController \* pButtonController, const tagVARIANT \* pVarIn, tagVARIANT \* __formal) Line 217   C++
>     msenv.dll!CControllerVisitorBase::DispatchVisit(CommandUI::Models::IControllerRoot \* pControllerRoot, const tagVARIANT \* pVarIn, tagVARIANT \* pVarOut) Line 84  C++
>     msenv.dll!CControllerVisitorBase::VisitController(CommandUI::Models::IControllerRoot \* pControllerRoot, const tagVARIANT \* pVarIn, tagVARIANT \* pVarOut) Line 45    C++
>     msenv.dll!CSurfaceCommandingSupport::Execute(CommandUI::Models::IControllerRoot \* pController, const tagVARIANT \* pVarIn, tagVARIANT \* pVarOut) Line 2934   C++
>     msenv.dll!CommandUI::Models::Impl::CExecutableCommandElementDataSource::Execute(const tagVARIANT & varIn, tagVARIANT \* pVarOut) Line 91 C++
>     msenv.dll!CommandUI::Models::Impl::CExecutableCommandElementDataSource::ExecuteVerbHandler(IVsUIDispatch \* pDisp, const wchar_t \* __formal, const tagVARIANT & refVarIn, tagVARIANT \* pVarOut) Line 130 C++
>     msenv.dll!Gel::CDataSource::Invoke(const wchar_t \* verb, tagVARIANT vaIn, tagVARIANT \* pvaOut) Line 302 C++
>     [Frames below may be incorrect and/or missing]  
>     [Managed to Native Transition]  
>     Microsoft.VisualStudio.Shell.14.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Invoke(string verb, object pvaIn, out object pvaOut) Line 341   C#
>     Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.VsCommand.Execute(object parameter) Line 74  C#
>     PresentationFramework.dll!MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource commandSource, bool userInitiated) Line 197  C#
>     PresentationFramework.dll!System.Windows.Controls.MenuItem.InvokeClickAfterRender(object arg) Line 1419 C#
>     WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs) Line 104 C#
>     WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler) Line 37 C#
>     WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl() Line 583  C#
>     WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state) Line 528 C#
>     mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954  C#
>     mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902  C#
>     mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 891    C#
>     WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 197 C#
>     WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke() Line 441  C#
>     WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue() Line 2232    C#
>     WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled) Line 2485    C#
>     WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled) Line 341    C#
>     WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o) Line 494    C#
>     WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs) Line 104 C#
>     WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler) Line 37 C#
>     WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs) Line 1445 C#
>     WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam) Line 392 C#
>     [Native to Managed Transition]  
>     user32.dll!__InternalCallWinProc@20() Line 116  Unknown
>     user32.dll!UserCallWinProcCheckWow(_ACTIVATION_CONTEXT \* pActCtx, void \* pfn, HWND__ \* hwnd, _WM_VALUE msg, unsigned int wParam, long lParam, void \* fEnableLiteHooks, int) Line 184    C
>     user32.dll!DispatchMessageWorker(tagMSG \* pmsg, int fAnsi) Line 2931    C
>     user32.dll!DispatchMessageW(const tagMSG \* lpMsg) Line 1002 C
>     msenv.dll!MainMessageLoop::ProcessMessage(IMsoStdComponentMgr \* pstdcm, IVsWindowManager \* pIVsWindowManager, tagMSG & msg) Line 1530   C++
>     msenv.dll!CMsoCMHandler::EnvironmentMsgLoop() Line 450  C++
>     msenv.dll!CMsoCMHandler::FPushMessageLoop(unsigned long uReason) Line 358   C++
>     msenv.dll!SCM::FPushMessageLoop(SCMI \* pscmi, unsigned long uReason, void \* pvLoopData) Line 2262   C++
>     msenv.dll!SCM_MsoCompMgr::FPushMessageLoop(unsigned long dwComponentID, unsigned long uReason, void \* pvLoopData) Line 2998 C++
>     msenv.dll!CMsoComponent::PushMsgLoop(unsigned long msgloop) Line 705    C++
>     msenv.dll!VStudioMainLogged() Line 1187 C++
>     msenv.dll!VStudioMain(MAINPARAM \* pMainParam) Line 1268 C++
>     devenv.exe!util_CallVsMain(MAINPARAM \* pMainParam, int \* piRes) Line 1084   C++
>     devenv.exe!CDevEnvAppId::Run(wchar_t \* wszCmdLine, int nCmdShow) Line 759   C++
>     devenv.exe!WinMain(HINSTANCE__ \* hInstance, HINSTANCE__ \* __formal, char \* lpCmdLine, int nCmdShow) Line 64 C++
>     devenv.exe!__scrt_common_main_seh() Line 264    C++
>     kernel32.dll!BaseThreadInitThunk(unsigned long RunProcessInit, long(__stdcall_)(void _) StartAddress, void \* Argument) Line 64  C
>     ntdll.dll!__RtlUserThreadStart(long(__stdcall_)(void _) StartAddress, void \* Argument) Line 997 C
>     ntdll.dll!_RtlUserThreadStart(long(__stdcall_)(void *) StartAddress, void \* Argument) Line 914  C

Parameters in EnsurePageLoaded method:
-  pVsPropPage 0x13dc7378 {m_bstrName=L"General" m_bstrHelpKeyword=L"VS.ToolsOptionsPages.GitHub_for_Visual_Studio.General" ...} CVsPropPage *
-  m_bstrName L"General" ATL::CComBSTR
-  m_bstrHelpKeyword L"VS.ToolsOptionsPages.GitHub_for_Visual_Studio.General" ATL::CComBSTR
  m_lNameId 0 long
-  m_guidPage {68C87C7B-0212-4256-BB6D-6A6BB847A3A7} _GUID
-  m_clsidPackage {C3D3DC68-C977-411F-B3E8-03B0DCCF7DFC} _GUID
  m_dwPageId 147 unsigned long
  m_lSort 2147483647 long
  m_lTbxSort 2147483647 long

**Comment by paladique** [comment]
I tried to reproduce this with no luck

Here a few scenarios I tried when opening Tools -> Options:
- While a non-GitHub hosted solution was open
- While a non-GitHub hosted solution was not open
- While a solution not under any source control was open
- While the Pull Request Pane was open
- With two instances of VS open
- Opened Tools -> Options from within the Extensions Window (clicked on "Change your extensions and updates settings")

I think the only difference between these two scenarios is that I'm on Update 3

@g233007 thanks for letting us know about this, I know it's happening at random times, but if you have any additional information about this that could be helpful we'd appreciate it (what you were doing/what you had open before the crash).
