### ISSUE TITLE
"Ignore on commit" list of files

### ISSUE THREAD

**Issue by tompazourek** [github/VisualStudio#445]
My workflow using VS Github extension is the following:

- I pick files from Changes and stage them
- I have some modifications (usually tweaks in various config files) in Changes that I never want to commit (but I still want the files to be tracked and in the repository)
- I need to pay close attention not to accidentally stage and commit those files (since I want the original version of them in repository, not my changed one with various personal tweaks)

The problem is that making sure that some changes aren't committed is both time consuming and error prone. If only there was some way that I could move those files to some kind of "Ignore on commit" list that I used to use in the old days of SVN.

I found that it is possible to do something similar with this git command:

```
git update-index --assume-unchanged 
```

I've tried that, but the problem with that is that I don't see those "assume-unchanged" files in any list and sometimes I need an overview of those files as well -- especially when I am moving those files or doing some actual changes in them, it would be useful to see those files and easily undo "no-assume-unchanged" on them. Also the point of using Github for VS is that I prefer not to interact with git through the command line.

**Is there some solution to my problem?**

I'm not completely sure if it's within the scope of VS or the extension.

Thanks a lot.

*(VS 2015 Update 2, Github for VS 1.0.18.6)*

**Comment by paladique** [comment]
Hi @tompazourek! Thanks for the detailed Issue! Unfortunately, this is within the scope of VS's git integration, so someone from [VS's support team](https://www.visualstudio.com/support/support-overview-vs) would probably be your best bet for a good answer.

**Comment by JeromeJ** [comment]
Hi! Has this been opened in another repo? I also need to have some files on "assume-unchanged" for the same reasons and would LOVE being able to still see a list of them somewhere. 

Like TortoiseSVN does in the Pending changes window:
![image](https://user-images.githubusercontent.com/650065/57528517-d88a1d80-7332-11e9-9f39-5323c3662f55.png)

If Visual Studio's git integration doesn't want to implement it, do we need to find another tool or make one? (to list said files)
