### ISSUE TITLE
Getting "Validation Failed" error message when trying to create PR

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#453]
Using the new 2.0 RC I'm getting a "Validation Failed" message when trying to create a PR:

![image](https://cloud.githubusercontent.com/assets/1775141/17182677/a2caa44c-5424-11e6-8fa4-708cdbc4d617.png)

**Comment by grokys** [comment]
This is happening because there is already a PR for the branch that I'm trying to create a PR for. The error that triggers the "Validation Failed" message is a `Octokit.ApiValidationException` and has the following information in its `HttpResponseBodySafe` property:

```
{"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"A pull request already exists for ouchmyfoothurts:test1."}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
```

So it looks like we need to parse the HTTP response to show a more meaningful error message.

**Comment by MelannieTorres-academico** [comment]
I had a similar problem, the branch I was trying to make the PR to wasn't published, to fix it I changed to the branch I was creating the PR to ran: git push -u origin MY_BRANCH and tried to do the PR again :) Hope this is useful for somebody!
