### ISSUE TITLE
Use PR template if it exists when creating PRs

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#463]
We're currently ignoring PULL_REQUEST_TEMPLATE.md and .github/* files in the PR creation form, and we should use templates to pre-fill the description, if the templates exist.

**Comment by grokys** [comment]
Desktop's behavior is also often useful to me where it auto-fills the PR title/comments with information from the commits in the branch. I'm not sure what the algorithm is there though.

**Comment by shana** [comment]
It does it if there's only one commit iirc. If there's more than one, it only fills in the title with the branch name. I usually don't use it because of that.

**Comment by grokys** [comment]
I find it quite useful, and I've been missing it when working with the new 2.0 RC. I agree that the template would be useful also. Not sure how the two could be combined...
