### ISSUE TITLE
Checkmark on Login Button icon Missing

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#467]
The check mark on the Login Button icon and Create button icon isn't visible when trying to login into the GitHub Extension. 

Not sure if this is the new design for V2.0.0.1.

**Steps to reproduce:**
- Launch Microsoft Visual Studio Enterprise
- Click "Connect" to login to GitHub Extension
- Enter valid credentials

**Expected** - Checkmark is expected in the login button icon. ![login](https://cloud.githubusercontent.com/assets/17054747/17309810/8dd68c7a-57f5-11e6-8ab2-ea29ebd95dad.png)

**Actual** - Checkmark not seen in the login button icon ![snip20160801_5](https://cloud.githubusercontent.com/assets/17054747/17309804/7f5805d4-57f5-11e6-9973-c802eb699691.png)

- GitHub Extension version: 2.0.0.1
- Visual Studio version: 14.0.25424.00

**Screenshot attached below:** 

![snip20160801_5](https://cloud.githubusercontent.com/assets/17054747/17309804/7f5805d4-57f5-11e6-9973-c802eb699691.png)

![login](https://cloud.githubusercontent.com/assets/17054747/17309810/8dd68c7a-57f5-11e6-8ab2-ea29ebd95dad.png)

**Comment by shana** [comment]
Yup, definitely a regression from 1.0.18.6, some styling change somewhere. Not critical for the release. We need to bisect and track down what broke it.
