### ISSUE TITLE
Cannot Create Repo or Publish Local Repo. 

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#469]
User can't currently create Repo or publish local repo to GitHub using the GitHub extension for Visual Studio.
Visual Studio returns this message - "_Versions of GitHub Extension for Visual Studio prior to 1.0.14 are not allowed to create new public repositories. Please upgrade your extension in Tools - Extensions and Updates_". Version conflict?

**Steps to reproduce**
- Launch Microsoft Visual Studio Enterprise for windows.
- Click "Connect" to login to GitHub Extension
- Enter valid credentials and login.
- Click create on the GitHub frame
- Enter repo name, description, and click the create button.

**Expected result** - A new repo should be created, which is visible in the GitHub frame of Visual Studio and also available on dot com.

**Actual result** - New repo isn't created and an error message is returned to why new repo wasn't created

**NOTE** -  This also happens when you try to publish a local repo to GitHub.

Screenshot attached below:
- GitHub Extension version: 2.0.0.1
- Visual Studio version: 14.0.25424.00 (Enterprise 2015)

![image](https://cloud.githubusercontent.com/assets/17054747/17379086/99a856c4-5975-11e6-9f99-bebae7947c36.png)

![snip20160803_15](https://cloud.githubusercontent.com/assets/17054747/17379115/c88155f4-5975-11e6-840f-5eb73cfe7da5.png)

![snip20160803_16](https://cloud.githubusercontent.com/assets/17054747/17379127/d3a3aec8-5975-11e6-954b-9d5c6d04536c.png)

![snip20160803_17](https://cloud.githubusercontent.com/assets/17054747/17379131/da46f456-5975-11e6-8ec4-aeb37ee46426.png)

![snip20160803_18](https://cloud.githubusercontent.com/assets/17054747/17379142/e19e7a62-5975-11e6-9fc6-4912598955e8.png)

**Comment by StanleyGoldman** [comment]
I tried to reproduce this issue with v2.0.15.1, and I was unable to.

**Comment by paladique** [comment]
This was resolved internally. Closing.
