### ISSUE TITLE
Open on GitHub sometimes 404s when path contains upper case

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#472]
- GitHub Extension version: 1.0.18.6
- Visual Studio version: 2015 Update 3

Right click on code windows and select 'GitHub > Open on GitHub'. If the source file or directory contains an upper case char, the GitHub page sometimes opens with a 404.

It appears there is an issue with Visual Studio. If a source file was opened automatically when a solution loads, `Document.Name` will return an all lower case path. If the user explicitly opens the document after the solution loads, the path will contain upper and lower chase chars es expected.

You can see what's happening here. I've executed the `go` method using TestDriven.Net's `Test With > In-Proc` command:

![document name](https://cloud.githubusercontent.com/assets/11719160/17396327/d26d411c-5a2a-11e6-9ef2-b50c1a735e17.png)

The highlighted `netcoretestrunnerlibrarytests.cs` was opened with the solution, but `Scratch.cs` was opened (or created) after the solution was opened. You can see `ProjectItem.Name` always returns a path with the expected casing, but with `Document.Name` it varies.

I'm guessing you could fix it by changing the following line:
https://github.com/github/VisualStudio/blob/master/src/GitHub.VisualStudio/Menus/LinkMenuBase.cs#L21

to...

`return repo.GenerateUrl(activeDocument.ProjectItem.Name, activeDocument.StartLine, activeDocument.EndLine);`

I hope that's useful. :smile: 

You can find discussion about it on Twitter here:
https://twitter.com/jcansdale/status/760547405926395904

**Comment by paladique** [comment]
This property is only returning the file name, and not the complete path, which is causing the copy/open links to fail, reopened because this change was reverted. The next step is to check the other properties in `Services.Dte2?.ActiveDocument?` to find a property that returns the full path with the proper casing.

**Comment by jcansdale** [comment]
Hello @paladique,

It seems there are (at least) 4 possibilities, but fortunately one of them gives the correct answer. 😄

The following test code:

```
        void dump(DTE dte)
        {
            var doc = dte.ActiveDocument;
            Console.WriteLine("Name: " + doc.Name);
            Console.WriteLine("FullName: " + doc.FullName);
            Console.WriteLine("ProjectItem.Name: " + doc.ProjectItem.Name);
            Console.WriteLine("ProjectItem.FileNames[1]: " + doc.ProjectItem.FileNames[1]);
        }
```

Outputs this:

```
Name: class1.cs
FullName: c:\source\scratch\classlibrary2\class1.cs
ProjectItem.Name: Class1.cs
ProjectItem.FileNames[1]: C:\Source\Scratch\ClassLibrary2\Class1.cs
```

I looks like `doc.ProjectItem.FileNames[1]` is what you need.

It seems that `[1]` can be any number and return the same path (at least for C# projects). It's probably safest to stick with 1.

**Comment by paladique** [comment]
Unfortunately we can't rely on  `ProjectItem.FileNames[1]`, because there is the [possibility ](https://msdn.microsoft.com/en-us/library/envdte.projectitem.filenames.aspx#Anchor_1) that more than one file can be associated with a ProjectItem. (ie. aspx/aspx.cs)

**Comment by shana** [comment]
@paladique As per the discussion last week, it's likely that we can figure out which of the entries in `Filenames` is the right one by comparing it to the ActiveDocument name and then extracting the correct case path from `Filenames`

**Comment by jcansdale** [comment]
@paladique I wondered about that at the time, and did try it with a source file that also had a designer. I've now tried it with .resx/.cs and .aspx/.cs/designer.cs items. I haven't found a situation where `doc.Filename` and `doc.ProjectItem.FileNames[1]` are different (except for the casing).

Here I'm testing it with aspx/aspx.cs:
![aspx](https://cloud.githubusercontent.com/assets/11719160/19329691/103c0eaa-90d2-11e6-8966-8b12d8aef169.png)

I'd be interested to know for sure, but I get the impression that the use of multiple backing files is pretty unusual/exotic. 😄
