### ISSUE TITLE
PR creation error messages not shown sometimes

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#475]
After dismissing the "Source and target branch cannot be the same" message once, and then leaving the PR creation UI and coming back, the error message stops being shown.

![error-message-not-shown](https://cloud.githubusercontent.com/assets/310137/17477504/f41b357e-5d65-11e6-9b40-59b0f9ff2885.gif)

The "PR already exists" message is not getting shown at all, I couldn't get it to work, the button just stays grey after the first submission.

**Comment by grokys** [comment]
This seems to be fixed now for me. Can you still repro?

**Comment by paladique** [comment]
Confirming this is fixed 👍
