### ISSUE TITLE
PR Creation: Cancel doesn't clear form

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#479]
If the PR creation is cancelled, the next time the form is opened it still contains the data filled in before the user cancelled.

**Comment by grokys** [comment]
I assume that here both "Cancel" and "Create pull request" should clear the form, but navigating away using the Back toolbar button shouldn't?

**Comment by shana** [comment]
That sounds about right, given user expectations. Might have to add some specific navigation actions to the UIController, since at the moment there's no difference between Cancel and Back.

**Comment by grokys** [comment]
This is now fixed.
