### ISSUE TITLE
Publish stays on Synchronization page

### ISSUE THREAD

**Issue by abuchholtzau** [github/VisualStudio#48]
After publishing a new repository to GitHub, the TE view stays on the publish page (pictured), instead of switching to the Home view.
![screenshot 25](https://cloud.githubusercontent.com/assets/3174849/9232684/e31bfadc-40e3-11e5-8853-c0c30e381057.png)

**Comment by shana** [comment]
@abuchholtzau Thanks, I'll look into it! Does it happen consistently for you?

**Comment by abuchholtzau** [comment]
Yup. I've tried it a couple of times and it's always the same behavior.

On Wednesday, August 12, 2015, Andreia Gaita <notifications@github.com>
wrote:

> @abuchholtzau <https://github.com/abuchholtzau> Thanks, I'll look into
> it! Does it happen consistently for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/VisualStudio/issues/48#issuecomment-130410004>.
>


-- 
Allison Buchholtz-Au
Harvard College '15
A.B. Candidate in Computer Science
