### ISSUE TITLE
Closing a PR on the website does not show it as closed on the list

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#481]
I closed a PR on the website so I could create a new PR from the extension for the same branch. The new one shows up, but so does the old one, both in the "Open" filter. The date on the new PR is updating every time I refresh, so for some reason it seems the status is not updating on the old PR, so the list thinks it's open when it's not.

**Comment by grokys** [comment]
This also appears to be happening with new PRs being opened on the site. However after a certain amount of time (not sure, about 5 mins?) it updates. Related #407.

**Comment by grokys** [comment]
Fixed by 009d24e47f51fc8526f2994e93790ddfc61cda83
