### ISSUE TITLE
Switch to serilog for logging

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#483]
We need a logging framework that is small, doesn't block, doesn't blow up, is reliable, easy to configure.
[Serilog](https://github.com/serilog/serilog) seems to fit this bill way better than NLog does.

**Comment by StanleyGoldman** [comment]
I've never used Serilog before, I've usually fall back on NLog, but I didn't mind the excuse to check it out.

This extension helps, [Visual Studio Gallery - Serilog Analyzer](https://visualstudiogallery.msdn.microsoft.com/b00c584e-71c0-4e5f-85ab-a3d2347a053c), it adds a few code analyzers to make sure you are using serilog correctly. [Github - Serilog Analyzer](https://github.com/Suchiman/SerilogAnalyzer#user-content-analyses)
