### ISSUE TITLE
Branch dropdown in "Create PR" view should be for destination branch not source branch

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#486]
Somehow these got swapped at some point in development!

**Comment by calloncampbell** [comment]
When creating PR, why can't I change the destination (left side) branch? We don't merge everything by default into the "master" branch. We have a "develop" branch and only merge into this. 

Please fix. The integration into VS looks promising.

**Comment by grokys** [comment]
Hi @calloncampbell - yes apologies for this. Things somehow got mixed up in development and nobody noticed until the new version was almost out. This will be fixed in the next update.
