### ISSUE TITLE
 Icons in solution explorer are missing and/or don't update when they should.

### ISSUE THREAD

**Issue by mwoffenden** [github/VisualStudio#512]
- GitHub Extension version: latest
- Visual Studio version: latest

__What happened__

Most of the time (50% or more),  icons in solution explorer are missing and/or don't update when they should.  Specifically:

- On project load, NO icons appear at all. 
- Icons don't update during some operations, such as adding a file.
- The icon at the root of the solution is missing, but appears for the items in solution folders.

**Comment by shana** [comment]
Hi @mwoffenden. Sorry to hear you're having issues there, but the GitHub Extensio for Visual Studio doesn't have any icons in Solution Explorer. That's either a bug in VS itself or another extension. Git support in VS is done by Microsoft, so if you're referring to that, you should send a bug report to MS via the feedback tool in Visual Studio.

**Comment by mwoffenden** [comment]
@shana - are you saying that the GitHub Extension has nothing to do with how the icons are displayed?
