### ISSUE TITLE
How to signing with GPG when I commit changes?

### ISSUE THREAD

**Issue by 772807886** [github/VisualStudio#513]
I have been setted up "commit.gpgsign" and "user.signingkey" in .gitconfig. And when I commit changes use command in Git Bash, it works, I must type in my password before commit.
And now, how to signing with GPG when I commit changes in GitHub Extension?

**Comment by shana** [comment]
Git actions in Visual Studio (commit, push, pull, sync, etc) are implemented by Microsoft, not by the GitHub extension, so we can't do much about this. You should use the feedback tool in Visual Studio to report this to Microsoft so that they're aware of the issue.

**Comment by weitzhandler** [comment]
For the reference: https://developercommunity.visualstudio.com/idea/531972/let-the-git-plugin-to-sign-commits-with-gpg-key-wi.html

Related: #260.
