### ISSUE TITLE
Opening same folder in different window will redirect to opened window instead of opening folder in new window

### ISSUE THREAD

**Issue by hansyulian** [github/VisualStudio#519]
Hello! Please read the contributing guidelines before submitting an issue.

- GitHub Extension version:
- Visual Studio version: 1.4

__What happened__ (with steps, logs and screenshots, if possible)

I am working with multi monitor and need to focus in a project folder, so i open a window like this:
![image](https://cloud.githubusercontent.com/assets/10959546/17955111/616d23fe-6ab2-11e6-8a94-e99a909887a9.png)

Then i open a project folder like this
![image](https://cloud.githubusercontent.com/assets/10959546/17955133/8d180e10-6ab2-11e6-836a-5d670833316c.png)

Since i working with dual monitor, and i need to take a look at same folder for reference, i open another visual studio code
![image](https://cloud.githubusercontent.com/assets/10959546/17955149/a9412b58-6ab2-11e6-9c4c-b07389fd454e.png)

And open the same folder again
![image](https://cloud.githubusercontent.com/assets/10959546/17955160/b627efdc-6ab2-11e6-8c67-d0faeacf9e2d.png)

Instead of opening the folder in the new window, the app focused to the previous one that i have already opened
![image](https://cloud.githubusercontent.com/assets/10959546/17955174/cb2b40aa-6ab2-11e6-9ef1-11ba2500bf3c.png)

I believe that this behavior is not unintentional, means you really put a code that behave to check and focusing like this instead of default possibility where the window will open the same folder. This is annoying especially for multi monitor worker. Please change the behavior

**Comment by shana** [comment]
It looks like your issue is on Visual Studio Code. This repo is for the GitHub Extension for Visual Studio 2015+, so we can't help you with this. You should file your issue on https://github.com/Microsoft/vscode

**Comment by hansyulian** [comment]
oh man, sorry for the confusion, yea, this is for visual studio code
