### ISSUE TITLE
Visual Studio Community 2013 Support

### ISSUE THREAD

**Issue by SirJosh3917** [github/VisualStudio#525]
I downloaded the extention, and ran it, and it gave me an error.

As you can see by the log below, I have three products for it to install on, however it doesn't support those products. Those products being 

`8/27/2016 9:57:35 PM - Found installed product - Microsoft Visual Studio Community 2013
8/27/2016 9:57:35 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
8/27/2016 9:57:35 PM - Found installed product - Microsoft Visual Studio Express 2013 for Windows `

And as you can see, `8/27/2016 9:57:35 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.`

Here is the error log:

`8/27/2016 9:57:34 PM - Microsoft VSIX Installer

8/27/2016 9:57:34 PM - -------------------------------------------

8/27/2016 9:57:34 PM - Initializing Install...

8/27/2016 9:57:35 PM - Extension Details...

8/27/2016 9:57:35 PM - 	Identifier      : c3d3dc68-c977-411f-b3e8-03b0dccf7dfc

8/27/2016 9:57:35 PM - 	Name            : GitHub Extension for Visual Studio

8/27/2016 9:57:35 PM - 	Author          : GitHub, Inc

8/27/2016 9:57:35 PM - 	Version         : 2.0.14.4

8/27/2016 9:57:35 PM - 	Description     : A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

8/27/2016 9:57:35 PM - 	Locale          : en-US

8/27/2016 9:57:35 PM - 	MoreInfoURL     : https://visualstudio.github.com/

8/27/2016 9:57:35 PM - 	InstalledByMSI  : False

8/27/2016 9:57:35 PM - 	SupportedFrameworkVersionRange : [4.5,)

8/27/2016 9:57:35 PM - 

8/27/2016 9:57:35 PM - 	Supported Products : 

8/27/2016 9:57:35 PM - 		Microsoft.VisualStudio.Community

8/27/2016 9:57:35 PM - 			Version : [14.0,)

8/27/2016 9:57:35 PM - 

8/27/2016 9:57:35 PM - 	References      : 

8/27/2016 9:57:35 PM - 		-------------------------------------------------------

8/27/2016 9:57:35 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0

8/27/2016 9:57:35 PM - 		Name         : Visual Studio MPF 14.0

8/27/2016 9:57:35 PM - 		Version      : [14.0,)

8/27/2016 9:57:35 PM - 		MoreInfoURL  : 

8/27/2016 9:57:35 PM - 		Nested       : No

8/27/2016 9:57:35 PM - 

8/27/2016 9:57:35 PM - 

8/27/2016 9:57:35 PM - Searching for applicable products...

8/27/2016 9:57:35 PM - Found installed product - Microsoft Visual Studio Community 2013

8/27/2016 9:57:35 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)

8/27/2016 9:57:35 PM - Found installed product - Microsoft Visual Studio Express 2013 for Windows Desktop

8/27/2016 9:57:35 PM - Found installed product - Global Location

8/27/2016 9:57:35 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on 
any currently installed products.

   at VSIXInstaller.App.InitializeInstall()

   at System.Threading.Tasks.Task.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()`

**Comment by mbrehmer** [comment]
I have the same issue with Visual Studio 2013 **Ultimate**, if I try to install the package manualy.

If I try to install the GitHub Extensions via Visual Studio's Extensions-Manager, I get version 0.5!
That's very unfortunate, because I work alot with Git(Hub).

**Comment by shana** [comment]
The extension doesn't support VS 2013, mostly because we use a bunch of APIs that weren't available before VS 2015. We would have to cut some features to be able to do a port to VS2013, and we have limited resources to support everything. I'd love to be able to support all versions of VS, but it just isn't feasible at this time.
