### ISSUE TITLE
[Feature request] Commit Description box

### ISSUE THREAD

**Issue by StarlightNL** [github/VisualStudio#526]
This is not a bug but more a feature request.
I love this Visual Studio plugin but one thing bothers me.
A lot of the times my commit messages look like this
![screenshot_1](https://cloud.githubusercontent.com/assets/7126102/18033450/2261fbb0-6d25-11e6-85e1-160ffbb74414.png)

The textbox doesn't take the maximum length for a commit message in account. It coult be better if it does.
The other thing is that there could be another text box for more details of the commit.

I hope this feature could be implemented soon for a better experience.

**Comment by shana** [comment]
The commit box isn't a part of this extension, it's a part of the Git support made by Microsoft and built-in to Visual Studio. I know it's hard to figure out which bits are the GitHub Extension and which bits are the built-in Git support, we have some trouble with that too sometimes!

You should submit this feedback to Microsoft via the feedback tool in Visual Studio, so they can improve it.
