### ISSUE TITLE
Octokat Image/Logo Missing on Welcome Page

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#533]
- GitHub Extension version: 2.0.15.0
- Visual Studio version: Dev15 preview 4
- Environment: Windows 8 and 10

**Steps to reproduce**
- Install the new [Visual Studio Dev15 Preview 4](https://go.microsoft.com/fwlink/?LinkId=733434)
- Launch after downloading Dev15 P4
- Download and install GHfVS 
- Close and relaunch Dev15 if it was still opened.

Actual result - GitHub extension is seen on the welcome page without the octokat logo
Expected result - Octokat logo should be seen with GitHub on the welcome page

Screenshot attached below:

![snip20160831_3](https://cloud.githubusercontent.com/assets/17054747/18142402/40fb2c1e-6f72-11e6-8f0a-acd9112b9ca1.png)

**Comment by shana** [comment]
Weird, I got that in the experimental instance but not in the normal one.

**Comment by paladique** [comment]
Closing this one since there is active discussion going on about this in #655
