### ISSUE TITLE
GitHub pane doesn't recognise enterprise repositories.

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#534]
On latest master GitHub pane doesn't recognise an enterprise repository:

![download](https://cloud.githubusercontent.com/assets/1775141/18238297/de8980da-733b-11e6-96f6-d7fe92a188dd.gif)

Reported by @brntbeer .

**Comment by grokys** [comment]
It seems `EnterpriseProbeTask` is failing with "A task was cancelled" here:

https://github.com/github/VisualStudio/blob/master/src/GitHub.Exports/Services/EnterpriseProbeTask.cs#L41

**Comment by grokys** [comment]
It seems that the request to `https://ghe.io/site/sha` is timing out. The timeout is currently 3 seconds but increasing that doesn't change the result: it still times out. Navigating to the URL in the browser however returns an SHA immediately.

**Comment by shana** [comment]
So it might be a difference in headers that are sent, maybe?

**Comment by grokys** [comment]
The only header being sent in the request is the user agent. Has enterprise changed recently to require auth when reading `/site/sha`?

**Comment by grokys** [comment]
Hmm it doesn't seem so - navigating to that URL from an incognito window works.

**Comment by shana** [comment]
So the only difference between a browser and our request is the headers that get sent. If you do it via curl on the command line, does it work? Is DNS being slow and our timeout too short perhaps?

**Comment by grokys** [comment]
Curl works fine. I've tried adding the headers that chrome sends in incognito mode and still timing out. Going to try to look at it with fiddler.

**Comment by grokys** [comment]
With fiddler running, request succeeds.

**Comment by shana** [comment]
lol

So it's what, DNS or the ssl certificate?
