### ISSUE TITLE
Extension does not respect VS project directory setting.

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#536]
Visual Studio 2015.3 / Extension 2.0.15.1

I have a path set in my VS settings for projects:

![image](https://cloud.githubusercontent.com/assets/1775141/18270722/c0efa326-742e-11e6-80e2-6ba916ee6e2d.png)

However, the extension doesn't use this path as the default base path when cloning a repo:

![image](https://cloud.githubusercontent.com/assets/1775141/18270740/d2bbe2ae-742e-11e6-9fe5-2686bca48a23.png)

**Comment by shana** [comment]
The clone path is not the same as the project path. The default clone path is set in VS in the git global settings (click on the `Home` title in Team Explorer, then `Settings` - `Global Settings`).

**Comment by grokys** [comment]
Ah - i wasn't aware that there was a separate setting for this. Closing.
