### ISSUE TITLE
Inline commit comments

### ISSUE THREAD

**Issue by paladique** [github/VisualStudio#549]
A helpful feature for a maintainer's workflow would be inline comments where users can always comment on any file line whose commit is available remotely, regardless of whether they're reviewing a particular PR or not

The initial flow envisioned is:
- Add right-click/quick action to comment on a file line
- Open the comment box on GitHub **or**
- Open a popup in VS **or**
- Open an inline window

**Comment by paladique** [comment]
The possibility of taking the user to GitHub to the specific line with the comment box exposed doesn't seem obvious at this moment. More investigation into this is probably needed. 

Octokit has [already provided](https://github.com/octokit/octokit.net/pull/413) the functionality to add/modify inline comments. This would provide easy access via inline window and/or popup through VS.

One question that comes to mind, and this may not be a priority at this time, do we want the user to have access to existing comments on the current page they are on? Could see this as a handy feature for a contributor.

**Comment by shana** [comment]
> The possibility of taking the user to GitHub to the specific line with the comment box exposed doesn't seem obvious at this moment. More investigation into this is probably needed.

Darn. Does that mean that there's no way of having a url that opens a commit with the comment box open?

> One question that comes to mind, and this may not be a priority at this time, do we want the user to have access to existing comments on the current page they are on? Could see this as a handy feature for a contributor.

Oh yes, definitely, we need to eventually figure out how to do this.

**Comment by capone3691** [comment]
Awesome features

**Comment by shana** [comment]
An option here is to do a custom "Peek Definition" window for the comment box. Need to figure out how to customize one of those to have a button for submitting and be triggered by a context menu.

**Comment by shana** [comment]
This is a test I put together to try and figure out how to do this: https://github.com/shana/PeekTest

**Comment by mikeblakeuk** [comment]
This would be ace.
I would love to see comments that are within GitHub on a source, with in visual studio.
That way, i could just open visual studio and fix each one.
I guess like this https://www.visualstudio.com/en-us/docs/git/pull-requests

**Comment by meaghanlewis** [comment]
Closing this issue out as inline comments was released in [v2.3.0.24](https://github.com/github/VisualStudio/releases/tag/v2.3.0.24).
