### ISSUE TITLE
Add current branch context to Visual Studio

### ISSUE THREAD

**Issue by Haacked** [github/VisualStudio#55]
Take a look at this screenshot.

![vs](https://cloud.githubusercontent.com/assets/19977/9506955/01aff062-4c00-11e5-8844-1c397b48c35d.png)

When you're working in Git, what's one of the most important pieces of context you need to know? Yep! What branch am I in? So how do I find that out today? I have to navigate to Team Explore and then click on Branches.

We should put this context front and center. Bonus if we can also provide a branch picker right there. Here's a couple of ideas.

![vs-branch-titlebar](https://cloud.githubusercontent.com/assets/19977/9507024/55a782fc-4c00-11e5-9c06-bf7e5053db7c.png)

![vs-branch-footer](https://cloud.githubusercontent.com/assets/19977/9507025/55a7bc0e-4c00-11e5-9722-46ecd1563b27.png)

I'm not sure if we can do this or if it requires the VS team to do it, but I thought I'd log it here for discussion.

**Comment by Haacked** [comment]
Or should this be in the Solution Explorer somewhere?

**Comment by shana** [comment]
Yeah, I don't know if either of those options is doable via extension, but the branch should definitely be displayed somewhere. I'll poke around and see what's possible.

**Comment by Haacked** [comment]
I'm going to close this in lieu of the [existing UserVoice issue on the same topic](http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2187775-help-me-know-what-branch-i-m-working-on).

**Comment by shana** [comment]
Ah yes, that would be a handy thing for VS to do.

**Comment by hanksjosh** [comment]
VsCommands puts the branch name in the title bar of VS.  http://vscommands.squaredinfinity.com/Features-SolutionBadges
