### ISSUE TITLE
Changes resets to zero, cannot commit.

### ISSUE THREAD

**Issue by itskaizad** [github/VisualStudio#550]
Hello! Please read the contributing guidelines before submitting an issue.

- GitHub Extension version: 2.0.15.1
- Visual Studio version: Enterprise 2015 Update 3

__What happened__ (with steps, logs and screenshots, if possible)
The changes counter resets to zero every time I open my Unity project in Visual Studio. Hence, I cannot commit anything since that option is unavailable when you have no changes. GitHub Desktop (Windows app) does show the changes correctly.
![desktop](https://cloud.githubusercontent.com/assets/6906507/18489592/1c97fec4-79cc-11e6-9b6a-a0684b3175a8.PNG)

![vs_toolbar](https://cloud.githubusercontent.com/assets/6906507/18489504/cee4cb26-79cb-11e6-95c8-e6f5f5336368.PNG)

**Comment by shana** [comment]
Hi! The GitHub Extension doesn't handle git operations inside Visual Studio, that's implemented by Microsoft separately, so we can't really help you there. You should report this to Microsoft via the feedback tool in Visual Studio.
