### ISSUE TITLE
Add sign-in button to Repository Home Page

### ISSUE THREAD

**Issue by Haacked** [github/VisualStudio#56]
When the user is unauthenticated and they visit a repository's home page in team explorer, we should provide a visual indication that they are not logged in and an option to log in. Something like this:

<img src="https://cloud.githubusercontent.com/assets/19977/9507744/18665ac6-4c05-11e5-9643-bc9eae826c02.png" width="430" alt="Home page with sign in button" />

When they log in, the "sign in..." button goes away.

**Comment by shana** [comment]
Oh wow, yes, of course we should be doing this! :100:
