### ISSUE TITLE
Login fails with Valid credentials

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#563]
- GitHub Extension version: v2.0.15.2
- Visual Studio version: 14.0.25424.00 Update 3

GHfVS login fails with valid credentials.

**_Steps to reproduce:_**
**1. Launch Visual Studio pre-installed with GHfVS extension.
2. Log out if you are previously logged in.
3. Click on Connect on GitHub pane.
4. Type valid credentials and click login.**

**Actual** - User with valid credentials can't login
**Expected** - User should login to GitHub extension with Valid credentials 

NOTE - This is sporadic and below is the message from the logs until we have [better logs](https://github.com/github/VisualStudio/issues/547)

2016-09-26 08:29:45.2566|INFO|thread:15|RepositoryHost|Log in to github.com host 'https://api.github.com/' with username 'evilfemi': Bad credentials
Bad credentials
2016-09-26 08:29:45.2915|INFO|thread: 1|RepositoryHosts|Log in to GitHub.com host 'https://api.github.com/' with username 'evilfemi' FAILED

**Comment by femisimon** [comment]
@grokys I was able to reproduce this using invalid credentials which are denied and using valid credentials which should be authorized but are also denied.

![snip20161018_78](https://cloud.githubusercontent.com/assets/17054747/19497781/c94419d2-9542-11e6-92a6-f1f0022bc3ca.png)

**Comment by grokys** [comment]
I think this should be fixed after recent fixes to .com.
