### ISSUE TITLE
Investigate the Create Pull Request Context menu 

### ISSUE THREAD

**Issue by paladique** [github/VisualStudio#568]
When working on a GitHub hosted repo in the Team Explorer window, if you navigate to Branches and right click on a branch, a context menu pops up with a greyed out "Create Pull Request" option.

(thanks for letting us know @jonico!)

![create pr greyed out](https://cloud.githubusercontent.com/assets/1414307/18933545/46e8c6da-85a3-11e6-9c87-246d532ec12f.jpg)

**Comment by paladique** [comment]
Marked this as a thing to investigate because I'm not sure if this is an command we can control

**Comment by paladique** [comment]
Uninstalled the extension to see if it goes away when uninstalled and it doesn't, it's enabled when the project is hosted by VSTS.

**Comment by shana** [comment]
We've figured this one, closing!
