### ISSUE TITLE
Sync Button should launch login dialog for unauthenticated users

### ISSUE THREAD

**Issue by Haacked** [github/VisualStudio#57]
Today, if a user clicks the "Sync" button and tries to sync a GitHub.com repository, they'll receive the standard basic authentication dialog. This will work fine if the user is not using two factor authentication (2fa). But if they are using 2fa, this is not a nice experience.

Instead, if the user clicks Sync, we should launch our own login dialog. And after the user logs in, we should take them to the Sync page (if possible) though it'd be fine to take them back to the home screen and let them click Sync again.

There's a few ways we might be able to accomplish this.

1. Hide the Sync button for unauthenticated users viewing a GitHub.com repository and add our own "Sync" button that launches the login dialog and then navigates to the Sync page.
2. Hook into the Sync button and override the event handling to launch our dialog. (I have no idea if this is possible).
3. We don't show the Team Explorer section and rebuild the whole section ourselves (ewww!)
4. Something else that people more knowledgeable about Team Explorer might think up.

Also, we need to make sure we don't forget to also hijack the menu if possible.

<img src="https://cloud.githubusercontent.com/assets/19977/9507891/2aa29e74-4c06-11e5-8c60-ef4fd1d58e79.png" width="430" />

**Comment by shana** [comment]
I'm almost certain that if we hide the Sync button, the context menu entry will also be hidden, they're sync'd :smile:
