### ISSUE TITLE
Object reference not set to an instance of an object when creating Pull Request

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#576]
- GitHub Extension version: v2.0.15.2
- Visual Studio version: Visual Studio 14.0 Experimental Instance

**Steps to reproduce:** 
- Uninstall GitHub Extension in Visual Studio 2015 Enterprise.
- Download [GitHub Extension version: v2.0.15.2](https://github.com/github/VisualStudio/releases/tag/v2.0.15.2)
- Copy the downloaded GitHub Extension VSix file into %localappdata%\Microsoft\VisualStudio\14.0Exp\Extensions in Windows explorer
- Goto %localappdata%\Microsoft\VisualStudio\14.0Exp\Extensions in Windows explorer and unzip the VSix file
- Launch Command prompt for Visual Studio and change directory to **_Common7\IDE\_**
- Type and Enter - _devenv /RootSuffix Exp_ after changing directory to launch Experimental Instance.
- Login to GitHub using _evilfemi_ credentials found [here](https://github.com/github/GHfVSTestAutomation/blob/master/src/main/resources/Data/) or any valid user.
- Clone **'DesktopTestRepo'**, switch branch to [add-branch-delete](https://github.com/evilfemi/DesktopTestRepo/tree/add-branch-delete)
- Make changes to _installer.cs_ file and save.
- Click on the **Home** icon and click on **Sync**
- Fetch new commits and Sync Branch.
- Click on the **Home** icon and click on **Pull Request**

Expected Result: The Pane to create Pull Request should be provided to Contributor

Actual Result: **_Object reference not set to an instance of an object_** message is returned when trying to create a Pull Request.

Screenshot attached:
![snip20161003_2](https://cloud.githubusercontent.com/assets/17054747/19087082/979b3c94-8a25-11e6-84c9-ef0f19e5f9ae.png)

**Comment by shana** [comment]
Does it happen in regular Visual Studio (not in the experimental instance)?

> Clone 'DesktopTestRepo', switch branch to add-branch-delete
Make changes to installer.cs file and save.
Click on the Home icon and click on Sync
Fetch new commits and Sync Branch.

Are all of these steps required to reproduce the issue? i.e., if you do step 1 and then go to home and click on `Pull Requests`, does it show the error?

**Comment by femisimon** [comment]
@shana It doesn't happen in regular Visual Studio.
And yes it still shows the error when you do step one then go _Home_ and click on _Pull Request._

**Comment by grokys** [comment]
Tried to reproduce here but can't, unfortunately...

**Comment by femisimon** [comment]
@grokys I just reproduce with the same step and another step.

**Description:**
In VS Experimental Instance, the GitHub pane seems to be failing to load, hence the _Object reference not set to an instance of an object_ error message. I have checked the logs for GitHubVisualStudio and Visual Studio's ActivityLog.xml and there are no logs for my activities running VS Exp. 
I am going to update the steps to reproduce

**Steps to reproduce:** 
- Uninstall GitHub Extension in regular Visual Studio 2015 Enterprise.
- Download [GitHub Extension version: v2.0.15.2](https://github.com/github/VisualStudio/releases/tag/v2.0.15.2)
- Copy the downloaded GitHub Extension VSix file into %localappdata%\Microsoft\VisualStudio\14.0Exp\Extensions in Windows explorer
- Goto %localappdata%\Microsoft\VisualStudio\14.0Exp\Extensions in Windows explorer and unzip the VSix file.
- Launch Command prompt for Visual Studio and change directory to **_Common7\IDE\_**
- Type and Enter - _devenv /RootSuffix Exp_ after changing directory to launch Experimental Instance.
- **Visual Studio should launch without GitHub Extension** i.e when you click Team Explorer, GitHub extension shouldn't be found in the pane.
- Create an _enable-extension.reg_ file with the following details

**`Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0Exp\ExtensionManager\EnabledExtensions]
"c3d3dc68-c977-411f-b3e8-03b0dccf7dfc,2.0.15.2"="C:\\USERS\\**_YOUR_COMPUTER_NAME_**\\APPDATA\\LOCAL\\MICROSOFT\\VISUALSTUDIO\\14.0EXP\\EXTENSIONS"`**
- Double click on the _enable-extension.reg_ file after saving to enable the extension.
- Relaunch Visual Studio Extension.
- Login to GitHub with Valid credentials
- Click on _Home_ icon and click on Pull Request.

Actual Result - _Object reference not set to an instance of an object_ error message is returned.
Expected Result - GitHub pane is expected.

**Comment by shana** [comment]
This was caused by the manual installation not installing things fully.

**Comment by VincentVancalbergh** [comment]
Any hint on how to proceed here? Deinstall and reinstall? Or do a Repair?
