### ISSUE TITLE
Connect to GitHub button missing in Manage Connection dropdown

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#577]
- GitHub Extension version: v2.0.15.2
- Visual Studio version: Visual Studio 14.0 Experimental Instance

**Steps to reproduce:** 
- Uninstall GitHub Extension in Visual Studio 2015 Enterprise.
- Download [GitHub Extension version: v2.0.15.2](https://github.com/github/VisualStudio/releases/tag/v2.0.15.2)
- Copy the downloaded GitHub Extension VSix file into %localappdata%\Microsoft\VisualStudio\14.0Exp\Extensions in Windows explorer
- Goto %localappdata%\Microsoft\VisualStudio\14.0Exp\Extensions in Windows explorer and unzip the VSix file
- Launch Command prompt for Visual Studio and change directory to **_Common7\IDE\_**
- Type and Enter - _devenv /RootSuffix Exp_ after changing directory to launch Experimental Instance.
- Login with valid credentials as a Dot com user.
- Click on **Manage Connections** to login as an Enterprise User.

**Actual result** - Connect to GitHub button isn't seen 
**Expected result** - Connect to GitHub button should be seen as part of the dropdown to enable user to login to Enterprise account.

Screenshot attached:

![snip20161004_4](https://cloud.githubusercontent.com/assets/17054747/19087639/a2222162-8a27-11e6-9b70-6769c83f24c4.png)

**Comment by shana** [comment]
This is because the package isn't getting loaded in the experimental instance

**Comment by kullanici1919** [comment]
thanks
