### ISSUE TITLE
Switching between branches where one branch has updated to newly added files causes uncommitted changes error 

### ISSUE THREAD

**Issue by saraford** [github/VisualStudio#578]
- GitHub Extension version: using grokys/maintainer-workflow as of 2pm PST 4 Oct 2016
- Visual Studio version: Visual Studio 2015 Community Edition

__What happened__ (with steps, logs and screenshots, if possible)

1. Create a new repo via Team Explorer - Manage Connections - GitHub - Create
2. Choose private GitHub repo with no license
3. Once GitHub repo is created, create a new C# console application
4. Via Team Explorer - Changes, commit the console application files to GitHub via "Commit and Sync"
5. On GitHub.com, create a new File1.md file with some content. Commit it by creating a new branch, e.g. saraford-patch-1, and call the pull request PR1
6. In Visual Studio, go to Team Explorer - Pull Requests, and open the PR1
7. In PR1 details view, click "switch branch"
8. Go to GitHub.com, and in Master branch, edit the Program.cs file. Commit it by creating a new branch, e.g. saraford-patch-2, and call the pull request PR2
9. In Visual Studio, go to Team Explorer - Pull Requests, and open the PR2
10. In PR2 details view, click "switch branch"
11. In GitHub.com, go to saraford-patch-2, and add 2 more files to the existing PR2
12. In Visual Studio, go to Team Explorer - Pull Requests, and open the PR2, but **do not switch branches.** All you do at this step is load the PR2 details view into the tool window.
13. In GitHub.com, go to saraford-patch-1 branch, and add a 1 new file to this PR1
14. In Visual Studio, go to Team Explorer - Pull Requests, and open the PR1.
15. Click to "switch branch" to PR1
16. You'll be prompted to update. Click "update"
17. Now go to Team Explorer - Pull Requests, and open PR2

**Results:**

![image](https://cloud.githubusercontent.com/assets/11529908/19097598/d40ebfea-8a5a-11e6-8b30-b5922f1ce68d.png)

**Expected:**
No issues with switching branches. 

**Notes**

This is what Team Explorer - Changes state looks like:

![image](https://cloud.githubusercontent.com/assets/11529908/19097637/04e61938-8a5b-11e6-9880-1322a80e4e3a.png)

**Comment by pabrams** [comment]
I'm having the same issue and .  When I switch branches in visual studio, uncommitted changes remain.  I want to merge a parent branch from upstream while keeping my uncommitted changes in a child branch.  How do I do that without manually moving files around?  Should I write my own scripts for this?
