### ISSUE TITLE
Login fails with error 'A task was canceled.'

### ISSUE THREAD

**Issue by cwitthauersvs** [github/VisualStudio#580]
- GitHub Extension version: 2.0.15.1
- Visual Studio version: Professional 14.0.25431.01 Update 3

On the login dialog, after entering credentials and clicking Login, after a minute or two the error message 'A task was canceled.' is displayed. Tried uninstalling and reinstalling the extension but issue persists.

Log file gist: https://gist.github.com/cwitthauersvs/abfabeacdb0c962320c454ff9f56d89d 

![error](https://cloud.githubusercontent.com/assets/22640158/19162000/16741280-8bc4-11e6-8a53-25a181fcc14b.png)

**Comment by cwitthauersvs** [comment]
Tried it again just now and it worked... not sure what I did that might have fixed it. Maybe it was just a transient network issue.

**Comment by paladique** [comment]
Hi @cwitthauersvs 👋  thanks for reporting this issue! I also speculated that this might be a connectivity issue (I haven't been able to repro this), but we should have a better message than what's in that screenshot.

**Comment by meaghanlewis** [comment]
Closing this issue out for now as we can't repro this error. we do have an existing issue to have better login failure messages that we can refer to in the future: https://github.com/github/VisualStudio/issues/547
