### ISSUE TITLE
not able to understand "Create new Git repository"

### ISSUE THREAD

**Issue by ranjan-ranjan** [github/VisualStudio#586]
- GitHub Extension version: 2.0.15.1
- Visual Studio version: Microsoft Visual Studio Community 2015 Update 3.
I am not able to understand the meaning of "Create new Git repository" in this step 
![1](https://cloud.githubusercontent.com/assets/16834561/19243182/2d365564-8f34-11e6-98c4-861ae7898f4f.png)

Kindly explain.

**Comment by grokys** [comment]
Hi @ranjan-ranjan,

The "New Project" dialog is not a part of the GitHub for Visual Studio extension, so you would be best searching for documentation on this feature in the Visual Studio documentation.

However, I believe it simply carries out a `git init` on the solution directory that is created.

**Comment by ranjan-ranjan** [comment]
I got it. The "Output" Document window helps:

```
A new Git repository has been created for you in C:\Users\user\Documents\Visual Studio 2015\Projects\ConsoleApplication29.
Opening repositories:
C:\Users\priyaranjans\Documents\Visual Studio 2015\Projects\ConsoleApplication29
Commit f53c078a created locally in repository C:\Users\user\Documents\Visual Studio 2015\Projects\ConsoleApplication29
```

It means that if the checkbox is selected, it creates a git repository. The folder `.git`, files `.gitignore` and `.gitattributes` are created by VS when the solution is created.

On the other hand if the checkbox is not selected, it normal solution without git repository.
