### ISSUE TITLE
"Amend Previous Commit" commits the changes

### ISSUE THREAD

**Issue by ranjan-ranjan** [github/VisualStudio#587]
- GitHub Extension version: 2.0.15.1
- Visual Studio version: Microsoft Visual Studio Community 2015 Update 3
 
"Amend Previous Commit" commits the changes.
![2](https://cloud.githubusercontent.com/assets/16834561/19244191/c11e6af6-8f38-11e6-8fd3-59832f32d509.png)

**Comment by grokys** [comment]
Hi @ranjan-ranjan,

This is part of Microsoft's Team Explorer, and as such not maintained by us (I know it's difficult to know where one ends and another begins!). You will need to contact Microsoft support about this issue.

For future reference, the GitHub for Visual Studio extension only provides cloning and publishing from/to GitHub and the GitHub pane (which currently only shows pull requests). Anything other than that is part of Visual Studio itself.

**Comment by ranjan-ranjan** [comment]
OK. I thought it was a bug in GitHub for Visual Studio extension.
