### ISSUE TITLE
old user name visible

### ISSUE THREAD

**Issue by ranjan-ranjan** [github/VisualStudio#588]
- GitHub Extension version: 2.0.15.1
- Visual Studio version: Microsoft Visual Studio Community 2015 Update 3

I have signed up github with a username and a profile name. Now, I have change my username and don't have a profile name. The result of commit in GitHub for Visual Studio extension is shown here:
![3](https://cloud.githubusercontent.com/assets/16834561/19244582/999bb4aa-8f3a-11e6-8a6d-8af6e72e360d.png)

**Comment by grokys** [comment]
Hi @ranjan-ranjan,

Again, this is part of Visual Studio, not the GitHub for Visual Studio extension.

The git operations in Visual Studio will use the username and email entered here. You will usually change these to correspond to the details you entered when you signed up with GitHub but you don't have to. The settings here correspond to the username and email in your git global config [in this guide](https://help.github.com/articles/setting-your-email-in-git). In particular you can [add additional email addresses to your GitHub profile](https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account) if you wish to link email addresses to your account.

I hope this helps; I'm not sure what you mean by "Now, I have change my username and don't have a profile name." so I haven't addressed that part of your question.

**Comment by ranjan-ranjan** [comment]
![4](https://cloud.githubusercontent.com/assets/16834561/19245082/ecf5166c-8f3c-11e6-9028-7b33d366e3dd.png)

**Comment by grokys** [comment]
@ranjan-ranjan I am having trouble understanding your question. Do you simply not want a username associated with your commits? This isn't possible as [git requires a username for commits](http://stackoverflow.com/a/11579722/6448). However you *can* set the username field to whatever you want.

Again: none of this functionality is related to GitHub or to GitHub for Visual Studio: this is git and Visual Studio functionality.

**Comment by ranjan-ranjan** [comment]
OK. Thanks.

**Comment by grokys** [comment]
No problem - I realize it's a little confusing as to how git, GitHub and Visual Studio fit together!
