### ISSUE TITLE
Repetition of 'Clone' option

### ISSUE THREAD

**Issue by ranjan-ranjan** [github/VisualStudio#590]
- GitHub Extension version: 2.0.15.1
- Visual Studio version: Microsoft Visual Studio Community 2015 Update 3

Repetition of 'Clone' option. These two can be combined.
![3](https://cloud.githubusercontent.com/assets/16834561/19260834/90d9f384-8faa-11e6-942a-410d46e86cdc.png)

**Comment by grokys** [comment]
Yes, there are two "Clone" buttons:

- The "Clone" button under "Local Git Repositories" is part of Visual Studio itself. This relates to the basic `git clone` which works by URL.
- The "Clone" feature under the GitHub section is specific to GitHub: it communicates to GitHub to get the list of repositories available to you, meaning that you do not have to copy and paste a URL from the site.

We cannot override the Visual Studio "Clone" button, we can only provide our own. In addition, even if we could override Visual Studio's Clone button, there would still need to be a way to clone by URL from sites other than GitHub.

**Comment by ranjan-ranjan** [comment]
OK.
I was suggesting about giving the url option as another option in the "Clone" feature under the GitHub section.

**Comment by grokys** [comment]
Yes, that would make sense if we could override the default Visual Studio behavior, but we're not able to do that.

**Comment by ranjan-ranjan** [comment]
OK. 
This was the behaviour that I was expecting in this issue:
![2](https://cloud.githubusercontent.com/assets/16834561/19279448/17fbc1a4-8fff-11e6-95b1-a43118b3b716.png)
