### ISSUE TITLE
"Compare" showing wrong results

### ISSUE THREAD

**Issue by ranjan-ranjan** [github/VisualStudio#591]
- GitHub Extension version: 2.0.15.1
- Visual Studio version: Microsoft Visual Studio Community 2015 Update 3

I added blank spaces in my C# file and pushed the changes to github. But when I compare the versions, its not showing any changes to the file.
Here is the snapshot of the extension in Visual Studio:
![1](https://cloud.githubusercontent.com/assets/16834561/19262174/464dd16a-8fb3-11e6-8ae8-36d671b94129.png)

and its result
![2](https://cloud.githubusercontent.com/assets/16834561/19262201/6abdb862-8fb3-11e6-8a9a-6e871e5a69dc.png)

The expected result should be https://github.com/ranjan-ranjan/new-Repo2/commit/cd551b0706fc36e677fbdc7832ac334b93831d6b#diff-1c26f49e0be6c36e9c67349fc81cd324

**Comment by grokys** [comment]
This is not part of the GitHub for Visual Studio extension, it is part of Visual Studio itself.

The extension is only responsible for:

Logging into GitHub
Cloning from GitHub
Publishing to GitHub
Creating a repository on GitHub
Pull requests
Gists

Anything other than that is part of Visual Studio itself.
