### ISSUE TITLE
Wrong history being shown

### ISSUE THREAD

**Issue by ranjan-ranjan** [github/VisualStudio#592]
- GitHub Extension version: 2.0.15.1
- Visual Studio version: Microsoft Visual Studio Community 2015 Update 3

On comparing the history of https://github.com/ranjan-ranjan/new-Repo2/commits/master/ConsoleApplication1/ConsoleApplication1/Program.cs 
in browser ![1](https://cloud.githubusercontent.com/assets/16834561/19262458/bb5f2304-8fb4-11e6-8fc2-9ae2a11d6aac.png) and GitHub extension for VS 
![2](https://cloud.githubusercontent.com/assets/16834561/19262592/82cf0882-8fb5-11e6-869e-b6269d75dad6.png)
, I see one extra result in extension.

This extra change seen in the extension is this one 
![3](https://cloud.githubusercontent.com/assets/16834561/19262539/23407da6-8fb5-11e6-96e7-4d341879baed.png) which tell that it is change of README.md file. And not of Program.cs as shown in the extension. The result is hidden when "Show full history" is clicked (marked in the snapshot).

Another snapshot when mouse pointer hovered over the "extra" history
![4](https://cloud.githubusercontent.com/assets/16834561/19262657/def87756-8fb5-11e6-9165-80f845e586a8.png)

**Comment by grokys** [comment]
This is not part of the GitHub for Visual Studio extension, it is part of Visual Studio itself.

The extension is only responsible for:

Logging into GitHub
Cloning from GitHub
Publishing to GitHub
Creating a repository on GitHub
Pull requests
Gists

Anything other than that is part of Visual Studio itself.
