### ISSUE TITLE
Separate "Commit" and "Commit History" being shown

### ISSUE THREAD

**Issue by ranjan-ranjan** [github/VisualStudio#593]
- GitHub Extension version: 2.0.15.1
- Visual Studio version: Microsoft Visual Studio Community 2015 Update 3

There should be separate "Commit" and "Commit History" message box being shown. Currently these two are combined.
![1](https://cloud.githubusercontent.com/assets/16834561/19265405/afbb9ad8-8fc2-11e6-8714-6ce129ef1dba.png)

**Comment by grokys** [comment]
This is not part of the GitHub for Visual Studio extension, it is part of Visual Studio itself.

The extension is only responsible for:

- Logging into GitHub
- Cloning from GitHub
- Publishing to GitHub
- Creating a repository on GitHub
- Pull requests
- Gists

Anything other than that is part of Visual Studio itself.
