### ISSUE TITLE
Switch Branch action Redirects to Pull Request List

### ISSUE THREAD

**Issue by tocsoft** [github/VisualStudio#624]
- GitHub Extension version: **N/A (master)**
- Visual Studio version: **2015 update 3**

using the new `Maintainer Workflow` code just merged into master. 

### Issue
switching branch from the pull request view switches back to the pull request list.

#### Setup
have a repository with two branches  (`master` and `pr`) and a pull request (from `pr` to `master`).
#### Actions
1. check out `master` using team explorer.
2. open PR list
3. open PR view (shows message 'This branch is currently not checked out, *switch branch*')
4. click *switch branch* 
5. be shown PR list again (<-I believe this is wrong)

### Expected 
switching branch should leave the currently open pull request open after the branch has switched so they can continue to work through their PR.

**Comment by femisimon** [comment]
This was reproduced.

**Actual** - The switch branch action checks out branch but redirects to Pull Request lists

**Comment by tocsoft** [comment]
this seems to be covered by/duplicates  #628
