### ISSUE TITLE
Maintainer Workflow: Change the message icon to be less scary

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#625]
Currently we're using a warning icon for our messages, which is a bit scary to users (what did I just do??? panic). Making it an informational icon (or a friendly octocat or something) will probably make it less scary and more of a guidance to next steps (which is what most messages are all about).

**Comment by donokuda** [comment]
The fix for this is included with https://github.com/github/VisualStudio/pull/607

![image](https://cloud.githubusercontent.com/assets/1174461/19662606/196f251a-99ed-11e6-830d-1b65f89d14fd.png)

**Comment by donokuda** [comment]
We reworked these messages in https://github.com/github/VisualStudio/pull/730
