### ISSUE TITLE
Maintainer Workflow: double clicking changed file should open a diff

### ISSUE THREAD

**Issue by tocsoft** [github/VisualStudio#626]
I would expect double clicking the file in the changed files tree to open the diff view for the change. _(this would preferably work without the branch needing to be checked outbut if not checked out then both side of the diff should be readonly)._

I would also expect a right click option to just open the file with out the diff _(this should probably only be enabled if they have the branch checked out, or maybe enabled but with a prompt asking them for permission to check out the branch first.)._

**Comment by grokys** [comment]
Yep, this is coming in a PR very soon ;) There's already a branch with the feature: `grokys/maintainer-workflow-diff`; it just needs updating with the changes made due to feedback on the main maintainer workflow PR.

**Comment by grokys** [comment]
@tocsoft see the PR https://github.com/github/VisualStudio/pull/567 for details of what is still to come.

**Comment by tocsoft** [comment]
awesome 👍 

woops - missed that list at the top of the PR, i'll stop pointing stuff out what your obviously tracking already then.

**Comment by grokys** [comment]
Not at all - it's good to have eyes on this, and you saved me filing the issue myself ;)
