### ISSUE TITLE
GitHub pane navigation broken

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#628]
Now that the maintainer workflow branch has been merged to master, it's clear that navigation in the GitHub pane is broken: switching branches switches the pane back to the PR list and subsequent navigation with the back/forward/PR buttons is broken.

**Comment by StanleyGoldman** [comment]
I think I found an easier way to reproduce the same issue. If I navigate to a pull request, use the back button to go back to the pull request list, and then use the forward button to attempt to go back to the pull request. I get an error.

![Video](http://i.imgur.com/R3WNJt8.gif)

**Comment by StanleyGoldman** [comment]
Hey @shana I made some progress on this; I could use your input.

**Comment by shana** [comment]
@StanleyGoldman I won't probably be able to give you input before monday, I have a really bad cold and it's getting late here. :sick:

**Comment by StanleyGoldman** [comment]
I understand. Rest well!

**Comment by StanleyGoldman** [comment]
Playing around some more, I discovered this as well.

![Error](http://i.imgur.com/fiNMHjY.gif)

**Comment by grokys** [comment]
> I understand. Rest well!

I read this as "I understand REST well". Was going to say: you're probably the only one! ;)
