### ISSUE TITLE
Publish is not respecting 'Private Repository' checkbox and publishing as public repo

### ISSUE THREAD

**Issue by acangialosi** [github/VisualStudio#63]
A user recently documented an account of a severe consequence that resulted after publishing a repository to GitHub.
https://www.humankode.com/security/how-a-bug-in-visual-studio-2015-exposed-my-source-code-on-github-and-cost-me-6500-in-a-few-hours
I was able to reproduce this myself with the following steps:
0) Sign into the GitHub extension.
1) Create a new local repository in Team explorer.
2) Click on Changes and Commit an initial commit into the repo.
3) Click sync to navigate to the synchronization page.
4) Check the Private Repository box and then click publish.

Result was a repository was successfully published to GitHub and was visible from an inprivate browser session where I was not signed in.

**Comment by acangialosi** [comment]
Dupe

**Comment by shiftkey** [comment]
Dupe of #62
