### ISSUE TITLE
Remote branch not found after "Fetch" or "Pull" action

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#630]
# Description
Remote branch not found after "Fetch" action was the message returned after making new commits and pushing commits to PR. Screenshots added

- GitHub Extension version: v2.0.15.3-alpha1 
- Visual Studio version: Enterprise 2015 -  Update 3

	
**Steps to reproduce**
- Have a repo that has an Open PR.
- Make sure branch is up-to-date
- Make changes to the branch and commit changes
- Click Team Explorer ==> Home Icon
- Click Sync and Push Outgoing commits
- Click Fetch/Pull on the Branch pane

**Expected** - Branch is up-to-date message should be returned.

**Actual** - Branch was not found in remote repository returned.

![snip20161024_88](https://cloud.githubusercontent.com/assets/17054747/19667798/d0a629c6-9a07-11e6-898d-7136b5b0eb95.png)

![snip20161024_86](https://cloud.githubusercontent.com/assets/17054747/19667806/e2303d44-9a07-11e6-9121-c637d9d6e89b.png)

**Comment by grokys** [comment]
I'm unable to reproduce this, two questions:

> Click Sync and Push Outgoing commits

This is in the Team Explorer "Synchronization" pane is that correct? Sync on that pane automatically pushes outgoing commits so once I've clicked it, the "Push" link is disabled.

>Click Fetch on the Branch pane

Do you mean on the "Synchronization" pane again here? I can't find a "Fetch" command on the branch pane. Or do you mean on the context menu for the current branch on the branch pane?

Either way, this is strange: the "Synchronization" pane isn't our code - it's part of Team Explorer itself.

**Comment by femisimon** [comment]
@grokys I should have added `Pull` when I reproduced it.  

> Either way, this is strange: the "Synchronization" pane isn't our code - it's part of Team Explorer itself.

The issue might be introduced by our code, cause I wasn't getting this error in v2.0.15.1.

> This is in the Team Explorer "Synchronization" pane is that correct? Sync on that pane automatically pushes outgoing commits so once I've clicked it, the "Push" link is disabled.

Sync will push outgoing commits

Screenshot attached as well:
![snip20161025_91](https://cloud.githubusercontent.com/assets/17054747/19697376/f5879e4e-9a9f-11e6-8ea7-1b4410be5c43.png)

**Comment by grokys** [comment]
Hmm, I stil can't quite understand - might be worth doing a screen share later today if you've got 20 mins free @femisimon ?

**Comment by femisimon** [comment]
@grokys yes, that works. Slacking you now.

**Comment by femisimon** [comment]
Closing this not reproducible.

**Comment by mrdnote** [comment]
I'm getting this error all the time when doing a fetch or pull. In the screenshot you can clearly see the item exists in the remote repo.

![image](https://user-images.githubusercontent.com/5628584/28208488-191d734c-68b8-11e7-83d2-b996d082eefd.png)

My workaround solution is to delete it locally and then check it out again...
