### ISSUE TITLE
New Commits & Files Changed Not Updated 

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#631]
# Description

After a commit is made and local branch is synced with remote, Contributor should be able to see the number of commits made and file changed when pane is refreshed but currently, the **Changes** section of the GitHub pane shows the files changed which do not correspond with the number of files changed and commits below the branch.
- GitHub Extension version: v2.0.15.3-alpha1 
- Visual Studio version: Enterprise 2015 -  Update 3

**Steps to reproduce**
- Have a repo that has an Open PR.
- Make sure branch is up-to-date
- Make changes to the branch and commit changes
- Click Team Explorer ==> Home Icon
- Click Sync and Push Outgoing commits
- Click Home Icon ==> Pull Requests
- Select the Open PR to see PR details
- Click Refresh icon to reflect the changes made.

**Expected** - New Commits and the number of files changed should correspond with the number of commits and files changed on dot com.

**Actual** - New Commits and the number of files changed are not reflected on the change when pane is refreshed. New commits and number of files changes are reflected after numerous Sync ==> Pull and Fetch of the branch which results to [#630](https://github.com/github/VisualStudio/issues/630)

**Comment by grokys** [comment]
I think the problem is that the Refresh button isn't working. When run in debug mode and viewing PR details, I get this assertion failure:

https://github.com/github/VisualStudio/blob/918fd182cd0dcf20258cbcd3d3c91feec31d3af0/src/GitHub.App/Controllers/UIController.cs#L261

So I think it's related to #628

**Comment by akehsanz** [comment]
yes...same issue now facing
@nov 18.
I can't make any "commit changes" in master branch
for my forks..
wht seems to be the issue ??
anyone pls HELP !!
