### ISSUE TITLE
Local branch update with X-commit behind redirects to PR List

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#632]
# Description
Updating a branch checked out locally with X-commit behind should update the local branch with new commits from remote without redirecting from the PR details pane, which is currently the case.

Relates to [#628](https://github.com/github/VisualStudio/issues/628)

- GitHub Extension version: v2.0.15.3-alpha1 
- Visual Studio version: Enterprise 2015 -  Update 3

**Steps to reproduce**
- Check out local branch, provided Local branch as no new changes
- Make changes to remote branch from another PC or Terminal.
- On Team Explorer ==> Home Icon ==> Pull Request
- Select the PR with the same branch with new commit(s) on remote.
- Click Update to update local 

**Expected:** PR details should be loaded on pane.

**Actual:** PR details loads for a few microseconds and redirects to PR list

**Comment by grokys** [comment]
Thanks, yep already tracking this in #628, so will close this as a duplicate. Fix incoming hopefully today!
