### ISSUE TITLE
Broken GitHub pane icon

### ISSUE THREAD

**Issue by tocsoft** [github/VisualStudio#642]
- GitHub Extension version: 2.0.15.1
- Visual Studio version: VS2015 update 3

When you have the 'GitHub Pane' docked such that it shows as a tab 
![image](https://cloud.githubusercontent.com/assets/166440/19701318/c2cd7372-9af2-11e6-9dbf-6646a6f33414.png)
but then you resize the sidebar until the tabs change to icons then it appears to have a broken icon image
![image](https://cloud.githubusercontent.com/assets/166440/19701351/e5e64d8e-9af2-11e6-96f3-7e6d90efd1b8.png)

and in blue
![image](https://cloud.githubusercontent.com/assets/166440/19701381/1562d078-9af3-11e6-88ab-aaf88021aa6b.png)
![image](https://cloud.githubusercontent.com/assets/166440/19701385/19a8dfd8-9af3-11e6-9350-0c749c35847b.png)
![image](https://cloud.githubusercontent.com/assets/166440/19701392/215f0f9a-9af3-11e6-9c99-6dd3f4690227.png)

**Comment by tocsoft** [comment]
I didn't even know the tabs showed as icons until I was playing around resizing the sidebar.

**Comment by grokys** [comment]
Yep, that's a new one for me too!

**Comment by shana** [comment]
wth is it doing? Just rendering a tiny corner of the image? siiiiigh!
