### ISSUE TITLE
'Publish to GitHub' panels TextBox styling not consistent with other controls

### ISSUE THREAD

**Issue by tocsoft** [github/VisualStudio#643]
- GitHub Extension version:  v2.0.15.1
- Visual Studio version: 2015 u3

Text boxes on Publish to GitHub panel are not in keeping to the same style as the rest of the panel/pane.

![image](https://cloud.githubusercontent.com/assets/166440/19702133/2f6da602-9af6-11e6-9996-49ff5ebd8ab4.png)

![image](https://cloud.githubusercontent.com/assets/166440/19702281/c1b3e986-9af6-11e6-86d8-1b02d4addcca.png)

![image](https://cloud.githubusercontent.com/assets/166440/19702286/c7694a88-9af6-11e6-8105-b7512a7002bc.png)

![image](https://cloud.githubusercontent.com/assets/166440/19702599/31a3a71c-9af8-11e6-8c95-8e83d3021b22.png)

my expectation: (blue theme)
- No rounded corners
- Darker boarder
- Yellow border on hover/focus

my expectation: (dark theme)
- No rounded corners
- Darker boarder
- hover/focus boarder looks fine

(basically to be like the drop downs just above)

**Comment by grokys** [comment]
Yeah, this stuff is a real PITA to get right as Team Explorer doesn't expose its styles for us to use AFAICT.

**Comment by tocsoft** [comment]
I can imagine it can get quite vexing at times... and i bet the fight starts again when the next version lands and they change their minds. :)

Its just minor thing really, but I felt it wanted tracking.

**Comment by grokys** [comment]
And yeah - they do change the styling from version to version: https://github.com/github/VisualStudio/issues/551 :(

**Comment by StanleyGoldman** [comment]
So I did some spelunking with Snoop and dotPeek and I learned a few things that might help. The Team Foundation controls don't seem to use any actual `TextBlock` controls. They always use `Microsoft.TeamFoundation.Controls.WPF.LabeledTextBox`. Which carries it's own xaml and internal styles, and is actually always yellow o_0, but that's how they avoid the text box prompt from fading into the background when the theme changes.

![img](http://i.imgur.com/KZf4XK0.png)
![img](http://i.imgur.com/3D2y4Xy.png)

The other thing I discovered that very well might be of use is `component/GitSharedResources.xaml` in `Microsoft.TeamFoundation.Git.Controls`. There are some styles like `PlainComboBox` which might help synchronize with the styles per version of Visual Studio.

**Comment by grokys** [comment]
Thanks for taking a look Stanley. Indeed looking in ILSpy, `LabeledTextBox` is actually public so we may be able to use that!

I'm not sure though about using styles from Team Foundation assemblies; I don't think these are considered public though that's a question for MS that I can ask.
