### ISSUE TITLE
UI Inconsistent in different Visual Studio Themes

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#644]
# Description

In the `Changes` section on the GitHub pane, we should have UI that adapts to the theme of the user, which makes functions visible and user-friendly. Currently on the PR details page on the `Changes` section - the text and table marginalization isn't user-friendly. 

Screenshots attached.
- GitHub Extension version: v2.0.15.3-alpha1 
- Visual Studio version: 2015 Enterprise Update 3

**Steps to reproduce**
- Launch Vs and login to GHfVS
- Click on Team Explorer ==> Home Icon ==> Pull Requests
- Select an open PR and click to view PR details
- Focus on the `Changes` section of the GitHub pane
- Switch to List view
- Switch between themes provided by Visual Studio (Dark, Blue, and Light)

**Expected** - The `Changes` section should be adaptive to the different Visual Studio themes.

**Actual** - The `Changes` section isn't adaptive to Visual Studio different themes.
# Screenshots
- **Dark**
  ![snip20161025_93](https://cloud.githubusercontent.com/assets/17054747/19703614/5094e83c-9ab9-11e6-9f4c-e868d80c9a77.png)
- **Blue**
  ![snip20161025_95](https://cloud.githubusercontent.com/assets/17054747/19703633/60a4cb2a-9ab9-11e6-9ee7-c414ed521d0c.png)
- **Light**
  ![snip20161025_96](https://cloud.githubusercontent.com/assets/17054747/19703645/6abc4b56-9ab9-11e6-9bed-8445b1acc463.png)

**Comment by femisimon** [comment]
The tabulated changes of File `Name` and `Path` UI not completely implemented as proposed by design. Added screenshot for some clarity.

![snip20161025_98](https://cloud.githubusercontent.com/assets/17054747/19705207/0c5a19ec-9ac0-11e6-8fdc-458e1329e040.png)

**Comment by StanleyGoldman** [comment]
Related to #643

**Comment by grokys** [comment]
Fixed in https://github.com/github/VisualStudio/pull/637
