### ISSUE TITLE
Files Changed Path in Changes section

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#645]
# Description

The path where files changed in a branch is displayed for users/contributors to trace isn't implemented yet.

This issue is opened to track that part of the PR review feature. If we still want to implement this. 
- GitHub Extension version:
- Visual Studio version:
# Question
- Are we sticking with `Changes` or `Files changed`?
# Screenshots Attached

![snip20161025_97](https://cloud.githubusercontent.com/assets/17054747/19704828/347f0fc4-9abe-11e6-864b-166f3e6ca16c.png)

Cc @grokys @shana @donokuda .

**Comment by grokys** [comment]
Hi @femisimon, I'm not sure what you mean here - do you mean that the icons to the right of the highlighted area aren't yet implemented? The list itself is there - you just need to click the hamburger menu button and select "Switch to List View":

![image](https://cloud.githubusercontent.com/assets/1775141/19722497/46829e66-9b77-11e6-9ee1-778860339dd6.png)

**Comment by grokys** [comment]
Also I used "Changes" as that is what is displayed elsewhere in Team Explorer (e.g. in the "Changes" pane). I'm fine with using a different labelling though if we want to (again, cc @donokuda)

**Comment by femisimon** [comment]
@grokys After selecting the Hamburger menu button and clicking ` Switch to List View` the path of the files changed in the repo isn't rendered.

Do we have the icons @donokuda ? We can implement it if we do.

**Comment by grokys** [comment]
Oh strange - they are displayed for me:

![image](https://cloud.githubusercontent.com/assets/1775141/19731356/71b6007a-9b9d-11e6-9d98-170f1108a87e.png)

**Comment by grokys** [comment]
Ok, after speaking with @femisimon the difference with his repro and mine was that he was changing files in the root of the repo. Because it's the root of the repo, we treat that as having a path of "" (as that is how GitHub understands the path - relative to the repo root).

Team Explorer on the other hand always displays the root as the name of the repo, so the path is never a blank string. We should probably do the same.
