### ISSUE TITLE
Deleted files not Indicated with strikethrough in PR details

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#646]
# Description

Deleted files in a branch with open/closed PR should indicate that the particular file(s) were removed or deleted from the repo by been strikethrough. Currently, deleted files are listed under `Changes` is seen as other file changed.
- GitHub Extension version: v2.0.15.3-alpha1 
- Visual Studio version: Enterprise 2015 Update 3.
## **Steps to reproduce**
- Launch Vs and login to GHfVS
- Select a repo with Open PR and switch to the branch
- Delete a file from the branch
- Commit changes made and sync.
- Click Team Explorer ==> Home Icon ==> Pull Requests
- Select the open PR with deleted file(s)
### **Expected**:
- Deleted file(s) has ~~strikethrough~~ and colored red.
### **Actual:**
- Deleted file(s) is displayed as a regular file on the `Changes` section

**Comment by grokys** [comment]
This feature is coming in #637. However, the file isn't colored red as I was trying to match the way that Team Explorer displays files. @donokuda do we want to display deleted files in red, different from Team Explorer?

**Comment by shana** [comment]
This UI is ours, not Team Explorer's, so there's no reason for us to use red here, we should have our own branded style.

@donokuda Do we have a set GitHub style currently for displaying deleted files? If not, my personal preference is not red, red is... not really subtle. Maybe a duller or more faded color? Gray?

**Comment by donokuda** [comment]
> @donokuda Do we have a set GitHub style currently for displaying deleted files? If not, my personal preference is not red, red is... not really subtle. Maybe a duller or more faded color? Gray?

Sorry I missed this earlier. We don't have a style for deleted files yet and 💯 on gray. I think the strike-through w/ gray should be enough to communicate that a file was deleted.
