### ISSUE TITLE
Not Unified visualstudio gitignore file

### ISSUE THREAD

**Issue by Sunlcy** [github/VisualStudio#649]
- GitHub Extension version:2.0.14.4
- Visual Studio version:VS Community 2015

I found the .gitignore gerenated by GitHub Extension for VS is different from that gerenated by Github web client. I ever created a repository with a gitignore file in **Github web client**, and created a project in VS and automatically created a corresponding git repository accidentally(*It will automatically add gitignore*). After I git pull, it encountered conflicts in .gitignore. So I think the file from GitHub Extension and Github web client is not unified. Though it doesn't matter in most cases, it's necessary to unify the gitignore files. 
One of conflicts is blew:
```
<<<<<<< HEAD
[Xx]64/
[Xx]86/
[Bb]uild/
bld/
[Bb]in/
[Oo]bj/
=======
x64/
x86/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
>>>>>>> a1d60a77af7cdf8267208998fb3aac1f312255bd
```

**Comment by shana** [comment]
If you create a repository in Visual Studio and have VS add it to source control, VS adds a ignore file of its own that's different. But even if they were the same, if you commit a file locally and commit a file with the name remotely, you're always going to get a conflict, since git doesn't know which one to take.

**Comment by Sunlcy** [comment]
@shana Yes, I know. But when I use git pull and it will merge these two commits without conflicts if two .gitignore files are the same. To the contrary, there will be conflict. So I think it's necessary to unify them since they are both maintained by github Inc.

**Comment by tocsoft** [comment]
@Sunlcy  The GHfVS doesn't generate the `.gitignore` visual studio is doing that.

A lot/all of the low level git operations are handled but VS itself not this extension.

**Comment by Sunlcy** [comment]
@tocsoft Oh，I've got it. Thank you for telling me tha!
