### ISSUE TITLE
Translation to russian issue

### ISSUE THREAD

**Issue by programmersommer** [github/VisualStudio#656]
- GitHub Extension version: 2.0.15.1
- Visual Studio version: 14.0.25431.01 Update 3

In translation to Russian Pull and Fetch translation is equal. So, it's not possible to understand what is pull and what is fetch. See attached screenshots.
![commit](https://cloud.githubusercontent.com/assets/12097421/19829526/bb339da6-9dec-11e6-9727-6443f609f2b0.PNG)
![commit_en](https://cloud.githubusercontent.com/assets/12097421/19829525/bb33bd04-9dec-11e6-8679-9f7b8619f4e7.PNG)

**Comment by tocsoft** [comment]
That part of the Git integration into Visual studio isn't actually provided by this extension that's all Microsoft's doing this extensions just adds a few GitHub-centric touches on top when your working with a repository hosted on here. 

You will probably want to report the translation issue it directly to Microsoft via the "Report a Problem" option behind the "Send feedback" button at the top right of VS.

![image](https://cloud.githubusercontent.com/assets/166440/19830280/318a1300-9dec-11e6-8838-41eab025fa5c.png)

**Comment by programmersommer** [comment]
Ok. I have report about problem. Thanks

**Comment by paladique** [comment]
Yep this is the git integration in VS, which we do not have control over. Thanks @tocsoft!
