### ISSUE TITLE
Find Replace with Regex Crashes VS

### ISSUE THREAD

**Issue by AdjutantML** [github/VisualStudio#663]
VS crashes when performing a Replace in Files operation with the following options:
 * Replace in Files
 * Find What : .*
 * Replace With : TEST
 * Include sub-folder : <yes>
 * Use Regular Expressions : <yes>
 * Look in : C:\Test
 * Look at these file types : *.txt
 * Keep modified files open after Replace All : <no>

The sample folder (C:\Test) contains a single text file with a few text characters.
Crashes with both of the following cases:
 * No project loaded
 * Small project loaded

Additional References
 * [http://stackoverflow.com/questions/37610896/find-and-replace-all-crashes-vs2015-and-2013](url)

**Comment by tocsoft** [comment]
This repo is only for the GitHub extension for VS not the whole of VS. We don't even cover the all the git source control features just a thin GitHub centric wrapper over the top. You will want to report this issue directly to Microsoft. I recommend using the send feedback feature from the top of VS.

**Comment by AdjutantML** [comment]
Thanks - whoops, wrong forum.
