### ISSUE TITLE
2FA Rejects Valid code (Sporadic)

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#671]
Two-factor Authentication rejects valid code sent as SMS.

Visual Studio Community 2015
GHfVS - v2.0.15.1

**Steps to reproduce**
- Login to GHfVS with an account with 2FA.
- Enter 2FA code.

Expected - Account with valid 2FA code should login successfully

Actual - Account with valid 2FA code is rejected.

![snip20161108_1](https://cloud.githubusercontent.com/assets/17054747/20110243/71d31f34-a598-11e6-91b1-fce340c409eb.png)

**Comment by femisimon** [comment]
- Reproduced this while testing VS 15 RC.

**Comment by paladique** [comment]
This required some internal updates that have been fixed, so closing.
