### ISSUE TITLE
Refresh icon redirects to create new pull request

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#673]
Cancelling the creation of a pull request and refreshing the list of pull request should provide an updated pull request list.
But it currently redirects to create new pull request.

Visual Studio Community
GHfVS - v2.0.15.1

**Steps to reproduce**
- Select a repo hosted on GitHub
- From Team Explore > Home > Pull Request
- Click create Pull Request
- Click cancel create Pull Request
- Click the refresh button

Expected - Should refresh and update the Pull Request List.

Actual - Redirects to "Create new Pull Request" in GitHub pane.

**Comment by paladique** [comment]
Fixed in #752
