### ISSUE TITLE
Wont open cloned files into a project?

### ISSUE THREAD

**Issue by seandeveloper** [github/VisualStudio#68]
Hi, 

Not sure what do do here. I am doing the course Using git with visual studio 2013 on microsofts virtual acadamy website. 

I have cloned a git repo from GitHub. Its a java-script open source project. I followed the instuctions on opening the cloned repo off the videos but only see folders and no files. I can open the open source projects in webstorm but not in visual studio 2015 lol. 

Any ideas be much appreciated.

Thanks.

**Comment by Haacked** [comment]
Hi @seandeveloper, does this project have a `.sln` file or `.csproj` files. As far as I know, Visual Studio 2015 doesn't just show files in a folder. It expects project files that list all the relevant files. You might try using [Atom](https://atom.io/) or [Visual Studio Code](https://code.visualstudio.com/) to open the JavaScript project.
