### ISSUE TITLE
Update design for start page clone dialog

### ISSUE THREAD

**Issue by donokuda** [github/VisualStudio#684]
Follow up to https://github.com/github/VisualStudio/pull/670

> @donokuda this branch won't build on 2015 but the xaml designer should be able to load the view. If not, just a mockup will do, we can fix it up ourselves. This is basically the clone dialog, only without the repository list and filter textbox, and instead just showing the name of the repository we're going to clone. Since the size of the window is pretty much fixed (because it has to accommodate the login dialog before), we have a lot of empty space that we need filling.
>
> We should probably have:
> - The avatar that owns the account
> - The name of the account
> - The name of the repository
> - The url to it (just to be clear and you know gotta fill that space)
> - repo/lock/fork icons maybe? 

Here's what I'm thinking the updated design could look like

<img src="https://cloud.githubusercontent.com/assets/1174461/20185561/5d01cba2-a721-11e6-8eef-0ddc57bce843.png" width="350px" />

**Comment by tocsoft** [comment]
Is the full url really giving us any real benefit?

Would it make more sense instead to have instead of `URL 🔗 https://github.com/{owner}/{repoName}`
having `Server 🔗 GitHub.com` or for GHE `Server 🔗 YourGHEServer.net`

**Comment by donokuda** [comment]
> Is the full url really giving us any real benefit?
> 
> Would it make more sense instead to have instead of `URL 🔗 https://github.com/{owner}/{repoName}`
> having `Server 🔗 GitHub.com` or for GHE `Server 🔗 YourGHEServer.net`

Showing just `github.com` or `YourGHEServer.net` instead of the full URL makes sense. If we do that, should we label it as "Source" instead of "URL?"

**Comment by shana** [comment]
> Showing just github.com or YourGHEServer.net instead of the full URL makes sense. If we do that, should we label it as "Source" instead of "URL?"

`Source` sounds appropriate :+1:

**Comment by shana** [comment]
For reference, this is what the create repository UI looks like right now.

![7-create-repo](https://cloud.githubusercontent.com/assets/310137/20393462/51f59ca0-acdc-11e6-90a0-c47122b17b17.png)

@donokuda What do you think of having this clone dialog more closely aligned in UI with the create repository dialog?

**Comment by donokuda** [comment]
> What do you think of having this clone dialog more closely aligned in UI with the create repository dialog?

I like that idea. Here's a quick mock-up with what I'm thinking we should go towards:

![image](https://cloud.githubusercontent.com/assets/1174461/20402726/c02c3168-acb2-11e6-9671-5ba4ab3dd8ad.png)

I ended up keeping the full URL since it would be consistent with Microsoft displaying the full URL in their clone dialog. Also showed how we would end up wrapping if a url is extremely long.

**Comment by tocsoft** [comment]
Would have though in this context that `Name` should be labelled `Repository` as `Name` doesn't really explain what its a name of exactly.

With regards `Organization` should it not be `Owner` instead? That is unless we can detect the difference on this screen and switch between the 2 based on context.

Still not a fan of the `Url` defiantly prefer `Source` with _domain.name_. Just guessing (as I cant find the screen that actually has the full url on) I would have thought that MS has to have the full url as they don't have the same sort options GHfVS has to show an "exploded" rich set of context specific information about the repo/owner etc.

**Comment by donokuda** [comment]
> Would have though in this context that `Name` should be labelled `Repository` as `Name` doesn't really explain what its a name of exactly.

> With regards `Organization` should it not be `Owner` instead? That is unless we can detect the difference on this screen and switch between the 2 based on context.

👍 Agree on both. I've updated the mock to reflect your feedback as well as changing URL to Source.

![image](https://cloud.githubusercontent.com/assets/1174461/20440675/e62c41c8-ad75-11e6-9a53-12fc4ba823ee.png)

> Still not a fan of the `Url` defiantly prefer `Source` with _domain.name_. Just guessing (as I cant find the screen that actually has the full url on) I would have thought that MS has to have the full url as they don't have the same sort options GHfVS has to show an "exploded" rich set of context specific information about the repo/owner etc.

Yeah that makes sense, however I still would lean towards having the full URL since it communicates the exact source where the repo is coming from. That way, I'm more confident that I'm cloning the right repository.

**Comment by shana** [comment]
> That way, I'm more confident that I'm cloning the right repository.

Yeah, that's a good thought.

**Comment by donokuda** [comment]
Opened up https://github.com/github/VisualStudio/pull/708 incorporating the design I posted above. 

A couple of things to note I didn't explain that would be really nice (and isn't apart of my open PR):

- The Repo icon changes between the book or a lock symbol depending if the repo is public or private respectively.
- The organization symbol should update with the org avatar if it's available. If not, it should default to the group icon.

**Comment by grokys** [comment]
> The Repo icon changes between the book or a lock symbol depending if the repo is public or private respectively.
> The organization symbol should update with the org avatar if it's available. If not, it should default to the group icon.

Unfortunately this info isn't currently available at the point that the dialog is shown. We're going to need to do a bit of a restructure of how we represent accounts, as the `Account` class is currently dependent on Reactive Extensions which won't be loaded at this point.
