### ISSUE TITLE
Incorrect error message when adding submodules

### ISSUE THREAD

**Issue by stevemk14ebr** [github/VisualStudio#695]
There is a project structured like such:

Main_Project_Folder

- .vs
- .git
- Project_Folder
   -- Dependancy_Folder
            -- .git (this .git folder is inside the dependency_folder)
   -- Project's source code files
   -- Project.csproj
- Project.sln

When attempting to commit the dependency folder and it's subfolders/files visual studio gives this error:
![VSError](http://i.imgur.com/HkgJKrT.png)

The standalone GitHub for windows program however gives a much more expressive error that actually states what is wrong:
![GithubError](http://i.imgur.com/YSO942og.png)

Visual studio should provide an error message that explains sub folders with their own .git folders is not allowed, rather than saying it is an invalid path.

**Comment by paladique** [comment]
Hi @stevemk14ebr 

The feature in that top screenshot is part of Visual Studio's Git functionality - we don't have any control over it. If you'd like to report this to Microsoft, you can do it through Visual Studio's feedback button, next to the Quick Launch box. Hope that helps!
