### ISSUE TITLE
Unable to clone the repositories using SSH URLs ( SSH Configuration Functionality Missing ??? )

### ISSUE THREAD

**Issue by Jogesh-Click2Cloud** [github/VisualStudio#698]
Github Extension version: 2.1.1.0

  Visual Studio version: VS "15

  I want to clone the repository using ssh Url , but I don't find a way out to clone repo using SSH URLs. Is  this functionality missing ????

**Comment by shana** [comment]
The manual cloning functionality (where you type in the url of the repository to clone) is part of the git support that Microsoft ships for Visual Studio, we don't own that bit. I'm not sure if Visual Studio supports cloning with ssh urls 😕
