### ISSUE TITLE
The extension locks visual studio installer modify button on VS2017RC

### ISSUE THREAD

**Issue by glat** [github/VisualStudio#703]
- GitHub Extension for Visual Studio  version: v2.1.1.2
- Visual Studio version: VS2017 RC

When the extension is installed, the Visual Studio Installer stops when you click the "Modify" installation button giving this error:

![senza-titolo-1](https://cloud.githubusercontent.com/assets/569200/20857877/053e3502-b939-11e6-9449-61e467912147.jpg)

Uninstalling the extension give back the possibility to modify the installation. This happens only with this extension, so I think it's a matter about the extension.

Kind regards

**Comment by shana** [comment]
@glat Thank you for the report. We'll pass this along to MS, they can best figure out what's wrong here.

@aarnott Any ideas on this issue?

**Comment by AArnott** [comment]
I'll ask the right folks to investigate ASAP. 
But I'm a little curious: the VS2017 RC installer shouldn't install 2.1.1.2 of this extension when you check the GitHub extension checkbox in the installer. Is this installing 2.1.1.2 because you downloaded from the gallery and the VS installer is activated to install the VSIX you downloaded?

**Comment by glat** [comment]
Yes. After upgrading the extension the installer show that error at any modify attempt.

**Comment by tinaschrepfer** [comment]
For step number 2, how did you upgrade the extension in VS?  Did you upgrade it through the gallery or through the VS installer?

**Comment by glat** [comment]
By Visual Studio menu Tools > Extensions. Vs itself notify the upgrade.

**Comment by Aliihi** [comment]
https://doc-04-6g-docs.googleusercontent.com/docs/securesc/eotjl42ocauapa2gtckon18ad8stj9mk/ipqd0iegv43d784kqasoe1ce9t69rk6p/1480960800000/09117406221172916312/09117406221172916312/0B-BA0O8_Jo5_aGlkN01ZUXlKMGs?e=download&nonce=6obn0td4kf0r0&user=09117406221172916312&hash=rl39tmrgvttf8jaqg6tssa0961jta5gf

**Comment by glat** [comment]
![senza-titolo-1](https://cloud.githubusercontent.com/assets/569200/20933620/ed07f57a-bbd8-11e6-8aad-89d775d5e570.jpg)

There are versions installed with the VS2017 RC installer and the one offered to upgrade to.

**Comment by tinaschrepfer** [comment]
Thanks!  We are investigating this internally.

**Comment by tinaschrepfer** [comment]
To help us investigate this issue, could you download and run vscollect.exe from this site: https://www.microsoft.com/en-us/download/details.aspx?id=12493, and then upload %temp%/vslogs.zip to a publicly available share for us to consume?  Thank you so much for your assistance and patience!

**Comment by glat** [comment]
Steps I did:

1) upgraded extension to the one offered as in previous screenshot
2) Launched VS
3) Closed VS
4) Cleaned %TEMP%
5) Launched VS Installer
6) Clicked "Modify Button"
7) I got that error and launched collect.exe

This is the result:
https://1drv.ms/u/s!AqitgM2nD0KZjO5cncTdnYV1fwhMwg

The think to understand is if this is a bug of VS Installer or something declared in the extension.

**Comment by shana** [comment]
@glat So one thing that's confusing me is that we've never had a 2.1.1.0 version released in the gallery. Did you mean 2.1.1.0 when you mentioned the version you upgraded to in the comments above?

**Comment by glat** [comment]
Yes, I mean. Just see the screenshot above with version offered by VS upgrade procedure.

**Comment by AArnott** [comment]
@shana said: 

> So one thing that's confusing me is that we've never had a 2.1.1.0 version released in the gallery.

What? I thought 2.1.1.0 was on the gallery for a while and that's what the issue was with the recent RC refresh?

**Comment by glat** [comment]
It was absolutely in. I saw it and VS offered to upgrade. So, it was not even ready for VS2017RC?

**Comment by shana** [comment]
@aanortt That's me mistyping the version that @glat reported. I meant 2.1.1.2, not 2.1.1.0

**Comment by shana** [comment]
@AArnott That's me mistyping the version that @glat reported. I meant 2.1.1.2, not 2.1.1.0

**Comment by glat** [comment]
@shana, in my first post I wrote 2.1.1.2 because I also tested it to check if the issue was already resolved. That version was downloaded by this repository. Even, the behaviour was not changed after upgrade from 2.1.1.0 to 2.1.1.2. The installer showed the same error.

**Comment by shana** [comment]
I'm assuming this is fixed with the VS RC  installer fixes and the extension updates we've shipped since, please reopen if there's still an issue.
