### ISSUE TITLE
GitHub Visual Studio login issue

### ISSUE THREAD

**Issue by MrDotDarko** [github/VisualStudio#705]
- GitHub Extension for Visual Studio  version: 2.1.1.0

- Visual Studio version: 14.0.25431.01 Update 3

__What happened__ (with steps, logs and screenshots, if possible)
(https://cloud.githubusercontent.com/assets/17105269/20930030/f4fbb8e4-bbc3-11e6-960e-d6217e8b9e85.png)

Ever since I have tried, I've never been able to login using the Visual Studio extension.  There has always been this red exclamation mark error saying (git:https//github.com) which doesn't really explain to me what exactly is going on.  It's not a username or password issue as I have tried making a fresh username for it, also its my understanding that if it was so, I would have the incorrect username/pw prompt. 

I've tried uninstalling then reinstalling to no avail. 

I have attached all needed files as gists

ActivityLog.xml
https://gist.github.com/MrDotDarko/8d1395054152964d2cd4dbee769b9540#file-activitylog-xml

extension.log
https://gist.github.com/MrDotDarko/8d1395054152964d2cd4dbee769b9540#file-extension-log

Thanks

**Comment by MrDotDarko** [comment]
I'm not sure what it is exactly but the account I was using was a Guest Account (Albeit it had upgraded admin privileges). 

I tried to replicate the issue on a normal newly created admin account and it worked fine so its looking like  it's a user privileges issue. I'll use a normal admin account instead, it works perfectly on it.

**Comment by jdshkolnik** [comment]
I've had the same issue and it persists to the latest version (2.1.1.5).

**Comment by shana** [comment]
@MrDotDarko `InvalidOperationException` is definitely wrong there 😞 Did you grab the extension.log file from %LOCALAPPDATA%\GitHubVisualStudio or from %TEMP%? One of them should have stacktraces, which might give us more clues as to why it's blowing up.

**Comment by MrDotDarko** [comment]
I think it was from local app data, what file am I looking for in the %TEMP% location?

**Comment by jdshkolnik** [comment]
This went away after resolving #743. You might want to see if it helps here.

**Comment by grokys** [comment]
This should now have been fixed with an update to github.com. Please reopen if you're still having problems.
