### ISSUE TITLE
Maintainer Workflow: Final pass of PR details UI

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#713]
We need a final pass of the PR details UI before the maintainer workflow feature is ready. The current state of the UI can be seen here: https://github.com/github/VisualStudio/pull/711

Pinging @donokuda to work his magic here.

**Comment by donokuda** [comment]
This should be finished with https://github.com/github/VisualStudio/pull/730 but feel free to reopen if y'all think otherwise.
