### ISSUE TITLE
Add renamed file status

### ISSUE THREAD

**Issue by paladique** [github/VisualStudio#719]
Files that have been moved will have a renamed status. `PullRequestFileStatus` only contains the added, removed, and modified status. When the [ModelService tries to parse the renamed status](https://github.com/github/VisualStudio/blob/master/src/GitHub.App/Services/ModelService.cs#L559), an invalid argument exception is thrown.

**Comment by grokys** [comment]
Ah good catch! One question: how do we want to display renamed files in the tree/list view? What does VS do?

**Comment by paladique** [comment]
VS is doing something similar to what we are. Hovering over the individual file displays the type of modification done to the file. 

Here's an example from a fork I have: 

![tree](https://cloud.githubusercontent.com/assets/1414307/21026506/ec9ebfe6-bd5a-11e6-98bf-739e7ad78457.PNG)

![list](https://cloud.githubusercontent.com/assets/1414307/21026508/f0b9ce2c-bd5a-11e6-8e9b-b16f80314b27.PNG)
