### ISSUE TITLE
Repo name field displays the previously created project name

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#72]
Repo name field doesn't display the current project name but the previous one

**Steps to reproduce:**
1. Create a new project
2. Make the initial commit
3. Publish the Repo 
4. Create another new project
5. Make the initial commit
6. Attempt to Publish

**Expected Results:** I think the Repo name field should display the new project name (or maybe be blank?)
**Actual Results:**  The field displays the previous project's name
Note: This is also the same behavior with the Repository Description field

![screen_shot_2015-09-04_at_11_09_10_am](https://cloud.githubusercontent.com/assets/10725993/9691177/c6ed95d6-52f5-11e5-8843-b728c010b7a4.png)

**Comment by shana** [comment]
The `Repo Name` in the title line is something that VS sets, so VS seems convinced you're on a different repository. When you created the new project, did you create it inside another existing repository? If you have a project open, and that project is in a git repository, and then you create another project, Visual Studio will set the path to a directory inside your current project by default. This might explain why it still thinks you're on the previous project.

**Comment by amytruong** [comment]
@shana - I was in another existing project/repo when I opened up another new project. That definitely explains why! :smile: 

Stupid question but how do I get out of the current git repo and project when I want to create an entirely new project/repo without having to close out the app? Apologies for the newbie question.

**Comment by shana** [comment]
@amytruong In the Create New Project dialog, you make sure to set the path to somewhere outside of a git repo, and check the Add to source control checkbox in case it's not checked. That will create a new solution and project in a new git reo and switch the source control context.
