### ISSUE TITLE
Maintainer Workflow: opening/diffing files in PRs from forks doesn't work.

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#725]
When viewing a PR from a fork in the PR details view, if the fork has not been fetched locally then "Compare File" and "Open File" fail silently. This is because to get the files to compare, we look up the PR HEAD commit and get the file from the returned tree.

We do a fetch before looking up the PR HEAD but if the fork is a repository that does not yet have a remote then we won't have fetched the commit.

I think we need to send an API request for [Get Contents](https://developer.github.com/v3/repos/contents/#get-contents) and then use the returned `download_url` to fetch the raw contents.

**Comment by grokys** [comment]
Actually we don't need to make two requests: the results from the API Get Contents contains the file contents.

**Comment by shana** [comment]
Oh nice, that's handy then! Will we be running against the limits of this API? I would imagine not, at least for text files...

**Comment by grokys** [comment]
Hmm, yeah, that's a good point. I'd say we _should_ be ok. Perhaps wait and see if anyone runs into problems?
