### ISSUE TITLE
Markdown doesn't display code blocks.

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#726]
The markdown parser we're using doesn't display code blocks properly. For example [this PR](https://github.com/aspnet/Mvc/pull/5097) is displayed like this:

![image](https://cloud.githubusercontent.com/assets/1775141/21052065/7033ffba-be23-11e6-9609-58e870b52e33.png)

**Comment by shana** [comment]
Oh dear, looks like someone needs to have some fun with the parser :P

**Comment by paladique** [comment]
Looks like this has something to do with double quotes. I made a PR and tried these combinations:

This is some text before some code:

This breaks
```  
Type.Method();

Type.Method("a string");
```

This breaks
```  
Type.Method();

Type.Method("a string");

Type.Method("a string");
```



This works
```  
Type.Method();
Type.Method("a string");
```

This works
``` 
Type.Method("a string");
Type.Method();
```

one line works
` Type.Method(); Type.Method("a string");`

This is the body text of the Pull Request Detail Model:

"This is some text before some code:\r\n\r\nThis breaks\r\n```  \r\nType.Method();\r\n\r\nType.Method(\"a string\");\r\n```\r\n\r\nThis breaks\r\n```  \r\nType.Method();\r\n\r\nType.Method(\"a string\");\r\n\r\nType.Method(\"a string\");\r\n```\r\n\r\n\r\n\r\nThis works\r\n```  \r\nType.Method();\r\nType.Method(\"a string\");\r\n```\r\n\r\nThis works\r\n``` \r\nType.Method(\"a string\");\r\nType.Method();\r\n```\r\n\r\none line works\r\n` Type.Method(); Type.Method(\"a string\");`"

**Comment by paladique** [comment]
Tried one more test with spacing, which did not work:

``` 
Type.Method();

Type.Method(); 
```
