### ISSUE TITLE
Crash on Update(VS2017RC)

### ISSUE THREAD

**Issue by abhijith94** [github/VisualStudio#727]
vsix install error.
- GitHub Extension for Visual Studio installed version:2.0.15.0
- GitHub Extension for Visual Studio update version:2.1.1.4
- Visual Studio version:2017RC(latest version)

vsix installer crashes on install.

![screenshot 58](https://cloud.githubusercontent.com/assets/20551722/21056969/bb798ed8-be5d-11e6-92c4-dc13d21f866c.png)

![screenshot 59](https://cloud.githubusercontent.com/assets/20551722/21056970/bb79cc40-be5d-11e6-8ccd-1fea1ecc4441.png)

**Comment by shana** [comment]
@tinaschrepfer This is with the new version that includes the PackageId. Could it be a sporadic bug in the vsix installer, or something more serious?

/cc @aarnott

**Comment by shana** [comment]
@abhijith94 Is this happening every time you try to upgrade?

**Comment by tinaschrepfer** [comment]
This is a known issue with the VSIXInstaller.exe in RC.1.  It will be addressed in an upcoming RC release.  For now, you won't be able to upgrade the GitHub extension.

**Comment by dub505** [comment]
Just an FYI, I cannot update to the latest version either.  My results appear to be the same as the original poster's.

![2016-12-09 1](https://cloud.githubusercontent.com/assets/13154648/21059099/95098a48-be06-11e6-9d9c-2e7f52ae7991.png)
![2016-12-09](https://cloud.githubusercontent.com/assets/13154648/21059106/9f3a9aca-be06-11e6-91d0-39435866423d.png)

**Comment by shana** [comment]
@dub505 @abhijith94 Could you try uninstalling the extension and then installing it, instead of updating? I'd like to figure out if this is only with the update path or if 2.1.1.4 is really unable to be installed in RC1.

**Comment by abhijith94** [comment]
@shana I tried to reinstall using **_visual studio installer_** but it still crashes.
Then I uninstalled github via **_visual studio installer_** and then installing it via **visual studio gallery** it crashes with the following log - 

10/12/2016 01:32:49 - Microsoft VSIX Installer
10/12/2016 01:32:49 - -------------------------------------------
10/12/2016 01:32:49 - vsixinstaller.exe version:
10/12/2016 01:32:49 - 15.0.25928.0 built by: D15REL
10/12/2016 01:32:49 - -------------------------------------------
10/12/2016 01:32:49 - Command line parameters:
10/12/2016 01:32:49 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:15.0.25928.0,/appidname:Microsoft Visual Studio,C:\Users\abhij\AppData\Local\Temp\VSIXgrjbxv2t.2vf
10/12/2016 01:32:49 - -------------------------------------------
10/12/2016 01:32:49 - Microsoft VSIX Installer
10/12/2016 01:32:49 - -------------------------------------------
10/12/2016 01:32:49 - Initializing Install...
10/12/2016 01:32:50 - Extension Details...
10/12/2016 01:32:50 - 	Identifier         : c3d3dc68-c977-411f-b3e8-03b0dccf7dfc
10/12/2016 01:32:50 - 	Name               : GitHub Extension for Visual Studio
10/12/2016 01:32:50 - 	Author             : GitHub, Inc
10/12/2016 01:32:50 - 	Version            : 2.1.1.4
10/12/2016 01:32:50 - 	Description        : A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
10/12/2016 01:32:50 - 	Locale             : en-US
10/12/2016 01:32:50 - 	MoreInfoURL        : https://visualstudio.github.com/
10/12/2016 01:32:50 - 	InstalledByMSI     : False
10/12/2016 01:32:50 - 	SupportedFrameworkVersionRange : [4.5,)
10/12/2016 01:32:50 - 
10/12/2016 01:32:51 - 	SignatureState     : ValidSignature
10/12/2016 01:32:51 - 	SignedBy           : GitHub, Inc.
10/12/2016 01:32:51 - 	Certificate Info   : 
10/12/2016 01:32:51 - 		-------------------------------------------------------
10/12/2016 01:32:51 - 		[Subject]       : CN="GitHub, Inc.", O="GitHub, Inc.", L=San Francisco, S=California, C=US
10/12/2016 01:32:51 - 		[Issuer]        : CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
10/12/2016 01:32:51 - 		[Serial Number] : 0EBDAA3F3A6BB14A964AF71ECC5E7C40
10/12/2016 01:32:51 - 		[Not Before]    : 14/01/2016 05:30:00
10/12/2016 01:32:51 - 		[Not After]     : 18/01/2019 17:30:00
10/12/2016 01:32:51 - 		[Thumbprint]    : C032DB9DCF24881728662DEE6895F243A313C44B
10/12/2016 01:32:51 - 
10/12/2016 01:32:51 - 	Supported Products : 
10/12/2016 01:32:51 - 		Microsoft.VisualStudio.Community
10/12/2016 01:32:51 - 			Version : [14.0,15.0]
10/12/2016 01:32:51 - 
10/12/2016 01:32:51 - 	References         : 
10/12/2016 01:32:51 - 		-------------------------------------------------------
10/12/2016 01:32:51 - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
10/12/2016 01:32:51 - 		Name         : Visual Studio MPF 14.0
10/12/2016 01:32:51 - 		Version      : [14.0,)
10/12/2016 01:32:51 - 		MoreInfoURL  : 
10/12/2016 01:32:51 - 		Nested       : No
10/12/2016 01:32:51 - 
10/12/2016 01:32:51 - 	Prerequisites      : 
10/12/2016 01:32:51 - 		-------------------------------------------------------
10/12/2016 01:32:51 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
10/12/2016 01:32:51 - 		Name         : Visual Studio core editor
10/12/2016 01:32:51 - 		Version      : [15.0.25824.0,16.0)
10/12/2016 01:32:51 - 
10/12/2016 01:32:51 - Signature Details...
10/12/2016 01:32:51 - 	Extension is signed with a valid signature.
10/12/2016 01:32:51 - 
10/12/2016 01:32:51 - The extension with ID 'c3d3dc68-c977-411f-b3e8-03b0dccf7dfc' is not installed to Microsoft Visual Studio.
10/12/2016 01:33:22 - The following target products have been selected...
10/12/2016 01:33:22 - 	Microsoft Visual Studio
10/12/2016 01:33:22 - 
10/12/2016 01:33:23 - Beginning to install extension to Microsoft Visual Studio...
10/12/2016 01:33:24 - Install Error : System.InvalidOperationException: Vsix Catalog Invalid
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

![screenshot 60](https://cloud.githubusercontent.com/assets/20551722/21062936/21e4742e-be79-11e6-8129-f0c31ace8ec4.png)

**Comment by shana** [comment]
@abhijith94 I'm sorry you're having this issue. Can you try installing this one, which is the same version that you had before you did the upgrade: https://github.com/github/VisualStudio/releases/download/v2.1.1.0/GitHub.VisualStudio.vsix

**Comment by abhijith94** [comment]
@shana It worked.

**Comment by shana** [comment]
@abhijith94 Great, thank you for testing!

**Comment by shana** [comment]
Closing this one down as it's a bug with the vsix installer that's shipped with RC. Hopefully an update there will fix this issue soon.
