### ISSUE TITLE
Access denied error while opening a directory

### ISSUE THREAD

**Issue by alrz** [github/VisualStudio#729]
- GitHub Extension for Visual Studio  version: 2.1.1.0
- Visual Studio version: VS2015 Update 3

__What happened__ 

Trying to scan ramdisk for repositories, this error shows up:

 `Access to the path 'x:\System Volume Information' is denied.`

and I couldn't open it directly.

**Comment by paladique** [comment]
Hi @alrz,

The extension doesn't scan the hard drive. How did you start the ramdisk scan?

**Comment by alrz** [comment]
> Local Repositories > Add

Apparently this doesn't add the repository in the selected directory, rather it search subdirectories.

**Comment by paladique** [comment]
That is part of Visual Studio's Git functionality - we don't have any control over it. If you'd like to report this to Microsoft, you can do it through Visual Studio's feedback button, next to the Quick Launch box.
