### ISSUE TITLE
PR list causes VS to hang when checking out PR in project with lots of PRs

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#738]
Steps to reproduce (note you may need to try this a few times - it doesn't always happen):

1. Check out `aspnet/Mvc`
2. Run with "break on CLR exceptions" disabled
3. Click on a PR
4. Click on the checkout link for the PR
5. Watch VS hang for a good amount of time

If you look at the output window, about 2250 `ObjectDisposedException`s are being thrown by `TrackingCollection.RemoveItem`. These exceptions are being caught in `ModelService.GetPullRequests` but I assume the sheer amount of exceptions being thrown and caught is causing a hang.

**Comment by StanleyGoldman** [comment]
I almost got a unit test where I can reproduce the scenario.

**Comment by StanleyGoldman** [comment]
You can also reproduce the scenario by performing any activity in the git repo with the view open.
For instance by checking in a simple file using the command line.

**Comment by grokys** [comment]
Fixed by #742
