### ISSUE TITLE
Search Work Items field looks disabled/cannot be accessed 

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#74]
Search Work Items field doesn't (seem to) work

**Steps to reproduce**
1. Navigate to Team Explorer 
2. Attempt to search in the "Work Items" field 

**Expected Results:** I think as a user, I should be able to click the box and enter in my search data (or control + ') to enable the field. I'm not sure what exactly is Work Items and tried to see if there was a "Work Items" section that I'm not aware of. 

**Actual Results:** I can't access the Work Items search field. It looks like it might be disabled?

![screen shot 2015-09-04 at 11 28 11 am](https://cloud.githubusercontent.com/assets/10725993/9694105/8e0f54a6-530a-11e5-8efe-779febfa6bef.png)

**Comment by Haacked** [comment]
Unfortunately we're not in control of that section. It doesn't work because it applies to Team System work items. When we implement issues, it'd be nice to make that search issues. I'm not sure such extensibility exists though. /cc @clboles

**Comment by shana** [comment]
FYI, Work items are the equivalent of our issues in Team Foundation Server (but with more functionality). See https://msdn.microsoft.com/en-us/library/hh409275.aspx
As far as I can tell, all the APIs that power that search box are internal/private, so it looks like there's no extensibility points that we can hook up to handle searching in a non-TFS context. :disappointed:

**Comment by amytruong** [comment]
Thanks for the context guys. :smile: I'll close this out.
