### ISSUE TITLE
2.1.1.5 can no longer be applied to VS 2017

### ISSUE THREAD

**Issue by artl93** [github/VisualStudio#741]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio  version: 2.1.1.5
- Visual Studio version: 15.0.26009.0

REPRO: 
- Install VS2017 (any build) 
- Go to https://marketplace.visualstudio.com/items?itemName=GitHub.GitHubExtensionforVisualStudio
- Download the extension (2.1.1.5) 
- Double-click the VSIX

EXPECTED: it to apply to VS 2015 and 2017
RESULT: it only applies to VS 2015

![image](https://cloud.githubusercontent.com/assets/9855795/21192698/4fc80af0-c1de-11e6-8f4e-0b7198066ccc.png)

**Comment by artl93** [comment]
I don't even see a release 2.1.1.5 here: https://github.com/github/VisualStudio/releases
In 2.1.1.4, the vsix manifest looks right. 
In the 2.1.1.5 I downloaded from the gallery, the vsixmanifest looks lie this: 
  `<Installation AllUsers="true">
    <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[14.0]" />
  </Installation>`

**Comment by artl93** [comment]
@aarnott - it sounds like this is a known thing ?

**Comment by AArnott** [comment]
Yes, this is a known thing to stop the failures from folks trying to install 2.1.1.4 on the first VS2017 RC.
VS2017 RC refresh customers can install 2.1.1.4 via the VS installer. 

When GitHub releases 2.1.1.6 I expect they will re-enable VS2017 support so you can update from the gallery.

**Comment by shana** [comment]
@artl93 Yup, we had to pull the extension from the gallery temporarily while the installer issues get fixed, we'll get it up again as soon as it's safe!

**Comment by thoemmi** [comment]
It's still not working with version 2.2.0.4. Visual Studio version is 15.0.26020.0.

**Comment by shana** [comment]
@thoemmi Is 2.2.0.4 not letting you install on VS 2017 at all, or is the installation failing in some other way?

**Comment by thoemmi** [comment]
In **Extensions and Updates** I select to update the extension:
![image](https://cloud.githubusercontent.com/assets/73690/22200995/f3ff0fcc-e161-11e6-8d0c-633f8597a69c.png)
But when I close Visual Studio and it actually starts the update, it says
![image](https://cloud.githubusercontent.com/assets/73690/22201016/10623e00-e162-11e6-8d5c-e5f467aa3956.png)
I get the same message when I download the vsix from the marketplace.

**Comment by shana** [comment]
@thoemmi That's really weird, I suspect VS's extension catalog is confused about what you have installed (or possibly trying to update the wrong vsix). Can you try downloading https://ghfvs-installer.github.com/releases/2.2.0.4/GitHub.VisualStudio.vsix directly and installing it?

**Comment by grokys** [comment]
@thoemmi also try uninstalling the extension from VS before reinstalling.

**Comment by thoemmi** [comment]
@grokys Uninstalling the existing old extension and installing the new one afterwards did the trick 👍

**Comment by jcansdale** [comment]
@thoemmi Did you uninstall using the Visual Studio installer or the extension manager?

The way I understood it, extensions installed using the extension manager should override extensions installed with Visual Studio for all users. Maybe this no longer works in Visual Studio 2017?

**Comment by thoemmi** [comment]
I uninstalled the extension in Visual Studio's **Extensions and Updates** dialog.

**Comment by tebeco** [comment]
Is there a workaround to let Visual Studio allow us to Uninstall the extension ? :p
```27/01/2017 13:08:09 - System.IO.FileNotFoundException: Unable to find the specified file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean markAsPackComponent)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)
```

**Comment by AArnott** [comment]
If VS won't let you uninstall the extension with the Extension Manager or the VS Installer (that is, if both fail) your installation may be corrupted by an earlier version of GitHub extension. Per the release notes in VS, you may need to uninstall VS and reinstall to get out of this state.
