### ISSUE TITLE
How many uninstalls does it take to remove this extension?

### ISSUE THREAD

**Issue by jdshkolnik** [github/VisualStudio#743]
Hi,

Not trying to be snide, I just thought the question was the most succinct way to convey the problem.

- GitHub Extension for Visual Studio  version: 2.1.1.5
- Visual Studio version: 4.6.01586

![image](https://cloud.githubusercontent.com/assets/2047520/21196178/b98b2672-c204-11e6-8781-3483954b22ce.png)

![image](https://cloud.githubusercontent.com/assets/2047520/21196204/d54dba32-c204-11e6-8aa9-5d2878dfc9cd.png)

![image](https://cloud.githubusercontent.com/assets/2047520/21196217/db322bd6-c204-11e6-9215-5b2510ace74f.png)

![image](https://cloud.githubusercontent.com/assets/2047520/21196257/fd32d136-c204-11e6-8e13-c53143626699.png)

**Comment by grokys** [comment]
Hi @jdshkolnik - yes that is very strange, I've never seen that behavior. Unfortunately we're not in control of the Visual Studio extension install/uninstall process so this would appear to be a Visual Studio bug.

@AArnott have you ever come across this?

**Comment by jdshkolnik** [comment]
I suspect it might be related to #705 in some way although it could also just be coincidence.

**Comment by shana** [comment]
You mentioned 2.1.1.5, but all your screenshots have 2.0.15.1 in it. Which version are you trying to uninstall, exactly?

**Comment by jdshkolnik** [comment]
@shana I had 2.1.15 but then I uninstalled it and so began my own GitHubVS Groundhog Day.

**Comment by shana** [comment]
@jdshkolnik do you have VS 2017 RC also installed in this machine by any chance?

**Comment by jdshkolnik** [comment]
@shana No, just the latest version of 2015 Enterprise.

**Comment by shana** [comment]
(also now we all have "I got you babe" stuck in our heads btw)

**Comment by shana** [comment]
@jdshkolnik so VS is funny about uninstalls, it never actually deletes anything from disk, it just marks extensions as "not active". I'm guessing something got it confused with the previous installation and it just never deactivated it.

Try opening a developer command line and running `devenv /updateConfiguration` after uninstalling the extension and exiting VS, see if that works.

if it doesn't help, try 'devenv /setup` (this one takes longer to run)

**Comment by jdshkolnik** [comment]
No luck with either command although we did manage to scare it a bit; the version went down.

![image](https://cloud.githubusercontent.com/assets/2047520/21207010/827a4396-c233-11e6-92a7-1ae3c9f315ef.png)

**Comment by shana** [comment]
It definitely is very confused. You can keep uninstalling and doing `devenv /updateConfiguration` (or `/setup` if that one is the one that does something) to hopefully go down the list of previously installed extension versions and finally clean it up.

The alternative is to go to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\` and do a search for `GitHub.VisualStudio.dll`. All the directories that contain a file with that name are installations of GHfVS (as I said, VS never actually cleans up after itself...). You can then delete or move all the directories that have the file (and *not* anything else, be careful on what you delete or move). You then have to run `devenv /setup` on a developer command line run as administrator to refresh the VS catalog.

**Comment by jdshkolnik** [comment]
There were so dozens of folders to delete but that finally did it! Wow. Thank you.

**Comment by AArnott** [comment]
@grokys, no I haven't seen this before.
@alexeyler, have you?

**Comment by AlexEyler** [comment]
@AArnott @grokys I haven't heard of this one. We normally mark the extension to be deleted by renaming the extension's vsixmanifest file as ".deleteme". When you start VS as an administrator, we would be able to actually delete or uninstall the extension. I'm not sure what went wrong in this scenario.
