### ISSUE TITLE
Team Explorer - Home view: Open Repository in Browser

### ISSUE THREAD

**Issue by couven92** [github/VisualStudio#747]
In the Team Explorer window, you should have the possibility to open up the Homepage of the GitHub repository in the Brower.

This could be done by adding a `Home Page` Button next to the already existing `Pulse`, `Graphs`, `Issue` and `Wiki` Buttons.

Alternatively, double-clicking on the Repository name above the buttons, where the repository link is displayed as a subtitle, would also be a reasonable solution.

- GitHub Extension for Visual Studio  version: `2.1.1.4`
- Visual Studio version: `Microsoft Visual Studio Enterprise 2017 RC VisualStudio/public/d15rel/15.0.26014.0`

**Comment by grokys** [comment]
Yes, I can see this would be useful. The only thing I'm worried about is an over-proliferation of buttons. However, I suspect that the number of people clicking on at least "pulse" and "graphs" would be pretty low (@saraford - we should probably collect metrics for these?) and could be replaced with a `Home Page` button.

**Comment by shana** [comment]
We could use the name of the repository as a link to it, too.

**Comment by jcansdale** [comment]
I have to admit, `Project > Home` does make a lot of sense. I'd like to see `Project > History` as well.

I'm not sure I've ever used Pulse, Graphs or Wiki, but I'd use `Home` and `History` a lot!

**Comment by couven92** [comment]
In the newest VS2017, the subtitle of the GitHub repository name is now a clickable link. This is great!

However, the `Home` button next to the `Changes`, `Branches`, etc. buttons is still missing. With the clickable link the `Home` but is not necessarily required, so if that feature is not being implemented I'd be okay with closing this issue now. Otherwise, we can leave it open as a reminder...
