### ISSUE TITLE
Add 'GitHub > Blame' command

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#748]
I often want to know about the history of a particular line. It would be nice if there was an obvious way to find this information.

The command would be similar to 'GitHub > Open on GitHub', but would open the 'Blame' page instead.

For example, 'GitHub > Open on GitHub' would go here:
https://github.com/github/VisualStudio/blob/76b99f8e1077f63e6f2dccc616a47933ec53af16/src/GitHub.Exports/Helpers/AssemblyResolver.cs#L53

For example, 'GitHub > Blame' would go here:
https://github.com/github/VisualStudio/blame/76b99f8e1077f63e6f2dccc616a47933ec53af16/src/GitHub.Exports/Helpers/AssemblyResolver.cs#L53

I know you can find the same information using 'Source Control > Annotate', but I didn't have a clue what 'Annotate' even meant! Also, the GitHub blame page is much prettier/more functional. 😄

**Comment by paladique** [comment]
This was merged in #835
