### ISSUE TITLE
Refactor Local/RemoteRepositoryModel classes.

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#756]
A while ago I refactored the repository model classes, but I didn't quite get it right as we've ended up with [this abomination](https://github.com/github/VisualStudio/blob/fixes/684-start-page-clone-dialog-ui/src/GitHub.StartPage/StartPageRepositoryModel.cs).

**Comment by shana** [comment]
Well, that abomination is now gone so less bad 😄 
Probably a good idea to go over them and audit the design for any improvements to be made.
