### ISSUE TITLE
Markdown doesn't display checkboxes

### ISSUE THREAD

**Issue by paladique** [github/VisualStudio#765]
Similar to #726 and code blocks, checkboxes aren't rendered in the details view.

![capture](https://cloud.githubusercontent.com/assets/1414307/21816206/4b0fad60-d72d-11e6-94c1-2efb5881c840.PNG)

**Comment by shana** [comment]
Checkboxes aren't standard markdown, they're a github extension. We'll need to customize our parser/renderer for it.
