### ISSUE TITLE
Connect dialog tooltips have strange prefix

### ISSUE THREAD

**Issue by StanleyGoldman** [github/VisualStudio#777]
![](http://i.imgur.com/RjAQtsw.png)
![](http://i.imgur.com/YKEGkzA.png)

**Comment by shana** [comment]
Yeah, that's the url that gets sent to the handler which then determines whether to open the webbrowser or the file dialog to handle them. `u:` is browser, `o:` is open (file dialog). I'm not sure the syntax parser for these messages supports separate "tooltip" text.

**Comment by grokys** [comment]
We should probably pass `NotificationFlags.NoTooltips` to `ShowNotification` to prevent this: that's what TE seems to do.

**Comment by meaghanlewis** [comment]
I believe that this banner now just looks like this:

![screen shot 2018-09-11 at 3 41 36 pm](https://user-images.githubusercontent.com/10103121/45391837-70cfd700-b5d9-11e8-9021-297e9c0317ca.png)
