### ISSUE TITLE
After logout only the login for github enterprise is active

### ISSUE THREAD

**Issue by Silv3rcircl3** [github/VisualStudio#78]
Let's assume I'm logged in into account A, open a local project from account B, make some changes and then try to commit these changes to GitHub. 
This will obviously fail and the output window from VS shows a 404.
So I click on the ```Sign out``` link   
![image](https://cloud.githubusercontent.com/assets/11612539/9810548/e5c16344-5871-11e5-823c-ece2b0f4dc47.png)   
then on the ```Login``` link
![image](https://cloud.githubusercontent.com/assets/11612539/9810577/11e661d6-5872-11e5-9adb-1fbd962e1469.png)   
and now the ```Connect to GitHub``` dialog automatically selects the ```GitHub Enterprise``` login and I'm unable to select the normal GitHub login. 
![image](https://cloud.githubusercontent.com/assets/11612539/9810784/6af5ba5a-5873-11e5-86b9-37982dad433a.png)

This behavior only appears if I'm opening a project from a different account. If I logout/login in a project from account A it is working fine. 

Regards.

**Comment by shana** [comment]
Thanks for the bug report!

If you logout and then switch to the Team Explorer Home page, and then go back to the Connect page and login, does it still happen?

**Comment by marcpiechura** [comment]
No, then it works :)

**Comment by shana** [comment]
Awesome, thanks for testing :blush:

**Comment by Silv3rcircl3** [comment]
Since this issue was fixed in some of the updates you can close this one ;)

**Comment by shana** [comment]
Ah, looks like I forgot to mark this one as fixed, thanks for the reminder! ^_^

**Comment by danielft11** [comment]
What´s the solution?

**Comment by meaghanlewis** [comment]
Hi @danielft11 we believe that we fixed this issue in this PR: https://github.com/github/VisualStudio/pull/1280. Are you still experiencing this issue?

One workaround that fixed this problem before was to:

1. Open Credential Manager from the Windows Start Menu
2. Click on Windows Credentials
3. Select the credentials related to your Enterprise server
4. Click on Remove
