### ISSUE TITLE
Error message not being cleared after checkout pull request succeeds

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#786]
- GitHub Extension for Visual Studio  version: 2.2.04
- Visual Studio version: Enterprise 2015

__What happened__

1. Opened GitHub repo in Visual Studio
2. Clicked 'Pull Requests' button
3. Selected pull request
4. Clicked on 'Checkout [pull-request-name]' link
5. Checkout failed (not sure why this happened):

![checkout](https://cloud.githubusercontent.com/assets/11719160/22077619/c288e9a0-dd69-11e6-9e2f-3cc6e66d5476.png)

6. Checkout subsequently succeeded
7. Error message was not cleared

__Expected Behavior__

Error message cleared when checkout succeeds.

**Comment by jcansdale** [comment]
Here's a different, but possibly related issue:

1. Open a solution with uncommitted changes
2. Open a PR
3. The 'Checkout' link is disabled because of the uncommitted changes
4. Right click and 'undo changes' on changes files in 'Team Explorer'
5. The link remains disabled

![uncommited](https://cloud.githubusercontent.com/assets/11719160/22475822/2596cdc8-e7d8-11e6-8f5e-b234f91ff377.PNG)

It is possible to refresh, but it wasn't immediately obvious.

(just making notes as I go along)

**Comment by jcansdale** [comment]
Trying to repro but came across this: #823

**Comment by grokys** [comment]
Closed by #842.
