### ISSUE TITLE
Insert Comment when reviwing is not working

### ISSUE THREAD

**Issue by AlbertoMonteiro** [github/VisualStudio#788]
- **GitHub Extension for Visual Studio version**: 2.2.0.4 
![image](https://cloud.githubusercontent.com/assets/836496/22160003/4d5e24a0-df22-11e6-91ef-9b255c0dcefa.png)
- **Visual Studio version**: Visual Studio 2015 Community Edition(14.0.25431.01 Update 03)
![image](https://cloud.githubusercontent.com/assets/836496/22160017/5bb07b16-df22-11e6-8696-a93dccdf9357.png)

-----------------------

### Description

I am trying the new features about PR stuff(https://github.com/blog/2305-manage-pull-requests-with-the-github-extension-for-visual-studio).

When I try to insert a commend nothing happens
![image](https://cloud.githubusercontent.com/assets/836496/22159835/88a5d4d2-df21-11e6-9af7-f7bc630acb1a.png)

And just a few files contains the option to insert a comment like the *.cs, but other files in PR, when I press right click in some line, the Insert Commend option does not appear.

Btw, how can I finish a review?

When I review code from GitHub using browser, I add comments on lines, and then I finish it clicking in "Review Changes" selecting one option: "Comment", "Approve", "Request Changes". I didnt found any way to this thought the Visual Studio.

**Comment by grokys** [comment]
Hi @AlbertoMonteiro - thanks for writing in! Unfortunately the "review" part of the PR workflow isn't yet implemented - we're hoping to implement this in the coming months. I think the "Insert Comment" menu you're seeing is part of Visual Studio itself rather than the GitHub extension.

**Comment by AlbertoMonteiro** [comment]
@grokys thanks for the feedback!
