### ISSUE TITLE
Inconsistent UI state in PR details view

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#797]
![image](https://cloud.githubusercontent.com/assets/310137/22293160/d10365a0-e30e-11e6-882f-a4e908d3ba73.png)

I tried to pull and got a merge conflict due to the remote branch being force-pushed, which left changed files on the local checkout. I reset the branch on the command line, which caused the ✔️ "Local branch up to date" message to show up, but the "4 uncommitted changes would be overwritten by merge" error never went away.

Steps to repro:

- Checkout a PR branch
- Force-push to the remote branch
- Switch to another branch locally
- Checkout the PR branch again
- Click on pull
- Click on pull again
  - Merge error message shows up
- Reset the branch on the command line to match the remote branch. Validate that local merge conflict files are gone and there's no locally changed files on git status
  - ✔️ message shows up, error message never goes away.

**Comment by grokys** [comment]
I think this is the same as https://github.com/github/VisualStudio/issues/786
