### ISSUE TITLE
GitHub provider on Start Page should use the new Clone API

### ISSUE THREAD

**Issue by prasethu** [github/VisualStudio#800]
In VS 2017, we've introduced a new Clone API that enables cloning in Team Explorer and returns progress through an IProgress<ServiceProgressData>.

To enable the Start Page to display progress in the status bar, the GitHub provider should pass on the IProgress<ServiceProgressData> to the Clone API.

A sample usage of the new Clone API can be found here:
https://github.com/prasethu/CloneAPISample

Specifically this file: CloneAPISample/VSIXProject2/Command1.cs

**Comment by prasethu** [comment]
@shana

**Comment by shana** [comment]
@prasethu Thanks for the heads up, we'll get this included on our roadmap!

**Comment by grokys** [comment]
@prasethu - I've implemented that here:

https://github.com/github/VisualStudio/commit/49a16aecd7b98627307a6811b448a3f56f3cd52b#diff-37b2ed98a57be40299d610a06bbc51b8R68

This seems to work, however I'm not sure if we should be creating a new `Progress<ServiceProgressData>` there (as in your sample) or if the intention was that we should be passing on the `IProgress<ServiceProgressData>` that is passed to us in [`AcquireCodeContainerAsync`](https://github.com/github/VisualStudio/blob/fixes/800-vs2017-clone-api/src/GitHub.StartPage/StartPagePackage.cs#L41)?

**Comment by prasethu** [comment]
@grokys Sorry about the late response but yes you should be passing it over.
