### ISSUE TITLE
Open file directly from project when PR is checked out

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#801]
When a PR branch is checked out, opening the file from the PR details view should open the current version of that file rather than a temporary file.

**Comment by grokys** [comment]
Thinking about this a little more, "Open" should continue with its current behavior as it's a complement to "Compare" which compares from BASE and HEAD. However we should probably add a new "Open in Solution"-or-something context menu which opens the file as it currently stands on disk.

**Comment by shana** [comment]
As a user, I would assume that doing "Open" would open the file in the project and not a temporary file, if the file is available, so I agree with your initial assertion. There's no reason for Open to open a temporary file if the branch is checked out and matches what the PR has.

Maybe we should not call the action "Open" if we can't open the "real" file, and instead call it "Preview" or something to that effect, to note that it's not the "real" thing on disk. If the "real" file is available, then we can have the "Open" action there to open it.

**Comment by grokys** [comment]
Yeah, I'd agree except the rest of team explorer opens a temporary file, and that makes sense because if you're diffing you expect the diff of the file as it stands in the commit.

The difference with the PR view is that if you've got the branch checked out and no local changes the file in the PR and the file on disk are the same. However what I'm worried about is that if you have local changes, they can be different. So you say "fine, lets open the file on disk if there are no local changes" but then the user makes local changes to that file and suddenly the "open" action is different.
