### ISSUE TITLE
Have a better way of opening the PR on the website from the details view

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#803]
Right now the only way to open the PR on the website from the PR details view is to click on the "View conversation on GitHub" link.

![image](https://cloud.githubusercontent.com/assets/310137/22354904/c9a0fe16-e427-11e6-9321-5765054d3092.png)

The position of the View Conversation link means that it's not the main thing the user is going to see (it's down below and its position changes depending on how big the PR description is. Because it's at the end of the PR description, it looks like it's something that's a part of the description, and not a common action to perform.

Feels like we need a better way to open the browser in this context, something like:

- Link popout or GitHub icon on the toolbar for going to the website
  - GitHub icon would allow us to always go to the website from any pane view
- Right click on the PR title

**Comment by jcansdale** [comment]
Even simpler would be to hyperlink the hash in `Pull Request #787`. I think people expect a link when they see a hash.

We should probably hyperlink the `Fixes #778 Fixes #779` references as well...

**Comment by grokys** [comment]
I think this was at least partially addressed by #836. Should we close this issue?

**Comment by jcansdale** [comment]
Yes, I think #836 addresses it. What do you think @shana?

RE my comment about hyperlinks, I can see a day where `#` hyperlinks navigate within the `GitHub` pane. Having a consistent navigate to equivalent page on github.com (like we do in #836) makes sense.
