### ISSUE TITLE
Link buttons on PR list don't say what button will do

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#824]
- GitHub Extension for Visual Studio version: 2.2.0.6

1. Hover over PR in list
2. See tooltip with same text as link/button.

![image](https://cloud.githubusercontent.com/assets/11719160/22488533/7d3427c4-e80a-11e6-8147-856c0098732f.png)

I expected the tooltip to be a description of what would happen if you click on the link.
Something like: ~~`Check out pull request locally`~~ `View pull request details`.

**Comment by shana** [comment]
Ah, eh, indeed. I think we were using it to display the full PR title in case it got truncated by the limited horizontal spacing. That was before we had a details view, though, so having the tooltip be more explicit about what it does would be more useful here, I agree.

**Comment by shana** [comment]
I believe we always capitalize `Pull Request` because it's a Thing(tm), so maybe "View Pull Request details"? Does that look weird, with everything but details capitalized?

**Comment by jcansdale** [comment]
No, I think "View Pull Request details", looks okay.

I guess the # links should also say: "View Pull Request on GitHub"?

**Comment by shana** [comment]
> I guess the # links should also say: "View Pull Request on GitHub"?

Yup, sounds like a good idea!

**Comment by grokys** [comment]
Closed by #827.
