### ISSUE TITLE
Changed file table columns keep ending up too narrow

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#825]
- GitHub Extension for Visual Studio  version: 2.2.0.6
- Visual Studio version: 2015

The change file columns keep ending up compressed. All I did was change PR.

![image](https://cloud.githubusercontent.com/assets/11719160/22507653/76d7fbde-e87e-11e6-91f4-2063105ee25c.png)

**Comment by paladique** [comment]
How were you able to repro this? I'm switching between PRs and not seeing this yet.

**Comment by jcansdale** [comment]
It kept doing it when I tried it that time. Now I'm struggling to repro. I'll keep an eye on it...

**Comment by jcansdale** [comment]
@paladique Okay, I have a repro. 😄

It appears to be when you open the PR details of a PR that is already open...

1. Open GitHub tool window.
2. Select a PR from the list.
3. Checkout the PR.
4. Navigate back (or click on PRs button).
5. Select the same PR from the list.

![image](https://cloud.githubusercontent.com/assets/11719160/22783670/b9ebfcb2-eec4-11e6-9d81-c06b82bb6223.png)

Seems to be pretty consistent.

**Comment by paladique** [comment]
Aha! Repro'd. Looks like it's only happening when you've selected the listview option.

**Comment by jcansdale** [comment]
@grokys If anyone is using the table view, this happens a lot. I've taken a look and so has @paladique, but we won't sure how it fix it. It's probably either dead simple or a right PITA. 😉
