### ISSUE TITLE
Support for multiple visual studio version

### ISSUE THREAD

**Issue by MistyKuu** [github/VisualStudio#828]
Hey,
It's not really an issue here but I don't know where I can ask you about this. I'm trying to add support for multiple versions of visual studio in my extension and I'm trying to follow the way you did. Create two separate projects GitHub.TeamFoundation.14 and GitHub.TeamFoundation.15 which reference different TeamFoundation libraries (respectively for vs2015 and 2017). However when I register them both in my package as MEF asset then it works only in Visual 2015. It looks like it tries to load GitHub.TeamFoundation.14.dll project and it fails because it contains incompatible teamfoundation libraries. How does your application loads them? I don't have a clue what else has to be done to make it work. I would appreciate any help. Thank you!

**Comment by paladique** [comment]
:wave: @MistyKuu While I'm not super familiar with the multiple version support part, someone in our gitter chat asked a question similar to yours. Here's an excerpt from that discussion:

> the trick is to have version-specific team explorer types as fields, mef properties or mef constructor parameters in your types, so that mef throws when it's scanning assemblies to build the mef catalog for later consumption

There's more discussion about it in our [gitter](https://gitter.im/github/VisualStudio) Check it out when you have a chance!
Hope that helps!

**Comment by jcansdale** [comment]
Our solutions are very similar except:

![image](https://cloud.githubusercontent.com/assets/11719160/22574465/e1c0f6f2-e9a6-11e6-898c-d7a7214f1620.png)

**Comment by MistyKuu** [comment]
@paladique thanks I'll take a look at it!
@jcansdale Yes I did exactly the same thing, I will check the gitter to find out how it's done.

**Comment by MistyKuu** [comment]
@paladique This is exactly what I was after, Thanks!

**Comment by grokys** [comment]
I wrote a blog post about this as it's something a few people have asked: https://grokys.github.io/ghfvs/supporting-multiple-visual-studio-versions/
