### ISSUE TITLE
Cloning a foreign Repository would be great

### ISSUE THREAD

**Issue by schittli** [github/VisualStudio#830]
Hello

This addon allows just to clone my own repositories.
Because all public github Projects allows to create a clone, it would be great if this addon would allow to clone any Project:

1. Paste any github clone link
2. Define the local directory
3. Go

Thanks a lot in advance,
Kind regards,
Thomas

**Comment by grokys** [comment]
Hi Thomas,

That feature is actually provided by visual studio:

- Go to the Team Explorer Connect page
- Under "Local Git Repositories" click "Clone"
- Enter the repo URL and local directory
- Click "Clone"

I agree though that it's kind of hard to find. We should maybe consider allowing the option of cloning from a URL in our clone dialog.

**Comment by schittli** [comment]
Hi grokys,
thank you very much for your fast, patiently and complete answer!
(I also googled for a solution and searched in this github project issues)

> We should maybe consider allowing the option of cloning from a URL in our clone dialog.

Yes, this would be great... it is usually a great usability practice, if one process (clone) has one start point and can handle every option (cloning own and foreign repositories).

Kind regards, Thomas
