### ISSUE TITLE
Right Click menus and dropdowns don't work

### ISSUE THREAD

**Issue by nateous** [github/VisualStudio#841]
logs gist: https://gist.github.com/nateous/9797e263a63afe4317659172047bc826

I've just updated to the latest version of the extension and now when I open my project I can't right click on a branch and create a new branch, and even the Action dropdown doesn't work. I have no idea what I broke, I've never seen this before.

This image probably doesn't help, because I can open the context menu...

![image](https://cloud.githubusercontent.com/assets/5033732/22715125/8e783f4a-ed5d-11e6-8601-7158ba30e1c9.png)

- GitHub Extension for Visual Studio  version: 2.2.0.6
- Visual Studio version: 
Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

1. I opened the project
2. Double clicked to get to `master` branch (worked fine?)
3. Right-click to create a new feature branch (nothing happens, I wait because sometimes it is slow, nothing)
4. Restart VS, try again, still no dice... 
5. Now I'm sad.

PS 
I'm in the middle of debugging (MS ticket is open and ongoing) why the extension loses connection, it seems that VS loses its ability to connect to any network related resource, so that is not really an extension issue. MS tech had me uninstall resharper... it got better, but luckily it happened again before they closed the issue, now they want me to use VS in safe mode... ugh (no plugin!). Oh yeah, and I'm trying to work too! ha!

**Comment by nateous** [comment]
Ok, well maybe updating to latest version has ruined my auth? I have 2fa turned on.

`Error logging into 'https://github.com/' as 'nateous'
Octokit.ForbiddenException: This API can only be accessed with username and password Basic Auth`

**Comment by nateous** [comment]
It says I am logged in....
![image](https://cloud.githubusercontent.com/assets/5033732/22715450/0329ef36-ed5f-11e6-9ee8-013f0486cb32.png)

**Comment by nateous** [comment]
Inline forms work, but the `View Options` dropdown doesn't open.
![image](https://cloud.githubusercontent.com/assets/5033732/22715530/474f16f0-ed5f-11e6-96bf-29111d8da677.png)

**Comment by grokys** [comment]
Hi @nateous - that is indeed very strange. However the windows in your screenshots don't contain any GitHub for Visual Studio content, so this would seem to be a Visual Studio issue. But just in case, try uninstalling GHfVS and see if the context menus come back.

**Comment by nateous** [comment]
Reinstalling GHfVS right? Because that is where the context menus are missing. I'll try that.

**Comment by grokys** [comment]
No, uninstalling GHfVS. The missing context menus aren't GHfVS's, they're Team Explorer's.

**Comment by nateous** [comment]
MS tech did have me devenv /clearcache, devenv /updateconfiguration, I really hope that didn't ruin all the things.

**Comment by nateous** [comment]
Uninstalled GHfVS, and context menus work fine (if that is what you are thinking wasn't working).

**Comment by nateous** [comment]
oh... wait, I'm so confused right now. After uninstalling GHfVS I still see my branches and can right click again. Am I totally confused as to what is giving me the ability to connect to my github stuff?

**Comment by grokys** [comment]
Yeah, it is slightly confusing! Team Explorer provides the git functionality in Visual Studio. We provide the _GitHub_ related functionality. So that means logging into GH with 2FA, cloning repositories from GH, publishing repositories to GH, Pull Requests etc. The basic git functionality on the other hand is Team Explorer.

It's hard to tell where one starts and the other ends though, for example:

![image](https://cloud.githubusercontent.com/assets/1775141/22715969/d5325584-ed93-11e6-8eb4-811c6e652374.png)

**Comment by nateous** [comment]
OK, I'm not sure which I actually use more, but context menus are back. Sorry for my confusion.

**Comment by nateous** [comment]
After reinstalling the context menus still work... so, shananigans... time to go home! Thanks again @grokys !
