### ISSUE TITLE
Split unit tests into one test project per project under test

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#857]
At the moment we're using one monolithic test project for all project in our solution. This means that to execute a single test, we need to build our entire solution. On my laptop it can easily take over a minute to execute a single test! This isn't very conducive to using testing. 😉 

I propose taking a light touch approach to this.

1. Duplicate the `UnitTests` project and rename/re-GUID for a project under test.
2. Add as Link source references to the tests for the target project.
3. Add as Link source references to any required test helper classes.
4. Remove any unused project, assembly and NuGet references.
5. Execute our unit tests quickly and rejoice. 🎈 

If/when we're happy with the new structure, we can consider moving our test source files into the individual test projects.

Does that make sense?

**Comment by grokys** [comment]
Yeah, sounds like a good idea. I'd be interested to see what the difference in speed under ncrunch is.

**Comment by jcansdale** [comment]
If I add a new unit test to `GitHub.App.UnitTests`, NCrunch now executes it within around 6 seconds. I think that's an improvement. 😉

**Comment by grokys** [comment]
Excellent! I say lets go ahead and split the unit tests then.

**Comment by meaghanlewis** [comment]
Just an FYI, I'm planning to start working on this next week. I'll split out main UnitTests project into:
- GitHub.Api.UnitTests
- GitHub.App.UnitTests
- .... (_and so on, until_)
- GitHub.VisualStudio.UnitTests
