### ISSUE TITLE
Can't see any pull request if origin is a fork

### ISSUE THREAD

**Issue by thomaslevesque** [github/VisualStudio#863]
- GitHub Extension for Visual Studio  version: 2.2.0.6
- Visual Studio version: 2015.3

When I open a Github project, I can't see any pull request in GHVS. I suspect this is because my repo is a fork, not the source repo where the pull requests are, but this doesn't fit my workflow at all...

Here's my use case :
- I maintain a project that is owned by an organization (in this case, [FakeItEasy](https://github.com/FakeItEasy/FakeItEasy/)
- I don't commit directly to the source repo; instead, I work on a fork, and submit pull requests from there
- In my local clone, I have 2 main remotes: `origin` is my fork, and `upstream` is the source repo

If I rename `origin` to something else, and `upstream` to `origin`, I can see the pull requests, so it seems GHVS uses `origin` to decide in which repo it looks for pull requests

There should be a way to select the remote for which I want to see the pull requests. Or maybe look at the source repo if `origin` is a fork. In the current state, this feature is useless unless my setup is exactly the one GHVS expects.

**Comment by grokys** [comment]
Hi @thomaslevesque - thanks for the detailed report! Yes this is actually something we've talked about and something we'd like to implement. Keep your eyes peeled!

**Comment by weitzhandler** [comment]
Very compelling!
Please give more love for contributors that are not owners and offer us more options to fetch/sync/pull branches from upstream. Currently only local/origin is available.
