### ISSUE TITLE
Pull request screen, Changes drop down menu icon hard to see in dark theme

### ISSUE THREAD

**Issue by tocsoft** [github/VisualStudio#872]
GitHub Extension for Visual Studio version: 2.2.0.6
Visual Studio version: 2015 update 3

The icon for the menu to the right of the changes node isn't right on a dark theme, and can't be seen very well.

![image](https://cloud.githubusercontent.com/assets/166440/23092183/36470708-f5bd-11e6-80a6-2e3514db8382.png)

Black on dark grey not the easiest combination to see 😉

**Comment by grokys** [comment]
Yeah this menu is actually going away in the next release: #866, so it will no longer be a problem.
