### ISSUE TITLE
cannot install due to missing package.json

### ISSUE THREAD

**Issue by elipapa** [github/VisualStudio#876]
- GitHub Extension for Visual Studio  version: v2.2.0.7
- Visual Studio version:  1.9.1 mac os

cannot install the extension after downloading it. It complains that `extensions/package.json` cannot be found.

![image](https://cloud.githubusercontent.com/assets/112610/23174196/80651e90-f853-11e6-9888-1fb6da141009.png)

**Comment by paladique** [comment]
Hi @elipapa,

Currently the GitHub for VS Extension will only work with Visual Studio 2015 and 2017 in a Windows environment. The screenshot looks like you might be using VS Code, which the extension will not work with at this time. Sorry for any inconvenience!
