### ISSUE TITLE
Remove AppDomain.AssemblyResolve event handler

### ISSUE THREAD

**Issue by AArnott** [github/VisualStudio#885]
The https://github.com/github/VisualStudio/pull/875 change removed (and re-added) a custom assembly resolver. But this is an anti-pattern in VS for several reasons, including the very one that caused your old one to be so problematic. This new one is also problematic for (at least) the reason that it forces your new package to be loaded on startup, which slows down VS start time.

No VS extension should have to do this, AFAIK. Instead, simply supply a pkgdef with codebase paths for each of your assemblies so that the CLR can find them when it looks for them.

**Comment by grokys** [comment]
Thanks @AArnott - yes we tried to remove it, but the change required seemed to big for a patch release so we went back to the assembly resolver for the moment. Based on your feedback though, we can try to obviate the need for it in the next patch release.

**Comment by shana** [comment]
@AArnott This is an interim fix to get the start page icon loading properly. Unfortunately, xaml references don't include full assembly names, which means codebase paths don't really fix this and other problem load time problems we have that the assembly resolver is currently handling. The better solution that avoids all these problems requires some amount of refactoring, so we're working on that for the next release.

**Comment by AArnott** [comment]
Thanks, @shana. I have very limited WPF experience, personally. But I've had enough to know that XAML compiles to include a full assembly name in at least some references. I know this because when I compile against an assembly that has no strong name, and then later it appears with a strong name, XAML won't find it. So as strong name is part of an assembly's full name, I'm surprised that there are other scenarios that you must be thinking of where XAML _doesn't_ include that.
