### ISSUE TITLE
Extension breaks when 2.2.0.9-Experimental is installed on top of 2.2.0.8

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#910]
- GitHub Extension for Visual Studio version: 2.2.0.8 and 2.2.0.9-Experimental
- Visual Studio version: 2015/2017

1. Install 2.2.0.8 via `Extensions and Updates`.
2. Install 2.2.0.9-Experimental via VSIX (local build)
3. Open Visual Studio.

Both versions are loaded at the same time and terrible things start happening!

![image](https://cloud.githubusercontent.com/assets/11719160/23604952/bc3a35c8-0252-11e7-82e4-74131eef5812.png)

See also #884.

**Comment by jcansdale** [comment]
I've worked out what the problem is. I assumed the `Experimental` flag would make the extension load *instead* of the `AllUsers` extension. Apparently the extension is actually *overlaid* on top of the `AllUsers` extension. This seems to work fine as long as none of your package GUIDs have changed!

The issue we were seeing was triggered when one of our package GUIDs did change. This caused both versions of our extension to load and all kinds of problems!

This is definitely something to watch out for if you ever remove a package! I'm worried about that is going to happen with all of the other package settings and GUIDs. Will package settings from the `AllUsers` extension leak through into the `Experimental` extension?

Hopefully @tinaschrepfer will let us know what's going on and whether this is a bug or how it's supposed to work. 😄 Thanks!

**Comment by grokys** [comment]
We have experienced a similar problem without changing guids:

![assembly-resolver-problem](https://cloud.githubusercontent.com/assets/1775141/26303260/56ab87c6-3ee7-11e7-8da5-64f0a8264261.png)

**Comment by grokys** [comment]
@jcansdale I believe we've removed the experimental flag, is this still an issue?

**Comment by jcansdale** [comment]
This kind if this might still be an issue when using F5 and a version is also installed for all users. It isn't an current issue though.
