### ISSUE TITLE
Cannot Login My Account

### ISSUE THREAD

**Issue by dp9u0** [github/VisualStudio#920]
- GitHub Extension for Visual Studio  version: 2.2.0.8
- Visual Studio version:  VS 2017 Community

I sign in use the right username and  password，but failed：

![image](https://cloud.githubusercontent.com/assets/10483023/23818689/98b318ba-0638-11e7-8835-0960e1ef453e.png)

i saw some NullReferanceException in the log.

here are parts of the log file：

- GitHubVisualStudio-te.log

Error loading the repository list from the registry 'System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 GitHub.TeamFoundation.RegistryHelper.PokeTheRegistryForRepositoryList() 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\src\GitHub.TeamFoundation.15\RegistryHelper.cs:行号 26

- extension.log

2017-02-17 21:03:17.7508|ERROR|thread: 1|SharedCache|Failed to set the UserAccount cache.
System.TypeInitializationException: “NativeMethods”的类型初始值设定项引发异常。 ---> System.Exception: Tried to load sqlite3.dll from D:\DEVELOP\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\Q2XRXPWL.OMU and failed miserably.
   在 SQLitePCL.SQLite3Provider.NativeMethods..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 SQLitePCL.SQLite3Provider.NativeMethods.sqlite3_open_v2(Byte[] filename, IntPtr& db, Int32 flags, Byte[] vfs)
   在 SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
   在 SQLitePCL.raw.sqlite3_open_v2(String filename, sqlite3& db, Int32 flags, String vfs)
   在 Akavache.Sqlite3.Internal.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks) 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\akavache\Akavache.Sqlite3\SQLite.cs:行号 193
   在 Akavache.Sqlite3.SQLitePersistentBlobCache..ctor(String databaseFile, IScheduler scheduler) 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\akavache\Akavache.Sqlite3\SqlitePersistentBlobCacheNext.cs:行号 44
   在 Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__2() 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\akavache\Akavache.Sqlite3\Registrations.cs:行号 34
   在 System.Lazy`1.CreateValue()
   在 System.Lazy`1.LazyInitValue()
   在 System.Lazy`1.get_Value()
   在 Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__3() 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\akavache\Akavache.Sqlite3\Registrations.cs:行号 36
   在 Splat.ModernDependencyResolver.GetService(Type serviceType, String contract) 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\splat\Splat\ServiceLocation.cs:行号 270
   在 Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract) 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\splat\Splat\ServiceLocation.cs:行号 151
   在 Akavache.BlobCache.get_UserAccount() 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\akavache\Akavache\Portable\BlobCache.cs:行号 87
   在 GitHub.Caches.SharedCache.<>c.<.ctor>b__4_0() 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\src\GitHub.App\Caches\SharedCache.cs:行号 52
   在 GitHub.Caches.SharedCache.GetBlobCacheWithFallback(Func`1 blobCacheFunc, String cacheName) 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\src\GitHub.App\Caches\SharedCache.cs:行号 103    在 SQLitePCL.SQLite3Provider.NativeMethods.sqlite3_open_v2(Byte[] filename, IntPtr& db, Int32 flags, Byte[] vfs)
   在 SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
   在 SQLitePCL.raw.sqlite3_open_v2(String filename, sqlite3& db, Int32 flags, String vfs)
   在 Akavache.Sqlite3.Internal.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks) 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\akavache\Akavache.Sqlite3\SQLite.cs:行号 193
   在 Akavache.Sqlite3.SQLitePersistentBlobCache..ctor(String databaseFile, IScheduler scheduler) 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\akavache\Akavache.Sqlite3\SqlitePersistentBlobCacheNext.cs:行号 44
   在 Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__2() 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\akavache\Akavache.Sqlite3\Registrations.cs:行号 34
   在 System.Lazy`1.CreateValue()
   在 System.Lazy`1.LazyInitValue()
   在 System.Lazy`1.get_Value()
   在 Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__3() 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\akavache\Akavache.Sqlite3\Registrations.cs:行号 36
   在 Splat.ModernDependencyResolver.GetService(Type serviceType, String contract) 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\splat\Splat\ServiceLocation.cs:行号 270
   在 Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract) 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\splat\Splat\ServiceLocation.cs:行号 151
   在 Akavache.BlobCache.get_UserAccount() 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\submodules\akavache\Akavache\Portable\BlobCache.cs:行号 87
   在 GitHub.Caches.SharedCache.<>c.<.ctor>b__4_0() 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\src\GitHub.App\Caches\SharedCache.cs:行号 52
   在 GitHub.Caches.SharedCache.GetBlobCacheWithFallback(Func`1 blobCacheFunc, String cacheName) 位置 C:\Users\grokys\Documents\GitHub\VisualStudio\src\GitHub.App\Caches\SharedCache.cs:行号 103
2017-02-17 21:03:17.7858|ERROR|thread: 1|SharedCache|Failed to set the LocalMachine cache.

**Comment by grokys** [comment]
Hi @dp9u0,

The log entries that you posted seem to be old entries not related to the login problem. Could you post your full logs? Also: try logging in again - it could be that it is an intermittent problem.

**Comment by dp9u0** [comment]
Hi @grokys 
Sorry i reinstall my os and couldn't found log files,
And when i try again after some days ,it worked.

**Comment by grokys** [comment]
Ok, glad it's working. If you have problems again, please reopen the issue.
