### ISSUE TITLE
Manually Checkout files for edit

### ISSUE THREAD

**Issue by Usmankhalid123** [github/VisualStudio#921]
- GitHub Extension for Visual Studio  version:2.2.0.8
- Visual Studio version:2017

__What happened__ (with steps, logs and screenshots, if possible)
When using xamarin in visual studio the build keeps failing as its tooling manually updates the resourcedesigner.cs file whenever .xml files are edited. This is not possible when i use git in visual studio as it checks(locks) the file from manual editing. How do i uncheck a file from visual studio. When using TFS an option appears in Visual studio in properties of the file as well as in options->source control but with github no such option appears and there are no options in general tab of the github extension for visual studio thus built fails as i cannot checkout the file from visual studio.
https://msdn.microsoft.com/en-us/library/4x00bk11(v=vs.90).aspx

![1](https://cloud.githubusercontent.com/assets/26201855/23869168/e1768e3a-0843-11e7-9374-a01dd01d0458.JPG)
![2](https://cloud.githubusercontent.com/assets/26201855/23869173/e3c88ada-0843-11e7-8da0-725f34274c9f.JPG)
![3](https://cloud.githubusercontent.com/assets/26201855/23869174/e5d80af8-0843-11e7-838b-8ac17ab0fa5d.JPG)
![4](https://cloud.githubusercontent.com/assets/26201855/23869178/e8e32264-0843-11e7-90eb-277d4c0e71b1.JPG)
![5](https://cloud.githubusercontent.com/assets/26201855/23869183/ea98bc72-0843-11e7-8b13-28bfe19ce878.JPG)

**Comment by shana** [comment]
Hi @Usmankhalid123. Git doesn't support locking files for editing. Git doesn't touch the file permissions so you should always be allowed to edit them. Could it be that when you pushed your files to git, they were readonly? Check the permissions on the files on Windows Explorer to see if that's the issue, you can toggle the readonly flag there if that's the case.
