### ISSUE TITLE
Error when pushing, syncing, fetching or pulling to remote repository.

### ISSUE THREAD

**Issue by theweavrs** [github/VisualStudio#922]
**What I am using:**
- GitHub Extension for Visual Studio version: 2.2.0.8
- Visual Studio version: Visual Studio 2017 Community

**What happened:**
I have been using GitHub Extension for Visual Studio in Visual Studio 2015 without any issue but as soon as I updated to 2017, I couldn't push commits to remote repo on GitHub. Here is what I get:

When I press Sync:
![sync](https://cloud.githubusercontent.com/assets/7473959/23886168/a16dbed8-089a-11e7-8062-ea00c075c30d.PNG)
_Nothing is added in the output window._

When I press *Push*:
![push](https://cloud.githubusercontent.com/assets/7473959/23886180/b81886fe-089a-11e7-9b83-6e1e77be5527.PNG)
The output window shows this:
```
Error encountered while pushing to the remote repository: Git failed with a fatal error.
PushCommand.ExecutePushCommand
```
When I press *Fetch*:
![fetch](https://cloud.githubusercontent.com/assets/7473959/23886200/e5e4acd4-089a-11e7-8afd-21bb535a397f.PNG)
The output window shows this:
```
Error encountered while fetching: Git failed with a fatal error.
FetchCommand.ExecuteFetch
```
------------------
All was working in Visual Studio 2015 and I have tried syncing using Git GUI and it works without a hitch.

Would appreciate any help. 
Thanks.

**Comment by RMcCurdy** [comment]
I have the exact same issue

**Comment by grokys** [comment]
Hi @theweavrs and @RMcCurdy - sorry for the delay in replying, this one got lost in my inbox.

I'm afraid that the Team Explorer Synchronization functionality isn't written by us - Team Explorer is a part of Visual Studio itself, so you're going to have to go to Microsoft to get help on this, sorry.

**Comment by Guruprasady** [comment]
Hello,

I am trying to push code from visual studio 2017 to my github account. But unable to do that because of the below error.
Please let me know if any suggestions/solution.

Failed to push the branch to the remote repository. See the Output window for more details.


Thanks in Advance

Regards,
Guruprasad

**Comment by meaghanlewis** [comment]
👋 @Guruprasady the same fact applies that Team Explorer Synchronization functionality isn't written by us - but a part of Visual Studio itself. You're going to contact Microsoft support to get help on this, sorry.

**Comment by pradipsnet** [comment]
Not sure why you are getting this error but I was facing the same error since my branch name was including a capital letter

**Comment by GusGusGusGus** [comment]
Having the same issue while trying to push to a remote repo.
**What I am using:**
VS2019 Enterprise Version 16.8.2 with the Git Extension
**What I did:**
Created a local feature branch based on the master branch
Pushing changes to remote repo
**The Error:**
_Error encountered while pushing branch to the remote repository: Value cannot be null.
Parameter name: name
Failed to push the branch to the remote repository. See the Output window for more details._

 Any help on this would be much appreciated.
