### ISSUE TITLE
Tooltip over the Home area of Team Explorer is incorrect

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#93]
Tooltip over the Home area of Team Explorer is incorrect. 

I spoke to @shana and this is an MS problem but she wanted an issue created to relay to them to fix.

![screen_shot_2015-09-15_at_11_37_05_pm](https://cloud.githubusercontent.com/assets/10725993/9911042/07015d98-5c55-11e5-8874-0cb897319992.png)

**Comment by meaghanlewis** [comment]
From what I can tell the tool tips appear to be correct and convey relevant information now. Going to close this out.

<img width="274" alt="screen shot 2017-11-20 at 12 17 49 pm" src="https://user-images.githubusercontent.com/10103121/33039586-467709a8-cded-11e7-8e9b-ceb919b4bb5c.png">

<img width="260" alt="screen shot 2017-11-20 at 12 18 01 pm" src="https://user-images.githubusercontent.com/10103121/33039590-4a106f6e-cded-11e7-830e-471438481cbf.png">

<img width="275" alt="screen shot 2017-11-20 at 12 18 06 pm" src="https://user-images.githubusercontent.com/10103121/33039596-4d6b18f8-cded-11e7-9c10-a615e2fb7bfa.png">

<img width="274" alt="screen shot 2017-11-20 at 12 18 15 pm" src="https://user-images.githubusercontent.com/10103121/33039598-50988d44-cded-11e7-864b-b8de54bef012.png">
