### ISSUE TITLE
Extension doesn't work with Visual Studio Team Explorer 2017

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#938]
- GitHub Extension for Visual Studio version: 2.2.0.9
- Visual Studio version: Visual Studio Team Explorer 2017

I installed GHfVS 'Extensions and Updates', but the extension didn't appear after relaunch.

See here:
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes

**Comment by simdimdim** [comment]
Same issue. Also not sure if even related, but the 'Open in/with Visual Studio' button doesn't show up in github for windows either.
