### ISSUE TITLE
Unable to start proces

### ISSUE THREAD

**Issue by BrilliantTechie** [github/VisualStudio#939]
I'm always getting "Unable to start process." whenever i try to commit or sync with github remote repository. 

- GitHub Extension for Visual Studio  version: 2.2.0.8
- Visual Studio version: 2017 Enterprise & Professional RTM

**Comment by paladique** [comment]
Hi @BrilliantTechie, sorry to hear you're having problems.
Committing and syncing in Visual Studio is specific to Git within Team Explorer, so your problem might not be related the GitHub for Visual Studio Extension itself. To confirm this is a GitHub for Visual Studio problem, can you send us your log files? You can find info on how to do this [here](https://github.com/github/VisualStudio/blob/master/CONTRIBUTING.md#bug-reporting).

**Comment by BrilliantTechie** [comment]
it seem you are right its a problem within Team Explorer https://developercommunity.visualstudio.com/content/problem/27564/git-unable-to-start-process.html?utm_source=t.co&utm_medium=referral

thanks
