### ISSUE TITLE
Can't install the beta version of the ext

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#94]
@Haacked asked me to write up an issue so a few more people could look into this. 

Currently, I can't install the extension by double-clicking on it to install. It crashes on me. 

**Steps to reproduce:**
1. Download the file
2. Double click to install

**Expected Results:** The ext installs

**Actual Results:** The ext crashes. 
I am on  Windows 8.1 (on a VM if that helps)
```
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	VSIXInstaller.exe
  Problem Signature 02:	14.0.23107.0
  Problem Signature 03:	559b7195
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.96.0
  Problem Signature 06:	55b96801
  Problem Signature 07:	157e
  Problem Signature 08:	12e
  Problem Signature 09:	System.UnauthorizedAccess
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	a10f
  Additional Information 4:	a10ff7d2bb2516fdc753f9c34fc3b069
```

**Work-arounds:**To use the production version, I ended up just opening up VS and navigating to Tools --> Extensions and Updates ---> Online and selected the the GitHub Extension for Visual Studio and it installed successfully on there. 

For the beta release (https://github.com/github/VisualStudio/releases/tag/v1.0.15.0-beta), I downloaded it and still getting the crash but I can't use the work around :point_up: 

I changed my UAC Settings here and right click to Install as Admin does not display. 
![screen shot 2015-09-16 at 11 09 04 am](https://cloud.githubusercontent.com/assets/10725993/9913843/bbad9b18-5c63-11e5-8906-6d3f3203ce72.png)
![screen_shot_2015-09-16_at_11_09_56_am](https://cloud.githubusercontent.com/assets/10725993/9913848/c1767b14-5c63-11e5-9525-f8862d78c6d5.png)

Any other ideas/suggestions? :pray: :grin:

**Comment by robrix** [comment]
Looks like a .vsix file might not be an installer (but I’m no expert, so defer to Folks Who Know™). Maybe it can be installed manually by moving it into the right path in Explorer? I’m not sure where that would be tho.

**Comment by shana** [comment]
Definitely permissions issues on windows 10, it's ridiculous. It's just never prompting for permissions when it runs the vsixinstaller. So dumb.

Another workaround for getting this to work is to run the Developer Command Prompt for VS2015 as an administrator, and then run `vsixinstaller /a file.vsix`.

**Comment by niik** [comment]
> Definitely permissions issues on windows 10

Looks like @amytruong is on 8.1 though.

**Comment by shiftkey** [comment]
@lildude this seems like something you showed me before I went on holiday. Were you running Windows 8.1 or Windows 10 on that test machine?

**Comment by lildude** [comment]
@shiftkey Win 10.

**Comment by shiftkey** [comment]
So from what I recall (jump in @lildude if I miss something) was that:

 - fresh Windows 10 environment
 - download the VS extension from the site
 - run it by hand

It was the same "nothing happened" behaviour that @shana talked about earlier.

@shana did you have any better advice to address this? At the time I suggested using the Extension Gallery to workaround it.

**Comment by lildude** [comment]
@shiftkey Yup, that's the precise behaviour as I remember it.  I also tried "Open with" IIRC and that didn't work either.

**Comment by shana** [comment]
No better advice, I'm afraid, installing from the gallery is the easiest way to work around this. It's a vsixinstaller bug and MS are aware of it :disappointed:
