### ISSUE TITLE
Tooltip over the GitHub header area of Team Explorer is incorrect.

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#95]
Tooltip over the GitHub header area of Team Explorer is incorrect.

I spoke to @shana and this is an MS problem but she wanted an issue created to relay to them to fix.
![screen_shot_2015-09-16_at_2_57_05_pm](https://cloud.githubusercontent.com/assets/10725993/9919714/7ec90de8-5c83-11e5-9835-d63ec7143df3.png)

**Comment by acangialosi** [comment]
We should make sure there's a positive hand off with a bug logged in our internal database.

**Comment by Haacked** [comment]
> We should make sure there's a positive hand off with a bug logged in our internal database.

Cool. When we know it's in your internal database, that would be a great time to close the bug here.

**Comment by Haacked** [comment]
> Tooltip over the GitHub header area of Team Explorer is incorrect.

@amytruong @shana could you clarify what exactly is wrong with it? What's the expected behavior?

**Comment by shana** [comment]
Sorry, the tooltip on #93 is an actual bug, this one isn't, it's just the tooltip that appears for all sections.
