### ISSUE TITLE
"Diff" Missing keyboard shortcut

### ISSUE THREAD

**Issue by chenop** [github/VisualStudio#967]
- GitHub Extension for Visual Studio  version:2.48.90
- Visual Studio version: 2015

__What happened__ (with steps, logs and screenshots, if possible)
Cannot bind keyboard shortcut to GitExt.Diff action
It is not present in the GitExt menu but it is displayed when doing:
in Solution Explorer --> Right click a file 

I expected to find it in:
Tools --> Option --> Environment --> Keyboard
In the list of commands it was not present (although other GitExt commands were there)

**Comment by paladique** [comment]
Hi @chenop, sorry you're having issues, but this repo is related to the GitHub for Visual Studio extension. If GitExtensions is what you were looking for, they have a [repo](https://github.com/gitextensions/gitextensions) as well.

**Comment by chenop** [comment]
Thanks @Paladique for replying.
The issue is about not able to add a shortcut for diff action inside visual studio.
So I think this is the right repo.

**Comment by chenop** [comment]
Also, Ill be happy to open pull request myself.
Please just direct me hire I can make VS to recognize a new action.

**Comment by paladique** [comment]
Hi @chenop thanks for the reply. I assumed this is not the right repo because 2.48.90 has never been a version for GitHub for Visual Studio, but it is a version on GitExtensions. Just to clarify, can you send me a screenshot of where you got that version from, and a screenshot of the diff view?

**Comment by chenop** [comment]
Hi @paladique, Indeed you are right.
I got confused.
Sorry for the hassle.
