### ISSUE TITLE
Custom controls no longer have Automation IDs

### ISSUE THREAD

**Issue by paladique** [github/VisualStudio#969]
While running GHfVS on master, I noticed that things like the GitHubPaneView and the PullRequestListView no longer have automation ids like they did in 2.2.0.8. They also seem to be missing in 2.2.0.10. Controls within those views (ie: Create new button in the PR list view) still have their automation ids.

**Comment by paladique** [comment]
After some more digging, this seems to have happened after #947 was merged.

**Comment by jcansdale** [comment]
Very sorry is this is something I broke! 😕

**Comment by shana** [comment]
Ah, the projects were moved but they didn't include all the required IDs? This is definitely something we should catch in QA before shipping a thing! We're aiming to get a 2.2.0.11 out the door with a hotfix, @paladique do you want to include the missing IDs there or just fix on master and wait for the next one?

**Comment by paladique** [comment]
@shana I can fix on master and wait for the next one, no need to hold it up. I can alter the control searching for now. The strange thing, which is pointing to no obvious fix, is that it's only happening to top level panels, for example: the PRListView panel doesn't have an id, but the controls (create new link, filters) within it does.
