### ISSUE TITLE
GitHub docs are promoted even when I am connected to TFVC Project

### ISSUE THREAD

**Issue by youhanaNaseim** [github/VisualStudio#971]
- GitHub Extension for Visual Studio  version:
![image](https://cloud.githubusercontent.com/assets/3439582/25636269/e4b68d2a-2f4e-11e7-93c3-abcf9ec69a8a.png)

- Visual Studio version:
![image](https://cloud.githubusercontent.com/assets/3439582/25636256/dda4d794-2f4e-11e7-9415-7dc6c34a2147.png)

- Connected to a TFVC Project on my local server
- Got prompt to create a workspace
- After the workspace got created I see some git docs:

![image](https://cloud.githubusercontent.com/assets/3439582/25636319/179dd4fa-2f4f-11e7-8e46-2a6053b9c69d.png)

**Comment by shana** [comment]
Hmm yes, showing the welcome message when you're in a non-github context is probably not the best time to do it.

**Comment by paladique** [comment]
Fixed in #982, enhancement in progress in #980
