### ISSUE TITLE
Specify developer ClientId / ClientSecret in environment variable rather than source

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#972]
From https://github.com/github/VisualStudio/pull/845#discussion_r113951578

> It would be nice if rather than getting the ClientId / ClientSecret from source, it got it from an environment variable (GITHUB_CLIENT_ID or something). That way the developer wouldn't have to dirty their repo whenever they wanted to try something out (a hassle when changing branches). It could complain with a visible/helpful error when these variables aren't set.

**Comment by shana** [comment]
I added a comment to the original comment. This data needs to be in code and not in the environment, given that it's data required during runtime and it's not really feasible to require users to manually configure their environment, and not very nice for devs trying out custom builds, either. We can make it easier to customize this by putting it in a separate file that we .gitignore so it doesn't dirty the repo, for instance.

**Comment by jcansdale** [comment]
That makes sense. I was only thinking about developers testing their changes locally not sending them to users!

> We can make it easier to customize this by putting it in a separate file that we .gitignore so it doesn't dirty the repo, for instance.

In fact I think we're pretty much all the way there. I commented in the code review when I noticed @grokys had added a `ApiClientConfiguration_User.cs` file. I think all we need to do is `.gitignore` this. 😄
