### ISSUE TITLE
keyboard shortcut for commit window

### ISSUE THREAD

**Issue by fabiomaulo** [github/VisualStudio#995]
Currently there is no way, AFAIK, to commit other than "click" the commit button.
Would be useful a Ctrl+ENTER to commit from inside the comment textbox.
Even more useful if, after the commit, the focus go back to the "Solution explorer".

Thanks.

**Comment by grokys** [comment]
Hi @fabiomaulo,

Committing is part of the Git functionality provided by Visual Studio, this extension just provides the GitHub integration - I know it can be confusing where one starts and the other begins! You can find more information on the features that our extension provides [here](https://github.com/github/VisualStudio/tree/master/docs).

**Comment by fabiomaulo** [comment]
Hi @grokys 
I mean CTRL+ENTER in the extension, no in VS
![image](https://cloud.githubusercontent.com/assets/125039/26030407/52db1a9a-3829-11e7-83af-049ab743d927.png)
